### ISSUE TITLE
机房视图-机柜无法删除

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1001]
对已经存在的机柜进行删除后，显示删除成功，但是刷新页面后，已经删除的机柜仍然存在。再次删除提示错误
![image](https://cloud.githubusercontent.com/assets/20636259/23594716/01f8e8ee-0257-11e7-90ba-8ba270cd6b91.png)

**Comment by RasAlGu1** [comment]
机器时间向后更改过

**Comment by RasAlGu1** [comment]
机器没有向后时间更改的情况下，出现这个问题，清理浏览器缓存后，删除的机柜消失

**Comment by eeiceyes** [comment]
fixed
