### ISSUE TITLE
【数据流】资源清单中的设备和接口统计的流入流出数据一致

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1002]
流入和流出的数据显示过渡一致，是否正常？
![image](https://cloud.githubusercontent.com/assets/20636259/23598956/dec42ba0-0278-11e7-9be5-73a727846d45.png)

**Comment by runner-mei** [comment]
因为这是嗅探的数据，没有流入可流出的说法，所以一样的
