### ISSUE TITLE
【数据流】编辑告警配置时，原先的告警配置显示与设置有出入

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1003]
部分地方的配置信息恢复成了默认状态
![image](https://cloud.githubusercontent.com/assets/20636259/23601338/ef07d5a4-0285-11e7-864e-4cfc2ae56b80.png)

**Comment by hengwei-lhm** [comment]
已修复 只对新添加的配置起效 需删除之前配置
