### ISSUE TITLE
【数据流】添加告警时，设置端口/协议-TCP时，告警无法触发

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1004]
添加告警时，设置端口/协议-TCP 参数时，告警无法触发
![image](https://cloud.githubusercontent.com/assets/20636259/23603303/8c4347fa-028f-11e7-99cf-654e21b63750.png)

**Comment by runner-mei** [comment]
不清楚这个，我试了是可以的，你确认一下，不行叫我

**Comment by runner-mei** [comment]
fix
