### ISSUE TITLE
【数据流】添加告警配置-IP地址时，无法直接输入IP地址

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1006]
在告警标准中，选择IP地址时，展开“IP地址和IP范围”
![image](https://cloud.githubusercontent.com/assets/20636259/23642543/57067b32-0336-11e7-96cd-8d3302708cc1.png)
无法直接再后发输入地址，需要点击IP范围后，在点击IP地址，才能输入地址信息

**Comment by hengwei-lhm** [comment]
已修复 只对新添加的配置起效 需删除之前配置
