### ISSUE TITLE
交换路由设备的运转视图中的组件状态，点开需要对齐

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1007]
组件中的电源和风扇，点开后的视图不对齐 ，需要把格式对齐
![image](https://cloud.githubusercontent.com/assets/20636259/23648067/fe07bfdc-0353-11e7-8d83-1e7403cc6dce.png)

**Comment by eeiceyes** [comment]
界面改了，这个问题可以关掉了
