### ISSUE TITLE
（国妇婴巡检需求）巡检填写中增加跳转链接和刷新按钮

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#1012]
在巡检对象上跳转连接（如单击对象直接定位到拓扑图该对象）、增加一列刷新按钮（当指标异常时通过刷新来查看是否异常一直存在）

![image](https://cloud.githubusercontent.com/assets/14171518/23693049/3c5600aa-040d-11e7-9b1d-5d3cb91de3d0.png)

**Comment by eeiceyes** [comment]
定位已加上

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170816_272_x64.exe  版本确认，close处理。     定位已经加上、刷新按钮不做
