### ISSUE TITLE
（国妇婴巡检需求）巡检查询

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#1013]
1、增加“巡检人”    
2、“生成时间”-》“巡检时间”
3、按照巡检对象将巡检指标进行汇总，同一个对象的指标集中在一块区域
4、结果值进行单位转换
![image](https://cloud.githubusercontent.com/assets/14171518/23693270/a08e6dea-040e-11e7-9c94-c3281d4625bb.png)

**Comment by eeiceyes** [comment]
完成1，2，4

**Comment by eeiceyes** [comment]
3按照对象排了下许，要分组的话改动比较大
