### ISSUE TITLE
巡检文件上传失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1017]
网管机环境：192.168.1.155 ；192.168.1.157
![image](https://cloud.githubusercontent.com/assets/20636259/23739067/98697802-04d7-11e7-9faf-4849a30debfe.png)

**Comment by eeiceyes** [comment]
权限问题，在目录下/var/lib/tpt/resources/custom_inspect_files，没有创建文件夹和文件的权限
