### ISSUE TITLE
[镇江农商行] 拓扑线路连接到缩略连线非直线

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1021]
客户：镇江农商行
环境：分布式部署
问题：拓扑图线路连接到缩略图设备的线路不是直线（线路设置方式为直接）如下图

![image](https://cloud.githubusercontent.com/assets/14171497/23846278/b1ba2508-0807-11e7-958e-dbd98f66113d.png)
级别：高

**Comment by eeiceyes** [comment]
fixed
