### ISSUE TITLE
[镇江农商行] 中间件测试报错"engine_id is missing"

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1022]
客户：镇江农商行
环境：分布式部署
问题：中间件添加测试报错 "engine_id is missing"

![image](https://cloud.githubusercontent.com/assets/14171497/23846494/b8ae9096-0808-11e7-9430-21dbaa9ac547.png)

**Comment by eeiceyes** [comment]
我这边试了下，能重现问题：
1，手动在数据库tpt_engine_nodes插入一条数据
2，重启服务，进入中间件添加界面，测试报出bug所描述的错误

**Comment by RasAlGu1** [comment]
测试通过
