### ISSUE TITLE
设备电压采集到的值很大

### ISSUE THREAD

**Issue by eeiceyes** [three-plus-three/hw_issues#1023]
交大的设备10.255.250.11在本地模拟后，hw_power_voltage指标采集到的电压出现1W多的值，确定下单位是否为伏特
![qq 20170313162351](https://cloud.githubusercontent.com/assets/4076162/23846771/f928783e-0809-11e7-9aff-99f195eeec5a.png)

**Comment by runner-mei** [comment]
fix

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170814_270_x64.exe   版本确认，close处理。
