### ISSUE TITLE
右键设备-实时监控-端口流量，停止时提示有误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1025]
右键设备-实时监控-端口流量，选择端口进行监控，启动后点击停止按钮，提示信息有误
![image](https://cloud.githubusercontent.com/assets/20636259/24026052/7cb77208-0af9-11e7-80ed-bc0a543cab64.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170713_181_x64.exe  版本确认，close处理。
