### ISSUE TITLE
[维信金科]ayava语音网管设备支持

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1027]
设备类型：AYAVA语音设备（S8300/G540）
文档手册
MIB库

级别：待开发

[MIB_WLAN_V200R006C10_20151022.zip](https://github.com/three-plus-three/hw_issues/files/849590/MIB_WLAN_V200R006C10_20151022.zip)

**Comment by runner-mei** [comment]
walk 文件呢？

**Comment by Cuic** [comment]
暂时不开发
