### ISSUE TITLE
告警日志数据过多时，只能查看到一部分的日志

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1035]
告警日志在日志数据过多时，仅可查看的部分日志，没有翻页的功能

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，close处理。
hengwei_setup_3.2.20171027_2837_x64.exe   版本确认，close处理。
