### ISSUE TITLE
组合告警中添加告警规则时，选择告警类型-Windows，告警规则中包含非Windows主机

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1036]
组合告警中添加告警规则时，选择告警类型-Windows，告警规则中包含非Windows主机
![image](https://cloud.githubusercontent.com/assets/20636259/24130473/a4cde83a-0e23-11e7-8ac8-6a589ac8d2e3.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170922_2764_x64.exe  版本确认，close处理。
