### ISSUE TITLE
没有写权限的用户可以越权操作

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1043]
可以删除机房和机柜
可以上传和清楚背景
设备总览中可以创建删除组，可以移除设备
巡检异常处理，可以确认异常项
可以做Tag列表进行添加和删除
可以对设备的TFTP脚本进行修改
在报表生成查看中，可以删除生成的报表
在预置报表查看中，可以删除生成的报表
在脚本管理中，可以修改、添加、删除脚本
在数据库脚本管理中，可以修改、添加、删除脚本
可以生成和导入license

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170829_2669_x64.exe  版本确认，  现象还在现

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170830_2674_x64.exe 版本确认
1.可以删除机柜
2.设备总览中可以创建删除组，可以移除设备
3.巡检异常处理，可以确认异常项
4.可以对设备的TFTP脚本进行修改
5.可以生成和导入license
以上确认还在现

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
生成和导入license改成只有admin权限的用户才能干

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170830_2677_x64.exe 版本确认，
1.巡检异常处理，可以确认异常项 还在现
https://github.com/three-plus-three/hw_issues/issues/1486 已经提出
