### ISSUE TITLE
拓扑图上，告警气泡点开没有告警信息

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1046]
告警触发，恢复之后，告警气泡仍存在，点击打开告警气泡里面没有告警信息显示

**Comment by RasAlGu1** [comment]
[server_biz.log.txt](https://github.com/three-plus-three/hw_issues/files/863730/server_biz.log.txt)

**Comment by eeiceyes** [comment]
最近有重现过吗？好久没有重现的话就关了吧

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe   版本10次确认未出现此现象，close处理。
