### ISSUE TITLE
IPMI风扇速度的小数位数过多

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1055]
·
![111111](https://cloud.githubusercontent.com/assets/20636259/24484263/e1679ab2-152f-11e7-980b-bf5846d7836d.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170724_208_x64.exe     版本确认，close处理。
