### ISSUE TITLE
[奇瑞汽车]设备线路连线错误

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1057]
网络环境中包含：思科、H3C、华为设备
网络设备拓扑生成线路连接错误,详见错误文档

**Comment by runner-mei** [comment]
[奇瑞错误说明.docx](https://github.com/three-plus-three/hw_issues/files/881306/default.docx)

**Comment by runner-mei** [comment]
[奇瑞walk_results.7z.003.zip](https://github.com/three-plus-three/hw_issues/files/881326/walk_results.7z.003.zip)
[奇瑞walk_results.7z.004.zip](https://github.com/three-plus-three/hw_issues/files/881329/walk_results.7z.004.zip)
[奇瑞walk_results.7z.005.zip](https://github.com/three-plus-three/hw_issues/files/881327/walk_results.7z.005.zip)
[奇瑞walk_results.7z.001.zip](https://github.com/three-plus-three/hw_issues/files/881330/walk_results.7z.001.zip)
[奇瑞walk_results.7z.002.zip](https://github.com/three-plus-three/hw_issues/files/881328/walk_results.7z.002.zip)

**Comment by runner-mei** [comment]
分析了一下问题，错误的原因多是因为连线两端的设备所用的 discovery protocol 不一致导致的。
如 4.203,4.204, 4.240 和 4.241 都是和 4.44 相连的，但 4.44 (h3c)就 lldp 和 ndp , 而 4.203,4.204, 4.240 和 4.241都只开启了 cdp（都是 cisco,不支持 ndp）,没有开启 lldp, 所以这些设备的 cdp 包发给 4.44 时， 4.44 就直接转发给相邻设备了（也就是 4.203,4.204, 4.240 和 4.241 ）。

现在改进算法，尽量不连错，但做不到纠正上述错误。

**Comment by runner-mei** [comment]
正确的解决方案是正确的配置设备如
1. 全部开启 lldp
2. 如果 h3c 或 huawei 的相邻设备是 cisco 时，而 cisco 又不支持 lldp 时，请开启 ndp 的 cdp 的兼容模式
