### ISSUE TITLE
常用工具-Trace Route-设置可选参数测试时，提示错误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1059]
![0001](https://cloud.githubusercontent.com/assets/20636259/24535051/51f1be3c-1604-11e7-93c4-01bfad17ed97.png)

![0002](https://cloud.githubusercontent.com/assets/20636259/24535054/5a90bb06-1604-11e7-9af9-032c43ae7b06.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.2.20170620_110_x64.exe  版本确认，close处理。
