### ISSUE TITLE
脚本管理和数据库脚本管理中存在.old脚本

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1062]
数据恢复时，勾选‘导入时覆盖配置’。恢复成功后，数据库脚本管理和脚本管理中会出现.old的脚本
并且脚本管理中的.old脚本无法删除
![111](https://cloud.githubusercontent.com/assets/20636259/24539515/97bb140a-1621-11e7-88e2-8b151d979ad1.png)

**Comment by eeiceyes** [comment]
fixed
