### ISSUE TITLE
软件安装完成界面启动IT综合运维平台显示不全

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#107]
软件安装完成界面，启动IT综合运维管理平台 后面的版本是否可以去掉？这样显示就好看些...
![image](https://cloud.githubusercontent.com/assets/14171497/11863488/4bcda57c-a4cf-11e5-9b4d-b442ce8f14f9.png)

**Comment by runner-mei** [comment]
这个不知道如何解决。
