### ISSUE TITLE
交换机SSH测试有时成功有时失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1070]
![01](https://cloud.githubusercontent.com/assets/20636259/24740550/4c5d13f2-1ad4-11e7-9417-5b5b6fca24e1.png)

设备:192.168.1.182
有时提示测试成功，有时提示测试失败

**Comment by runner-mei** [comment]
fix

**Comment by runner-mei** [comment]
fix

**Comment by RasAlGu1** [comment]
Version 2.2.20170406_2280_x64

**Comment by runner-mei** [comment]
fix
