### ISSUE TITLE
设备端口使用情况、设备运行情况报表，生成或者编辑成功的提示条出息位置错误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1072]
设备端口使用情况、设备运行情况报表，生产或者编辑成功的提示条出息位置错误。
不会在报表管理页面出现，在编辑“设备端口使用情况、设备运行情况报表“时，会出现在编辑页面
![image](https://cloud.githubusercontent.com/assets/20636259/24747090/dc8291aa-1aed-11e7-86a5-0fbd89dd53bf.png)

**Comment by runner-mei** [comment]
fix

**Comment by RasAlGu1** [comment]
添加或编辑这2张表时，提示错误
Template Execution Panic in DeviceRunReport/edit.html:
load template(bootstrap3/cron.html) fail, file does not exist

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-lhm** [comment]
fixed
