### ISSUE TITLE
拓扑图上设备颜色显示异常，刷新设备后正常显示

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1074]
颜色规则日志

Action_network_device[1]_metric[mem]

create '5:Trigger_network_device[1][126.0.0.28[jf2-120.0.0.4]]_metric[mem]' failed, failed to get metric definition [http://127.0.0.1:8080/hengwei/internal/s/_internal/definitions], 502: read_error

**Comment by runner-mei** [comment]
fix
