### ISSUE TITLE
自定义检测告警-SQL脚本，告警通知没有SQL语句的执行结果

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1075]
告警没有检测关键字。
告警通知输出的默认告警描述，没有SQL脚本执行后的输出内容。
![image](https://cloud.githubusercontent.com/assets/20636259/24784781/71e83e7c-1b87-11e7-98b1-58c7ed3bf9f8.png)

**Comment by runner-mei** [comment]
我是默认取结果中的 message 字段作为告警内容的，如果你没有的话会自动生成一个

**Comment by runner-mei** [comment]
请在页面加上说明吧

**Comment by eeiceyes** [comment]
在页面上加了说明

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe  版本确认，close处理。
