### ISSUE TITLE
FTP服务器-立刻上传配置失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1080]
C:\Program Files\hengwei>cd C:\Program Files\hengwei\ 
"BACKUP_DIR=data\backup"

C:\Program Files\hengwei>"C:\Program Files\hengwei\tpt.exe" backup_db -db.backup_target=-gbk "-db.backup_file=data\backup\tmp.backup.zip" 
'-gbk' is unknown db
"备份失败"

**Comment by runner-mei** [comment]
fix
