### ISSUE TITLE
启动“拓扑添加”失败，提示报错

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1085]
![image](https://cloud.githubusercontent.com/assets/20636259/24947868/f64d9588-1f9a-11e7-93f5-8aaa00908248.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_219_x64.exe     版本确认，close处理。
