### ISSUE TITLE
主机运作视图中，CPU使用率后面没有数据显示

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1088]
![999](https://cloud.githubusercontent.com/assets/20636259/24993556/7ba39de0-2059-11e7-85db-fe9d394c0c33.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170725_210_x64.exe  版本确认，close处理。
