### ISSUE TITLE
告警日志-按照级别筛选查询，有数据查询不到

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1089]
![01](https://cloud.githubusercontent.com/assets/20636259/24997067/d4b70d14-2067-11e7-8c60-98c9570f51b0.jpg)

![02](https://cloud.githubusercontent.com/assets/20636259/24997121/1929ed90-2068-11e7-90d0-5c9a13a040cd.jpg)

**Comment by eeiceyes** [comment]
告警记录的cookies表中有level字段，但history表中没有，这个导致按级别查询实时和历史告警时出现了不一致的情况，目前对于历史告警是去比较对应的告警规则的级别，但该级别可以修改（在告警发生后修改会出现该问题）

**Comment by runner-mei** [comment]
fix?
