### ISSUE TITLE
右键设备-更改图元，修改初始高度宽度后，刷新设备后高度宽度变回初始值

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#1095]
![022](https://cloud.githubusercontent.com/assets/20636259/25320797/579cb6f8-28dc-11e7-9ec4-99d8cbc1260d.jpg)

**Comment by eeiceyes** [comment]
大小可以直接修改，设备等级也有对应的大小，两者有冲突，暂时选择后者吧，影藏直接修改大小的输入框

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170816_272_x64.exe  版本确认，close处理。
