### ISSUE TITLE
平均CPU利用率 不能进行选择操作

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1107]
设备右击>>>实时监控>>>平均CPU利用率     bug：一进去是可以进行选择>>>对象类型，轮询间隔，监控指标，管理对象操作 。过一会就不能进行选择   

![2](https://cloud.githubusercontent.com/assets/22296563/26023639/9df9bc74-37f3-11e7-9d36-57ed4f8ce2c3.png)

**Comment by eeiceyes** [comment]
改成不是遮罩，而是直接隐藏了
