### ISSUE TITLE
平均内存利用率 不能进行选择操作

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1108]
设备右击>>>实时监控>>>平均内存利用率         bug：一进去是可以进行选择>>>对象类型，轮询间隔，监控指标，管理对象操作 。过一会就不能进行选择
![2](https://cloud.githubusercontent.com/assets/22296563/26023676/5fff52ca-37f4-11e7-9df4-a5cb1c5f1eb0.png)

**Comment by eeiceyes** [comment]
改成不是遮罩，而是直接隐藏了
