### ISSUE TITLE
端口流量信息  有两次弹出提示信息

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1109]
设备右击>>>实时监控>>>端口流量信息>>>点击启动   bug：会弹出两个提示信息，第一个提示提出信息点击确定，两个再弹出提示
![1](https://cloud.githubusercontent.com/assets/22296563/26023716/1afb2f2c-37f5-11e7-9fa4-e8219edd09bb.png)

**Comment by eeiceyes** [comment]
在打开对话框后马上关闭会有一定概率出现该问题
