### ISSUE TITLE
隐藏叶子节点  没有隐藏叶子节点也没有任何提示

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1110]
设备右击——节点操作——隐藏叶子节点              bug：没有隐藏叶子节点也没有任何提示
![3](https://cloud.githubusercontent.com/assets/22296563/26023725/5e1b28ca-37f5-11e7-85ae-25b3514bb1f0.png)

**Comment by eeiceyes** [comment]
这个功能不需要提示
