### ISSUE TITLE
脚本管理删除，没有提示信息

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1112]
系统管理——脚本管理——脚本浏览列表点击“删除”      bug：没有提示信息
![1](https://cloud.githubusercontent.com/assets/22296563/26098996/02ee3d52-3a5c-11e7-8f23-3bcdcabb1a7d.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
已确认
