### ISSUE TITLE
电子邮件通知，添加通知方式，没有显示详细

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1113]
系统管理——通知方式——点击添加——电子邮件通知，Syslog通知，外部程序通知，数据库通知，短信通知，http通用，企业微信通知。  Bug：添加通知方式，应该显示为：选择那一项就显示那一项。
![2](https://cloud.githubusercontent.com/assets/22296563/26099322/f3c71da2-3a5c-11e7-9883-5e64fe3c10dd.png)
![3](https://cloud.githubusercontent.com/assets/22296563/26099329/f8fbe67c-3a5c-11e7-858b-7e04651640c2.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
已确认
