### ISSUE TITLE
添加设备，提示信息带有代码

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1114]
运维管理→网络视图→右击空白处→添加设备→点击“测试”   提示：不需要输入任何值，点击“测试”按钮       bug：提示信息带有代码
![image](https://play.minio.io:9000/testbucket/20170517_1.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20170517%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170517T142712Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=ea9ea4954b3fd983626ce45175c7d75d220b86f6fa22b4d7129cae96d355b39e)

**Comment by eeiceyes** [comment]
不能重现了
