### ISSUE TITLE
[硬件监控] 服务器硬盘监控

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1117]
需求：针对服务器硬盘状态监控；
例：服务器做read 一块硬盘坏掉，系统正常使用，客户并不知道 这块硬盘已经坏掉！

case级别：高

**Comment by runner-mei** [comment]
IPMI 对硬盘不支持，有好像有 日志
https://github.com/three-plus-three/hw_issues/issues/1119

**Comment by runner-mei** [comment]
不同设备对此有同的支持， IBM, DELL， HP 可以通过带外的 SNMP 或 CIM 支持
[192.168.48.240.txt](https://github.com/three-plus-three/hw_issues/files/1054671/192.168.48.240.txt)

**Comment by runner-mei** [comment]
现已经支持 IBM, 其它厂商因为无数据暂未支持。

**Comment by Cuic** [comment]
IBM 服务器磁盘：WBEM
HP  服务器磁盘：WinRAR （HP-WMI）
