### ISSUE TITLE
[奇瑞汽车] 邮件服务器新增验证方式

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1120]
新增邮件服务器新增验证方式
![image](https://cloud.githubusercontent.com/assets/14171497/26184402/541f98fe-3bb7-11e7-8bb1-3dc3f3e444c0.png)

**Comment by runner-mei** [comment]
我新增加了对 GSSAPI 的支持。
1. 在安装目录下有一个 runtime_env/blat 目录
2. 在系统环境变量中增加 blat_path 变量， 值为 xxxxxxx\runtime_env\blat\blat.exe 
3. 重启就好了

**Comment by runner-mei** [comment]
fix
