### ISSUE TITLE
[华东电网] 巡检查询通过巡检人员过滤查询（一个任务多个巡检人巡检任务），无法查询出结果

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1121]
[华东电网] 巡检查询通过巡检人员过滤查询（**一个任务多个巡检人巡检任务**），无法查询出结果

![image](https://cloud.githubusercontent.com/assets/14171497/26184883/f791511a-3bb9-11e7-8ff4-0efb865b79f6.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
还是不能查询
![image](https://user-images.githubusercontent.com/22296563/28308615-583577ea-6bd9-11e7-8e3e-2e18c76d4989.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
ok
