### ISSUE TITLE
[南京港务] Brocade 光纤交换机支持

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1123]
Brocade 8Gb SAN Switch Module for IBM eServer BladeCenter 
存储光纤交换机 需要支持

**Comment by runner-mei** [comment]
[192.168.70.130.txt](https://github.com/three-plus-three/hw_issues/files/1009691/192.168.70.130.txt)

**Comment by runner-mei** [comment]
这个没有 cpu, mem, 加了几个其它的指标

**Comment by runner-mei** [comment]
https://github.com/three-plus-three/hw_issues/issues/1116

**Comment by Cuic** [comment]
是的
