### ISSUE TITLE
[告警规则]打开告警规则 出错

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1125]
Can not found kpi with mo_type = 'service_host' category='unknown'

**Comment by runner-mei** [comment]
这个问题是怎么回事，我觉得不太对，先请 @Cuic 说清楚 BUG 如何重现吧。

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.2.20170621_119_x64.exe     版本确认，close处理。
