### ISSUE TITLE
添加线路，提示框信息带有代码

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1127]
1.点击“运维管理→网络视图→右击空白处→“添加线路”→点击“源目交换”
2.弹出提示框“确认要交换线路的源端和目的端吗？” →再点击“确定”
Bug：提示框信息带有代码
![20170518_1](https://cloud.githubusercontent.com/assets/22296563/26197451/c8e8a8be-3bf4-11e7-9b0f-4be6ec254a6b.png)

**Comment by eeiceyes** [comment]
添加线路不显示源目交换，该功能只针对已经添加的线路

**Comment by eeiceyes** [comment]
fixed
