### ISSUE TITLE
添加线路，没有判断上下行带宽大小值

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1129]
1.	点击“运维管理→网络视图→右击空白处→“添加线路”
Bug：没有判断上下行带宽大小值，下行宽带值大于上行带宽值    例如：上行宽带：100    下行带宽：10000 也能正常添加成功的 

![201705018_2](https://cloud.githubusercontent.com/assets/22296563/26235074/7513652e-3c9b-11e7-934c-0e6f1c390efa.png)

**Comment by eeiceyes** [comment]
不做大小对比的约束，这个不需要改

**Comment by xiauye** [comment]
ok
