### ISSUE TITLE
（永安期货）bfd监控指标中只保留ciscoBfdSessState指标，并对相应指标进行翻译

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#113]
保留红框中的内容并翻译
![image](https://cloud.githubusercontent.com/assets/14171518/11927152/7852cbfc-a805-11e5-8f9e-1cef7876830f.png)
![image](https://cloud.githubusercontent.com/assets/14171518/11927174/91034df2-a805-11e5-8964-f3c6c7c90fe5.png)
告警信息进行处理
![image](https://cloud.githubusercontent.com/assets/14171518/11927208/c3c9dcf6-a805-11e5-90ab-96c539a40e9a.png)

**Comment by runner-mei** [comment]
指标已更改， 告警描述请你自已做一个模板，然后发给我。

**Comment by hengweiGR** [comment]
只保留ciscoBfdSessState指标，并翻译成“状态”

**Comment by runner-mei** [comment]
fixed it
