### ISSUE TITLE
设备显示设置（默认），不能隐藏设备信息

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1131]
点击“运维管理→网络视图→右击空白处→“设备显示设置（默认）→选择“显示属性”
bug：例如：不勾选IP地址，还是在拓扑图中显示IP地址。
![20170518_4](https://cloud.githubusercontent.com/assets/22296563/26235166/f4f421f2-3c9b-11e7-9936-5a7078b64d88.png)

**Comment by eeiceyes** [comment]
这个就是这么设计的，不支持无下标方式，所有都不选择时，默认显示设备IP地址

**Comment by xiauye** [comment]
ok
