### ISSUE TITLE
设备轮询设置(默认)，标题没有明确

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1132]
点击“运维管理→网络视图→右击空白处→设备轮询设置(默认)”  
bug：窗口标题：轮询设置   应该修改为：设备轮询设置    
bug公共点：设备轮询设置(默认)，线路轮询设置(默认)

![20170518_6](https://cloud.githubusercontent.com/assets/22296563/26235228/4616fc58-3c9c-11e7-991a-b2098ad4475e.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
已确认
