### ISSUE TITLE
设备显示设置（默认），标题没有明确

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1133]
选择菜单“运维管理→网络视图→右击空白处→设备显示设置（默认）
 bug：窗口标题：默认显示设置   应该修改为：设备显示设置     
  bug公共：设备显示设置（默认），线路显示设置（默认）

![20170518_5](https://cloud.githubusercontent.com/assets/22296563/26235297/b7ad56b4-3c9c-11e7-8ac7-f63ab5ad5307.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
已确认
