### ISSUE TITLE
主机系统日志的监控分析

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#1135]

**Comment by runner-mei** [comment]
当然服务器重启之后，想要追查为什么重启时，查看 cpu 或 mem 的历史记录是没有用的
这时面需要查看 event log，所以网管中集成一个 event log  查看工具这样才能完整形成一个闭环

**Comment by runner-mei** [comment]
重复 https://github.com/three-plus-three/hw_issues/issues/1534
