### ISSUE TITLE
[杭州华数] 声音告警分类告出

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1137]
告警类型
需求如：如果是高级级别和紧急级别的告警 可以设置有声音告警告出！

分情况告警... 例如：紧急级  当当当    高级 叮叮叮   开关按钮分开~

**Comment by runner-mei** [comment]
ok

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170729_232_x64.exe    版本确认，告警语言还是播放的“ 叮叮叮”声音，未播放添加的音乐

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170801_238_x64.exe     版本确认，close处理。
