### ISSUE TITLE
（ca）百分比计算错误

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#1140]
![ca1](https://cloud.githubusercontent.com/assets/14171518/26441051/92b6644e-4161-11e7-97b9-4fb65bc479a0.jpg)
![ca2](https://cloud.githubusercontent.com/assets/14171518/26441049/929d0e9a-4161-11e7-9d7c-9449aa1c5435.jpg)

**Comment by eeiceyes** [comment]
直接url取了主机192.168.1.157的disk_partition的指标数据
{"available":1975857152,"filesystem":"tmpfs","filesystem_type":"tmpfs","free":1975857152,"mounted_on":"/run","name":"/run","total":1984552960,"used":8695808,"used_per":1,"used_percent":1}
{"available":1984548864,"filesystem":"tmpfs","filesystem_type":"tmpfs","free":1984548864,"mounted_on":"/dev/shm","name":"/dev/shm","total":1984552960,"used":4096,"used_per":1,"used_percent":1},

是不是used_percent的计算上有点问题，都向上取整了？

**Comment by runner-mei** [comment]
我靠，在修 bug 呢

**Comment by runner-mei** [comment]
fix
