### ISSUE TITLE
端口状态告警，没有取消“全选”功能

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1141]
1.选择菜单栏“运维管理→网络视图→选择设备右击→添加告警→端口状态告警”
2.点击“全选”按钮
bug：没有取消“全选”功能
![20170524_1](https://cloud.githubusercontent.com/assets/22296563/26519769/a159084c-42f8-11e7-9a64-e24fc1a11c14.jpg)

**Comment by eeiceyes** [comment]
改成反选了
fixed
