### ISSUE TITLE
创建机柜失败的情况下，提示信息出现代码

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1142]
1.选择菜单“运维管理→机房视图→右击空白处→添加机房”
Bug：创建机柜失败的情况下，提示信息出现代码
![20170526_1](https://cloud.githubusercontent.com/assets/22296563/26519867/49b10f20-42fa-11e7-9c64-79799914c753.png)

**Comment by eeiceyes** [comment]
此类错误的原则，有疑问提bug，能翻译的一律翻译，不能的再议

**Comment by eeiceyes** [comment]
fixed
