### ISSUE TITLE
选择对象功能与窗口分离

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1143]
1.选择菜单“运维管理→业务视图→视图列表点击电脑图标”
2.右击空白处→选择【添加管理对象】
Bug:选择对象功能与窗口分离
![20170526_2](https://cloud.githubusercontent.com/assets/22296563/26519886/ac1f95fa-42fa-11e7-9df1-05ade008012c.png)

**Comment by eeiceyes** [comment]
fixed
