### ISSUE TITLE
在弹出提示框中，点击【取消】，多次提示，提示内容不正确

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1144]
1.选择菜单“运维管理→业务视图→视图列表点击【电脑图标】 
2.在视图页面“右击空白处→添加状态节点”，弹出“添加状态节点”窗口
3. 在添加状态节点窗口中，管理对象列表中，点击操作列表中【×】
Bug：在弹出提示框中，点击【取消】，多次提示，提示内容不正确
![20170527_1](https://cloud.githubusercontent.com/assets/22296563/26519896/e0fd1c98-42fa-11e7-8924-49eb1ed22920.jpg)

**Comment by eeiceyes** [comment]
fixed
