### ISSUE TITLE
同一个管理对象可以重复添加多个

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1145]
1.选择菜单“运维管理→业务视图→视图列表点击【电脑图标】 
2.在视图页面“右击空白处→添加状态节点”，弹出“添加状态节点”窗口
3. 在添加状态节点窗口中，管理对象列表中，点击【添加】
Bug：同一个管理对象可以重复添加多个
![20170527_2](https://cloud.githubusercontent.com/assets/22296563/26519905/20dde626-42fb-11e7-862d-094452f9a4af.jpg)

**Comment by eeiceyes** [comment]
加了限制

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，close处理。
hengwei_setup_3.2.20171027_2837_x64.exe   版本确认，close处理。
