### ISSUE TITLE
选择已选择项没有显示出来

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1146]
1.在业务视图页面中“按住Ctrl键不放，用鼠标选中容易两个设备→右击→添加实体线路”
2.在选择网络线路列表中，选择一个线路 ，点击【已选择项】
Bug：已选择项没有显示出来
![20170527_3](https://cloud.githubusercontent.com/assets/22296563/26519921/800e755c-42fb-11e7-912e-6165c7286c25.jpg)

**Comment by eeiceyes** [comment]
fixed
