### ISSUE TITLE
实体线路与虚拟线路的属性没有区分

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1147]
1.选择菜单“运维管理→业务视图→视图列表点击【电脑图标】 
2.在业务视图页面中“选中线路右击→线路属性”
Bug：实体线路与虚拟线路的属性没有区分，都是一样的。
![20170527_4](https://cloud.githubusercontent.com/assets/22296563/26519953/1c2f8c78-42fc-11e7-8519-9a67511646cb.png)

**Comment by eeiceyes** [comment]
加了个描述

**Comment by eeiceyes** [comment]
fixed
