### ISSUE TITLE
编辑预置报表信息页面，点击【确定】按钮，名称文本框提示"含有中英文特殊字符"信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1148]
![mt7wf 8f 08_hl7 r_v 9b8](https://cloud.githubusercontent.com/assets/28615156/26767290/1411c73c-49d1-11e7-912f-503bca663c09.png)

步骤：
1.点击“”报表管理-预置报表管理“”
→【预置报表】页面被表示
3.选中名称“”【预置报表】设备运行率统计报表“”，点击【编辑】按钮
→“”【预置报表】设备运行率统计报表“”编辑页面被表示
4.页面信息不修改，点击【确定】按钮
→名称文本框提示"含有中英文特殊字符"信息→NG

周边：
1.“”【预置报表】线路运行率统计报表“”编辑页面同样出现→NG
2.“”【预置报表】主机运行率统计报表“”编辑页面同样出现→NG
3.“”【预置报表】数据库运行率统计报表“”编辑页面同样出现→NG
4.“”【预置报表】中间件运行率统计报表“”编辑页面同样出现→NG
5.“”【预置报表】标准应用行率统计报表“”编辑页面同样出现→NG

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.2.20170613_96_x64.exe 版本确认，close处理。
