### ISSUE TITLE
“编辑主机”页面中"设备类型"修改后，点击【确定】按钮，返回“设备管理”页面不显示修改后的设备信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1150]
前提：
添加一台IP地址：192.168.141的服务器设备信息

步骤：
1.点击“资源管理-设备管理”
→设备管理页面被表示
2.选中“192.168.141”设备，点击编辑按钮
→“编辑主机”页面被表示
3.设备类型：“服务器”修改为“交换路由”，点击【确定】按钮
→设备管理页面没有IP地址：192.168.1.141设备信息不被表示→NG

![default](https://cloud.githubusercontent.com/assets/28615156/26771293/ea15f68c-49ef-11e7-81d4-c7fc1692d6a5.jpg)
![default](https://cloud.githubusercontent.com/assets/28615156/26771424/b567f146-49f0-11e7-8164-ea2ed60132b8.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.2.20170615_100_x64.exe  版本确认，BUG现象未再现、close处理。
