### ISSUE TITLE
“设备管理”页面无法点击设备类型为“KVM交换机”的IP地址信息进入编辑信息页面

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1151]
1.点击“资源管理-设备管理”
→设备管理页面被表示
2.点击【添加】按钮
→添加设备页面被表示
3.IP地址：192.168.1.101，设备类型：KVM交换机，点击【确定】按钮
→返回“设备管理”页面
4.点击IP：192.168.1.101信息时
→没有入设备信息编辑页面→NG
![1496640268 1](https://cloud.githubusercontent.com/assets/28615156/26771647/6b5e3fb8-49f2-11e7-82e1-4d0c85709cf8.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.2.20170615_100_x64.exe  版本确认，BUG现象未再现、close处理。
