### ISSUE TITLE
“用户管理”界面选中用户名：test的信息， 点击【编辑】按钮，跳转页面出错

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1152]
步骤：
1.点击“系统管理-用户管理”
→用户管理页面被表示
2.点击【添加】按钮
→添加用户界面被表示
3.名称：test，密码：asd123，密码确认：asd123，角色：adminaa输入，点击【确定】按钮
→用户管理页面被表示
4.选中用户名：test 信息，点击【编辑】按钮
→跳转页面错误信息被表示→NG

周边：
1.只有：test 名称出错，别的名称没有问题

![1496645711 1](https://cloud.githubusercontent.com/assets/28615156/26773770/5018bb22-49ff-11e7-9c4a-f627116d50c6.jpg)

**Comment by eeiceyes** [comment]
test后面存在空格

**Comment by eeiceyes** [comment]
自动去除空格
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.2.20170609_87_x64.exe 版本验证没有问题，close处理。
