### ISSUE TITLE
添加线路信息框中，源设备与目的设备选择后，点击【源目交换】按钮，提示“保存失败”信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1155]
步骤：
1.选择菜单“运维管理→网络视图→右击空白处→“添加线路” 
→添加线路信息框被表示
2.源设备与目的设备的IP地址选择，点击【源目交换】按钮
→“确定要交换线路的源端和目的端吗？”提示框被表示
3.点击【确定】按钮
→BUG：提示“保存失败”信息
![1496804974 1](https://user-images.githubusercontent.com/28615156/26860873-eb2cfbae-4b72-11e7-96c5-f038d5124ebe.jpg)

**Comment by eeiceyes** [comment]
添加时屏蔽该操作，只针对编辑线路时有效

**Comment by hengwei-test** [comment]
hengwei_setup_2.2.20170609_87_x64.exe 版本确认，close处理。
