### ISSUE TITLE
报表管理→预置报表管理：报表没有导出 

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1158]
1.选择菜单“报表管理→预置报表管理”
2.在预置报表管理列表中任意选择一个预置报表→再点击【立刻生成】
3.在生成报表窗口中，勾选【存档（同时生成PDF和HTML,可在报表浏览查看并导出）】，→再点击【确定】
Bug：报表管理→预置报表管理：报表没有导出 
![1](https://user-images.githubusercontent.com/22296563/26916879-8fdf29e2-4c5e-11e7-9dfa-6b070beb4a2f.jpg)

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170818_277_x64.exe 版本确认，close处理。
