### ISSUE TITLE
报表管理→自定义统计数据→添加：记录规则:下拉列表不能关闭

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1159]
1.选择菜单“报表管理→自定义统计数据”
2.在自定义统计数据页面中，点击【添加】
3.添加统计数据窗口中，选择【记录规则】显示下拉列表→再点击【×】图标
Bug：报表管理→自定义统计数据→添加：记录规则下拉列表不能关闭
![2](https://user-images.githubusercontent.com/22296563/26917259-21dffb5e-4c60-11e7-87f4-ca581a4e7eb5.jpg)

**Comment by eeiceyes** [comment]
不需要关闭按钮
