### ISSUE TITLE
【虚拟化视图】：虚拟化视图页面上传背景图片后，再次上传别的图片无效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1160]
步骤：
1.选择菜单“运维管理→虚拟化视图→右击空白处→上传背景” 
→上传图片A，虚拟化视图页面背景修改为图片A
2.右击空白处→上传背景”
→BUG：成功导入图片B，但是虚拟化视图背景还是图片A

周边：
1.网络视图页面不出现次现象→OK
2.业务视图界面同样出现→NG
3.IE11版本，虚拟化视图页面背景清除不了→NG

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe  版本确认，close处理。
