### ISSUE TITLE
【虚拟化视图】在虚拟化视图页面选择折现，页面显示的线路效果无效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1161]
步骤：
1.选择菜单“运维管理→虚拟化视图→右击空白处→线路排布→折线（先横后竖）” 
→BUG：虚拟化视图下线路没有折线效果

**Comment by eeiceyes** [comment]
虚拟化视图不支持这个功能，是我这边菜单定义错了

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.2.20170609_87_x64.exe 版本确认，close处理。
