### ISSUE TITLE
[华东电网]巡检人员如果离职需要对账号禁用

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1165]
巡检管理需求情况：人员离职客户往往将其账号删除 ，但是以往的历史数据需要保留做查询，如果账号删除历史数据也就无法做查询。
 需求：将离职人员的账号进行禁用。这样就不能删除账号。给登录账号一个状态

例如：正常、离职、锁定、禁用。。。。

**Comment by runner-mei** [comment]
这个假删除功能已实现
