### ISSUE TITLE
【系统管理→通知方式】添加短信通知、HTTP调用，页面没有页边距

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1166]
1.选择菜单“系统管理→通知方式”
2.点击【添加】选择【短信通知、HTTP调用】

bug：添加“短信通知、HTTP调用”，页面没有页边距

![1](https://user-images.githubusercontent.com/22296563/26963869-5d0d1c90-4d21-11e7-9c52-633637622d4a.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
fixed
