### ISSUE TITLE
【(设备总览)图标→添加分组】，不能删除新分组

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1167]
1.在平台页面中，选择【设备总览】图标
2.点击【添加分组】，添加多个分组
3.选中新分组，右击选择【删除】
bug：不能删除新分组

![2](https://user-images.githubusercontent.com/22296563/26964447-1589daa4-4d24-11e7-8b49-10b5efc36531.png)

**Comment by eeiceyes** [comment]
添加分组连续添加会出现这个问题
fixed
