### ISSUE TITLE
(敦和资产)netapp储存问题

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#1168]
1、存储卷信息无法获取
2、磁盘信息不匹配，存储管理界面上每个存储有24块盘，但我们界面只显示聚合中的磁盘数
![1](https://user-images.githubusercontent.com/22296563/27017979-6b810d6e-4f5f-11e7-9366-3e9f48984602.png)
![2](https://user-images.githubusercontent.com/22296563/27017980-6bad1062-4f5f-11e7-82a7-8f634eb2bfe7.png)
![3](https://user-images.githubusercontent.com/22296563/27017981-6bb3c560-4f5f-11e7-8495-661adc177a3b.png)
![4](https://user-images.githubusercontent.com/22296563/27017982-6bb7eed8-4f5f-11e7-84c4-0a79d67a488f.png)
![5](https://user-images.githubusercontent.com/22296563/27017983-6bbc6382-4f5f-11e7-9dc9-4a8cbda5e4e2.png)
![6](https://user-images.githubusercontent.com/22296563/27017988-6bfda7f2-4f5f-11e7-9a2e-8ad9870b4640.png)
![7](https://user-images.githubusercontent.com/22296563/27017987-6be80b0e-4f5f-11e7-8fd1-52cee30df1e8.png)
![8](https://user-images.githubusercontent.com/22296563/27017984-6bd37158-4f5f-11e7-9fa4-408655d8e6ef.png)
![9](https://user-images.githubusercontent.com/22296563/27017985-6bdd4c14-4f5f-11e7-8563-b4b479ae90c2.png)
![10](https://user-images.githubusercontent.com/22296563/27017986-6be4f1ee-4f5f-11e7-8207-be7b5758183a.png)

**Comment by runner-mei** [comment]
walk 的数据呢

**Comment by hengweiGR** [comment]
[192.168.40.102.txt](https://github.com/three-plus-three/hw_issues/files/1090421/192.168.40.102.txt)

**Comment by runner-mei** [comment]
[192.168.40.104.txt](https://github.com/three-plus-three/hw_issues/files/1090685/192.168.40.104.txt)
