### ISSUE TITLE
【网络视图】拓扑图超出页面显示时，下拉滚动条被浏览器的下拉滚动条覆盖无法显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1170]
前提条件：
IE浏览器
步骤：
1.选择菜单“运维管理→网络视图“
→BUG：拓扑图超出页面显示时，下拉滚动条被浏览器的下拉滚动条覆盖无法显示。

周边：
1.在谷歌与火狐浏览器上此现象不在线
2.BUG：点击【常用工具】按钮，显示出的常用工具也被TE浏览器滚动条覆盖
![1497246507 1](https://user-images.githubusercontent.com/28615156/27020812-b020d104-4f76-11e7-9e04-a54f8cce5cd6.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
