### ISSUE TITLE
【用户管理】添加用户管理界面，角色文本框中的文字显示不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1171]
步骤：
1.选择菜单“系统管理→用户管理” 
→用户管理页面被表示
2.点击【添加】按钮
→BUG添加用户管理界面，角色文本框中的文字显示不全
![1497247985 1](https://user-images.githubusercontent.com/28615156/27021309-02dedb22-4f7a-11e7-8cac-9bdd0363ae1a.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170719_2532_x64.exe   版本确认，close处理。
