### ISSUE TITLE
【网络视图】添加设备页面，关联的Tag文本框中的文字信息显示不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1172]
步骤：
1.选择菜单“运维管理→网络视图”
→网络视图页面被表示
2.空白地方，鼠标右击，选择“添加设备”
→BUG：添加设备信息框被表示， 关联的Tag文本框中的文字信息显示不全

![1497247985 1](https://user-images.githubusercontent.com/28615156/27021969-4ae09786-4f7e-11e7-947b-a143103fc67d.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170809_2594_x64.exe   版本确认，close处理。
