### ISSUE TITLE
【通知方式】添加通知方式页面，通知用户文本框中的信息显示不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1173]
步骤：
1.点击“系统管理→通知方式”
→通知方式页面被表示
2.点击【添加-电子邮件添加】按钮
→BUG添加通知方式页面中，通知用户文本框中的信息显示不全

周边：
1.添加微信通知方式页面中目标对象文本框同样再现此现象。→BUG
2.维护信息模板选择字段1时，同样再现此现象。→BUG
3.创建子图和创建缩略图的信息框中，过滤文本框同样出现此现象。→BUG
4.执行Ping信息框中的IP地址文本框同样出现此现象。→BUG
5.端口状态告警信息框中的告警条件栏同样出现此现象。→BUG
6.监控总览页面，添加“主机文件信息查看”的参数设置中同样出现此现象。→BUG

![xsx8t3r95hdhng4nu t 8o](https://user-images.githubusercontent.com/28615156/27023281-759534f4-4f84-11e7-808f-4e713eac15cd.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
周边中的，第2、3、4 在Windows版本还再现

**Comment by hengwei-test** [comment]
周边中的，第2、3、4 在Windows版本还再现

**Comment by hengwei-test** [comment]
添加周边6

![1503450751 1](https://user-images.githubusercontent.com/28615156/29594444-7798d2d2-87e3-11e7-8890-34e37f4afe70.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170922_2764_x64.exe  版本确认，close处理。
