### ISSUE TITLE
【通知组】通知组页面点击“添加”按钮，跳转页面错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1174]
步骤：
1.点击“系统管理→通知组”
→通知组页面被表示
2.点击【添加】按钮
→BUG：跳转页面错误
![1497253743 1](https://user-images.githubusercontent.com/28615156/27023826-c8de860e-4f86-11e7-85d0-10cd77ab21ce.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.2.20170821.864~e59ff45.x86_64.rpm    版本确认，close处理。
