### ISSUE TITLE
（kvm）页面单位乱码

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#1175]
![image](https://user-images.githubusercontent.com/14171518/27024212-47bb163a-4f88-11e7-8ee1-9a31d4bbf5de.png)
![image](https://user-images.githubusercontent.com/14171518/27024255-6dc644da-4f88-11e7-890d-bdf86952a1a5.png)

**Comment by runner-mei** [comment]
FIX?
