### ISSUE TITLE
【图元管理】自定义图元管理页面，选择多个图元时，修改删除信息框重复出现

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1176]
步骤：
1.选择菜单“运维管理→网络视图→右击空白处→图元管理”
→图元管理页面被表示
2.鼠标点击依次点击多个图元图标
→BUG：修改删除信息框重复出现

周边：
1.状态图元的图标同样出现此现象

![p 04 2ffsn6 6msyjf i 0](https://user-images.githubusercontent.com/28615156/27063729-fee92386-5025-11e7-9469-af7b9c55804d.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe  版本确认，close处理。
