### ISSUE TITLE
【拓扑导航树】点击工具栏中的【拓扑导航树】按钮，拓扑导航树内容不显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1177]
前提：
1.IE浏览器
2.创建子图信息
3.创建缩略图信息

步骤：
1.打开工具栏，点击【拓扑导航树】按钮
→BUG:拓扑导航树内容不显示

周边：
1.火狐和谷歌浏览器不在现 →OK

![1497322846 1](https://user-images.githubusercontent.com/28615156/27064212-cdd84026-5028-11e7-8105-fb855ad38d87.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170809_2594_x64.exe   版本确认，close处理。
