### ISSUE TITLE
【缩略图】网络视图页面创建缩略图成功后，【根图】按钮不显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1178]
步骤：
1.选择菜单“运维管理→网络视图→右击空白处→创建缩略图”
→弹出“创建缩略图”窗口
2.名称：as，选择全部设备，点击【确定】按钮
→BUG：返回网络视图页面，【根图】按钮不显示

周边：
1.网络视图页面，删除缩略图页面刷新后，在【根图】按钮下还显示缩略图名称→BUG
![1497324488 1](https://user-images.githubusercontent.com/28615156/27064885-49925ba4-502c-11e7-92a0-cdfe2b23c523.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170823_2647_x64.exe 版本确认，添加缩略图后，点击根图显示中没有缩略图的名称
刷新页面后，显示缩略图名称

**Comment by eeiceyes** [comment]
3.2已经fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，close处理。
