### ISSUE TITLE
(韩华新能源)dell存储支持

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#1179]
下图中红框区域未取到数据：

https://github.com/three-plus-three/hw_issues/tree/master/test_data

![1](https://user-images.githubusercontent.com/14171518/27065367-4cb78568-502f-11e7-86ad-0389c0bb8fe2.png)
![2](https://user-images.githubusercontent.com/14171518/27065368-4cc19058-502f-11e7-9dad-f0fe14587db4.png)
![3](https://user-images.githubusercontent.com/14171518/27065370-4ccbd874-502f-11e7-91aa-194d3408d9f2.png)
![4](https://user-images.githubusercontent.com/14171518/27065371-4d41becc-502f-11e7-986f-bfdd04df75bc.png)
![5](https://user-images.githubusercontent.com/14171518/27065369-4ccb4c7e-502f-11e7-8b76-7fbc1b1216d6.png)

**Comment by runner-mei** [comment]
test
