### ISSUE TITLE
【显示设置】显示设置信息框中的选择框与文字重叠

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1181]
步骤：
1.选择菜单“运维管理→网络视图→右击空白处→设备显示设置（默认）”
→BUG：显示设置信息框中的选择框与文字重叠

![1497327283 1](https://user-images.githubusercontent.com/28615156/27066884-dcd650ca-5039-11e7-847a-ce352569159e.jpg)
![1497327352 1](https://user-images.githubusercontent.com/28615156/27066885-dcf45656-5039-11e7-8b72-1f977cb78e7a.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.2.20170823.872~6ca2978.x86_64.rpm 版本确认，还是有显示不全的现象
![1503471010 1](https://user-images.githubusercontent.com/28615156/29602399-93dce72e-8812-11e7-94e2-d675db3a1243.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170922_2764_x64.exe  版本确认，close处理。
