### ISSUE TITLE
【网络视图】执行Ping操作栏中，“可选参数”中的信息与选择框未对齐显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1182]
步骤：
1.选择菜单“运维管理→网络视图→选中设备右击→选择常用工具→点击Ping测试”
→执行信息框被表示
2.点击【可选参数】按钮
→BUG：“可选参数”中的信息与选择框未对齐显示

周边：
1.在采集设置中同样出现此问题→BUG

![1497332259 1](https://user-images.githubusercontent.com/28615156/27067491-b73e16a0-503d-11e7-81cf-5407b4a0a833.jpg)
![1497416246 1](https://user-images.githubusercontent.com/28615156/27116012-1c3c263c-5101-11e7-91bf-29edf3e48392.jpg)

**Comment by eeiceyes** [comment]
已经fixed?

**Comment by hengwei-test** [comment]
ping测试框已经对齐，在采集中还是未对齐

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
