### ISSUE TITLE
【机房视图】编辑机柜里的设备后，点击【确定】按钮后，返回网络视图页面

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1183]
1.点击“机房视图”
→机房视图页面被表示
2.选择机柜右击，选“机柜属性”
→编辑机柜信息框被表示
3.点击IP地址
→选择设备信息框被表示
4选择设备信息框被表示中，点击【确定】按钮
→BUG：页面刷新跳转到网络视图页面

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170809_2594_x64.exe   版本确认，close处理。
