### ISSUE TITLE
【网络视图】网络视图页面鼠标右击，显示选择项出现排版差距过大

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1185]
前提：
火狐浏览器
步骤：
1.选择菜单栏“运维管理→网络视图”
→网络视图页面被表示
2.网络视图页面鼠标右击
→BUG：显示选择项出现排版差距过大
周边：
1.IE与谷歌浏览器不发生此现象

![1497344764 1](https://user-images.githubusercontent.com/28615156/27075038-665c63cc-505b-11e7-8749-0e1234ec54c3.jpg)
![1497344901 1](https://user-images.githubusercontent.com/28615156/27075039-66860d4e-505b-11e7-949d-7bde1f74a988.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170809_2594_x64.exe   版本确认，close处理。
