### ISSUE TITLE
【网络视图】拓扑图放大超过显示页面时，鼠标滚轮上下失效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1186]
前提：
IE浏览器
步骤：
1.选择菜单栏“运维管理→网络视图”
→网络视图页面被表示
2.放大拓扑图，超过页面显示，鼠标滚轮上下滚动
→BUG：鼠标滚轮上下失效

周边：
1.火狐和谷歌浏览器此现象不在现

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2790_x64.exe  版本确认，close处理。
