### ISSUE TITLE
【网络视图】选择端口信息框中，横向缩小选择端口信息框后选择端口栏不缩短

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1187]
步骤：
1.选择菜单栏“运维管理→网络视图→选中设备右击→历史记录查看→端口出流量”
→选择端口信息框被表示
2.横向缩小选择端口信息框
→BUG：选择端口栏不缩短
![g4 bituc kryy3wlwerm rh](https://user-images.githubusercontent.com/28615156/27112841-16b5273c-50ec-11e7-9866-4f5f78733eb6.png)

**Comment by eeiceyes** [comment]
这个不改了

**Comment by hengwei-test** [comment]
了解了
