### ISSUE TITLE
【设备管理】添加设备后获取不到设备相关信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1190]
步骤：
1.选择菜单“运维管理→网络视图→空白地方鼠标右击→添加设备”
→添加设备页面被表示
2.IP地址：192.168.1.141 ，snmp参数：读参数：public，写参数：private，数据添加，点击【确定】按钮
→返回网络视图页面
3.刷新设备，选择设备右击，选择设备属性。
→BUG：获取不到设备相关信息

周边：
1.使用常用工具能获取ping信息和snmp信息

![1497420659 1](https://user-images.githubusercontent.com/28615156/27118123-5bee83d2-510c-11e7-846b-900312aaaf93.jpg)
![1497420701 1](https://user-images.githubusercontent.com/28615156/27118124-5bf33882-510c-11e7-9dd8-b15d76835950.jpg)
![1497420721 1](https://user-images.githubusercontent.com/28615156/27118125-5bfa7fe8-510c-11e7-9770-d0fef771a376.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.2.20170821.864~e59ff45.x86_64.rpm    版本确认，close处理。
