### ISSUE TITLE
【系统管理→通知方式】选择（微信通知，HTTP调用）页面没有页边距

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1191]
1.选择菜单“系统管理→通知方式”
2.在通知组页面中，点击【添加】，选择【微信通知，HTTP调用】
bug：没有页边距
![2](https://user-images.githubusercontent.com/22296563/27120086-da36957e-5114-11e7-95bf-b6f2dc6f6072.png)

**Comment by eeiceyes** [comment]
fixed
