### ISSUE TITLE
【虚拟中心管理】虚拟中心管理页面，不能多个VCenter设备信息一起选择删除

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1194]
前提：
添加多个VCenter设备信息
步骤：
1.点击“虚拟化&存储→虚拟中管理”
→虚拟化中心页面被表示
2.多个设备信息选择，进行删除
→BUG：跳转页面错误，信息没有删除

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.2.20170620_110_x64.exe  版本确认，close处理。
