### ISSUE TITLE
业务视图添加编辑功能，可对其名称与备注信息进行编辑

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#1196]
![image](https://user-images.githubusercontent.com/14171518/27212864-a7946696-5295-11e7-9c44-b9c36f436a97.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe  版本确认，close处理。
