### ISSUE TITLE
账户限定ip登录无效

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#1197]
![image](https://user-images.githubusercontent.com/14171518/27215406-9dcd13b6-52a3-11e7-89ea-4a29a17aea47.png)
限定在192.168.1.144上登录,但是其他主机也可以登录

**Comment by runner-mei** [comment]
我试了没有问题， 请注意网管机上总是能登录的

**Comment by hengweiGR** [comment]
网管机IP：192.168.1.140   新建帐户test 限定在192.168..1.144上可以登录
在网管机上登录test帐户失败，显示被限定
对于网管机和admin的特殊情况在添加用户的地方进行文字说明

**Comment by eeiceyes** [comment]
在登录IP输入域旁边加了说明

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170703_147_x64.exe    版本确认，close处理。
