### ISSUE TITLE
【报表规则管理】添加“中间件负载统计报表”时，弹出的“统计类型”窗口中的对象类型数据表示不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1199]
步骤：
1.点击“报表管理→报表规则管理”
→报表规则管理页面被表示
2.点击“添加”按钮，“中间件负载统计报表”选择
→BUG：“统计类型”窗口中的对象类型数据表示不全

![1497605378 1](https://user-images.githubusercontent.com/28615156/27221068-db5f3af4-52b9-11e7-937b-63dcbe90c3b2.jpg)

**Comment by eeiceyes** [comment]
报表统计目前只支持这个

**Comment by eeiceyes** [comment]
不是bug，其他的类型没做报表

**Comment by hengwei-test** [comment]
了解
