### ISSUE TITLE
【报表规则管理】添加“设备流量端口分析表”页面，点击“端口选择”按钮，弹出的“端口选择”窗口显示不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1200]
前提：
IE浏览器
步骤： 
1.点击“报表管理→报表规则管理”
→报表规则管理页面被表示
2.点击“添加”按钮，“设备流量端口分析表”选择
→添加“设备流量端口分析表”页面被表示
3.点击“端口选择”按钮
→BUG：弹出的“端口选择”窗口显示不全
![nkuly 22rzv z8t4 f8jq](https://user-images.githubusercontent.com/28615156/27221461-40f1550e-52bb-11e7-80e4-1fae286c0fda.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
设备端口使用情况报表和设备运行情况报表 还出现此现象

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170801_238_x64.exe     版本确认，close处理。
