### ISSUE TITLE
【报表管理】添加“设备端口使用情况报表”页面，页面名称未被表示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1201]
步骤：
1.点击“报表管理-报表规则管理”
→报表规则管理页面被表示
2. 点击“添加”按钮
→添加下拉菜单被表示
3.“设备运行情况报表”选择
→BUG:添加“设备端口使用情况报表”页面，页面名称未被表示

周边：
1.设备运行情况报表同样出现此现象→BUG
2.设备运行情况报表的页面名称出现错误→BUG

![1497836821 1](https://user-images.githubusercontent.com/28615156/27266512-7952674c-54d4-11e7-92a8-020196048a91.jpg)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
页面名称前面的图标不显示

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170628_139_x64.exe     版本确认，close处理。
