### ISSUE TITLE
【机房视图】机房视图页面，点击工具栏中的“机房管理”图标，机房视图信息不显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1206]
前提：
1.IE浏览器
2.有机房和机柜的信息存在
步骤：
1.点击“运维管理→机房视图”
→机房视图页面被表示
2.点击工具栏中的“机房管理”图标
→BUG：机房视图信息不显示
周边：
1.谷歌和火狐浏览器不再现此现象。
![yvoezyu4l5j_3e i yu8dq](https://user-images.githubusercontent.com/28615156/27280683-68e82f12-551b-11e7-8451-c3e1987fbb55.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.2.1.20170621.25~1b90bf8.x86_64.rpm    版本确认，close处理。
