### ISSUE TITLE
【脚本管理】脚本管理页面添加的脚本不能删除

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1208]
前提：
1.添加多个脚本信息
步骤：
1.点击“系统管理→脚本管理”
→脚本管理页面被表示
2.脚本浏览信息框中，点击脚本删除按钮
→BUG：脚本无法删除

**Comment by hengwei-test** [comment]
优先级：高

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-2.3.20170620.659~b471344.x86_64.rpm  版本确认，close处理。

**Comment by hengwei-test** [comment]
tpt-3.2.1.20170621.25~1b90bf8.x86_64.rpm    版本确认，close处理。
