### ISSUE TITLE
【告警管理→告警规则】触发告警会连续发两条通知信息

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1209]
选择菜单“告警管理→告警规则”（微信通知，邮件通知）

注意：通知方式设置重复次数不管设置多少都会连续会两条

bug：触发告警通知信息会连续发两条，，有时候触发通知会延迟半个小时以上才会发送通知。
![2](https://user-images.githubusercontent.com/22296563/27327779-43f4bc3a-55e2-11e7-9e37-68084577f97e.png)

**Comment by runner-mei** [comment]
请确认是不是规则中重复发送设置导致的
