### ISSUE TITLE
[巡检结果]巡检结果页面的巡检报表下载出错

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1210]
步骤：
1.点击“运维管理→巡检结果查询”
→跳转到“巡检结果查询页面”
2.选择需要下载的巡检结果报告，点击“下载报告”按钮
→BUG：跳转页面出现“下载错误”文言
![1498013916 1](https://user-images.githubusercontent.com/28615156/27365082-b0ab9d92-5670-11e7-8554-5df6b0e25426.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.2.1.20170621.25~1b90bf8.x86_64.rpm    版本确认，close处理。
