### ISSUE TITLE
[设备总览]生成设备树失败

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1211]
在IT运维管理平台界面图标中，点击【设备总览】
bug：[设备总览]生成设备树失败

![3](https://user-images.githubusercontent.com/22296563/27368409-f245b102-5684-11e7-978c-b8b3c2fa788b.jpg)

**Comment by eeiceyes** [comment]
明天再确认下

**Comment by xiauye** [comment]
把设备树根源删除，但本身没有删除。但是必须手动刷新设备树才会再次出现。

提议：要么不让删除设备树根源，要么就能添加设备树根源，或者做一个提示
