### ISSUE TITLE
[数据管理→地址簿运行日志]两个搜索按钮，没有跟输入框对齐

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1212]
选择菜单【数据管理→地址簿运行日志】
bug：两个搜索按钮，没有跟输入框对齐
![4](https://user-images.githubusercontent.com/22296563/27369805-377bea14-568c-11e7-8234-b8c983c6327c.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
ok
