### ISSUE TITLE
[监控总览]监控总览页面只要一个默认面板组情况。删除默认面板组后，再次进入监控总览页面出现错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1214]
前提
监控总览只要一个面板组
步骤：
1.点击“运维管理→监控管理”
2.删除默认面板组
3.再次点击“运维管理→监控管理”
→BUG：总览页面出现错误

[web_server.zip](https://github.com/three-plus-three/hw_issues/files/1094276/web_server.zip)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170703_147_x64.exe     版本确认，close处理。
