### ISSUE TITLE
[服务总览]服务总览中数据库的显示设置的显示指标的选项无法清除

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1215]
步骤：
1.点击“运维管理→服务总览”
2.Oracle数据库栏中点击设置监控项
3.显示指标中的活动会话数选择
4.返回服务总览页面刷新，Oracle显示活动会话数监控图标
5.再次Oracle数据库栏中点击设置监控项
6.显示指标中的活动会话数选择清除
→BUG：返回服务总览页面刷新，Oracle显示活动会话数监控图标不清除，显示设置中活动会话数选择未清除

![1499064655](https://user-images.githubusercontent.com/28615156/27781285-cf329b7e-5fff-11e7-98dc-a0f92d51b3f3.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
在hengwei_setup_2.3.20170703_147_x64.exe 版本确认BUG现象还在现，
添加图片：1499064655.jpg

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170712_163_x64.exe 版本确认，close处理。
