### ISSUE TITLE
[线路流量监控]上下行流量监控信息窗口中的“上下行流量”文字乱码

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1216]
前提：
IE浏览器
步骤：
1.点击“监控管理→线路流量监控→上下行流量”
→BUG：弹出上下行流量信息窗口中的“上下行流量”文字乱码

周边：
1.火狐和谷歌浏览器不在线
2.上下行帧流量信息窗口同样在线次现象→BUG

![1498195715 1](https://user-images.githubusercontent.com/28615156/27467971-5483524e-5819-11e7-8567-8ae82977cb58.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170703_147_x64.exe    版本确认，close处理。
