### ISSUE TITLE
[报表管理]报表规则管理页面，选择规则点击立刻生成，在生成报表查看页面没有显示立刻生成的报表

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1217]
前提：
1.IE浏览器
2.添加任意一条报表规则
步骤：
1.点击“报表管理→报表规则管理”
2.选择要生成的规则，点击"立刻生成"按钮
3.点击“报表管理→生成报表查看”
→BUG：立刻生成的报表规则的信息，没有生成报表信息

周边
1.火狐和谷歌浏览器没有出现此现象

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170703_147_x64.exe    版本确认，close处理。
