### ISSUE TITLE
WinRM, Wbem, WMI 等访问参数在 3.2 版本中不能正确地保存

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#1218]
WinRM, Wbem, WMI 等访问参数不能正确地保存
这些参数中原来的 用户名和密码保存在 user_name 和 user_password 字段中
而到了 3.2 中变成了 user 和 password 字段。

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170704_2463_x64.exe  版本确认，close处理。
