### ISSUE TITLE
[登录]用户名密码输入错误三次，没有锁定

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1219]
登录用户名密码输入错误三次，没有锁定
![1](https://user-images.githubusercontent.com/22296563/27523906-3151c818-5a63-11e7-93a6-18d04619f896.jpg)

**Comment by runner-mei** [comment]
你确定是三次， 我忘得是 4 次吧

**Comment by xiauye** [comment]
我的不知道输入多少次，一直没有锁定。

**Comment by runner-mei** [comment]
admin 用户不锁定

**Comment by eeiceyes** [comment]
fixed
