### ISSUE TITLE
[报表管理]自定义统计数据页面，规则信息的轮询记录间隔的参数无法修改

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1221]
前提：
添加一条自定义统计数据
步骤：
1.点击“报表管理→自定义统计数据”
2.规则的轮询时间间隔参数点击
3.轮询间隔选择别的时间，点击“确定”按钮
→BUG：提示显示的规则已经不存在
![1498463879 1](https://user-images.githubusercontent.com/28615156/27529829-965b8094-5a88-11e7-8566-a1a3b478200e.jpg)

**Comment by eeiceyes** [comment]
规则是按指标和轮询间隔来区别唯一性的，这个提示表示另一个“指标相同但轮询间隔不同”的规则已经存在，不是bug

**Comment by hengwei-test** [comment]
轮询间隔的时间修改后，页面刷新后轮询间隔返回初始值

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
