### ISSUE TITLE
[报表管理]预置报表查看页面，报表信息删除后浏览器刷新后报表信息自动复原

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1222]
前提：
预置报表查看页面存在报表信息
步骤;
1.点击“报表管理→预置报表查看”
2.所有的报表信息删除
3.浏览器刷新
→BUG：报表信息删除后浏览器刷新后报表信息自动复原

[web_server.zip](https://github.com/three-plus-three/hw_issues/files/1101498/web_server.zip)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170703_147_x64.exe    版本确认，close处理。
