### ISSUE TITLE
[数据库管理]添加的数据库时，点击“测试访问参数”按钮时，测试不通过

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1223]
步骤：
1.点击“资源管理→数据库管理”
2.点击“添加”按钮
3.数据类型选择“MySQL”，正确的信息填入
4.点击“测试访问参数”
→BUG：测试不通过
![1498533141 1](https://user-images.githubusercontent.com/28615156/27569850-725d5862-5b2c-11e7-98e6-be48ffb01a7b.jpg)

**Comment by runner-mei** [comment]
你看看错误描述，没有问题啊

**Comment by hengwei-test** [comment]
问题已经了解，解决了
