### ISSUE TITLE
[报表管理]预置报表查看页面，查看选择框中选择“所有生成的报表”，显示的报表信息是生成报表查看页面的报表信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1224]
前提：
生成报表查看页面中有报表生成的信息
步骤：
1.点击“报表管理→预置报表查看”
2.预置报表查看页面，查看的信息选择“所有生成的报表”
→BUG：显示的报表信息是生成报表查看页面中的报表信息，不是预置报表的信息
周边：
1.“最近一周生成的报表”选择同样出现此现象→BUG

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170703_147_x64.exe    版本确认，close处理。
