### ISSUE TITLE
[用户操作日志]用户操作页面的数据，导出后的数据不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1231]
前提：
确认用户操作页面的数据个数
步骤
1.点击“系统管理→用户操作日志”
2.点击“导出”按钮
→BUG：导出的数据确认，丢失2条操作数据
![1498718554 1](https://user-images.githubusercontent.com/28615156/27674723-74d9268a-5cd9-11e7-941f-570efc9ca3e5.jpg)
![1498718606 1](https://user-images.githubusercontent.com/28615156/27674724-74db090a-5cd9-11e7-9f8d-b2dcd66d337f.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170703_2456_x64.exe       版本确认，close处理。
