### ISSUE TITLE
[用户操作日志]用户操作日志页面，在选择时间窗口中，月份不显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1232]
步骤：
1.点击“系统管理→用户操作日志”
2.点击起始时间信息框
→BUG：月份显示框中的时间空白表示
周边：
1.巡检结果页面的时间框同样再现此现象→BUG
2.告警日志页面的时间框同样再现此现象→BUG
3.设备日志页面的时间框同样再现此现象→BUG
4.Syslog查询页面的时间框同样再现此现象→BUG
5.SnmpTrap查询页面的时间框同样再现此现象→BUG
6.记录数据查询页面的时间框同样再现此现象→BUG
7.流量数据查询页面的时间框同样再现此现象→BUG
8.生成报表查看页面，的导出报表的生成时间框同样再现此现象→BUG
9.预置生成报表查看页面，的导出报表的生成时间框同样再现此现象→BUG

![1498719192 1](https://user-images.githubusercontent.com/28615156/27675522-fb6050fe-5cdc-11e7-84bc-d5a2eca2ca15.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
结束时间月份只显示1个月份错误：
步骤：
1.点击：“监控管理→告警日志”
2.起始时间点击：当前月份选择，页面空白鼠标左键点击
3.结束时间点击，选择月份查看
→BUG：结束时间月份显示不全

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
巡检结果页面的时间，首次选择“时间晚于”时只显示当前系统时间前的月份，当点击“提交早于”后，再次点击“时间晚于”时只显示全部的月份。参考图片：1-1
![1-1](https://user-images.githubusercontent.com/28615156/28403416-2b16e044-6d57-11e7-905b-dd24c44ec678.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，close处理。
