### ISSUE TITLE
[监控管理]告警管理子菜单栏中“组合告警”现在，告警管理子菜单栏关闭

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1233]
前提：
不隐藏菜单栏
步骤：
1.点击“告警管理”
2.点击“组合管理”
→BUG：跳转到组合告警页面，告警管理子菜单栏关闭

周边;
点击告警管理栏中别的选项，不发送此现象

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170809_2594_x64.exe   版本确认，close处理。
