### ISSUE TITLE
[Ping测试]Ping测试执行窗口，点击“关闭”按钮，页面锁定操作无效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1234]
步骤：
1.点击“常用工具→Ping测试”
2.Ping执行窗口，点击“关闭”按钮
→BUG：页面锁定操作无效

周边：
1.Trace Route执行窗口同样出现此现象→BUG
2.Dig执行窗口同样出现此现象→BUG
3.网络视图页面，选中设备右击菜单中常用工具此现象不在现
4.工具栏中的常用工具此现象不在现

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170703_2456_x64.exe       版本确认，close处理。
