### ISSUE TITLE
[四川省肿瘤医院]oracle数据库问题

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1235]
oracle数据库表空间监控页面缺少信息、表空间使用计量单位太大，无法体现细节。

![52dc6f40d6b2d024724a9a627526324a](https://user-images.githubusercontent.com/28615156/27680579-cd0448f2-5cee-11e7-8784-db34c4a8951c.jpg)
![b9e0e917fea5232e091151371c3540eb](https://user-images.githubusercontent.com/28615156/27680578-cd0043e2-5cee-11e7-801c-2f534687446a.jpg)
![b617c9eb96255f76cde9b910d7e6faf8](https://user-images.githubusercontent.com/28615156/27680576-cc7bb5f0-5cee-11e7-9df3-4b1d5a56faab.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170712_163_x64.exe 版本确认，close处理。
