### ISSUE TITLE
[FTP服务器]FTP服务器上传备份文件时，上传信息框中没有“上传成功”和“上传失败”信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1236]
步骤：
1.点击“系统管理→服务器设置”
2.点击“FTP服务器”
3.FTP服务器信息正确输入，点击“立刻上传配置备份”按钮
→BUG：上传信息框中没有“上传成功”和“上传失败”信息

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170703_2456_x64.exe       版本确认，close处理。
