### ISSUE TITLE
[邮件服务器]邮件服务器添加一个测试功能，确认账号密码信息是否正确

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1237]

**Comment by eeiceyes** [comment]
2.3和3.3修复

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20180125_700_x64.exe   版本确认无问题；

hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，出现此现象
![default](https://user-images.githubusercontent.com/28615156/35421475-6192f376-027e-11e8-891f-cbd55e1acaad.png)
