### ISSUE TITLE
[图元管理]图元修改没有发生改变

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1239]
选择菜单" 系统管理→图元管理"
bug：图元修改没有发生改变

![1](https://user-images.githubusercontent.com/22296563/27719192-3fde7eda-5d83-11e7-81e7-f89702f0e240.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170729_232_x64.exe  版本确认，BUG现象还在现

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
bug还是存在

**Comment by eeiceyes** [comment]
fixed
