### ISSUE TITLE
[线路显示设置（默认）]添加的自定义不能取消显示

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1240]
1.选择菜单“运维管理→网络视图→空白处右击→线路显示设置（默认）
2.在线路显示默认窗口中，点击【添加自定义】
bug：自定义显示设置不能取消，勾选去掉重新打开还是存在
![2](https://user-images.githubusercontent.com/22296563/27723455-ba0f22c4-5d9f-11e7-8147-20a2ca19693b.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
ok
