### ISSUE TITLE
[线路显示设置]添加自定义显示设置，无法取消

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1241]
1.选择菜单“运维管理→网络视图→选择线路右击→显示设置”
2.在线路显示窗口中，点击【添加自定义】
bug：添加的自定义在线路显示出来，但是再打开添加的自定义不存在了，无法取消
![3](https://user-images.githubusercontent.com/22296563/27723551-4e922590-5da0-11e7-8f08-2b5b67248c88.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
ok
