### ISSUE TITLE
[通知组]添加通知组页面，点击“确定”按钮后，跳转页面错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1243]
前提：
添加邮件通知方式
步骤：
1.点击“系统管理→通知组”
2.点击“添加”按钮
3.信息输入，通知方式：邮件，点击“确定”按钮
→BUG：跳转页面错误

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170703_2456_x64.exe       版本确认，close处理。
