### ISSUE TITLE
[通知方式]部分通知方式无法跳转到编辑页面

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1244]
前提;
添加数据库通知方式
步骤;
1.点击“系统管理→通知方式”
2.选择数控的通知方式，点击“编辑”按钮
→BUG：无法跳转到编辑页面
周边;
1.http调用/外部程序通知同样出现此现象→BUG

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170703_2456_x64.exe       版本确认，close处理。
