### ISSUE TITLE
[四川省肿瘤医院]主机、数据库告警无法区分具体条目

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1251]
主机文件系统、数据库告警触发后无法区分具体条目。
告警通知只知道当前有告警，无法判断告警具体对象是主机的哪个分区，告警值多少；数据库的哪张表，具体值多少。都需要用户进行二次判断。
![img_20170629_190311](https://user-images.githubusercontent.com/28615156/27845815-fe93acb2-6164-11e7-88a1-089302e48f6f.jpg)
![img_20170629_190451](https://user-images.githubusercontent.com/28615156/27845876-7de9e65c-6165-11e7-9579-9fd10f26fd20.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170718_191_x64.exe    版本确认，close处理。
