### ISSUE TITLE
[常用工具]设备配置查看页面，点击"规则状态"按钮，信息框中的格式信息显示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1253]
步骤：
1.点击“常用工具→设备配置查看”
2.点击"规则状态"按钮
→BUG：信息框中的格式信息显示错误

![1499221575 1](https://user-images.githubusercontent.com/28615156/27847621-50b4d53c-6171-11e7-8a21-4e5c98bcbab8.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170830_2674_x64.exe   版本确认，close处理。
