### ISSUE TITLE
[资产管理]选择时期可以手动输入

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1255]
[资产管理]例如：合同，选择有效时期可以准确的实现手动输入
![2](https://user-images.githubusercontent.com/22296563/27852105-6368e3a2-6190-11e7-867f-930dd38879d4.png)

**Comment by hengwei-wtk** [comment]
已经修改

**Comment by xiauye** [comment]
日期控件手动输入还是存在问题。   
![image](https://user-images.githubusercontent.com/22296563/29348554-1e2f9318-8287-11e7-9309-c8eed349880e.png)
