### ISSUE TITLE
[资产管理]合同：所有添加的附件，提供查看，下载的功能

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1256]
[资产管理]合同：所有添加的附件，提供查看，下载的功能
![3](https://user-images.githubusercontent.com/22296563/27852302-3b3bae4a-6191-11e7-8b33-1b47402c465d.png)

**Comment by hengwei-wtk** [comment]
下载功能已经实现  在线查看附件功能，重新提一个需求

**Comment by xiauye** [comment]
ok
