### ISSUE TITLE
[监控管理]实时监控画面，点击管理对象框时，“启动”与“导出”按钮图片在页面发生移动

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1257]
前提：
IE浏览器
步骤：
1.点击“监控管理→实时监控”
2.点击“管理对象框”
→“启动”与“导出”按钮图片在页面发生移动
周边:
火狐和谷歌浏览器不再现
![1499237457 1](https://user-images.githubusercontent.com/28615156/27852491-f8de827e-6191-11e7-8162-e18d181b0d3d.jpg)
![1499237676 1](https://user-images.githubusercontent.com/28615156/27852492-f8f9b4fe-6191-11e7-9cf9-f114a4431da6.jpg)

**Comment by eeiceyes** [comment]
影响很小，暂不解决

**Comment by eeiceyes** [comment]
3.3fixed
