### ISSUE TITLE
[监控管理]设备运行图页面，端口信息栏选择第二页，端口信息框页面格式出错

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1258]
前提：
1.添加路由器：192.168.1.172
步骤：
1.点击“监控管理→设备运行视图”
2.选择对象框中，选择“192.168.1.170”
3.设备运行视图页面，端口信息栏中选择第二页
→BUG：端口信息框页面格式出错
![1499246339 1](https://user-images.githubusercontent.com/28615156/27858318-632279fa-61a7-11e7-854f-e7269e78281d.jpg)

**Comment by eeiceyes** [comment]
fixed
