### ISSUE TITLE
[虚拟化视图]运行视图，没有显示出来

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1259]
1.选择菜单“运维管理→虚拟化视图→选中设备右击→运行视图”
bug：内存、CPU使用率，没有显示出来
![2](https://user-images.githubusercontent.com/22296563/27900678-e13d7b0e-6261-11e7-8d9e-0f410b47441f.png)

**Comment by runner-mei** [comment]
以后记得，这种 bug, 请先直接取数看一下，是前台还是后台取数的问题
