### ISSUE TITLE
[常用工具]配置备份规则页面中“立刻备份”按钮的图标不对

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1262]
步骤：
1.点击“常用工具→配置备份规则”
→BUG：“立刻备份”按钮的图标不对
![1499653095 1](https://user-images.githubusercontent.com/28615156/28000588-2ebeaf0c-6559-11e7-9184-459624ea1a96.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170713_181_x64.exe  版本确认， 立即备份 图标隐藏
