### ISSUE TITLE
[线路显示设置]线路显示设置的显示属性窗口所有的选项选择，点击“应用”按钮，弹出“保存设置失败”提示窗

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1265]
步骤：
1.点击“运维管理→网络视图”
2.选择的线路，鼠标右击选择“显示设置”
3.线路显示设置窗口选择“显示属性”
4.显示属性窗口所有的属性选择，点击“应用”按钮
→BUG：弹出“保存设置失败”提示窗
![1499755724 1](https://user-images.githubusercontent.com/28615156/28054763-d2b35834-6648-11e7-884c-ee06bebdb5d6.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_219_x64.exe     版本确认，close处理。
