### ISSUE TITLE
[线路显示设置]线路显示设置窗口，添加的自定义指标中，指标选择框只有一个选项

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1266]
步骤：
1.点击“运维管理→网络视图”
2.选择的线路，鼠标右击选择“显示设置”
3.点击“添加自定义”按钮
4.自定义指标栏中，点击指标选择框
→BUG：只有一个“线路流量”选择项

![1499759266 1](https://user-images.githubusercontent.com/28615156/28058787-656a157c-6654-11e7-9710-0e8e4f10764c.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
