### ISSUE TITLE
[服务总览]MySQL数据库的对象显示设置窗口的自定义指标中指标选择“会话信息”后，再次更改别的指标，指标获取栏信息不变

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1267]
前提:
添加一个MySQL数据库信息
步骤:
1.点击“运维管理→服务总览”
2.点击添加的MySQL数据库的“设置监控项”按钮
3.对象显示设置窗口点击“添加自定义”按钮
4.选择“启用”，指标栏选择“会话信息”，点击“应用”，点击“关闭”按钮
5.点击添加的MySQL数据库的“设置监控项”按钮
6.指标栏选择“版本号”
→BUG：选择别的指标，指标取值栏中的信息不变

周边：
1.SqlServer数据库同样出现此现象→BUG
2.DB2数据库同样出现此现象→BUG
3.Sybase数据库同样出现此现象→BUG
4.中间件中同样出现此现象→BUG

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
