### ISSUE TITLE
[历史记录规则]MySQL数据库的会话信息记录规则的记录指标修改后，在编辑页面中不可以修改记录数据的总数

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1268]
前提：
1.添加MySQL数据库信息
2.添加历史记录规则：管理对象：MySQL数据库，参数设置：会话信息-总数据行数-记录所有数据的总行数，基本信息：启用-5分钟。参考图片：1-1
步骤：
1.点击"报表管理→历史记录规则"。
2.点击mysql记录规则的，记录指标中的“所有数据行”。
3.会话信息窗口第二条数据选择并且确定。参考图片：1-2
4.选择mysql记录规则，点击编辑按钮
→BUG：编辑页面中不可以修改记录数据的总数。参考图片：1-3
![1-1](https://user-images.githubusercontent.com/28615156/28100535-3b565466-66f5-11e7-8fdd-0da276a47991.jpg)

![1-2](https://user-images.githubusercontent.com/28615156/28100534-3b54aca6-66f5-11e7-8de2-1d5b7fb35126.jpg)

![1-3](https://user-images.githubusercontent.com/28615156/28100536-3bb8161a-66f5-11e7-9c45-bb5eca332474.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
