### ISSUE TITLE
[历史记录规则]MySQL的历史记录规则编辑后不成功

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1269]
前提：
1.添加MySQL数据库信息
2.添加历史记录规则：管理对象：MySQL数据库，参数设置：会话信息-总数据行数-记录所有数据的总行数，基本信息：启用-1分钟。参考图片：2-1
步骤：
1.点击“报表管理→历史记录规则”。
2.选择mysql数据库的历史记录规则，点击“编辑”按钮。
3.编辑规则页面，记录指标的参数修改，点击“确定”按钮。参考图片：2-2
→BUG:修改后的规则在历史记录规则页面，未编辑成功。参考图片：2-3

![2-1](https://user-images.githubusercontent.com/28615156/28100956-fceb6506-66f7-11e7-81d7-c242fecfbe2e.jpg)

![2-2](https://user-images.githubusercontent.com/28615156/28100958-fd0a9124-66f7-11e7-98f9-d8a6a5956bea.jpg)

![2-3](https://user-images.githubusercontent.com/28615156/28100957-fd07afea-66f7-11e7-9678-269ff9b2cb16.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
