### ISSUE TITLE
[历史记录规则]添加的MySQL数据库参数设置，在会话信息窗口的信息显示不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1270]
前提：
1.添加MySQL数据库信息
步骤：
1.点击“报表管理→历史记录规则”
2.点击“添加”按钮
3.选择 ：管理对象：MySQL数据库，参数设置：会话信息-总数据行数-记录[命令=Sleep]的总数，基本信息：启用-5分钟。点击确定按钮
4.历史记录规则页面，mysql记录规则中“记录指标”的参数“命令=Sleep”鼠标左击
→BUG：会话信息窗口的依据列栏没有信息显示

![3-1](https://user-images.githubusercontent.com/28615156/28102368-4f0f292c-6701-11e7-896c-e1e26a665180.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
