### ISSUE TITLE
[服务总览]MySQL数据的默认显示设置窗口的自定义指标点击“应用”按钮，弹出“保存设置失败”提示框

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1273]
前提：
添加MySQL数据库
步骤;
1.点击“运维管理→服务总览”
2.点击“MySQL”的设置监控项
3.默认显示设置窗口，点击“添加自定义”按钮
4.默认显示设置窗口，点击“应用”按钮
→BUG：弹出“保存设置失败”提示框
![1499845931 1](https://user-images.githubusercontent.com/28615156/28108146-1cc0dc42-671d-11e7-9bda-9808fd33ef4b.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
