### ISSUE TITLE
[服务总览]mysql的表空间窗口没有左右滚动条

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1274]
前提：
1.添加MySQL数据库
步骤：
1.点击“运维管理→服务总览”
2.点击mysql数据库的“表空间”按钮
→BUG：mysql的表空间窗口没有左右滚动条

周边：
1.SqlServer数据库同样出现→BUG
2.DB2数据库同样出现→BUG

![1499847347 1](https://user-images.githubusercontent.com/28615156/28108823-6ecac438-671f-11e7-946c-2ada435dc9cc.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170724_208_x64.exe     版本确认，close处理。
