### ISSUE TITLE
[服务总览]打开SqlServer数据库的“Checkpoint writes (pages/s) ”监控项的窗口时，弹出加载信息失败提示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1275]
前提：
1.添加SqlServer数据库
步骤:
1.点击“运维管理→服务总览”
2.点击SqlServer数据库的“设置监控项”按钮
3.对象显示设置窗口中，选择“Checkpoint writes (pages/s) ”，点击应用按钮
4.服务总览页面，点击SqlServer数据库的“Checkpoint writes (pages/s) ”监控项图标
→BUG：弹出加载信息失败信息

![1499849303 1](https://user-images.githubusercontent.com/28615156/28109808-f49ea270-6722-11e7-92e3-9d487f930bfd.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
