### ISSUE TITLE
[显示设备]选择(显示属性)任意选择一个勾选，提示失败，也能显示出来。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1277]
所有的拓扑图，[显示设备]显示属性任意选择一个勾选，点击【应用】， 提示保存设置失败，但是还是显示出来了，有得显示出来了，取消不掉。

![4](https://user-images.githubusercontent.com/22296563/28152793-d7800118-67d4-11e7-821c-a5fae44e59a3.png)
![5](https://user-images.githubusercontent.com/22296563/28152794-d7a862b6-67d4-11e7-89d2-9bd46cd7e41e.png)

**Comment by eeiceyes** [comment]
fixed
