### ISSUE TITLE
[业务视图]显示图元，图片没有显示出来

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1278]
[业务视图]空白处右击→添加视图节点
bug：显示图元图片没有显示出来

![1](https://user-images.githubusercontent.com/22296563/28153275-310be1b4-67d7-11e7-9651-d31d9a450bf9.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
还是没有显示出来

**Comment by eeiceyes** [comment]
fixed
