### ISSUE TITLE
路由交换设备端口告警添加接口名称

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#128]
在告警规则中》添加路由交换设备告警 》 "端口描述"》状态 》"所有数据行"

1.状态 为空；没有状态；
2.缺少端口名称； 

![image](https://cloud.githubusercontent.com/assets/14171497/12168393/d14f722c-b56c-11e5-8974-c45281ce65a7.png)

**Comment by runner-mei** [comment]
看看修好了没有

**Comment by xiauye** [comment]
还是没有

**Comment by eeiceyes** [comment]
指标模型定义不对，端口描述不应该有状态字段

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170922_2764_x64.exe  版本确认，close处理。
