### ISSUE TITLE
[业务视图]添加视图节点，提示添加失败，但是视图还是添加了。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1280]
[业务视图]空白处右击→添加视图节点
bug：提示添加失败，但是视图节点也添加了。
![2](https://user-images.githubusercontent.com/22296563/28153472-208e8f70-67d8-11e7-9fe8-b1d66e92e552.png)
![3](https://user-images.githubusercontent.com/22296563/28153473-2096a304-67d8-11e7-9c43-d6b992cb8af8.png)

**Comment by eeiceyes** [comment]
移到m19继续观察

**Comment by eeiceyes** [comment]
好久没重现了
