### ISSUE TITLE
[资源管理]设备类型“服务器”的设备信息添加“Tag”标签时，在设备属性窗口没有Tag标签属性

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1282]
前提：
添加一台设备类型为“服务器”的设备
步骤;
1.点击“资源管理→Tag列表”
2.点击名称“主干线路”，关联对象窗口选择设备类型为“服务器”的IP
3.网络视图页面，添加主干线路标签的设备图标，右击选择“设备属性”
→BUG:在设备属性窗口没有Tag标签属性

周边：
设备类型为“交换路由”、“路由器”、“交换机”的设备在设备属性窗口有Tag标签属性

![1500009082 1](https://user-images.githubusercontent.com/28615156/28199514-c342c022-6898-11e7-9168-b11d98100ae7.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170714_185_x64.exe    版本确认，close处理。
