### ISSUE TITLE
[Tag列表]添加同名的Tag标签时，弹出的“同名标签存在”提示框关闭后，页面灰色表示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1283]
步骤：
1.点击“资源管理→Tag列表”
2.点击“添加”按钮，添加名称为“z”的标签
3.再次点击“添加”按钮，添加名称为“z”的标签
4.弹出“同名标签存在”提示框，点击“确定”按钮
→BUG;“同名标签存在”提示框关闭，页面灰色表示

![1500010551 1](https://user-images.githubusercontent.com/28615156/28199655-f8c78dda-6899-11e7-9bbc-93339060a91d.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170714_185_x64.exe    版本确认，close处理。
