### ISSUE TITLE
[运行时段设置]运行时刻段设置页面，每周的每一天都不选择时，点击“确定”按钮，页面刷新每周选项都被选择

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1284]
步骤：
1.点击“资源管理→运行时段设置”
2.每周选项中都不选择，点击“确定”按钮
→BUG:页面刷新每周选项都被选择
周边：
1.网络线路同样出现此现象→BUG
2.数据库同样出现此现象→BUG
3.中间件同样出现此现象→BUG
4.标准应用同样出现此现象→BUG
5.添加告警规则时候同样出现此现象→BUG

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170829_2669_x64.exe  版本确认，close处理。
