### ISSUE TITLE
[监控一览]添加并同步一台正确的VCenter设备信息后，添加一台错误的VCenter设备信息，在监控一览页面错误的VCenter设备信息被获取

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1286]
前提;
添加并同步一台正确的VCenter设备信息后
步骤：
1.点击“虚拟机&存储→虚拟中心管理”
2.点击“添加”按钮，输入错误的信息，点击“确定”按钮
3.点击“虚拟机&存储→监控一览”
→BUG:错误的VCenter设备信息被获取

![1500015654 1](https://user-images.githubusercontent.com/28615156/28202106-79766350-68a6-11e7-93ac-c74039c38a29.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170714_185_x64.exe    版本确认，close处理。
