### ISSUE TITLE
[ESX/ESXI主机管理]虚拟机管理页面删除一台虚拟机设备信息，ESX/ESXI主机管理页面的虚拟机数未更新

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1287]
步骤：
1.点击“虚拟化&存储→虚拟机管理”。
2.虚拟机管理页面删除一条节点信息。 参考图片：1-1
3.点击“虚拟化&存储→ESX/ESXI主机管理”。
→BUG：ESX/ESXI主机管理页面的虚拟机数未更新。 参考图片：1-2

![1-1](https://user-images.githubusercontent.com/28615156/28203746-93a2a7e6-68ad-11e7-9118-1cd9674d1d5a.jpg)

![1-2](https://user-images.githubusercontent.com/28615156/28203747-93a7efb2-68ad-11e7-9100-b276886ea7ab.jpg)

**Comment by eeiceyes** [comment]
那个虚拟机数代表的是从虚拟中心读取到的数量，和虚拟中心同步时会更新，在网管系统删除虚拟机时，数量是不会变化的，所以不是bug

**Comment by hengwei-test** [comment]
了解
