### ISSUE TITLE
[数据存储管理]数据存储管理页面的信息添加备注信息是，弹出的备注框被显示不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1288]
步骤：
1.点击“虚拟机&存储→数据存储管理”
2.点击节点信息中的备注信息
→Bug:弹出的备注框被显示不全

![11](https://user-images.githubusercontent.com/28615156/28204517-d5a5726a-68b0-11e7-8a8c-31d5e59972eb.jpg)

**Comment by eeiceyes** [comment]
显示位置改到左边了

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
