### ISSUE TITLE
[设备配置模板]设备配置模板页面，能够添加同名的模板信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1289]
步骤：
1.点击“常用工具→设备配置模板”
2.点击“添加模板”按钮
3.添加名称：z-1等模板
4.再次点击“添加模板”按钮
5.添加名称：z-1等模板，点击“确定”按钮
→BUG:同名的模板信息能够添加

![1500024604 1](https://user-images.githubusercontent.com/28615156/28207066-e6d65842-68ba-11e7-8252-9f7edb89c4d7.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
