### ISSUE TITLE
[生成报表查看]线路流量报表中线路流量的单位还是“b/s”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1290]
前提：
添加线路流量的报表规则信息
步骤：
1.点击“报表管理→生成报表查看”
2.查看生成的线路流量的报表信息
→BUG：线路流量报表中线路流量的单位还是“b/s”

![1500258701 1](https://user-images.githubusercontent.com/28615156/28254051-eb120b22-6adb-11e7-94f7-c1db1ab95335.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170717_188_x64.exe   版本确认，close处理。
