### ISSUE TITLE
[Syslog查询]无法发送中文的Syslog消息到管理平台

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1292]
步骤：
发送Syslog消息为中文时候，平台无法识别
添加log：logging.zip

[logging.zip](https://github.com/three-plus-three/hw_issues/files/1151905/logging.zip)

**Comment by runner-mei** [comment]
这个不是问题，只不过我只支持 utf-8 而已

**Comment by runner-mei** [comment]
在界面上增加一个选字符集编码的下拉选项。
这个编码存在 tpt_log_alerts 表的 attributes 的 charset 字段中， attributes 字段 json 对象.

字符集编码的可选值为 

GB2312
GB18030
HZ-GB2312
GBK
BIG5
EUC-JP
ISO2022JP
SHIFTJIS
EUC-KR
UTF8
UTF16

**Comment by eeiceyes** [comment]
加好了
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，无法接收到中文的syslog。

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180615_3482_x64.exe 版本确认，close处理。
