### ISSUE TITLE
[日志告警规则]日志告警规则，Syslog消息收到时，未触发告警规则

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1293]
日志告警规则，Syslog消息收到时，未触发告警规则
![1500279570 1](https://user-images.githubusercontent.com/28615156/28260021-cc24447a-6b0b-11e7-861a-48121d6c3920.jpg)
[logging.zip](https://github.com/three-plus-three/hw_issues/files/1151931/logging.zip)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170720_197_x64.exe   版本确认，close处理。
