### ISSUE TITLE
[网络视图]在网络视图页面下，鼠标可以无限向下滚动网络视图

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1295]
前提;
1.谷歌浏览器
步骤：
1.点击“运维管理→网络视图”
2.鼠标滚轮向下滚动
→BUG:网络视图页面，可以无限向下拉伸

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
