### ISSUE TITLE
[设备总览]设备总览同时移除多个设备信息后，在同步Tag导入删除的设备后，弹出“添加管理对象失败”消息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1296]
前提:
Tag列表添加名称：test
test标签管理设备：126.0.0.2、126.0.0.5、126.0.0.9
步骤：
1.点击“运维管理→设备总览”
2.添加新的分组"test"
3.test分组，依据Tag导入设备
4.126.0.0.2、126.0.0.5、126.0.09三台设备信息一起选择移除
5.再次test分组，依据Tag导入设备
→BUG:弹出“添加管理对象失败”消息

![1500349023 1](https://user-images.githubusercontent.com/28615156/28299725-7a8fdfa0-6bad-11e7-9618-a93aca43ed30.jpg)

**Comment by eeiceyes** [comment]
删除操作不支持多个节点同时删除，先禁用多选操作

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe 版本确认，依次删除3台设备，再次依据Tag导入设备 发生错误 添加图片1-1
![1-1](https://user-images.githubusercontent.com/28615156/28701128-908b6208-7386-11e7-8697-58d05322c5e8.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170729_232_x64.exe    版本确认，close处理。
