### ISSUE TITLE
[设备总览]依据Tag导入设备后，分组右键选择“移入设备”，Tag导入设备在对象选择中没有被勾选

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1297]
前提:
Tag列表添加名称：test
test标签管理设备：126.0.0.2、126.0.0.5、126.0.0.9
步骤：
1.点击“运维管理→设备总览”
2.添加新的分组"test"
3.test分组，依据Tag导入设备
4.右键“test”选择“移入设备
→BUG：Tag导入设备在对象选择中没有被勾选，选择Tag同步的设备后弹出“添加管理对象失败”消息

![1500349743 1](https://user-images.githubusercontent.com/28615156/28300112-c57415f2-6baf-11e7-9381-92a6760774bc.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，依次删除3台设备，再次依据Tag导入设备 发生错误 添加图片1-1
![1-1](https://user-images.githubusercontent.com/28615156/28701048-1d7f2aba-7386-11e7-9532-3a81b3a1bd94.png)

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
