### ISSUE TITLE
[告警规则]告警规则页面中的告警指标下拉菜单中无法具体显示指标名称

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1298]
步骤;
1.点击“告警管理→告警规则”
2.点击“告警指标”文本框
→告警指标下拉菜单中无法具体显示指标名称
![1500358370 1](https://user-images.githubusercontent.com/28615156/28303206-749b2c64-6bc4-11e7-953f-2f3f467da564.jpg)

**Comment by eeiceyes** [comment]
加大现实宽度

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
