### ISSUE TITLE
[设备配置查看]设备配置信息，关联一个错误模板，一个正确模板，对比结果显示“error”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1299]
前提：
添加一个错误的配置信息模板
添加一个正确的配置信息模板
步骤：
1.点击“常用工具→设备配置查看”
2.配置信息关联一个错误模板，一个正确模板
3.点击“对比模板”
→BUG:对比结果显示“error”

![1500360902 1](https://user-images.githubusercontent.com/28615156/28304608-f1f3d9d0-6bca-11e7-9e98-ee4b686dcd6f.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
再有问题，先找老梅确认下

**Comment by hengwei-test** [comment]
原始手顺写的不全重新写手顺：
前提：
1.添加一个错误的配置信息模板
2.添加2个正确的配置信息模板
步骤：
1.设备配置查看页面中，配置信息添加3个模板
2.在设备配置模板中删除一个模板
3.设备配置查看页面中，选择配置信息，点击对比模板
→BUG:对比结果显示“error”

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170901_2684_x64.exe  版本确认，close处理。
