### ISSUE TITLE
[监控总览]设备CPU利用率的面板设置中参数设置为Top 10 、显示类型为柱形图时候，面板中只显示4台设备信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1300]
前提：
操作平台添加相对应的设备信息 参考图：1-1
步骤：
1.点击“运维管理→监控总览”
2.“设备CPU利用率TOP10”的面板设置中参数设置为Top 10 、显示类型为柱形图  参考图：1-2
→BUG:“设备CPU利用率TOP10”的面板中只显示4台设备信息 参考图：1-3

周边：
1.内存利用率只显示9台设备信息 →BUG:

![1-1](https://user-images.githubusercontent.com/28615156/28305683-29e219ac-6bcf-11e7-9902-c4bb55850897.jpg)

![1-2](https://user-images.githubusercontent.com/28615156/28305684-29e6c498-6bcf-11e7-94d5-3ee3e5776465.jpg)

![1-3](https://user-images.githubusercontent.com/28615156/28305685-29e8e6ba-6bcf-11e7-8e5a-35356fa731d8.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
