### ISSUE TITLE
[监控总览]监控总览画面，添加“设备负载监控”面板，面板中CPU的利用率的信息的单位是“B/s”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1304]
步骤：
1.点击“运维管理→监控总览”
2.添加“设备负载监控”面板，参数指标选择“CPU利用率”，选择一台设备信息，点击确定  参考图：1-1
→BUG:面板中CPU的利用率信息的单位是“B/s” 参考图：1-2

周边：
1.内存利用率同样出现此现象→BUG
2.“图例”在一定时间会与时间轴上的时间信息发生重合，从而看不清时间信息。  参考图1-3

![1-1](https://user-images.githubusercontent.com/28615156/28306236-2054fbe6-6bd1-11e7-90f8-ecb155936c23.jpg)

![1-2](https://user-images.githubusercontent.com/28615156/28306237-20555032-6bd1-11e7-9f2d-4de9d5eab446.jpg)

![1-3](https://user-images.githubusercontent.com/28615156/28306678-d3b54bcc-6bd2-11e7-81e5-4cd461211e67.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170724_208_x64.exe     版本确认，close处理。
