### ISSUE TITLE
[监控总览]监控总览页面中，未输入名称的面板能够添加成功

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1307]
步骤：
1.点击“运维管理→监控总览”
2.点击“+面板”按钮，类型选择“线路流量监控”
3.面板设置的通用页面名称不填写，点击“参数设置”后，点击“确定”按钮
→BUG:未输入名称的面板能够添加成功

周边：
1.面板设置的通用页面名称填写，点击“确定”按钮，面板添加不成功
2.添加面板类型为“设备负载监控”的时候同样出现此现象→BUG
3.添加面板类型为“主机文件信息查看”的时候同样出现此现象→BUG
4.添加面板类型为“主机指标查看”的时候同样出现此现象→BUG
5.添加面板类型为“设备负载TopN”的时候同样出现此现象→BUG
6.添加面板类型为“线路流量TopN”的时候同样出现此现象→BUG
7.添加面板类型为“组合端口流量监控”的时候同样出现此现象→BUG
8.添加面板类型为“Remote Ping延迟”的时候同样出现此现象→BUG
9.添加面板类型为“Ping检查”的时候同样出现此现象→BUG
10.添加面板类型为“访问不可达或最近重启设备”的时候同样出现此现象→BUG
11.添加面板类型为“TCP端口连接数查看”的时候同样出现此现象→BUG
12.添加面板类型为“IIS连接数查看”的时候同样出现此现象→BUG
13.添加面板类型为“自定义SQL语句”的时候同样出现此现象→BUG
14.添加面板类型为“DB2备份状态查看”的时候同样出现此现象→BUG
15.添加面板类型为“DB2表空间查看”的时候同样出现此现象→BUG
16.添加面板类型为“标准应用状态查看”的时候同样出现此现象→BUG
17.添加面板类型为“Ftp目录对比”的时候同样出现此现象→BUG
18.添加面板类型为“防火墙指标查看”的时候同样出现此现象→BUG
19.添加面板类型为“通知消息查看”的时候同样出现此现象→BUG

![1500366205 1](https://user-images.githubusercontent.com/28615156/28307991-715f5d78-6bd7-11e7-85ce-81cfef1f9d94.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170829_2669_x64.exe  版本确认，close处理。
