### ISSUE TITLE
[监控总览]添加面板类型为“通知消息查看”时，面板设置的参数设置为空白

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1308]
步骤;
1.点击“运维管理→监控管理”
2.监控总览页面，点击“+面板”按钮，添加面板类型“通知消息查看”
3.面板设置窗口选择参数设置
→BUG:面板设置的参数设置为空白

![1500367108 1](https://user-images.githubusercontent.com/28615156/28308251-33acc32a-6bd8-11e7-9e2f-79f185e080fb.jpg)

**Comment by eeiceyes** [comment]
该面板确实不需要参数，隐藏设置界面

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认，close处理。
