### ISSUE TITLE
[监控总览]添加的“自定义SQL语句”模板，无法显示数据库数据

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1309]
步骤：
1.点击“运维管理→监控管理”
2.点击“+面板”，添加面板类型：自定义SQL语句
3.面板设置的参数设置选择“oracle”，SQL脚本“select table_name from all_tables”
→BUG:面板无法显示数据库数据

**Comment by eeiceyes** [comment]
不是bug,界面下方还有列名映射，比如设置TABLE_NAME => 列1

**Comment by hengwei-test** [comment]
SQL 语句执行只返回1条数据   参考图片1-1
在数据库脚本管理执行同一条SQL语句出来多条数据    参考图片1-2


![1-1](https://user-images.githubusercontent.com/28615156/28703220-2ce09674-7395-11e7-9bf3-0a94de691512.jpg)


![1-2](https://user-images.githubusercontent.com/28615156/28703221-2ceff286-7395-11e7-9e58-5a089f773813.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170729_232_x64.exe    版本确认，close处理。
