### ISSUE TITLE
[华东电网] 天清汉马防火墙支持

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1311]
设备： 启明星辰  天清汉马 防火墙支持 
MIB库：附件 （夏修叶上传）
walk 数据：附件 （夏修叶上传）
https://github.com/three-plus-three/hw_issues/blob/master/test_data/%E5%8D%8E%E4%B8%9C/10.128.4.173.txt

https://github.com/three-plus-three/hw_issues/blob/master/test_data/%E5%8D%8E%E4%B8%9C%E7%94%B5%E7%BD%91/FW-P%E7%B3%BB%E5%88%97mib.selection.tar

**Comment by runner-mei** [comment]
fix
