### ISSUE TITLE
[历史记录查看]流量刷新不出来，一直显示在加载中

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1313]
1.[历史记录查看]选中线路右击→历史记录查看→流量
2.在流量查询窗口中，先清空→再添加对象→刷新数据
bug：流量刷新不出来，一直显示在加载中
![image](https://user-images.githubusercontent.com/22296563/28352855-4f975f9c-6c8b-11e7-9349-be2758f22703.png)

**Comment by eeiceyes** [comment]
fixed
