### ISSUE TITLE
[设备负载监控]CPU利用率、内存利用率 bug：不能导出

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1315]
[设备负载监控]CPU利用率、内存利用率
bug：不能导出
![image](https://user-images.githubusercontent.com/22296563/28402986-37685a5a-6d55-11e7-979f-18cc4e8f044e.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
ok
