### ISSUE TITLE
[数据流]新添加的用户无法登入

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1318]
步骤：
1.新添加的用户信息无法登入管理平台
![1500618356 1](https://user-images.githubusercontent.com/28615156/28451573-90fdbb5c-6e20-11e7-8ef8-9df9b7ad7a00.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hhengwei_nflow_setup_3.2.20170727_2553_x64.exe 版本确认，close处理。
