### ISSUE TITLE
[数据流]首页，应用排行，设置宽度选择任意一个值，没有点击确定就设置了宽度

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1319]
[数据流]首页，应用排行，设置宽度选择任意一个值，没有点击确定就设置了宽度，也无法取消
![image](https://user-images.githubusercontent.com/22296563/28452087-93750ef0-6e23-11e7-8902-a736eaeb8244.png)

**Comment by hengwei-lhm** [comment]
fixed
