### ISSUE TITLE
[数据流]首页，应用排行窗口，点击（编辑）显示设置，选择所有设备，跟你选择单个设备，显示没有任何变化

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1320]
[数据流]首页，应用排行窗口，点击（编辑）选择设备，所有设备，跟你选择单个设备，显示没有任何变化
![image](https://user-images.githubusercontent.com/22296563/28452373-f695e3d2-6e24-11e7-91a4-fd1b9daaf540.png)

**Comment by hengwei-lhm** [comment]
所有设备 :  http://127.0.0.1/hengwei/internal/nflow/query/application_topn?interval=1h&className=%E8%AE%BE%E5%A4%87&max_records=5&id=2

单个设备 ：http://127.0.0.1/hengwei/internal/nflow/query/application_topn?interval=1h&className=%E8%AE%BE%E5%A4%87&max_records=5&id=2&device=127.0.0.1
