### ISSUE TITLE
[数据流]服务器设置，修改端口任意信息，没有发生改变

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1321]
[数据流]服务器设置，修改任意端口信息，没有发生改变
![image](https://user-images.githubusercontent.com/22296563/28506938-86a1994c-7061-11e7-9520-dd30af55145a.png)

**Comment by runner-mei** [comment]
fixed

**Comment by xiauye** [comment]
修改端口错误
![image](https://user-images.githubusercontent.com/22296563/28865622-1a68a2ae-77a3-11e7-843c-6fceffd2285b.png)

**Comment by runner-mei** [comment]
fix

**Comment by xiauye** [comment]
版本：hengwei_nflow_setup_3.2.20170807_2584_x64.exe   

bug仍然存在

**Comment by xiauye** [comment]
版本：hengwei_nflow_setup_3.2.20170807_2584_x64.exe

bug仍然存在

**Comment by runner-mei** [comment]
fix

**Comment by xiauye** [comment]
ok
