### ISSUE TITLE
[数据流](映射)，应用映射、站点排名页面，删除选中项按钮，没有选中任何内容，直接点击删除，也提示删除成功

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1323]
[数据流](映射)，应用映射、站点排名页面，删除选中项按钮，没有选中任何内容，直接点击删除，也提示删除成功
![image](https://user-images.githubusercontent.com/22296563/28507328-9f494c1c-7064-11e7-8955-468d84fd8911.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by xiauye** [comment]
如果没有选中任何类型，直接点击删除。 应该提示“请选中要删除的类型”
![image](https://user-images.githubusercontent.com/22296563/28864744-0e74a2b6-77a0-11e7-902f-1223fcf0b80e.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by xiauye** [comment]
ok
