### ISSUE TITLE
[资产管理](资产申请)从资产备件中选中一个或者多个资产，进入资产申请。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1329]
[资产申请]从资产备件中选中一个或者多个资产，进行资产申请。 选中的资产直接可以跳到资产申请页面中去。

**Comment by hengwei-wtk** [comment]
资产申请已修改

**Comment by xiauye** [comment]
点击添加资产没有反应
![image](https://user-images.githubusercontent.com/22296563/29348824-d731220e-8288-11e7-9a65-0a560b307c43.png)
