### ISSUE TITLE
[资产管理]日期插件，更换一下，能获取当前时间的

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1332]
[资产管理]日期插件，更换一下，能获取当前时间的
软件协议，软件许可

![image](https://user-images.githubusercontent.com/22296563/28611413-4ff33c5c-721e-11e7-958f-ad9bcc578f8f.png)

**Comment by hengwei-wtk** [comment]
已经将时间控件更换

**Comment by xiauye** [comment]
ok
