### ISSUE TITLE
[网络视图]线路显示设置的显示属性窗口选择下标显示后，再次在显示属性窗口点击“应用默认设置”，网络视图选择的线路下标信息不消失

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1334]
1.点击“运维管理→网络视图”
2.选择的线路，鼠标右击选择“显示设置”
3.线路显示设置窗口选择“显示属性”
4.显示属性窗口选择“线路名称”、“源设备”、和这俩属性都选择“在下标中显示”
5.再次选择同一条线路，鼠标右击选择“显示设置”
6.点击“应用默认设置”
→BUG:网络视图选择的线路下标信息消失

![1501132981 1](https://user-images.githubusercontent.com/28615156/28655622-a1031160-72cf-11e7-9e74-94b47eeadd91.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_222_x64.exe   版本确认 出现 保存设置失败  添加图片1-1
![1-1](https://user-images.githubusercontent.com/28615156/28700035-dcd1b830-737f-11e7-8966-15517c8342f5.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170729_232_x64.exe    版本确认，close处理。
