### ISSUE TITLE
[数据库管理]编辑数据库信息时，数据库名称修改，点击“确定”按钮，提示内部错误消息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1336]
步骤：
1.点击“资源管理→数据库管理”
2.选择任意数据库信息，点击“编辑”按钮
3.数据库编辑页面，名称修改
4.点击“确定”按钮
→bug:提示内部错误消息，返回数据库管理页面，名称已经修改成功

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170729_232_x64.exe    版本确认，close处理。
