### ISSUE TITLE
[采集设置]设备采集，选择任意采集方式，都提示采集失败

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1337]
[采集设置]设备采集，选择任意采集方式，都提示采集失败
![image](https://user-images.githubusercontent.com/22296563/28700918-3de53336-7385-11e7-87c6-68f7ae137082.png)

![image](https://user-images.githubusercontent.com/22296563/28700959-762f1d88-7385-11e7-8fd9-fd36ed18f89b.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
ok
