### ISSUE TITLE
[Syslog]发送没有类型和等级的syslog信息时候，平台自动添加syslog信息的类型和等级

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1339]
发送没有类型和等级的syslog信息时候，平台自动添加syslog信息的类型和等级

![1501213346 1](https://user-images.githubusercontent.com/28615156/28701626-ffdd1194-7389-11e7-8a95-5c2635d0cf18.jpg)

![1501213364 1](https://user-images.githubusercontent.com/28615156/28701625-ffdbbdbc-7389-11e7-90b9-e43150bacd64.jpg)

**Comment by eeiceyes** [comment]
从数据库中看到的这两个字段（等级和类型）的值都是0

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170821_279_x64.exe 版本确定还是不能显示显示‘未知类型’和‘未知等级’
参考图片：
![1-1](https://user-images.githubusercontent.com/28615156/29547616-c1836ada-872d-11e7-9df5-5edafc42afa1.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170828_2662_x64.exe 版本确认，close处理。
