### ISSUE TITLE
[告警规则]告警规则页面打不开，弹出内部错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1342]
步骤：
1.点击“告警管理→告警规则”
→BUG:告警规则页面打不开，弹出内部错误
[web_server.zip](https://github.com/three-plus-three/hw_issues/files/1186615/web_server.zip)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170801_243_x64.exe   版本确认，close处理。
