### ISSUE TITLE
[网络视图]网络视图设备右击中的“历史记录查看→平均CPU利用率”，获取不到历史记录CPU信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1343]
步骤：
1.点击“运维管理→网络视图”
2.选中设备右击，选择“历史记录查看→平均CPU利用率”
→BUG:获取不到历史记录CPU信息

周边：
1.平均内存利用率同样出现此现象→BUG
2.端口总流量同样出现此现象→BUG
3.端口入流量同样出现此现象→BUG
4.端口出流量同样出现此现象→BUG
5.端口总帧流量同样出现此现象→BUG
6.端口入帧流量同样出现此现象→BUG
7.端口出帧流量同样出现此现象→BUG

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170801_238_x64.exe     版本确认，close处理。
