### ISSUE TITLE
后台任务个数为 0 时，请不要显示， 更不要显示红色

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#1348]
后台任务个数为 0 时，请不要显示， 更不要显示红色

![default](https://user-images.githubusercontent.com/1052632/28819848-0d7f6e18-76e2-11e7-98ce-9866c09c0c8e.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170822_2628_x64.exe   版本确认，close处理。

**Comment by hengwei-test** [comment]
重新安装版本后又重现此现象

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170823_2647_x64.exe 版本确认，close处理。
