### ISSUE TITLE
[网络视图]定位拓扑图上最下面的一个IP地址设备，新打开的页面拓扑图向上移动，一部分设备看不见

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1349]
前提：
网络视图上添加多个设备信息
步骤：
1.点击工具栏中的资源查找，选择IP定位
2.输入一个拓扑上最下面的IP地址，选择拓扑定位，点击确认
→BUG:新打开的页面拓扑图向上移动，一部分设备看不见

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170927_2780_x64.exe 版本确认，close处理。
