### ISSUE TITLE
[配置备份查看]查看具体的配置备份信息时候，页面显示“您没有访问当前页面的权限”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1352]
前提：
1.新建角色12，菜单权限部分选择  参考图片 1-1
2.新建用户admin1，角色选择：12
3.平台有配置备份信息
步骤：
1.点击“常用工具→配置备份查看”
2.点击设备IP地址
→BUG:页面显示“您没有访问当前页面的权限”
![1-2](https://user-images.githubusercontent.com/28615156/28864858-8227f8ca-77a0-11e7-9cae-7731ca6dfbdc.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170803_248_x64.exe 版本确认，close处理。
