### ISSUE TITLE
[角色管理]不赋予操作权限的角色，新建用户登入后能修改历史记录规则状态

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1353]
前提：
1.新添加一个角色12，操作权限不赋予
2.建一个用户，角色使用12

步骤：
1.点击“报表管理→历史记录规则”
2.修改规则状态
→BUG:历史记录规则状态还能修改
周边：
1.告警规则页面同样出现此现象→BUG
2.组合告警规则页面同样出现此现象→BUG
3.资源管理菜单中缺少选项 →BUG  参考图片1-3
4.生成报表查看页面能够删除报表信息→BUG
5.运行视图中运维信息内容能够修改→BUG
6.能够修改背景图操作→BUG

![1-1](https://user-images.githubusercontent.com/28615156/28903067-75bba790-7835-11e7-99cc-77501ee7fcb6.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/28903068-763d5808-7835-11e7-9e86-3d92d5ce5521.jpg)

![1-3](https://user-images.githubusercontent.com/28615156/28903319-cf17f586-7836-11e7-9d02-a899c7457b16.jpg)

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170803_248_x64.exe 版本确认，close处理。

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170829_2669_x64.exe  版本确认，close处理。
周边2还在现
https://github.com/three-plus-three/hw_issues/issues/1486  中加了周边
