### ISSUE TITLE
[数据流](Dos/瞬间阻塞)生成报表，怎么都设置都没有报表生成。生成报表前提的数据是存在。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1355]
[Dos/瞬间阻塞]生成报表，怎么都设置都没有报表生成。生成报表前提的数据是存在。

![image](https://user-images.githubusercontent.com/22296563/28866664-35c0a710-77a6-11e7-9e5c-3902e3ba7572.png)

**Comment by hengwei-lhm** [comment]
Dos/瞬间阻塞 http://127.0.0.1/hengwei/internal/nflow/attack/history?start_at=2017-08-09T01:53:27.454Z&end_at=2017-08-09T02:53:27.454Z&catalog=3&query=&limit=10&orderBy=type&ascending=1&page=1&byColumn=0&offset=0
