### ISSUE TITLE
[数据流]用户管理，添加用户报错

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1356]
[数据流]用户管理，添加用户报错
![image](https://user-images.githubusercontent.com/22296563/28866817-aa5d0ca8-77a6-11e7-8c0d-4672400b1201.png)

**Comment by runner-mei** [comment]
fix

**Comment by xiauye** [comment]
还是报一样的错误

**Comment by runner-mei** [comment]
fix

**Comment by xiauye** [comment]
ok
