### ISSUE TITLE
[虚拟机管理]ESX/ESXI主机同步更新后，虚拟机管理中的虚拟机数据不更新

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1357]
前提:
添加ESX/ESXI主机IP：192.168.1.120  进行同步操作
步骤：
1.vmware esxi关闭的虚拟机开启，修改名称和IP地址
2.点击“虚拟化&存储→ESX/ESXI主机管理”，进行同步操作
3.点击“虚拟化&存储→虚拟机管理”
→BUG：虚拟机管理中的虚拟机数据不更新

[192.168.1.129 cpu 信息.txt.zip](https://github.com/three-plus-three/hw_issues/files/1193434/192.168.1.129.cpu.txt.zip)

![1-1](https://user-images.githubusercontent.com/28615156/28868394-f122e34c-77ab-11e7-9e95-12dadcca081c.png)

![1-2](https://user-images.githubusercontent.com/28615156/28868396-f1284b02-77ab-11e7-9a5c-8641b9de3347.png)

![1-3](https://user-images.githubusercontent.com/28615156/28868398-f12d5246-77ab-11e7-940f-02fbe962984f.png)

![1-4](https://user-images.githubusercontent.com/28615156/28868397-f12b7b42-77ab-11e7-8147-958b2e0ebb08.png)

**Comment by eeiceyes** [comment]
名称不更新的问题已经好了

**Comment by eeiceyes** [comment]
{"channel":"cpu/2520/","client_name":"-","client_id":11,"created_at":"2017-08-04T15:55:04.8391378+08:00","error":{"code":562001,"message":"internal error:\r\n    cpu_for_vmware_virtual_machine: metric 'cpu_usage_average' is unsupported.\r\n    read 'sys.oid' failed, snmp is missing.\r\n    cpu_ucd: snmp is missing.\r\n    cpu_host_resource: snmp is missing.","internals":[{"code":500,"fields":{"metric_id":"cpu_for_vmware_virtual_machine"},"message":"metric 'cpu_usage_average' is unsupported."},{},{"code":400102,"fields":{"metric_id":"cpu_ucd"},"message":"snmp is missing."},{"code":400102,"fields":{"metric_id":"cpu_host_resource"},"message":"snmp is missing."}]}
,"engine_id":0}
