### ISSUE TITLE
[主机设备]运行视图，理论宽带限制超出视图模板页面

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1358]
[主机设备]理论宽带限制超出视图模板页面
![image](https://user-images.githubusercontent.com/22296563/28903671-dd0fd76a-7838-11e7-913d-c2c859be8419.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
2.3.20170804_253_x64 ，success
