### ISSUE TITLE
[华东电网] 检修功能模块开发

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1360]
华东电网检修模块
检修模块结合流程管理平台；
详细功能说明：另附件查阅。

[国网华东分部检修管理模块需求确认书.zip](https://github.com/three-plus-three/hw_issues/files/1195845/default.zip)

[华东电网检修管理系统 - 功能需求规格说明书.zip](https://github.com/three-plus-three/hw_issues/files/1195854/-.zip)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
