### ISSUE TITLE
[网络视图]cisco交换机设备面板视图取不到数据

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1361]
前提：
添加一台Cisco交换机设备
步骤：
1.点击“运维管理→网络视图”
2.网络视图页面，选择Cisco设备图标右击
3.选择设备面板视图
→BUG:设备面板视图取不到数据
![1-1](https://user-images.githubusercontent.com/28615156/28953382-2ef5c478-790a-11e7-9c89-d0287f4ad16a.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170804_253_x64.exe   版本确认，close处理。
