### ISSUE TITLE
[主机设备]配置Winrm参数端口修改没有保存。 

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1363]
[主机设备]配置Winrm参数端口修改没有保存。 
![image](https://user-images.githubusercontent.com/22296563/28957179-5fb4ba74-7923-11e7-9786-ac2ac17845e8.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
2.3.20170804_253_x64      success
