### ISSUE TITLE
[组合告警]组合告警规则触发后，在当前告警页面的记录数显示组合告警，没有组合告警消息显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1364]
前提：
添加一条组合告警
步骤：
1.触发一条组合告警
2.点击“告警管理→当前告警”
→BUG:当前告警页面的记录数显示组合告警，没有组合告警消息显示

![1-1](https://user-images.githubusercontent.com/28615156/28961641-9a5e8a1c-7935-11e7-9a8d-9d6477edb9c5.jpg)

**Comment by eeiceyes** [comment]
问题无法重现

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170804_253_x64.exe 版本，10次确认次现象未再现，先close处理。以后再发现此现象Open处理
