### ISSUE TITLE
[历史记录规则]添加IIS历史记录规则时，在指标选择栏没有指标选择

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1367]
前提：
添加中间件IIS信息
步骤：
1.点击“报表管理→历史记录规则”
2.点击“添加”按钮
3.选择“中间件-IIS”，管理对象选择"IIS"
4.点击“更多指标”，指标选择窗口点击指标栏
→BUG:在指标选择栏没有指标选择  参考图片：1-1

周边：
1.在添加告警规则时，有指标选择   参考图片1-2
2.添加Nginx同样出现此现象→BUG
3.添加Apache时同样出现此现象→BUG

![1-1](https://user-images.githubusercontent.com/28615156/29053286-cb8f1068-7c21-11e7-9152-0e58a867560c.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/29053287-cba1dcde-7c21-11e7-9bb9-838662975880.jpg)

**Comment by eeiceyes** [comment]
该些类型对应的指标集中确实不存在包含数字型字段的指标，所以没法坐历史记录
