### ISSUE TITLE
[TFTP脚本管理]在tftp脚本列表中，显示所有的脚本内容 。  

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1372]
[TFTP脚本管理]在tftp脚本列表中点击（空），弹出窗口输入脚本内容，再点击确定。
bug： 在tftp脚本列表中，显示所有的脚本内容 。          
           应该以文件名称的形式显示在tftp列表中。

![image](https://user-images.githubusercontent.com/22296563/29062976-81f0320e-7c56-11e7-8885-c9d5ea760242.png)

**Comment by runner-mei** [comment]
显示已配置或未配置吧

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
1.hengwei_setup_2.3.20170810_261_x64.exe  版本确认，添加脚本后还是脚本内容全部显示
当页面刷新后显示“已配置”

**Comment by eeiceyes** [comment]
下一个版本再验下

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe  版本确认，添加脚本后还是脚本内容全部显示
当页面刷新后显示“已配置”  参考图片：1-1  
![1-1](https://user-images.githubusercontent.com/28615156/29255855-c598d9ae-80d7-11e7-8f7f-885e9272a144.jpg)

**Comment by eeiceyes** [comment]
这个做法可以接受，不用改

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe   版本确认，close处理。
