### ISSUE TITLE
[设备配置查看]查看备份错误日志，选择其他菜单都在备份错误日志下方。有的菜单不能操作

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1373]
[设备配置查看]在设备配置查看列表中，点击备份错误日志查看
bug：查看备份错误日志，选择其他菜单都在备份错误日志下方。  例如：选择数据管理菜单
         第二张图片：不能看到完整的错误日志

前提：在配置备份规则中设备错误配置备份

![image](https://user-images.githubusercontent.com/22296563/29063822-accd0d14-7c59-11e7-9311-bc3d4df16c3d.png)

![image](https://user-images.githubusercontent.com/22296563/29064065-6d0f1cf2-7c5a-11e7-8e84-2f86c89820f9.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
ok
