### ISSUE TITLE
[设备配置备份]linux 环境下 没有权限创建文件

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1374]
[设备配置备份]linux 环境下 没有权限创建文件
open /var/lib/tpt/baconf/168/switch/192.168.1.172.txt: permission denied

![image](https://user-images.githubusercontent.com/22296563/29064571-f6b9756e-7c5b-11e7-8286-f608b837b09c.png)

**Comment by runner-mei** [comment]
fix

**Comment by xiauye** [comment]
还是没有权限，创建文件

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
tpt-2.3.20170811.153~de10ef8.x86_64.rpm    版本确认时，配置备份正常进行，点击设备查看详细的备份信息时出错
参考图片：1-1
![1-1](https://user-images.githubusercontent.com/28615156/29257959-7eeb886a-80e8-11e7-9812-4e3ea62a2719.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-2.3.20170814.158~dfcbc21.x86_64.rpm   版本确认，close处理。
