### ISSUE TITLE
[业务总览]添加，提示加载失败

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1375]
[业务总览]添加，提示加载失败
![image](https://user-images.githubusercontent.com/22296563/29065506-e733216e-7c5e-11e7-80af-71cb876957d8.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by runner-mei** [comment]
反复提了很多次，将 log 发过来啊

**Comment by xiauye** [comment]
昨天忘记上传了
https://coding.net/u/runner-mei/p/hw_issues/git/blob/master/scene_data/web_server.log
