### ISSUE TITLE
[配置备份规则]没有发通知

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1376]
[配置备份规则]没有发通知

**Comment by runner-mei** [comment]
没有你这么提 bug 的，我没有办法改 bug 啊，我都不知道发生了什么。

**Comment by xiauye** [comment]
[配置备份规则]配置备份规则有个变动通知，配置备份变动没有发通知

**Comment by xiauye** [comment]
![image](https://user-images.githubusercontent.com/22296563/29112084-4336676c-7d1f-11e7-9f4b-1464c942b9d0.png)

https://coding.net/u/runner-mei/p/hw_issues/git/blob/master/scene_data/logs.rar
