### ISSUE TITLE
标准应用管理所属对象不填，保存失败

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#1377]
![image](https://user-images.githubusercontent.com/14171518/29105584-5acdd860-7d01-11e7-812a-b920d17a59d1.png)
![image](https://user-images.githubusercontent.com/14171518/29105589-65e1a646-7d01-11e7-8ddd-c87a3000dc02.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170810_261_x64.exe
