### ISSUE TITLE
[设备总览]点击设备总览，跳转页面出现“创建节点失败！”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1383]
步骤：
1.点击“网络视图→设备总览”
→BUG:跳转页面出现“创建节点失败！”

![1-1](https://user-images.githubusercontent.com/28615156/29151955-05d0ee7c-7db7-11e7-9296-c30bf680a42f.jpg)

**Comment by eeiceyes** [comment]
POST http://192.168.1.121:8082/hengwei/mc/mo_trees?random_ts=1503560471202&screen_width=1280&screen_height=680 HTTP/1.1
Host: 192.168.1.121:8082
Connection: keep-alive
Content-Length: 77
Pragma: no-cache
Cache-Control: no-cache
Origin: http://192.168.1.121:8082
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Content-Type: application/json; charset=UTF-8
Accept: application/json, text/javascript, */*; q=0.01a
user: admin
Referer: http://192.168.1.121:8082/hengwei/web/network_devices/device_browse
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.8
Cookie: tpt_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MDM1NjMzODMsImlhdCI6MTUwMzU1OTc4MywiaXNzIjoiaGVuZ3dlaV9pdCIsInN1YiI6InRwdCJ9.RZQLghYz4rvk-AnpTciG4zWCT5v7D4YWbzmJ389FXJ8; PLAY_SESSION=93154ee1fad8a01ff58835c84f12d8e4f1792e93-_expire=1503561149&session_id=2f2d7434-19f9-4f61-9498-3cba3e9551d3&_valid=true&_TS=1503561149&user=admin; PLAY_FLASH=

{"label":"设备树","parent_id":0,"node_type":"","content":{"key":"device"}}


HTTP/1.1 500 Internal Server Error
Content-Length: 28
Content-Type: application/json; charset=utf-8
Date: Thu, 24 Aug 2017 07:42:29 GMT
Set-Cookie: PLAY_FLASH=; Path=/; HttpOnly
Set-Cookie: PLAY_SESSION=e76e03ec2d5aee7e4fb426de5b5f6909ba145ce3-_TS=1503562349&_expire=1503562349&_valid=true&session_id=2f2d7434-19f9-4f61-9498-3cba3e9551d3&user=admin; Path=/hengwei
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

{"code":500,"message":"EOF"}

**Comment by eeiceyes** [comment]
request和response内容看上一条批注

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170830_2674_x64.exe   版本确认，close处理。
