### ISSUE TITLE
[业务视图]添加多个业务集中展示的模块时，模块的页面排布出错

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1385]
步骤：
1.点击“运维管理→业务总览”
2.点击“添加”按钮，名称输入“1”点击，确定按钮
3.按照 2的操作步骤一次添加名称 “2”、“3”、“4”、“5”的模块
4.安装2的操作步骤添加名称“10”的模块
→BUG:模块的页面排布出错  参考图片：1-1

周边：
1.添加一个模板的自定义排列功能，能够让用户自己来调整模块的位置

![1-1](https://user-images.githubusercontent.com/28615156/29152292-3ce64da6-7db9-11e7-9fef-bd01f0ef2b68.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，close处理。
hengwei_setup_3.2.20171027_2837_x64.exe   版本确认，close处理。
