### ISSUE TITLE
[业务总览]鼠标光标拿开显示设备详细信息不会消失显示。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1386]
[业务总览] 1.鼠标光标放到某个节点上去，显示设备详细信息，鼠标光标拿开显示设备详细信息不会消失显示。图1
        2.有时候鼠标光标放到某个几点上去，sx显示设备详细信息，在界面上没有规定的地方进行显示。图2
![image](https://user-images.githubusercontent.com/22296563/29152384-c0964ea8-7db9-11e7-8122-0501d42f434e.png)

![image](https://user-images.githubusercontent.com/22296563/29152569-ac3d8a7e-7dba-11e7-806e-6ed916751605.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
ok
