### ISSUE TITLE
[组合告警日志]在组合告警日志列表中，有个级别图片没有显示出来 

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1388]
[组合告警日志]告警日志，组合告警日志列表中，有个级别图片没有显示出来 

![image](https://user-images.githubusercontent.com/22296563/29153087-e54d46e4-7dbd-11e7-91fb-9533a87a11ef.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
ok
