### ISSUE TITLE
[虚拟机管理]开启的Linux系统的虚拟机获取不到IP信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1389]
前提：
1.添加虚拟中心IP：192.168.1.120 、账号：root、密码：tpt_8498b2c7 、进行同步操作
2.Linux操作系统的虚拟机配置好IP信息，操作系统开启
步骤：
1.点击“虚拟化&存储→虚拟机管理”
2.选择Linux系统虚拟机，点击查看按钮
→BUG:Linux系统的虚拟机获取不到IP信息  参考图片：1-1

周边：
1.虚拟机列表页面同样获取不到IP信息→BUG  参考图片：1-2

![1-1](https://user-images.githubusercontent.com/28615156/29154432-395131ac-7dc7-11e7-9b5c-4e3d34709e75.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/29154433-3958816e-7dc7-11e7-955b-6a2380d1a299.jpg)

**Comment by runner-mei** [comment]
请在 vm 中安装  vmware 的驱动

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171124_521_x64.exe  版本确认，close处理。
