### ISSUE TITLE
[业务总览]业务系统窗口添加管理对象时候，对象类型栏和管理对象栏超出窗口

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1390]
步骤：
1.点击“运维管理→业务总览”
2.点击添加按钮
4.业务系统窗口点击“添加”按钮
→BUG:对象类型栏和管理对象栏超出窗口

![1-1](https://user-images.githubusercontent.com/28615156/29155052-cb1063d4-7dcb-11e7-92c2-a4755ca5932a.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170922_2764_x64.exe  版本确认，close处理。
