### ISSUE TITLE
[监控总览]设备负载监控中没有没有设备历史记录的使用记录线条

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1391]
步骤：
1.点击“运维管理→监控总览”
2.点击添加面板按钮
3.选择“设备负载监控”，参数设置中选择多个设备，点击“确定按钮”
→BUG:设备负载监控中没有没有设备历史记录的使用记录线条   参考图片：1-1

周边
1.在2.3版本中有具体的颜色线  参考图片：1-2

![1-1](https://user-images.githubusercontent.com/28615156/29158323-29213122-7ddd-11e7-8d1d-e66d29404345.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/29158324-2923485e-7ddd-11e7-9d6b-2082968fb2a3.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170823_2647_x64.exe 版本确认，close处理。
