### ISSUE TITLE
[监控总览]监控总览页面添加面板超页面显示后，当页面拉到最后一个面板时，面板添加等按钮显示不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1392]
前提：
1.火狐浏览器
2.在监控总览页面添加多个面板信息，是面板信息在页面显示不全，出现滚条
步骤：
1.点击“运维管理→监控总览”
2页面内容向下拉
→BUG:当页面拉到最后一个面板时，面板添加等按钮显示不全

周边：
1.在2.3版本的监控总览页面不会出现2个滚动条→BUG
2.IE/谷歌浏览器不在线次现象

![1-1](https://user-images.githubusercontent.com/28615156/29159968-0eab8f26-7de3-11e7-95b8-edfcfcd72857.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170823_2647_x64.exe 版本确认，还出现此现象

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170824_2657_x64.exe 版本确认，close处理。
