### ISSUE TITLE
[当前告警]当前告警的窗口缩小后，当前告警窗口断开

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1393]
步骤：
1.点击“告警管理→当前告警”
2.缩小当前告警窗口
→BUG:缩小当前告警窗口断开 参考图片：1-1

![1-1](https://user-images.githubusercontent.com/28615156/29162939-6fde9842-7ded-11e7-89bb-b9a6db2e0bf6.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe  版本确认，close处理。
