### ISSUE TITLE
[配置备份规则]配置备份变动没有发通知

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1394]
[配置备份规则]配置备份变动没有发通知
配置备份变动截图
![default](https://user-images.githubusercontent.com/22296563/29169012-4f90c9ae-7e04-11e7-8a3d-7ce2e14ab54a.png)
https://share.weiyun.com/8ede36be2f5d90576c54c9518b9bf89d

**Comment by runner-mei** [comment]
这个是没有问题的，但是你的测试方法有是问题的，手工修改配置后，请在 安装目录下运行

lib\baconf\on_git_completed.bat

**Comment by xiauye** [comment]
ok
