### ISSUE TITLE
[业务总览]业务总览页面添加的设备信息中，运行时间以秒为单位

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1395]
前提：
业务总览页面添加有设备的模块
步骤：
1.点击“运维管理→业务总览”
2.鼠标放在设备的监控图标上
→BUG:运行时间以秒为单位 

![1-1](https://user-images.githubusercontent.com/28615156/29201486-3cdbf63e-7e91-11e7-9aff-dc28d49a0c4c.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe  版本确认，close处理。
