### ISSUE TITLE
[通知方式]外部程序通知方式测试时，测试成功，但是脚本没有运行成功

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1396]
前提:
1.centos系统 添加脚本  参考图片 1-1、1-2 
步骤:
1.点击“系统管理→通知方式”
2.点击添加按钮、添加外部程序通知
3.基本属性：名称:test 、脚本命令： cd /tmp
                                                         sh sh.sh      参考图片：1-3
4.点击测试按钮
→BUG:显示测试成功，在centos系统中脚本没有运行

![1-1](https://user-images.githubusercontent.com/28615156/29203352-e373e838-7ea2-11e7-8f11-d6d628ca3a43.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/29203353-e3754124-7ea2-11e7-9a9e-1a5d6b963967.jpg)
![1-3](https://user-images.githubusercontent.com/28615156/29203354-e3849912-7ea2-11e7-98d6-b0e648fc70f6.jpg)
[server_biz.zip](https://github.com/three-plus-three/hw_issues/files/1217087/server_biz.zip)

**Comment by runner-mei** [comment]
这个是你脚本运行失败了

**Comment by hengwei-test** [comment]
了解  脚本写错了 没有执行权限   已经确认没有问题
