### ISSUE TITLE
[标准应用服务]Linux版本添加Dhcp时测试失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1398]
前提：
centos系统

步骤：
1.点击“资源管理→标准应用管理”
2.点击添加按钮，添加服务类型为Dhcp、Dhcp服务器:192.168.1.1 、点击测试访问参数
→BUG:添加Dhcp时测试失败

![1502446405 1](https://user-images.githubusercontent.com/28615156/29209399-dbf84b1c-7ec0-11e7-8c93-32e55c4a8fc9.jpg)

**Comment by hengwei-test** [comment]
tpt-3.2.20170831.901~70e2f59.x86_64.rpm  版本确认出现以下现象

![1504165215 1](https://user-images.githubusercontent.com/28615156/29912104-0bef7910-8e63-11e7-875f-93a7114c51aa.jpg)

**Comment by runner-mei** [comment]
请确认一下，是不是防火墙的问题

**Comment by hengwei-test** [comment]
tpt-3.2.20170831.901~70e2f59.x86_64.rpm  确认是防火墙的问题

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.2.20170904.912~665af57.x86_64.rpm版本确认，close处理。
