### ISSUE TITLE
[业务总览]新添加的设备还在获取数据中，业务总览页新建模块添加正在获取的设备后，新添加的模块显示不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1399]
前提：
添加192.168.1.2、192.168.1.6、192.168.1.141设备信息还在取数中
步骤：
1.点击“运维管理→业务总览”
2.点击添加按钮，新的模块中添加正在获取数据的主机IP，点击确定按钮
→新添加的模块显示不全

![1-1](https://user-images.githubusercontent.com/28615156/29256469-2afbca2c-80dd-11e7-9f93-d3b21902d807.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/29256470-2b3bedfa-80dd-11e7-8282-c0254c2c701d.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170814_270_x64.exe   版本确认，close处理。
