### ISSUE TITLE
[告警规则]端口告警规则触发后，告警规则禁用后在当前告警窗口告警消息不消失

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1406]
前提：
添加192.168.1.172设备的端口流量告警  参考图片：1-1

步骤：
1.当告警规则触发后，点击“告警管理→告警规则”
2.选择192.168.1.172告警规则，点击禁用按钮
→一段时间后，当前告警窗口告警消息不消失

添加数据库信息:"[{"status":1,"notification":"8"},{"status":0,"notification":""}]"
[poller.zip](https://github.com/three-plus-three/hw_issues/files/1224255/poller.zip)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170818_278_x64.exe  版本确认，close处理。
