### ISSUE TITLE
[线路信息显示]线路的显示信息太宽

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1407]
[线路信息显示]线路的显示信息太宽
![image](https://user-images.githubusercontent.com/22296563/29304154-34fa1fa0-81c4-11e7-99f7-8ce4eec1fbb6.png)

**Comment by eeiceyes** [comment]
默认的名称就是这么宽，默认的线路显示设置是不显示这一项的；如果觉得太长要么设置成不显示（默认设置），要么修改线路名称。

**Comment by xiauye** [comment]
ok
