### ISSUE TITLE
[监控管理]实时监控页面正在监控数据中，打开设备负载监控的cpu监控，在设备负载窗口点击导出按钮，导出的数据是实时监控页面的数据

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1408]
步骤：
1.点击“监控管理→实时监控”
2.实时监控页面选择设备，点击开始，生成设备信息
3.点击“监控管理→设备负载监控→CPU利用率”，选择设备信息，生成设备信息，点击导出按钮
→BUG:导出的数据是实时监控页面的数据

![1-1](https://user-images.githubusercontent.com/28615156/29305714-a8c3d842-81cc-11e7-8765-27ce20d7601d.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/29305715-a8c68736-81cc-11e7-8921-a35e982674bf.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，close处理。
hengwei_setup_3.2.20171027_2837_x64.exe   版本确认，close处理。
