### ISSUE TITLE
[标准应用服务]添加的Dhcp标准应用服务，访问一会成功一会失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1409]
步骤：
1.点击“资源管理→标准应用管理”
2.点击添加按钮，类型选择Dhcp、Dhcp服务器：192.168.1.1、点击确定按钮
→BUG:Dhcp标准应用服务，访问一会成功一会失败
周边：
Dns和smtp同样出现此现象

![1-1](https://user-images.githubusercontent.com/28615156/29308215-899f13b8-81d7-11e7-9f88-9d9169713a15.jpg)

[server_biz.zip](https://github.com/three-plus-three/hw_issues/files/1224504/server_biz.zip)

**Comment by runner-mei** [comment]
这个是网络问题， 我用别的工具也是如此， 可能是这几天 192.168.1.1 不稳定

**Comment by hengwei-test** [comment]
了解
