### ISSUE TITLE
Windows 添加历史记录规则报错

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#141]
一台Windows系统添加磁盘历史规则，运行日志出现错误；
walk 数据：10.2.3.206
错误如下：
 
internal error:
    disk_partition_win_rm: 'wbem' is required.
    disk_partition_win_wmi: 'wmi' is required.
    disk_partition_hr_windows: row with key is '11' process failed, '1.3.6.1.2.1.25.2.3.1.5' isn't found for the 'N:\ Label:新加卷  Serial Number c6b6da6f' - row with key is '5' cann`t convert to uint32, value is [string]`[int32]-636841985

![disk](https://cloud.githubusercontent.com/assets/14171497/12414270/6555b77c-becf-11e5-83f9-c5bac0f26782.jpg)
[10.2.3.206.txt](https://github.com/three-plus-three/hw_issues/files/95591/10.2.3.206.txt)

**Comment by runner-mei** [comment]
已修复
