### ISSUE TITLE
[业务总览]业务总览页面，添加的业务模块中数据库的监控项数据获取不到

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1410]
前提：
1.添加MySQL数据库，在服务总览页面设置mysql数据库的监控项 参考图片：1-1
步骤;
1.点击“运维管理→服务总览”
2.点击添加按钮，添加业务模块在模块中添加MySQL数据库
→BUG:添加的业务模块中数据库的监控项颜色发生变化、但是数据获取不到   参考图片：1-2

周边：
1.中间件和标准应用同样发生此现象 →BUG

![1-1](https://user-images.githubusercontent.com/28615156/29343811-0c0802d6-8266-11e7-93eb-32bac35208d0.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/29343810-0bf65efa-8266-11e7-9b39-d18ab5bc8307.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170821_279_x64.exe  版本验证 同样出现此现象

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170823_2647_x64.exe 版本确认，close处理。
