### ISSUE TITLE
[表报规则管理]TCP连接数统计报表生成的报表点击查看出现内部错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1411]
前提:
1.历史记录规则添加TCP连接数的规则
步骤：
1.点击“报表管理→报表规则管理”
2.点击添加按钮，添加TCP连接数统计报  参考图片：1-2
→BUG:TCP连接数统计报表生成的报表点击查看出现内部错误

![1-1](https://user-images.githubusercontent.com/28615156/29345570-515e6f8a-8272-11e7-8a1a-8de31ae6b40b.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/29345571-5166018c-8272-11e7-849e-01f57ec12699.jpg)

[Desktop.zip](https://github.com/three-plus-three/hw_issues/files/1227088/Desktop.zip)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170818_277_x64.exe  版本确认，close处理。
