### ISSUE TITLE
[资产管理]添加员工，不能把员工的姓名作为唯一值，应该把员工ID设为唯一值

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1418]
[资产管理]添加员工，不能把员工的姓名作为唯一值，应该把员工ID设为唯一值

![image](https://user-images.githubusercontent.com/22296563/29352598-f142ef04-8299-11e7-9a5f-54c7b7a85f4f.png)

**Comment by hengwei-wtk** [comment]
ok

**Comment by xiauye** [comment]
ok
