### ISSUE TITLE
[监控管理]cisco交换机的运行视图中，硬件信息中温度信息取不到

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1419]
前提：
添加Cisco交换机、IP地址：192.168.1.172
步骤：
1.点击“监控管理→设备运行管理”
2.管理对象选择：192.168.1.172
3.运行视图页面选择硬件
→BUG:硬件信息中温度取不到

![1-1](https://user-images.githubusercontent.com/28615156/29355005-f62591d6-82a1-11e7-8053-d3ef67ae4dc1.jpg)

**Comment by runner-mei** [comment]
温度有时会的值有时会没有，只有状态，请当值没有时显示不支持，而不是 0

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
