### ISSUE TITLE
[浙江期货]添加设备端口状态告警，规则触发后网络视图设备没有气泡图标出现

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1420]
步骤;
1.网络视图选中设备，右击选择“添加告警→添加状态告警”
2.端口告警状态，选择一个端口设置为告警规则   参考图片：1-1、1-2
→BUG:规则触发后网络视图设备没有气泡图标出现
周边：
1.端口流量告警同样出现此现象→BUG
2.告警触发后，选中触发规则的设备右键选择当前告警，没有触发告警的消息→BUG

![1-1](https://user-images.githubusercontent.com/28615156/29357099-f768a824-82a8-11e7-95ae-077d605a49cf.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/29357100-f769e07c-82a8-11e7-8b6c-5896a771d2c9.jpg)
![1-3](https://user-images.githubusercontent.com/28615156/29357101-f84cb0f0-82a8-11e7-86d8-4bb839672b89.jpg)
[Desktop.zip](https://github.com/three-plus-three/hw_issues/files/1227722/Desktop.zip)

**Comment by runner-mei** [comment]
我已实现接口，请zhj继续

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170831_2679_x64.exe 版本确认，
1.告警规则删除后，当前告警中的告警数不对
2.网络视图告警气泡产生后，点击气泡查看当前告警窗口，关闭窗口网络视图气泡消失

**Comment by eeiceyes** [comment]
1，告警气泡数不对的问题已经解决

**Comment by runner-mei** [comment]
删除的问题已解决

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170920_387_x64.exe  版本确认，close处理。
