### ISSUE TITLE
[资产管理]添加一个预警管理，再进行编辑，是不可以进行编辑的

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1422]
[资产管理]添加一个预警管理，再进行编辑，是不可以进行编辑的
![image](https://user-images.githubusercontent.com/22296563/29357556-8ad4abde-82aa-11e7-913d-448fbdbc0e71.png)

**Comment by hengwei-wtk** [comment]
已修复

**Comment by xiauye** [comment]
ok
