### ISSUE TITLE
[告警规则]添加Ping测试[结果] = true 时触发告警、规则触发后，当前告警中的告警内容为“管理ip不可达！”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1423]
步骤;
1.网络视图页面选中设备右击，选择“已设置告警规则”
2.Ping测试的告警规则的结果修改为“ true ”
→规则触发后，当前告警中的告警内容为“管理ip不可达！”

![1-1](https://user-images.githubusercontent.com/28615156/29357955-fcd3be22-82ab-11e7-953a-30de86775736.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/29357956-fd9413b6-82ab-11e7-8f7b-56c6be09fee0.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170830_2674_x64.exe   版本确认，close处理。
