### ISSUE TITLE
[VLAN信息]VLAN信息未获取到

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1425]
前提：
centos操作系统
步骤;
1.点击“运维管理→网络视图”
2.空白地方右击，选择“VLAN信息”
→BUG:VLAN信息未获取到

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
tpt-2.3.20170821.166~7a131d8.x86_64.rpm  版本确认，close处理。
