### ISSUE TITLE
[资产管理]告警通知，一个资产告警通知一模一样的发三次

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1427]
[资产管理]告警通知，一个资产告警一模一样的通知发三次
![image](https://user-images.githubusercontent.com/22296563/29394060-8c071b3c-833a-11e7-9a75-437b9650da8f.png)
![image](https://user-images.githubusercontent.com/22296563/29394067-98c01ef0-833a-11e7-8439-de7aae68c5ec.png)

**Comment by hengwei-wtk** [comment]
ok

**Comment by xiauye** [comment]
ok
