### ISSUE TITLE
[报表规则管理]Linux环境操作系统，添加的报表规则生成报表后没有发送邮件

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1430]
前提：
centos操作系统
步骤：
1.点击“报表管理→报表规则管理”
2.点击添加按钮，添加“端口流量分析报表”   参考1-1
→BUG:报表设备时间规则触发了，报表生成没有发送邮件信息
周边：
1.点击立即生成同样出现此现象→BUG
2.线路流量分析报表同样出现此现象→BUG
3.设备负载统计报表同样出现此现象→BUG
4.告警事件统计报表同样出现此现象→BUG
5.中间件负载统计报表同样出现此现象→BUG
6.TCP连接数统计报表同样出现此现象→BUG
7.虚拟化负载统计报表同样出现此现象→BUG
8.自定义负载统计报表同样出现此现象→BUG
9.巡检点统计报表同样出现此现象→BUG
10巡检任务统计报表同样出现此现象→BUG
11.设备端口使用情况报表同样出现此现象→BUG
12设备运行情况报表同样出现此现象→BUG

![1-1](https://user-images.githubusercontent.com/28615156/29401716-ec79b608-8364-11e7-9cd5-a2f175a07f6d.jpg)

[Desktop.zip](https://github.com/three-plus-three/hw_issues/files/1230517/Desktop.zip)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-2.3.20170821.166~7a131d8.x86_64.rpm 版本确认，现象还在现

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.2.20170828.885~eeb06de.x86_64.rpm 版本确认，close处理。
