### ISSUE TITLE
[用户管理]Linux环境操作系统，多次输入密码错误账号锁定，admin账号进行解锁时发生错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1431]
前提：
新建用户多次输入错误的密码账号被锁定
步骤;
1.admin账号，点击“系统管理→用户管理”
2.点击锁定账号的状态的解锁图标
→BUG:admin账号进行解锁时发生错误

![1-1](https://user-images.githubusercontent.com/28615156/29402329-26b4b078-8367-11e7-883b-2f621aaa0382.jpg)
[Desktop.zip](https://github.com/three-plus-three/hw_issues/files/1230552/Desktop.zip)

**Comment by runner-mei** [comment]
fixed?

**Comment by hengwei-test** [comment]
tpt-2.3.20171027.300~e149012.x86_64.rpm 版本3次确认 未再现此现象 、close处理
