### ISSUE TITLE
[角色管理]新添加的角色操作，角色管理页面选择全部角色，点击删除按钮后显示没有权限操作

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1432]
前提：
1.添加新的用户信息，用户角色选择“administrator”    参考图片：1-1
2.添加新的角色信息  参考图片：1-2
步骤：
1.新添加用户操作，点击“系统管理→角色管理”
2.点击全选，点击“删除”按钮
→点击删除按钮后显示没有权限操作   参考图片：1-3

![1-1](https://user-images.githubusercontent.com/28615156/29446006-858cf0b4-841c-11e7-9662-e2a6e70fe641.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/29446007-85933b40-841c-11e7-90f5-2822f3a81cfa.jpg)
![1-3](https://user-images.githubusercontent.com/28615156/29446008-8593c876-841c-11e7-9e35-e2f3f23d1ac6.jpg)
[Desktop.zip](https://github.com/three-plus-three/hw_issues/files/1233414/Desktop.zip)

**Comment by eeiceyes** [comment]
加了个强制约束，非admin或具有administrator角色的用户，强制隐藏用户管理和角色管理功能

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170922_2764_x64.exe  版本确认，close处理。
