### ISSUE TITLE
[数据流] 360浏览器，登录界面不兼容

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1433]
[数据流] 360浏览器，登录界面不兼容
![image](https://user-images.githubusercontent.com/22296563/29447068-8ad3553a-8422-11e7-9e63-df76a3170bbf.png)

**Comment by runner-mei** [comment]
fix

**Comment by runner-mei** [comment]
fix

**Comment by xiauye** [comment]
ok
