### ISSUE TITLE
[报表生成查看]Linux操作环境、报表生成查看页面导出的压缩文件，解压出错

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1434]
前提：
1.centos操作环境
2.有多份报表信息生成
步骤：
1.点击“报表管理→报表生成查看”
2.点击导出按钮，导出全部的报表信息
→BUG:导出的压缩文件解压出错    

周边：
1.巡检结果页面的下载报告同样出现此现象→BUG
2.预置报表查看页面同样出现此现象→BUG

![1-1](https://user-images.githubusercontent.com/28615156/29447883-92c341a2-8426-11e7-8ab5-7b7f88bce58c.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.2.20170823.872~6ca2978.x86_64.rpm 版本确认，close处理。
