### ISSUE TITLE
[通知方式]添加外部程序通知后，点击编辑页面空白表示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1435]
步骤：
1.点击“系统管理→通知方式”
2.点击添加按钮，添加外部程序的通知方式
3.选择外部程序通知方式，点击编辑按钮
→BUG:点击编辑页面空白表示
周边：
1.添加后的外部程序规则，在通知方式页面没有类型显示→BUG

![1-1](https://user-images.githubusercontent.com/28615156/29450222-5cb92ef0-8430-11e7-919b-3a3fa4381c0a.jpg)

[web_server.txt](https://github.com/three-plus-three/hw_issues/files/1233726/web_server.txt)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170823_2647_x64.exe  版本确认编辑还是不好使

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170824_2650_x64.exe
