### ISSUE TITLE
[拓扑图]每次刷新的时候，都会把机器名显示出来一下，然后又自动消失

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1436]
[拓扑图]每次刷新的时候，都会把机器名显示出来一两秒，然后又自动消失
![image](https://user-images.githubusercontent.com/22296563/29451382-1067c08e-8435-11e7-8656-eebcda3a96a0.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，close处理。
