### ISSUE TITLE
[资产管理]  通知信息连续发三条一模一样的

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1438]
[资产管理]  通知信息连续发三条一模一样的
2017/08/18 17:56:41.490187 event.go:71: [error - 0 ] umarshal 'OK' to *httputil.ResultImpl failed, invalid character 'O' looking for beginning of value
2017/08/18 17:56:41.557565 event.go:71: [error - 1 ] umarshal 'OK' to *httputil.ResultImpl failed, invalid character 'O' looking for beginning of value
2017/08/18 17:56:41.666933 event.go:71: [error - 2 ] umarshal 'OK' to *httputil.ResultImpl failed, invalid character 'O' looking for beginning of value

**Comment by runner-mei** [comment]
fix
