### ISSUE TITLE
[刷新设备]显示刷新信息太长。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1439]
[刷新设备]显示刷新信息太长。
![image](https://user-images.githubusercontent.com/22296563/29501085-55961d98-8658-11e7-9aed-ef14fc7b1db7.png)

**Comment by eeiceyes** [comment]
改了下，现在只显示出现错误和未完成的后台任务

**Comment by xiauye** [comment]
ok
