### ISSUE TITLE
[用户操作日志]当线路信息更新后，在用户操作日志页面的类型显示“update_link”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1441]
前提：
1.添加的线路信息更新
步骤;
1.点击“系统管理→用户操作日志”
→BUG:用户操作日志页面中类型显示为“update_link”

![1503284641 1](https://user-images.githubusercontent.com/28615156/29502251-2e963be8-8661-11e7-8f81-d2863497c510.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
