### ISSUE TITLE
[登入]当强制登入的账号，非正常退出的账号再次登入没有强制登入选项出现

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1443]
前提：
IP：192.168.1.201 使用admin账号登入管理平台
步骤：
1.IP：192.168.1.99使用admin账号强制登入
2.IP：192.168.1.99登入后，关闭浏览器
3.IP：192.168.1.99再次使用admin账号登入管理平台
→BUG:再次登入时没有出现强制登入选项

**Comment by runner-mei** [comment]
现在已改成 192.168.1.99再次使用admin账号登入时不需要强制登入选项
但 192.168.1.201 登出后再次登入需要强制登入选项

**Comment by hengwei-test** [comment]
就的数据覆盖安装环境
hengwei_setup_3.2.20170831_2679_x64.exe 版本确认，  
1.192.168.1.99用户强制登入后，192.168.1.201 登出再次登入没有强制登入选项

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170901_2684_x64.exe  版本确认，close处理。
