### ISSUE TITLE
[网络视图]设备显示设置中，设置机器名称不在下标显示不成功

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1446]
步骤：
1.点击“运维管理→网络视图”
2.空白地方右击，选择“设备显示设置（默认）”，选择显示属性所有选项全部选择确定   参考图片：1-1
3.再次空白地方右击，选择“设备显示设置（默认）”，在显示属性中把“在下标显示”选择取消 参考图片：1-2
→BUG:网络视图上设备的机器名称还显示

![1-1](https://user-images.githubusercontent.com/28615156/29505872-563a2186-867b-11e7-81c7-2b219c5e384a.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/29505873-56531f60-867b-11e7-9c18-2d385a32944e.jpg)
[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/1237933/server_biz.txt)

**Comment by eeiceyes** [comment]
全部都不选是采用节点的默认名称，一般是设备的IP地址

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，close处理。
