### ISSUE TITLE
[监控管理]交换机设备运行视图页面的硬件信息获取不到

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1447]
前提：
添加IP：192.168.1.172 设备信息
步骤：
1.点击“监控管理→设备运行视图”
2.选择对象选择IP:192.168.1.172
3.运行视图页面选择硬件信息
→BUG:硬件信息获取不到

![1-1](https://user-images.githubusercontent.com/28615156/29507278-fdbb538e-8681-11e7-93e2-fb0485ef6c9f.jpg)
[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/1238017/server_biz.txt)
[web_server.txt](https://github.com/three-plus-three/hw_issues/files/1238018/web_server.txt)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170821_2627_x64.exe  版本验证  还是同样的现象

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170823_2647_x64.exe 版本确认，close处理。
