### ISSUE TITLE
[告警规则]添加的告警规则到达触发条件不触发告警

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1449]
poller报错信息：

2017/08/21 17:54:04 [warn] failed to send result to channel [ cpu/5803//599aa2739020d10dc0000323 ]
2017/08/21 17:54:04 [srv] poll failed, request 'http://127.0.0.1:8082/hengwei/ds/metric_trigger/@snapshot?by_lines=true' fail: 500 Internal Server Error: pq: 已保留的连接位置为执行非复制请求的超级用户预留
2017/08/21 17:54:10 [srv] poll failed, request 'http://127.0.0.1:8082/hengwei/ds/metric_trigger/@snapshot?by_lines=true' fail: 500 Internal Server Error: pq: 已保留的连接位置为执行非复制请求的超级用户预留
2017/08/21 17:54:14 [srv] poll failed, request 'http://127.0.0.1:8082/hengwei/ds/metric_trigger/@snapshot?by_lines=true' fail: 500 Internal Server Error: pq: 已保留的连接位置为执行非复制请求的超级用户预留

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170927_2780_x64.exe  版本确认，close处理。
