### ISSUE TITLE
[数据库管理]添加oracleRAC数据库时，点击“测试访问参数”时发生错误测试不通过

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1450]
步骤：
1.点击“资源管理→数据库管理”
2.点击添加按钮，添加数据库类型为：oracleRAC的数据库 参考图片：1-1
3.点击“测试访问参数”
→BUG:发生错误测试不通过
周边：
1.点击“测试”时显示测试通过
![1-1](https://user-images.githubusercontent.com/28615156/29549241-c39479c0-8739-11e7-857b-9ccbf39f4b28.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/29549240-c37b531e-8739-11e7-9f1d-279065f67c4f.jpg)
[web_server.txt](https://github.com/three-plus-three/hw_issues/files/1240846/web_server.txt)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170824_2657_x64.exe 版本确认，close处理。
