### ISSUE TITLE
[业务视图]业务视图页面点击业务视图名称没有编辑名称的功能

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1451]
步骤：
1.点击“运维管理→业务视图”
2.点击“添加”按钮，添加新的业务视图
→BUG:添加的业务视图，点击业务视图名称没有编辑名称的功能

![1-1](https://user-images.githubusercontent.com/28615156/29553580-54381bbc-874e-11e7-8be5-91d2ee085a28.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170922_2764_x64.exe  版本确认，close处理。
