### ISSUE TITLE
[业务视图]业务视图中点击还原按钮，再进行“导出图片”操作，导出后的图片不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1453]
前提：
添加业务视图，视图中添加多个管理对象
步骤：
1.业务视图的视图中点击“还原”按钮
2.空白地方右击选择“导出图片”
→导出后的图片不全

![1-1](https://user-images.githubusercontent.com/28615156/29555549-9dfaac36-8755-11e7-887c-8656e2403820.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，还出现此现象

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
