### ISSUE TITLE
[国妇婴] 自动巡检的结果预先读取，不要进去后慢慢读。

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#1455]
场景： 因为巡检规则太多，每次时间太长， 用户希望预先读好， 然后用户直接点进去看就行了。

**Comment by eeiceyes** [comment]
原先读取方式一个一个读，而且默认的超时时间比较长。

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
