### ISSUE TITLE
[当前巡检任务]过期的任务，巡检任务自动分配到“后续任务（最近一周）”里

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1456]
前提：
1.添加巡检点
2.分配一个指定日期的巡检任务
步骤：
1.点击“运维管理→当前巡检任务”
→BUG:过期的任务，巡检任务自动分配到“后续任务（最近一周）”里，没有“过期任务”这一栏

周边：
1.在巡检异常一览中确认过期任务后，“后续任务（最近一周）”里的过期任务不消失

![1-1](https://user-images.githubusercontent.com/28615156/29595218-bb8a598e-87e8-11e7-8012-472733846aa5.jpg)

3.2版本参考图片：
![1-2](https://user-images.githubusercontent.com/28615156/29595238-d9a92a9e-87e8-11e7-95bc-4034a783a9d1.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170901_329_x64.exe   版本确认，close处理。

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170904_335_x64.exe 版本后导入旧的数据 再次出现此现象  参考图片：1-1
hengwei_setup_2.3.20170904_335_x64.exe 版本全新安装重新添加的数据，未出现此现象

![1-1](https://user-images.githubusercontent.com/28615156/30054124-9c8b9ba4-925d-11e7-9a00-788d9f06d4f0.jpg)
