### ISSUE TITLE
[巡检点管理]添加巡检点中有个巡检指标，添加ping测试结果，应该为：true，false

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1459]
[巡检点管理]添加巡检点中有个巡检指标，添加ping测试结果，应该为：true，false
![image](https://user-images.githubusercontent.com/22296563/29596637-9e7b8d2e-87f0-11e7-86af-3087ea5426ec.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
取值失败，但是手动刷新就会成功
![image](https://user-images.githubusercontent.com/22296563/29958631-43082244-8f26-11e7-91ae-bc41ffd59302.png)

**Comment by runner-mei** [comment]
fixed

**Comment by xiauye** [comment]
ok
