### ISSUE TITLE
（南华期货）告警中的数据与历史记录中的数据单位不同，并且由于取数间隔不同导致数据相差过大

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#146]
![1](https://cloud.githubusercontent.com/assets/14171518/12469400/6f4717d2-c026-11e5-9e19-ddd0d3ff6dae.jpg)
![2](https://cloud.githubusercontent.com/assets/14171518/12469405/7c459a26-c026-11e5-9b28-2420acf72c42.jpg)

**Comment by runner-mei** [comment]
单位已改成 bits/s

**Comment by runner-mei** [comment]
单位已改成 bits/s
