### ISSUE TITLE
[业务总览]添加同名的业务系统时，提示框中应该添加“同名的业务系统已存在”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1460]
前提：
添加一个test的业务系统
步骤：
1.点击“运维管理→业务总览”
2.点击添加按钮，添加名称为：test的同名业务系统
→BUG:提示框中应该添加“同名的业务系统已存在”

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，close处理。
