### ISSUE TITLE
[巡检结果查询]巡检结果的巡检报高用PDF方式查看、PDF中的“利用率”的文字换行

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1462]
前提：
添加巡检任务，进行巡检填写，生成巡检结果
步骤：
1.点击“运维管理→巡检结果查看”
2.点击巡检结果的“巡检报告（PDF）”
→PDF中的“利用率”的文字换行
![1-1](https://user-images.githubusercontent.com/28615156/29599406-0cc76224-8802-11e7-83a1-911fe48b9eb3.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
