### ISSUE TITLE
[网络视图]拓扑图定位时候，定位的位置不准确

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1465]
步骤：
1.拓扑图定位时候，定位的位置不准确

**Comment by eeiceyes** [comment]
现场通过配置启用了twaver的拓扑图，去掉data/conf/web.properties中的配置即可,topology.apply_new=false
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170828_311_x64.exe 版本 去掉data/conf/web.properties中的配置即可,topology.apply_new=false 确认，close处理。
