### ISSUE TITLE
[TFTP脚本管理]测试Cisco交换机的脚本测试发生端口错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1466]
步骤：
1.点击“常用工具→TFTP脚本管理”
2.选择IP:192.168.1.172,交换机进行脚本测试发生以下错误信息

2017/08/24 13:08:54 [warn] [ssh] ssh parameters is empty
2017/08/24 13:08:54 [warn] [telnet] username is missing
2017/08/24 13:08:54 [warn] [snmp] username is missing
2017/08/24 13:08:54 masterHost is 127.0.0.1
============== console ==============
2017/08/24 13:08:54 backup device '4134' failed, 
connect failed, dial tcp 192.168.1.172:0: getsockopt: connection refused
2017/08/24 13:08:54 ============
2017/08/24 13:08:54 ERROR
192.168.1.172
2017-08-24T13:08:54.409816+08:00

connect failed, dial tcp 192.168.1.172:0: getsockopt: connection refused
当前设备的测试结束。

**Comment by runner-mei** [comment]
fix
这是你 telnet 或 ssh 参数没有配置

2017/08/24 13:08:54 [warn] [ssh] ssh parameters is empty
2017/08/24 13:08:54 [warn] [telnet] username is missing

**Comment by hengwei-test** [comment]
snmp和telnet 访问参数已经配置

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170828_2662_x64.exe 版本确认，close处理。
