### ISSUE TITLE
[告警规则]添加的告警规则，到达触发条件没有触发告警规则

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1467]
添加的告警规则，到达触发条件没有触发告警规则
错误信息：

load notfications failed, request 'http://127.0.0.1:8082/hengwei/ds/notification_group/3?includes=notification_rule' fail: 500 Internal Server Error: table 'db' is not a subclass of 'notification_rule'.

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170824_2657_x64.exe 版本确认，BUG现象还在现，报一下问题：
  | load  notfications failed, request  'http://127.0.0.1:8082/hengwei/ds/notification_group/3?includes=notification_rule'  fail: 500 Internal Server Error: table 'db' is not a subclass of  'notification_rule'.
-- | --

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170825_2661_x64.exe 版本确认，close处理。
