### ISSUE TITLE
[自定义统计数据]添加自定义统计数据，提示“创建失败”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1469]
步骤：
1.点击“报表管理→自定义统计数据”
2.点击添加按钮添加自定义统计数据信息
→BUG:添加数据，点击“确定按钮”、提示“创建失败”

![1503569284 1](https://user-images.githubusercontent.com/28615156/29661774-a291e612-88f7-11e7-9486-817deadcad07.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170829_2669_x64.exe  版本确认，close处理。
