### ISSUE TITLE
（南华期货）线路流量过大时由于科学计数法导致告警规则运行失败

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#147]
47425	149-M7I-1_so-0/1/0 connect to 150-M7i-2_so-0/1/0 滨江机房至张江机房 铁通155M专线_[指标]线路流量[总流量]	'2.412967e+06' isn't a number.

**Comment by runner-mei** [comment]
已修复

**Comment by runner-mei** [comment]
已修复
