### ISSUE TITLE
[主机管理]添加主机IPMI的访问参数时，点击测试按钮，提示“参数测试失败”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1470]
步骤：
1.点击“资源管理→主机管理”
2.点击“添加”按钮，添加IPMI[带外管理]的参数
3.点击测试按钮
→点击测试按钮，提示“参数测试失败”

![1503631163 1](https://user-images.githubusercontent.com/28615156/29698396-b71ca29e-8987-11e7-97c9-c011060e111d.jpg)

**Comment by eeiceyes** [comment]
实际的访问权限中，用户名首字母是大写的
