### ISSUE TITLE
[报表管理]点击添加“设备端口使用情况报表”，提示“Template Execution Error”错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1471]
步骤：
1.点击“报表管理→报表规则管理”
2.点击添加“设备端口使用情况报表”
→BUG:提示“Template Execution Error”错误

周边：
1.添加设备运行情况报表同样出现此现象→BUG

![1503632133 1](https://user-images.githubusercontent.com/28615156/29698725-3b6dd7d2-898a-11e7-9eda-cd77d5df35f8.jpg)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170828_2662_x64.exe 版本确认，close处理。
