### ISSUE TITLE
[通知方式]添加通知方式，点击编辑按钮发生错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1472]
步骤：
1.点击“系统管理→通知方式”
2.点击添加按钮，添加邮件通知方式
3.选择邮件通知方式，点击编辑按钮
→点击编辑按钮发生错误

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170825_2661_x64.exe 版本确认，close处理。
