### ISSUE TITLE
[报表规则管理]添加的报表规则，报表生成时未发送邮件

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1473]
步骤：
1.点击“报表管理→报表规则管理”
2.点击添加按钮，添加报表规则
3.当规则触发后，生成报表信息
→BUG:生成报表信息时，未发送邮件

周边
预置报表同样发生此现象→BUG

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170828_2662_x64.exe 版本确认，close处理。
