### ISSUE TITLE
[业务总览]新建用户没有操作权限，有访问权限，点击业务总览页面，显示无访问权限

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1474]
前提;
1.新建角色，赋予角色业务总览页面访问权限，不赋予操作权限  参考图片：1-1
2.新建一个用户信息，选择新建的角色
步骤：
1.新建用户登入平台，点击“运维管理→业务总览”
→BUG:显示无访问权限

![1-1](https://user-images.githubusercontent.com/28615156/29704287-bd02a1b2-89ab-11e7-8e72-4d4427e6a490.jpg)

![1-2](https://user-images.githubusercontent.com/28615156/29704286-bcfefd82-89ab-11e7-8f63-cfbab2e10d7a.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170829_2669_x64.exe  版本确认，close处理。
