### ISSUE TITLE
[告警日志]新建用户没有操作权限，告警日志页面还能进行导出操作

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1475]
前提;
1.新建角色，赋予角色业务总览页面访问权限，不赋予操作权限 参考图片：1-1
2.新建一个用户信息，选择新建的角色
步骤;
1.新建用户登入平台，点击“告警管理→告警日志”
→BUG告警日志页面还能进行导出操作

周边：
1.巡检结果查询同样出现此现象→BUG
2.实时监控页面同样出现此现象→BUG
3.网络视图页面导出设备&接口信息同样出现此现象→BUG
4.网络视图页面导出图片同样出现此现象→BUG
5.组合告警日志页面同样出现此现象→BUG
6.设备管理页面同样出现此现象→BUG
7.主机管理页面同样出现此现象→BUG
8.syslog查询页面同样出现此现象→BUG
9.地址簿页面同样出现此现象→BUG
10.记录数据查询页面同样出现此现象→BUG
11.流量数据查询页面同样出现此现象→BUG
12.生成报表查看页面同样出现此现象→BUG
13.预置报表查看页面同样出现此现象→BUG

![1-1](https://user-images.githubusercontent.com/28615156/29707314-77338de8-89b7-11e7-84ae-302e20eba47d.jpg)

**Comment by eeiceyes** [comment]
导出是无损操作，是属于查看操作
