### ISSUE TITLE
[告警规则日志]没有操作权限的用户，在告警规则日志可以操作

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1476]
前提;
1.新建角色，赋予角色业务总览页面访问权限，不赋予操作权限 参考图片：1-1
2.新建一个用户信息，选择新建的角色
步骤：
1.新建用户登入平台，点击“告警管理→规则运行日志”
→BUG:在告警规则日志可以操作

周边：
1.规则运行日志同样出现此现象→BUG
2.网络视图页面，工具栏中的背景修改同样出现此现象→BUG
3.数据库脚本管理同样出现此现象→BUG
4.脚本管理页面同样出现此现象→BUG
5.图元管理页面同样出现此现象→BUG
6.机房视图页面，工具栏中删除机柜同样出现此现象→BUG
7.Tag列表页面同样出现此现象→BUG
8.设备属性窗口的关联Tag修改同样出现此现象→BUG

![1-1](https://user-images.githubusercontent.com/28615156/29707264-457dde2a-89b7-11e7-88fe-e10c5a06129e.jpg)

**Comment by eeiceyes** [comment]
fixed，第8点不需要修改，设备属性不能报错即可

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170829_2669_x64.exe  版本确认，close处理。
