### ISSUE TITLE
[监控管理]没有操作权限用户，点击“设备负载监控”没有选择对象框弹出

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1477]
前提;
1.新建角色，赋予角色业务总览页面访问权限，不赋予操作权限 参考图片：1-1
2.新建一个用户信息，选择新建的角色
步骤：
1.新建用户登入平台，点击“监控管理→设备负载监控”
→BUG:没有选择对象框弹出

周边：
1.线路流量监控同样出现此现象→BUG
2.设备负载TOPN同样出现此现象→BUG
3.线路流量TOPN同样出现此现象→BUG

![1-1](https://user-images.githubusercontent.com/28615156/29707294-6722ea8e-89b7-11e7-84e2-fb57e14bd843.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170829_2669_x64.exe  版本确认，close处理。
