### ISSUE TITLE
[巡检点管理]巡检点管理页面，第一个条巡检点规则，点击所属业务，弹出的提示框显示不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1478]
前提：
添加巡检点规则
步骤：
1.点击“运维管理→巡检点管理”
2.第一个条巡检点规则，点击所属业务
→弹出的提示框显示不全

![1503652819 1](https://user-images.githubusercontent.com/28615156/29708101-297f7e24-89ba-11e7-8cde-fe864cb8f18b.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，close处理。
