### ISSUE TITLE
[通知方式]添加的短信通知方式，选择短信通知方式进行编辑，编辑页面信息显示不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1479]
前提：
添加短信通知方式，内容信息都填写
步骤：
1.点击“系统管理→通知方式”
2.选择短信通知方式，点击编辑按钮
→BUG:编辑页面信息显示不全,手机号码不显示  参考图片：1-2

周边：
1.http调用通知方式同样出现此现象→BUG

![1-1](https://user-images.githubusercontent.com/28615156/29756449-b304f61a-8bd6-11e7-9719-90b0dc0ad581.jpg)

![1-2](https://user-images.githubusercontent.com/28615156/29756447-b2f1c4be-8bd6-11e7-9902-351e17041b94.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170829_2669_x64.exe  版本确认，短信通知方式已经修复，周边1还是出现此现象

**Comment by eeiceyes** [comment]
web通知方式在2.3版本是独立表存的，原本就有一个attributes字段，现在合并表后，需要改个名字，改成fields

**Comment by eeiceyes** [comment]
我这边改了

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170831_2679_x64.exe 版本确认，close处理。
