### ISSUE TITLE
测试 SNMP可写测试

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#148]
对设备SNMP写权限的测试是否开启

**Comment by runner-mei** [comment]
这个可能需要弹出对话框，让用户来选写什么 Oid
对话框中需要提供三个值
 1. Oid           // 最好是下拉框并可以手工埴写的
 2. 类型         下拉框， 可取值为
           				int32
				uint32
				counter
				gauge
				counter64
				octets   
				opaque
				oid
				ipaddress
 3. 值

测试时指标为 snmp_set， 方法为  PUT, 上面的三个参数如下处理
1.  Oid   作为 snmp.oid 参数
2. 类型和值 放在 body 中
   格式为  [类型] 值，  如果值为 octets, opaque, 时将字符串作 16 进制编码

**Comment by runner-mei** [comment]
你测试可以让用户选下面几个
sysContact  .1.3.6.1.2.1.1.4 .0
sysName .1.3.6.1.2.1.1.5 .0
sysLocation.1.3.6.1.2.1.1.6 .0
