### ISSUE TITLE
[通知方式]编辑企业微信通知方式，点击确定按钮发生错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1480]
前提：
添加企业微信通知方式
步骤：
1.点击“系统管理→通知方式”
2.选择企业微信通知方式，编辑备注内容
3.点击“确定”按钮
→点击确定按钮发生错误

![1-1](https://user-images.githubusercontent.com/28615156/29756647-14832db6-8bd8-11e7-99f2-0e5b20330f76.jpg)

[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/1254913/server_biz.txt)
[web_server.txt](https://github.com/three-plus-three/hw_issues/files/1254912/web_server.txt)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170829_2669_x64.exe  版本确认，close处理。
