### ISSUE TITLE
[报表规则管理]添加设备运行情况报表，页面显示信息不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1481]
步骤;
1.点击“报表管理→报表规则管理”
2.点击添加按钮，添加设备运行情况报表
→BUG:页面显示信息不全

周边：
1.设备端口使用情况报表同样出现此现象→BUG
2.添加设备中多了“无”这个选项→BUG

![1503890123 1](https://user-images.githubusercontent.com/28615156/29757973-5bd827fc-8be2-11e7-80e1-2a35c6b8e245.jpg)

**Comment by hengwei-lhm** [comment]
header与其他页面不一致的问题不管， 设备选项中多了一个 无的选项已修复

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，close处理。
