### ISSUE TITLE
[告警规则]添加的线路总流量告警，添加的告警规则，在告警规则页面显示告警条件与设置的不一致

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1482]
前提：
1.添加线路流量告警 参考图片1-1
步骤：
1.点击“告警管理→告警规则”
→BUG：新添加线路流量告警最的告警条件与设置的不一致  参考图片：1-2
周边：
1.设备端口的告警规则同样出现此现象→BUG
2.组合端口的告警规则同样出现此现象→BUG

![1-1](https://user-images.githubusercontent.com/28615156/29760070-6d0ef134-8bf3-11e7-8fe6-73eb8de70605.jpg)

![1-2](https://user-images.githubusercontent.com/28615156/29760071-6d0feb8e-8bf3-11e7-8d58-e85aa22eab1d.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170829_2669_x64.exe  版本确认，close处理。
