### ISSUE TITLE
[告警规则]添加告警规则信息页面，告警的类型点击不好使

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1483]
步骤：
1.点击“告警管理→告警规则”
2.点击添加按钮
3.告警规则页面，依次点击“设备”、“线路与端口”、“主机”、“数据库”、“中间件”
4.中间件的扩展栏打开，点击“主机”
→BUG:点击扩展栏打开类型以上的选项无效

周边：
1.现象发生后点击扩展栏一下的类型有效操作
2.刷新页面后操作好使

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170830_2674_x64.exe   版本确认，还是出现同样的现象
