### ISSUE TITLE
[机房视图]无操作权限用户，机房视图页面能够删除机柜

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1486]
前提;
1.新建角色，赋予角色业务总览页面访问权限，不赋予操作权限 参考图片：1-1
2.新建一个用户信息，选择新建的角色
3.机房视图新建机柜
步骤：
1.新建用户登入平台，点击“运维管理→机房视图”
2.机房视图选择机柜，右击删除机柜
→BUG:无操作权限用户，机房视图页面能够删除机柜

周边：
1.编辑机柜属性同样出现此现象→BUG
2.业务视图的名称和备注修改同样出现此现象→BUG
3.服务总览的显示设置/备注的操作同样出现此现象→BUG
4.巡检填写页面同样出现此现象→BUG
5.巡检异常处理页面同样出现此现象→BUG
6.点击通知方式的名称，进入编辑页面可以编辑操作→BUG
7.点击通知组的名称，进入编辑页面可以编辑操作→BUG
8.点击名称进入编辑页面的设备端口使用情况报表和设备运行情况报表同样出现此现象→BUG
9.TFTP脚本内容可以进行编辑同样出现此现象→BUG
10.设备配置模板同样出现此现象→BUG
11.设备配置查看页面可以修改“备份规则”、“管理配置模板”操作同样出现此现象→BUG
12.虚拟化页面的显示设置/备注操作同样出现此现象→BUG
13.虚拟机管理页面的备注可以操作同样出现此现象→BUG
14.数据存储管理页面的备注可以操作同样出现此现象→BUG
15.后台任务的设备信息可以删除同样出现此现象→BUG

![1-1](https://user-images.githubusercontent.com/28615156/29766028-fdd183be-8c0f-11e7-8b4c-935cbdcfdf2e.jpg)

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170829_2669_x64.exe  版本确认， 现象还在现

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170830_2677_x64.exe 版本确认，还是有以下的页面能够进行操作

1.业务视图的名称和备注修改同样出现此现象→BUG
2.服务总览的显示设置的操作同样出现此现象→BUG
3.巡检填写页面同样出现此现象→BUG
4.设备配置模板同样出现此现象→BUG
5.设备配置查看页面可以修改“备份规则”、“管理配置模板”操作同样出现此现象→BUG
6.虚拟化的监控一览页面的显示设置/备注操作同样出现此现象→BUG
7.虚拟机管理页面的备注可以操作同样出现此现象→BUG
8.数据存储管理页面的备注可以操作同样出现此现象→BUG
9.后台任务的设备信息可以删除同样出现此现象→BUG
10.历史记录中能够修改记录指标的参数
11.业务流量查看页面，点击右上角的"+"按钮能够添加业务操作

**Comment by eeiceyes** [comment]
巡检比较特殊，既然是他的任务，他就可读写

**Comment by eeiceyes** [comment]
第9条也暂时不用管它

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170901_2684_x64.exe  版本确认，close处理。
