### ISSUE TITLE
[用户管理]无操作权限的用户，用户管理页面被锁定的用户的状态为“正常”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1487]
前提;
1.新建角色，赋予角色业务总览页面访问权限，不赋予操作权限
2.新建一个用户信息，选择新建的角色
3.新建一个有操作权限的用户，登入平台多次输入错误的密码，使账号被锁定
步骤：
1.无操作权限用户登入，点击“系统管理→用户管理”
→用户管理页面被锁定的用户的状态为“正常”

![1-1](https://user-images.githubusercontent.com/28615156/29800807-9b58a192-8c9e-11e7-9072-a54805f8f69a.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，close处理。
