### ISSUE TITLE
[告警规则]添加告警规则，达到告警规则的触发条件没有触发告警

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1488]
1.添加告警规则，达到告警规则的触发条件没有触发告警
添加一下错误信息：

request 'http://127.0.0.1:8082/hengwei/ts/alerts' fail: 400 Bad Request: it is not a valid json string, json: cannot unmarshal number into Go struct field AlertEntity.current_value of type string

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170829_2669_x64.exe  版本确认，close处理。
