### ISSUE TITLE
[图元管理]图元管理页面修改图元图标不成功

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1489]
前提：
IE11浏览器登入平台
步骤：
1.点击“系统管理→图元管理”
2.选择图元点击修改图元
→BUG:修改图元图标不成功

周边：
谷歌和火狐浏览器不发生此现象

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
