### ISSUE TITLE
[巡检任务管理]分配巡检任务，选择巡检时间段 支持一下手动输入

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1490]
[巡检任务管理]分配巡检任务，选择巡检时间段 支持一下手动输入

![image](https://user-images.githubusercontent.com/22296563/29806012-7a518254-8cbf-11e7-92d7-af18c3ec2693.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
2.3上也改了

**Comment by xiauye** [comment]
已验证
