### ISSUE TITLE
[网络视图]交换机设备的面板视图中，关闭端口不起效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1491]
前提：
添加Cisco交换机 192.168.1.172

步骤：
1.点击“运维管理→网络视图”
2.选中交换机设备右击，选择“设备面板视图”
3.选择一个端口，选择关闭端口
→BUG:关闭端口不起效

交换机设备已经配置了snmp的读写权限
![1503987266 1](https://user-images.githubusercontent.com/28615156/29806986-7daeee5a-8cc4-11e7-96e6-34ab408d7175.jpg)

**Comment by eeiceyes** [comment]
调用端口关闭的代码是：
ExchangeResult result = ExchangeRequest.metricById(ExchangeRequest.MANAGEDOBJECTs, deviceId, "snmp_set")
                .withParam("snmp.oid", "1.3.6.1.2.1.2.2.1.7." + ifIndex + ".9")
                .setBody("[int32]" + requestString)
                .setAction(ExchangeRequest.PUT)
                .send(metricServer);

报的错误是NoCreation

**Comment by runner-mei** [comment]
"1.3.6.1.2.1.2.2.1.7." + ifIndex + ".9"   改成  "1.3.6.1.2.1.2.2.1.7." + ifIndex

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
