### ISSUE TITLE
[业务总览]业务系统中的线路指标信息中的单位显示不对

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1492]
前提：
1.业务总览页面添加业务系统
2.业务系统中添加线路信息
步骤：
1.点击“运维管理→业务总览”
2.鼠标放在线路指标的图标上
→业务系统中的线路指标信息中的单位显示不对

![1503988775 1](https://user-images.githubusercontent.com/28615156/29807989-ec426352-8cc8-11e7-9cfa-7ca86f5d7771.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170922_2764_x64.exe  版本确认，close处理。
