### ISSUE TITLE
[拓扑图最大化] 拓扑图最大化，进行右击任何操作，操作完成之后需要手动刷新页面。才能正常使用。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1493]
[拓扑图最大化] 拓扑图最大化，进行右击任何操作，操作完成之后需要手动刷新页面。才能正常使用。
![image](https://user-images.githubusercontent.com/22296563/29808183-995b16ba-8cc9-11e7-8c99-a988952843c9.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
ok
