### ISSUE TITLE
[任务异常一览]任务异常一览选中已过期任务后，结果选中了正确率异常任务下的巡检任务

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1494]
前提：
1.巡检任务中存在一个已经提交的异常任务
2.过期任务中没有过期任务
步骤：
1.点击“运维管理→任务异常一览”
2.选择已过期任务
→BUG:结果选中了正确率异常任务下的巡检任务

![1-1](https://user-images.githubusercontent.com/28615156/29809095-5ac7a342-8ccd-11e7-9d00-abddf673d5eb.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，还是出现此现象

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170922_2764_x64.exe  版本确认，close处理。
