### ISSUE TITLE
[交换路由设备]运行视图硬件信息，页面显示问题

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1496]
[交换路由设备]运行视图硬件信息，页面显示问题
![image](https://user-images.githubusercontent.com/22296563/29809620-824caa3c-8ccf-11e7-8b63-d1547b2f0be9.png)

**Comment by eeiceyes** [comment]
fix bugs

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20180125_700_x64.exe   版本确认，close处理。
