### ISSUE TITLE
[设备总览]设备树，依据Tag导入设备，关闭按钮显示问题

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1497]
[设备总览]设备树依据Tag导入设备，关闭按钮显示问题

![image](https://user-images.githubusercontent.com/22296563/29856854-1a6def5c-8d88-11e7-867d-6069021df313.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
已确认
