### ISSUE TITLE
[通知方式]测试邮件通知方式时，通知用户的邮件未发送邮件

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1498]
前提：
新添加用户 参考图片：1-1
步骤：
1.点击“系统管理→通知方式”
2.添加邮件通知方式，通知用户中选择新添加的用户
3.点击测试
→BUG:通知用户的邮件未发送邮件

![1-1](https://user-images.githubusercontent.com/28615156/29857902-91452834-8d8d-11e7-8bf9-d2896d9b1723.jpg)

**Comment by runner-mei** [comment]
直接填邮箱的发了， 选用户的没有发是么？
如果将 milestone 改成未计划的

**Comment by hengwei-test** [comment]
旧的数据覆盖安装的环境   hengwei_setup_3.2.20170831_2679_x64.exe 版本确认，告警规则触发后，邮件通知方式中用户的邮件地址未发送邮箱

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170901_333_x64.exe版本确认，告警规则触发后，用户的邮箱未发送邮件
hengwei_setup_3.2.20170901_2692_x64.exe版本确认，已经修复这个现象

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170906_339_x64.exe  版本确认， 告警规则触发后用户的邮件未发送

**Comment by runner-mei** [comment]
2.3 已修复

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170907_346_x64.exe 版本确认，close处理。
