### ISSUE TITLE
[登录用户]IP地址没有更新

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1500]
[登录用户]IP地址没有更新
![image](https://user-images.githubusercontent.com/22296563/29859548-350f6068-8d95-11e7-9330-ffa56c5b688a.png)

**Comment by runner-mei** [comment]
fix

**Comment by xiauye** [comment]
HIMP2.3也需要修改

**Comment by runner-mei** [comment]
fix

**Comment by xiauye** [comment]
ok
