### ISSUE TITLE
[用户管理]有操作权的用户，自己在用户编辑页面自己的角色更改为无操作权的角色，更改后的用户有操作权限

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1501]
前提：
1.新建一个无操作权限有访问权限的角色
2.新建一个用户，角色选择“administrator”
步骤：
1.新添加的用户登入平台，点击“系统管理→用户管理”
2.选择自己登入的用户，点击编辑按钮，角色修改该为无操作权的角色
3.修改后的用户登入操作平台
→更改后的用户有操作权限

**Comment by eeiceyes** [comment]
@runner-mei 该问题即使要改，也不在老版本上改了

**Comment by runner-mei** [comment]
3.2 不修复该问题，你看看 3.3 是不是好了
