### ISSUE TITLE
[设备总览]设备总览页面中工具栏按钮无效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1505]
步骤：
1.点击“运维管理→设备总览”
2.点击工具栏按钮
→点击工具栏按钮无效

**Comment by eeiceyes** [comment]
设备总览页面有点特殊，改成不显示按钮

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，close处理。
