### ISSUE TITLE
[SSO] 增加 LDAP 的支持

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#1508]
后台已增加 LDAP 的支持，但 LDAP 中的用户可能不在 系统中，如果 LDAP 中的用户不在系统中时，SSO 会自动重定向到 /new_user_from_sso 页面。

/new_user_from_sso 页面
1. 从 url 中获取 ticket, 然后验证 ticket
2. 验证 ticket 后从结果用读用户名
3. 以该用户名创建新用户，同时密码为 "ldap"， 注意由于后台 bug, 该用户也可能已存在，请求处一下已存在的情况
   同时 LDAP 中的角色列表我会读到 roles 字段中， 创建用户时可以根据这个 roles 来指定用户的角色。

4. 创建新用户后转到该用户的编辑页面

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
LDAP账号登入后只有一个首页图标，剩下所有页面没有访问权限

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170906_339_x64.exe  版本确认，close处理。
