### ISSUE TITLE
[当前告警]直接报错

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1511]
[当前告警]直接报错

![image](https://user-images.githubusercontent.com/22296563/29957811-0090967a-8f22-11e7-8aad-a68264f1cee2.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170904_2693_x64.exe  版本确认，close处理。
