### ISSUE TITLE
[安装]旧数据覆盖安装平台启动后，tpt_mc后台任务在一直重启

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1512]
1.旧数据覆盖安装平台启动后，tpt_mc后台任务在一直重启

[web_server.txt](https://github.com/three-plus-three/hw_issues/files/1273434/web_server.txt)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170904_2693_x64.exe  版本确认，close处理。
