### ISSUE TITLE
[告警管理]当前告警点击直接报错

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1513]
[告警管理]当前告警点击直接报错
![image](https://user-images.githubusercontent.com/22296563/30009500-8ba01872-915b-11e7-964a-cf7eb894d56e.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170904_2693_x64.exe  版本确认，close处理。
