### ISSUE TITLE
[巡检任务管理]分配巡检任务设置（邮件发送用户、邮件发送地址）通知，都会连续发送两份邮件。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1515]
[巡检任务管理]分配巡检任务设置（邮件发送用户、邮件发送地址）通知，都会连续发送两份邮件。

![image](https://user-images.githubusercontent.com/22296563/30013834-6ade32ca-917b-11e7-87fb-a6b1dd5dfd0d.png)

![image](https://user-images.githubusercontent.com/22296563/30013768-03e5673c-917b-11e7-9cda-07765e129ecb.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170904_335_x64.exe   版本确认，close处理。
