### ISSUE TITLE
[虚拟化视图]虚拟机的历史记录查看的内存利用率窗口中文字显示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1516]
前提：
1.添加VCenter主机，进行同步操作
步骤：
1.点击“虚拟化&存储→虚拟化视图”
2.选择一台运行的设备，右击选择“历史记录查看-内存利用率”
→BUG:内存利用率窗口中文字显示错误

![1-1](https://user-images.githubusercontent.com/28615156/30015099-e16738aa-9181-11e7-8b23-6bee34b1059f.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，close处理。
