### ISSUE TITLE
[自定义检测告警]设置通知组，把系统管理下面的所有通知组删除，自定义检测告警也跟着删除

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1517]
[自定义检测告警]设置通知组，把系统管理下面的所有的通知组删除，自定义检测告警也跟着删除

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
删除通知组，提示修改一下

![1-1](https://user-images.githubusercontent.com/28615156/30041442-a7b28b96-921c-11e7-842f-7834b9e06a06.png)

**Comment by eeiceyes** [comment]
提示“删除失败，存在自定义检测告警规则引用了该通知组！”

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170905_336_x64.exe 版本确认，close处理。
