### ISSUE TITLE
[生成拓扑图]失败报错。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1518]
[生成拓扑图]失败报错。   再安装HIMP2.3保留以前的数据不要删除再进行生成拓扑图

![image](https://user-images.githubusercontent.com/22296563/30020227-bcf6db24-9195-11e7-86ab-b199b884fdff.png)
[拓扑图生成文件.txt](https://github.com/three-plus-three/hw_issues/files/1274265/default.txt)

**Comment by eeiceyes** [comment]
fixed
