### ISSUE TITLE
[华东电网](当前巡检任务)自定义巡检项也要添加到巡检率中

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1520]
[当前巡检任务]自定义巡检项也要添加到巡检率中
![image](https://user-images.githubusercontent.com/22296563/30049310-b84b364e-924c-11e7-97f5-66a0ab62b9a1.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
ok
