### ISSUE TITLE
[华东电网](巡检报告查看)饼图中，显示要简单明了。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1521]
[巡检报告查看]饼图中，要简单明了。例如：已提交无异常，修改：已异常；已提交有未处理异常，修改：有未处理异常；已提交无未处理异常，修改：无处理异常
![image](https://user-images.githubusercontent.com/22296563/30049471-6e23e204-924d-11e7-91e8-58172e85dcf7.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
ok
