### ISSUE TITLE
[用户管理]新的用户管理需要添加用户首页登入的页面

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1526]
新的用户管理需要添加用户首页登入的页面

![1504776259 1](https://user-images.githubusercontent.com/28615156/30156155-7a0b4e90-93f1-11e7-9797-87a5ddf5256b.jpg)

**Comment by runner-mei** [comment]
在 3.3 中修复

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171123_2910_x64.exe   版本确认，close处理。
