### ISSUE TITLE
[设备管理]网络视图页面添加后的设备，获取不到设备信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1532]
1.网络视图页面添加后的设备，获取不到设备信息

周边：
手动修改设备类型后，能获取到设备数据指标，在设备属性页面获取不到描述信息。

![1505118646 1](https://user-images.githubusercontent.com/28615156/30265509-dc9080c4-970e-11e7-81a4-a84da503e52d.jpg)

[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/1291878/server_biz.txt)
[web_server.txt](https://github.com/three-plus-three/hw_issues/files/1291879/web_server.txt)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170912_2715_x64.exe   版本确认，close处理。
