### ISSUE TITLE
[设备显示设置(默认)]显示属性，机器名先设置在下标中显示，然后在取消在下标中显示。有的机器机器名还是显示在下标中。

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1533]
[设备显示设置(默认)]显示属性，机器名先设置在下标中显示，然后在取消在下标中显示。有的机器机器名还是显示在下标中。
![image](https://user-images.githubusercontent.com/22296563/30306513-30d4bf96-97ab-11e7-97fd-cc8ac8f7c2da.png)

**Comment by hengwei-test** [comment]
2.3的Linux同样出现此现象

**Comment by eeiceyes** [comment]
fixed，对于新添加的设备才会有效

**Comment by xiauye** [comment]
ok
