### ISSUE TITLE
[syslog告警]发送syslog信息，设置告警关键字， 发送syslog信息中没有设置的关键字也会告警

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1535]
[syslog告警]发送syslog信息，设置告警关键字， 发送信息中没有设置的关键字也会告警
![image](https://user-images.githubusercontent.com/22296563/30317230-1100a4a6-97dc-11e7-8c20-a574fe92b855.png)
![image](https://user-images.githubusercontent.com/22296563/30317249-251e8eb2-97dc-11e7-8c86-4d8c5796cc21.png)

**Comment by runner-mei** [comment]
syslog内容呢？

**Comment by xiauye** [comment]
[日志告警规则]syslog告警关键字为：test       发送syslog任意内容，但是内容不包含：test

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171122_512_x64.exe版本确认，close处理。
