### ISSUE TITLE
[配置备份]发两条变动通知 ，设置好配置备份规则发一条，到了设定的备份时间段再发一条

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1538]
[配置备份]发两条通知 ，设置好配置备份规则发一条，到了设定的备份时间段再发一条
![image](https://user-images.githubusercontent.com/22296563/30360883-985b2944-9886-11e7-9f18-bd8d595c380d.png)

**Comment by runner-mei** [comment]
？
不明白，再发一条？
