### ISSUE TITLE
[日志文件告警]文件日志告警规则后，服务重启后，文件日志规则再次触发

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1541]
前提：
添加文件日志告警规则
步骤：
1.文件日志告警规则触发
2.网管机服务重启
→服务重启后，文件日志规则再次触发

![1-1](https://user-images.githubusercontent.com/28615156/30580014-ae0240cc-9d4d-11e7-8683-f289f56ce636.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170920_387_x64.exe  版本确认，close处理。
