### ISSUE TITLE
[标准应用管理]所有的服务类型，响应时间，显示都有问题

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1542]
[标准应用管理]所有的服务类型，响应时间，显示都有问题
![image](https://user-images.githubusercontent.com/22296563/30584270-d0ea1fca-9d5b-11e7-9c18-0edc10e41510.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
已确认
