### ISSUE TITLE
[登入]账号锁定后，输入正确的密码登入时，提示的文言出错

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1544]
前进：
多次输入错误的密码使账号被锁定
步骤：
输入正确的密码时，提示的文言出错
提示错误的文言：用户名或密码不正确！

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170922_395_x64.exe  版本确认，close处理。
