### ISSUE TITLE
[网络视图]新添加的用户在网络视图第一次进行添加缩略图操作后，网络视图页面所有设备图标全部集中在右上角

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1545]
前提：
1.admin账号添加设备信息
2.添加新的用户，角色选择administrator
步骤：
1.新添加的用户在网络视图页面选择多个设备添加缩略图  参考图片：1-1
→BUG:网络视图页面所有设备图标全部集中在右上角        参考图片：1-2

周边：
添加的缩略图删除后，网络视图页面的设备位置还原
![1-1](https://user-images.githubusercontent.com/28615156/30727921-e46da062-9f86-11e7-9312-55016ac42d41.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/30727922-e4a8ac16-9f86-11e7-9287-3afb397f0a7e.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
