### ISSUE TITLE
[农科院] 虚拟化上 宿主机cpu、mem有断点，导致宿主机颜色时有时无

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#1546]
![image](https://user-images.githubusercontent.com/14171518/30730548-836e2b7e-9f9a-11e7-8b4d-b2816b505094.png)
![image](https://user-images.githubusercontent.com/14171518/30730567-97f4819c-9f9a-11e7-855d-869b7156cd08.png)

**Comment by runner-mei** [comment]
改进，看看是否已解决。
