### ISSUE TITLE
[用户管理]正在登录运维平台的用户，应该是不能进行删除。  

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1547]
[用户管理]1、正在登录运维平台的用户，应该是不能进行删除。
2、正在登录运维平台的用户直接删除之后，再打开运维平台登录页面直接报错
![image](https://user-images.githubusercontent.com/22296563/30730564-9651e118-9f9a-11e7-8131-b7a9c19bee4f.png)

**Comment by eeiceyes** [comment]
新的用户模块改吧

**Comment by runner-mei** [comment]
新的用户模块改上已改好， 实现方式为不删除
