### ISSUE TITLE
[告警日志]告警日志页面，告警类型添加一个全部这个选项

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1553]
1. 告警日志页面，告警类型添加一个全部这个选项
2. 2.3中也修改一下

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170927_2780_x64.exe  版本确认，已经添加“全部类型”选项

hengwei_setup_2.3.20170929_408_x64.exe  版本确认，没有添加“全部类型”选项

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，close处理。
