### ISSUE TITLE
[标准应用管理]有操作权角色的用户，标准应用添加页面显示无权限操作

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1556]
前提：
1.添加所有页面，都有操作权限的角色
2.新添加的角色，创建新的用户
步骤：
1.点击“资源管理→标准应用管理”
2.点击添加按钮
→显示无权限操作
周边
1.批量添加同样出现此现象

![1-1](https://user-images.githubusercontent.com/28615156/30793132-5c619638-a1f2-11e7-948c-cba22a6f4bb6.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/30793133-5c621d9c-a1f2-11e7-9374-6f1f8d8f69a9.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。

**Comment by hengwei-test** [comment]
2.3的版本也修复一下

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171023_435_x64.exe   版本确认，close处理。
