### ISSUE TITLE
[标准应用管理]批量添加标准应用时，少添加一个标准应用管理信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1557]
步骤：
1.点击“资源管理→标准应用管理”
2.点击“批量添加”按钮
3.选择http，添加多个http信息、点击确认按钮
→返回标准应用列表、少添加一个标准应用管理信息

周边：
1.ftp、ldap等都出现这个现象

![1-1](https://user-images.githubusercontent.com/28615156/30793663-0ffc37e0-a1f6-11e7-981c-749ce5082f8d.jpg)
![1-2](https://user-images.githubusercontent.com/28615156/30793664-101fb85a-a1f6-11e7-877b-93bbb07f32a0.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170925_2774_x64.exe   版本确认，close处理。
