### ISSUE TITLE
[当前告警]添加个条同样条件用一台设备的告警规则，规则触发后、在当前告警页面显示的统计数目不对

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1558]
前提：
添加2条相同条件同一台机器的告警规则
步骤;
1.告警规则触发后，删除最先触发的告警规则
2.当前告警页面确认
→当前告警页面显示的统计数不对

![1506323020 1](https://user-images.githubusercontent.com/28615156/30796271-eb1716d0-a203-11e7-8f48-da4f3985cd5d.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，close处理。
hengwei_setup_3.2.20171027_2837_x64.exe   版本确认，close处理。
