### ISSUE TITLE
[网络视图]端口状态告警窗口，设置告警条件时、弹出“保存错误”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1560]
步骤：
1.网络视图选中设备右击、选中“添加告警-端口流量告警”
2.告警添加选择“b/s”、值选择“20”点击确认按钮
→设置告警条件时、弹出“保存错误”
![1506331435 1](https://user-images.githubusercontent.com/28615156/30801595-618ab5c6-a216-11e7-8e79-496f5c4bce87.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171102_457_x64.exe   版本确认，close处理。
