### ISSUE TITLE
[LDAP]LDAP服务器关闭后，使用LDAP账号登入时提示消息“用户名或密码不正确!”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1562]
前提：
使用过LDAP账号登入过管理平台
步骤：
1.LDAP服务器关闭后，使用LDAP账号登入时提示消息“用户名或密码不正确!”

周边：
1.LDAP服务器关闭后，使用LDAP账号登入时添加提示消息“LDAP服务关闭”之类的消息

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170927_2776_x64.exe  版本确认，close处理。
