### ISSUE TITLE
[业务视图]业务视图页面，点击业务视图节点上的告警气泡，提示“加载失败”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1563]
1.业务视图页面，点击业务视图节点上的告警气泡，提示“加载失败”

![1506416375 1](https://user-images.githubusercontent.com/28615156/30851850-6ad3c91c-a2dc-11e7-9e34-b112084c3ae2.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170927_2780_x64.exe  版本确认，close处理。

**Comment by hengwei-test** [comment]
2.3版本上也修复一下

**Comment by eeiceyes** [comment]
2.3fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171122_511_x64.exe版本确认，close处理。
