### ISSUE TITLE
[监控总览]没有操作权限的用户，监控总览页面点击“全屏”按钮操作无效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1564]
步骤：
1.没有操作权限的用户、点击“运维管理→监控总览”
2.点击“全屏”按钮
→BUG:全屏按钮无效

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
