### ISSUE TITLE
[业务总览]自动创建业务视图时，提示“创建失败”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1565]
1.业务总览页面，点击业务系统名称，自动创建业务视图时，提示“创建失败”

![1-1](https://user-images.githubusercontent.com/28615156/30853085-594dba6e-a2e0-11e7-8318-288f921c9466.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170927_2780_x64.exe  版本确认，close处理。
