### ISSUE TITLE
[任务异常一览]无操作权限的用户、任务异常一览页面能够确认巡检

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1566]
前提;
1.新建角色，赋予角色业务总览页面访问权限，不赋予操作权限 参考图片：1-1
2.新建一个用户信息，选择新建的角色
步骤：
1.无操作权限用户、点击“运维管理→任务异常一览”
→任务异常一览页面能够确认巡检

![1506418808 1](https://user-images.githubusercontent.com/28615156/30853773-4ecbd3bc-a2e2-11e7-8a6b-3006599c6eac.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
