### ISSUE TITLE
[业务总览]无操作权限的用户、业务总览页点击业务系统的名称能够自动创建关联业务视图

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1567]
前提;
1.新建角色，赋予角色业务总览页面访问权限，不赋予操作权限 参考图片：1-1
2.新建一个用户信息，选择新建的角色
步骤：
1.点击“运维管理→业务总览”
2.点击业务系统的名称
→能够自动创建关联业务视图

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
