### ISSUE TITLE
[虚拟化视图]无权限操作用户、虚拟化视图页面能够上传背景操作

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1569]
前提;
1.新建角色，赋予角色业务总览页面访问权限，不赋予操作权限 参考图片：1-1
2.新建一个用户信息，选择新建的角色
步骤：
1.虚拟化视图页面能够上传和删除背景操作
周边
1.网络视图页面能够上传和删除背景操作
2.业务视图页面能够上传和删除背景操作

![1506477788 1](https://user-images.githubusercontent.com/28615156/30892640-4e24634a-a36c-11e7-93b0-e67eb31d920f.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
