### ISSUE TITLE
[业务总览]业务总览自动创建业务时，创建的业务视图名称存在时，提示“创建失败”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1571]
前提：
1.添加test业务视图
2.业务总览页面，添加test业务系统
步骤：
1.业务总览页面，点击test业务系统的名称
→创建的业务视图名称存在时，提示“创建失败”

![1506500274 1](https://user-images.githubusercontent.com/28615156/30902880-8204a67e-a39f-11e7-9391-f70bdb25c15d.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，还是提示创建失败 
![1507519710 1](https://user-images.githubusercontent.com/28615156/31324433-10c1f83c-ace5-11e7-8b29-a71902f9f895.jpg)
