### ISSUE TITLE
[生成拓扑图]Linux版本生成拓扑图时一直在进行中，显示线路信息无法拓扑出来

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1572]
1.Linux版本生成拓扑图时一直在进行中，显示线路信息无法拓扑出来

[topology_discover_1506571427673.txt](https://github.com/three-plus-three/hw_issues/files/1339549/topology_discover_1506571427673.txt)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.3.1.20171020.1009~877bb01.x86_64.rpm    版本确认，close处理。

**Comment by hengwei-test** [comment]
tpt-3.2.20171020.1012~652c00e.x86_64.rpm     版本确认，close处理。
