### ISSUE TITLE
[业务总览]Linux环境、新建用户在业务总览页面没有访问权限

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1576]
前提：
1.新建一个角色，所有页面的访问操作权限
2.新建用户使用新建的角色
步骤：
1.新建用户登入平台，点击“运维管理→业务总览”
→提示“您没有访问当前页面的权限”

![1506651854](https://user-images.githubusercontent.com/28615156/30998351-70834ace-a500-11e7-933c-5e90e4b8c7fb.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.2.20171020.1012~652c00e.x86_64.rpm     版本确认，close处理。
