### ISSUE TITLE
[线路流量监控]监控上下行帧流量时、点击“下行”按钮，在监视窗口视图鼠标放在监视信息上不显示线路信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1578]
步骤：
1.点击“监控管理→线路流量监控→上下行帧流量”
2.选择线路，在线路帧流量监控窗口点击“下行”
3.鼠标放在监控信息上
→监视信息上不显示线路信息

![11111](https://user-images.githubusercontent.com/28615156/31003441-4bddfb66-a522-11e7-8ea0-0ec620c79ea2.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
所有有这种叠加显示的界面都有可能出现这个问题

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
