### ISSUE TITLE
[虚拟化视图]带符号的虚拟机名称,在虚拟化视图中符号乱码

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1579]
1.带符号的虚拟机名称,在虚拟化视图中符号乱码

![1506678526 1](https://user-images.githubusercontent.com/28615156/31010879-011a7178-a53f-11e7-96de-506109414be2.jpg)

![1506678604 1](https://user-images.githubusercontent.com/28615156/31010881-019fa4a6-a53f-11e7-80d0-2ef0db74e98a.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，close处理。
hengwei_setup_3.2.20171027_2837_x64.exe   版本确认，close处理。
