### ISSUE TITLE
[记录数据查询]记录数据查询页面，记录类型选择Windows后，在记录规则中能选择Linux设备信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1581]
步骤：
1.点击“报表管理→记录数据查询”
2.记录类型选择Windows、点击记录规则
→在记录规则中能选择Linux设备信息

![1506743705 1](https://user-images.githubusercontent.com/28615156/31042289-f95df84a-a5d6-11e7-8af5-1083b1bbdfc7.jpg)
![1506743728 1](https://user-images.githubusercontent.com/28615156/31042290-f976fab6-a5d6-11e7-9635-dd5d7a9957ed.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171020_2816_x64.exe.xltd.cfg  版本确认，close处理。
