### ISSUE TITLE
[当前巡检任务]在填写当前巡检任务页面，当前值中的信息过多，使结论栏中的文字发送换行

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1582]
1.在填写当前巡检任务页面，当前值中的信息过多，使结论栏中的文字发送换行

![1507533126 1](https://user-images.githubusercontent.com/28615156/31327934-d5c55e20-ad04-11e7-9463-c304382c7f54.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171026_2836_x64.exe     版本确认,还是出现此现象

![1509084814 1](https://user-images.githubusercontent.com/28615156/32090282-3711f2b8-bb21-11e7-988c-3d3af71a6498.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171102_2911_x64.exe 版本确认，close处理。
