### ISSUE TITLE
[虚拟化视图]第一次操作与虚拟化中心同步失败。第二次操作再进行同步就同步成功

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1584]
[虚拟化视图]第一次操作与虚拟化中心同步失败。第二次操作同步就同步成功
![image](https://user-images.githubusercontent.com/22296563/31370280-be2bc35e-adbc-11e7-88b3-aa07447e2b2b.png)

**Comment by hengwei-test** [comment]
与  https://github.com/three-plus-three/hw_issues/issues/1387   重复 close处理。
