### ISSUE TITLE
[巡检任务管理]新添加的巡检任务中，邮件发送地址添加多个时，邮件发送失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1585]
1.新添加的巡检任务中，邮件发送地址添加多个时，邮件发送失败

后台任务报错信息：
create job handler failed, 'to_address' is invalid - mail: expected single address, got "\r\nzhz9561847865@163.com"

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171011_413_x64.exe   版本确认，close处理。
