### ISSUE TITLE
[后台任务]后台任务中设备ping通后，后台任务不消失

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1592]
1.后台任务中设备ping通后，后台任务不消失

**Comment by eeiceyes** [comment]
这个是用来显示当前出问题的后台任务的，现在改成只显示最近2小时的

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171101_2844_x64 版本确认、设备刷新时后台任务图标不出现

**Comment by eeiceyes** [comment]
直接打补丁是oK的，下一版本再验证

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171102_2848_x64.exe 版本 确认超过2小时 后台任务还未删除   

![1509700356 1](https://user-images.githubusercontent.com/28615156/32366710-4d3d800e-c0ba-11e7-9d69-293c1e50b49c.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，close处理。
