### ISSUE TITLE
[remote_ping]在监控总览页面，添加remote_ping的面板、获取不到remote_ping的数据

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1594]
1.在监控总览页面，添加remote_ping的面板、获取不到remote_ping的数据
2.只在3.2上Telnet设备上remote_ping SSH设备出现

[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/1381199/server_biz.txt)

**Comment by hengwei-test** [comment]
等2.3出10/12以后版本再确认一下

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171020_2816_x64.exe.xltd.cfg  版本确认，close处理。
