### ISSUE TITLE
[监控总览]添加DB表空间查看面板时，在面板设置的参数设置窗口，选择多个数据时，表空间的选项容易重叠显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1595]
1.添加DB表空间查看面板时，在面板设置的参数设置窗口，选择多个数据时，表空间的选项容易重叠显示

![1507789854 1](https://user-images.githubusercontent.com/28615156/31482448-f454f924-af5a-11e7-8ad4-7ee2247869c2.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171020_2816_x64.exe.xltd.cfg  版本确认，close处理。
