### ISSUE TITLE
[监控总览]remote_ping面板中ping的设备如果出现ping通的情况、监控总览页面刷新后remote_ping面板所有数据信息没有

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1596]
1.remote_ping面板中ping的设备如果出现ping通的情况、监控总览页面刷新后remote_ping面板所有数据信息没有

[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/1381305/server_biz.txt)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171020_2816_x64.exe.xltd.cfg  版本确认，close处理。
