### ISSUE TITLE
[业务总览]添加的业务总览系统中关联业务视图、添加后的业务总览系统中自动获取关联业务视图的设备信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1598]
1.添加的业务总览系统中关联业务视图、添加后的业务总览系统中自动获取关联业务视图的设备信息

**Comment by eeiceyes** [comment]
在添加或编辑业务系统时，如果管理对象为空，将自动从关联视图进行同步

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171026_2836_x64.exe     版本确认，close处理。
