### ISSUE TITLE
[直接报错]新安装运维平台第一次登录进去直接报错

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1600]
新安装运维平台第一次登录进去直接报错
![image](https://user-images.githubusercontent.com/22296563/31652767-dbd760e8-b352-11e7-823a-f6693eda1179.png)

**Comment by eeiceyes** [comment]
可能前台启动好了，后台还没启动好，访问的时候刚好报错，很偶然发生，暂时不改了
