### ISSUE TITLE
[生成拓扑图]生成拓扑图结束，打开任意视图页面都报错。  不用admin用户登录

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1601]
[生成拓扑图]生成拓扑图结束，打开任意视图页面都报错。  不用admin用户登录
![image](https://user-images.githubusercontent.com/22296563/31653271-914610ae-b354-11e7-849c-f5e17326b1d5.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
已确认
