### ISSUE TITLE
拓扑图上设备右键菜单增加批量添加IP地址ping告警的入口

### ISSUE THREAD

**Issue by eeiceyes** [three-plus-three/hw_issues#1602]
添加界面支持批量输入多个目标IP地址，重复输入地址不会重复添加告警

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171019_425_x64.exe 版本确认 发生错误
![1508477619 1](https://user-images.githubusercontent.com/28615156/31806594-94f055e0-b59b-11e7-8558-a8326da9afae.jpg)

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171021_2822_x64.exe  版本确认，close处理。
