### ISSUE TITLE
[巡检任务]在巡检任务编辑页面、巡检方式的巡检人员分配是可编辑的

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1603]
1.在巡检任务编辑页面、巡检方式的巡检人员分配是可编辑的

**Comment by hengwei-test** [comment]
https://github.com/three-plus-three/hw_issues/issues/1607 重复

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，close处理。
