### ISSUE TITLE
[华东电网] 巡检管理功能对巡检任务可以编辑添加组 

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1607]
在巡检任务分配中因任务多时比较乱难以管理.可用组的方式进行分配梳理.并对组里的任务进行统一批量管理.如:禁用/启用

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，close处理。
