### ISSUE TITLE
[中间件负载统计报表]在统计类型中只有一个中间件，其它都中间件都没有统计过来

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1608]
[中间件负载统计报表]在统计类型中只有一个中间件，其它都中间件都没有统计过来
![image](https://user-images.githubusercontent.com/22296563/31808299-22dca5bc-b5a5-11e7-8da7-540d00b6ec77.png)

**Comment by eeiceyes** [comment]
这个是日后根据需求来做定制开发的，目前就是这样
