### ISSUE TITLE
[报表规则管理]添加任意报表是，有效时段应该是必须输入时间段，不选择时间统计出来的报表，不知道为当前哪个时间段的报表

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1609]
[报表规则管理]添加任意报表是，有效时段应该是必须输入时间段，不选择时间统计出来的报表，不知道为当前哪个时间段的报表
![image](https://user-images.githubusercontent.com/22296563/31808582-6b356a32-b5a6-11e7-86a9-8daa1e22728b.png)

**Comment by eeiceyes** [comment]
增加描述“如果为空，则统计所有时段。”

**Comment by xiauye** [comment]
已验证
