### ISSUE TITLE
[虚拟化负载统计报表]趋势分析，没有统计出来

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1610]
[虚拟化负载统计报表]趋势分析，没有统计出来
![image](https://user-images.githubusercontent.com/22296563/31809697-5aaabd8e-b5ab-11e7-91dc-152466fca550.png)

![image](https://user-images.githubusercontent.com/22296563/31809710-6a400830-b5ab-11e7-90cc-a7a8e0ced2a1.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
已验证
