### ISSUE TITLE
[LDAP]LDAP 账号登入时区分大小写限制

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1617]
1.LDAP 账号登入区分大小写限制

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171222_3086_x64.exe版本确认，还是有问题
![1514184969 1](https://user-images.githubusercontent.com/28615156/34334789-76293bb4-e984-11e7-9580-835c135675d3.jpg)

administrator账号登入：
![1514185156 1](https://user-images.githubusercontent.com/28615156/34334800-886ed5e0-e984-11e7-9bc9-d1b8754266fb.jpg)


Administrator账号登入：

![1514185193](https://user-images.githubusercontent.com/28615156/34334806-8c752f72-e984-11e7-841f-33d7c46280e2.jpg)

**Comment by runner-mei** [comment]
已修复，大小写用户名认为是同一个

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180402_3103_x64.exe  版本确认，close处理。
