### ISSUE TITLE
[监控总览]监控总览页面，Telnet取数方式的remote_ping获取不到数据

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1618]
1.监控总览页面，Telnet取数方式的remote_ping获取不到数据

![1508750630 1](https://user-images.githubusercontent.com/28615156/31881722-fa78e1b6-b816-11e7-8845-77265505b63d.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171023_435_x64.exe   版本确认，close处理。
