### ISSUE TITLE
[Remote Ping测试]没有触发告警

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1620]
[Remote Ping测试]没有触发告警
![image](https://user-images.githubusercontent.com/22296563/31925186-98600236-b8b9-11e7-9bac-b2ab0d2a8c54.png)
告警规则异常：
![image](https://user-images.githubusercontent.com/22296563/31926641-70d3c10e-b8c2-11e7-8395-4ef400415a53.png)

**Comment by runner-mei** [comment]
我没有重现问题
