### ISSUE TITLE
[业务总览]添加第一个业务图时添加按钮是正常的，添加第二个业务图时，点击添加按钮不起效

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1621]
[业务总览]添加一个业务图时正常的，添加第二个业务图时，点击添加按钮不起效
![image](https://user-images.githubusercontent.com/22296563/31926279-29fa0ccc-b8c0-11e7-9633-c0bd1a923c80.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by xiauye** [comment]
已确认
