### ISSUE TITLE
[当前告警]多个告警级别的告警规则触发后，告警规则页面全选统一修改告警规则

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1622]
步骤：
1.告警规则页面多个告警级别的告警规则触发
2.选择所有告警规则批量修改告警规则
→在告警级别分类的当前告警页面，告警信息不显示

![1508836175 1](https://user-images.githubusercontent.com/28615156/31934264-3211574e-b8de-11e7-92e3-99826c4ccebd.jpg)

![1508836351 1](https://user-images.githubusercontent.com/28615156/31934773-aca116f6-b8df-11e7-95dd-b15e1491e3aa.jpg)

**Comment by eeiceyes** [comment]
fixed，级别以触发时的告警级别为准

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171026_2836_x64.exe     版本确认，close处理。
