### ISSUE TITLE
[用户操作日志]直接报错

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1624]
[用户操作日志]直接报错

![image](https://user-images.githubusercontent.com/22296563/32090280-35b49efc-bb21-11e7-8eac-b1116d4918f4.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171102_2911_x64.exe 版本确认，close处理。
