### ISSUE TITLE
[当前告警]按钮失效

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1625]
[当前告警]按钮失效
![image](https://user-images.githubusercontent.com/22296563/32090410-d5f1a572-bb21-11e7-9155-aa2e12c252c4.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171102_2911_x64.exe 版本确认，close处理。
