### ISSUE TITLE
[任务异常一览][巡检异常处理]都直接报错

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1627]
[任务异常一览]直接报错
![image](https://user-images.githubusercontent.com/22296563/32090495-4c316074-bb22-11e7-9fcc-59a5cdee8890.png)
[巡检异常处理]直接报错
![image](https://user-images.githubusercontent.com/22296563/32090698-381ed930-bb23-11e7-9b80-6a1464c92f93.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171102_2911_x64.exe 版本确认，close处理。
