### ISSUE TITLE
[资产管理、服务管理]缺上两个图标

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1629]
[资产管理、服务管理]缺上两个图标
![image](https://user-images.githubusercontent.com/22296563/32092931-02d815ac-bb2d-11e7-86ae-a00d70298a5b.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171102_2911_x64.exe 版本确认，还出现此现象。

![1509685168 1](https://user-images.githubusercontent.com/28615156/32361029-e15a6690-c096-11e7-8e7f-87d2083bfc26.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171107_2927_x64.exe 版本确认，还是出现此现象

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171123_2910_x64.exe   版本确认，close处理。
