### ISSUE TITLE
[服务管理]采购管理、两票管理流量图、采购流量图。都直接报错

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1630]
[服务管理]采购管理、两票管理流量图、采购流量图。都直接报错 
采购管理
![image](https://user-images.githubusercontent.com/22296563/32093051-84a53970-bb2d-11e7-95b0-4490b5bcbe4a.png)
两票管理流量图、采购流量图
![image](https://user-images.githubusercontent.com/22296563/32093124-cd47b662-bb2d-11e7-8eb0-e32378a05fff.png)

**Comment by runner-mei** [comment]
转到  https://github.com/three-plus-three/itsm/issues/62
