### ISSUE TITLE
[用户管理]添加用户时、提示“pq: 重复键违反唯一约束"hengwei_users_and_roles_user_id_role_id_key" ”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1632]
1.添加用户时、提示“pq: 重复键违反唯一约束"hengwei_users_and_roles_user_id_role_id_key" ”

**Comment by runner-mei** [comment]
转到  https://github.com/three-plus-three/itsm/issues/62

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171107_2920_x64.exe 版本确认，close处理。
