### ISSUE TITLE
[业务总览]点击创建的业务名称，自动创建失败，直接报错

### ISSUE THREAD

**Issue by xiauye** [three-plus-three/hw_issues#1636]
[业务总览]点击创建的业务名称，自动创建失败，直接报错
![image](https://user-images.githubusercontent.com/22296563/32162530-4e2bde12-bd94-11e7-8a8a-063201939ea1.png)

![image](https://user-images.githubusercontent.com/22296563/32162711-df3403c6-bd94-11e7-939a-211feb3dd936.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171102_2911_x64.exe 版本确认，close处理。
