### ISSUE TITLE
[登入]新创建的用户登入时，提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1638]
1.新创建的用户登入时，提示错误

![1509513654 1](https://user-images.githubusercontent.com/28615156/32261154-a818f4b8-bf07-11e7-9a2c-476c6d595ebc.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171107_2927_x64.exe 版本确认，close处理。
