### ISSUE TITLE
服务器添加告警--文件信息更新时间运行报错

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#164]
internal error: ls_by_ssh: failed to parse '-rw-r--r--. 1 root root 31 12月 10 16:24 /opt/script.sh ' at '-rw-r--r--. 1 root root 31 12月 10 16:24 /opt/script.sh', '12月 10 16:24' is invalid time. ls_from_result: '' isn't supported

**Comment by runner-mei** [comment]
已修复
