### ISSUE TITLE
[平台安装]平台安装后，启用新的用户管理、tp_mc重启失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1640]
1.平台安装后，启用新的用户管理、tp_mc重启失败

. 11:42:48
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x7d8c04]

goroutine 9 [running]:
github.com/revel/revel.(*Router).Reverse(0x0, 0xeabccc, 0x10, 0xc042442270, 0xc0424c99c0)
	C:/CI_Programs/Jenkins/jobs/tpt_build/workspace/src/engine/tpt_vendor/src/github.com/revel/revel/router.go:600 +0x94
mc/app/routes.tAutoBackup.Index(0x0, 0x0, 0x43cc0b, 0xc0424d20b8)
	C:/CI_Programs/Jenkins/jobs/tpt_build/workspace/src/engine/src/mc/app/routes/routes.go:1147 +0xf1
mc/app.init.1.func2(0xc0420f87e0, 0x2, 0x2, 0x30, 0x2, 0x2)
	C:/CI_Programs/Jenkins/jobs/tpt_build/workspace/src/engine/src/mc/app/init.go:119 +0x4c
github.com/three-plus-three/modules/web_ext.Init.func1.2(0xc0423f86a0, 0x0, 0x40ff7c, 0xc042004460, 0x0)
	C:/CI_Programs/Jenkins/jobs/tpt_build/workspace/src/engine/tpt_vendor/src/github.com/three-plus-three/modules/web_ext/init.go:141 +0x38
github.com/three-plus-three/modules/menus.(*apartClient).write(0xc04253d9a0, 0xc042451fc4, 0x2, 0x2)
	C:/CI_Programs/Jenkins/jobs/tpt_build/workspace/src/engine/tpt_vendor/src/github.com/three-plus-three/modules/menus/client-gen.go:148 +0x47
github.com/three-plus-three/modules/menus.(*apartClient).run.func1()
	C:/CI_Programs/Jenkins/jobs/tpt_build/workspace/src/engine/tpt_vendor/src/github.com/three-plus-three/modules/menus/client-gen.go:241 +0x5d
github.com/three-plus-three/modules/menus.(*apartClient).run(0xc04253d9a0)
	C:/CI_Programs/Jenkins/jobs/tpt_build/workspace/src/engine/tpt_vendor/src/github.com/three-plus-three/modules/menus/client-gen.go:275 +0x1c6
created by github.com/three-plus-three/modules/menus.Connect
	C:/CI_Programs/Jenkins/jobs/tpt_build/workspace/src/engine/tpt_vendor/src/github.com/three-plus-three/modules/menus/client-gen.go:54 +0x28d
[mc][sys] wait process failed - exit status 2
[mc][sys] --------------------  proc end  --------------------
[mc]2017-11-02 11:41:51.9665075 +0800 CST [sys]current status is 'SRV_RUNNING'
[mc][sys] -------------------- proc start --------------------
[mc][sys] C:\Program Files\hengwei/bin/tpt_mc.exe
[mc][sys] 		-importPath
[mc][sys] 		mc
[mc][sys] 		-srcPath
[mc][sys] 		C:\Program Files\hengwei/lib
[mc][sys] 		-runMode
[mc][sys] 		prod
INFO  2017/11/02 11:41:54 module.go:117: Sorted keys module.static
INFO  2017/11/02 11:41:54 module.go:117: Sorted keys module.swagger
INFO  2017/11/02 11:41:54 module.go:117: Sorted keys module.testrunner
INFO  2017/11/02 11:41:54 module.go:117: Sorted keys module.web_templates
INFO  2017/11/02 11:41:54 module.go:152: Loaded module static
INFO  2017/11/02 11:41:54 module.go:152: Loaded module swagger
INFO  2017/11/02 11:41:54 module.go:152: Loaded module web_templates
INFO  2017/11/02 11:41:54 revel.go:249: Initialized Revel v0.17.1 (2017-07-14) for >= go1.6
INFO  2017/11/02 11:41:54 main.go:30: Running revel server
INFO  2017/11/02 11:41:54 init.go:70: begin to read variables from server - http://127.0.0.1:39000/hengwei/

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171102_2911_x64.exe 版本确认，close处理。
