### ISSUE TITLE
设备禁采增加一个 only_some 选项

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#1641]
当前 设备禁采 功能中有三个选项
1. 禁采所有
2. 可采 ICMP
3. 可以所有

现在 增加一个 only_some 选项， 含义为可采集指定的指标。
指标为一个列表，它是一个全局的设置

**Comment by eeiceyes** [comment]
存在文件{data_path}/conf/sampling_kpis.properties文件中
格式参照{device_id}=cpu,mem,arp_info

**Comment by runner-mei** [comment]
有界面么？

**Comment by hengwei-test** [comment]
拓扑图上右键菜单中选择禁采
![default](https://user-images.githubusercontent.com/28615156/35375021-5e0386e2-01e0-11e8-92b3-2001b8f6e448.png)


设备列表中：

![default](https://user-images.githubusercontent.com/28615156/35375050-877e7040-01e0-11e8-89a1-99bd58ff9896.png)
