### ISSUE TITLE
[登入]任意用户管理中的账号登入，登入后都显示admin用户登入

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1642]
1.任意用户管理中的账号登入，登入后都显示admin用户登入

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171123_2910_x64.exe   版本确认，版本确认还出现此现象

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，close处理。
