### ISSUE TITLE
[用户管理]用户管理页面用户删除，跳转页面空白显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1643]
1.LDAP用户删除，跳转页面空白显示

[um.txt](https://github.com/three-plus-three/hw_issues/files/1440241/um.txt)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171107_2927_x64.exe 版本确认，close处理。
