### ISSUE TITLE
[用户管理]新创建用户时，当相同账号存在时，提示信息不够准确

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1646]
1.新创建用户时，当相同账号存在时，提示信息不够准确
正确：“该用户名已被添加”

![1509691893 1](https://user-images.githubusercontent.com/28615156/32362785-dc4fbc76-c0a6-11e7-85fc-4157d1546f73.jpg)

**Comment by runner-mei** [comment]
这个不管
