### ISSUE TITLE
[用户管理]添加用户时，登入IP添加错误的格式能够创建用户成功、没有提示信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1647]
1.添加用户时，登入IP添加错误的格式能够创建用户成功、没有提示信息

正确：“请输入合法的IP地址段，每行输入一个地址或地址段”

**Comment by runner-mei** [comment]
FIX

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171107_2920_x64.exe 版本确认，close处理。
