### ISSUE TITLE
[用户管理]首页上点击“admin”，进入当前用户页面、点击确定按钮、提示“ java.lang.UnsupportedOperationException: 新版本用户不可删除”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1650]
[用户管理]首页上点击“admin”，进入当前用户页面、点击确定按钮、提示“ java.lang.UnsupportedOperationException: 新版本用户不可删除”

![1509694899 1](https://user-images.githubusercontent.com/28615156/32364232-a7e603a2-c0ae-11e7-8c78-d27418c1320c.jpg)

**Comment by runner-mei** [comment]
如果当前用户管理是 v2 用跳到   /hengwei/um/users/:id

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171107_2920_x64.exe 版本确认，close处理。
