### ISSUE TITLE
[用户组管理]用户组管理中能添加同名的用户组

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1652]
1.用户组管理中能添加同名的用户组

![1509699290 1](https://user-images.githubusercontent.com/28615156/32366420-f14cf1b8-c0b8-11e7-89b9-44afbfd7933c.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171107_2920_x64.exe 版本确认，还是出现此现象

![1510028458 1](https://user-images.githubusercontent.com/28615156/32477011-2e0f76c0-c3b6-11e7-81a9-5d67a32e3a67.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171123_2910_x64.exe   版本确认，close处理。
