### ISSUE TITLE
[交通医学院] 标准化应用 HTTP监控延迟数据修整

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1653]
标准化应用 HTTP监控延迟数值过大,与横轴纵轴的数据不匹配,小数点后保留2位.
版本:2.3

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171108_466_x64.exe   版本确认，close处理。
