### ISSUE TITLE
[通知管理]新建通知规则时，通知用户只能获取admin用户

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1655]
1.新建通知规则时，通知用户只能获取admin用户
2.http短信/短信同样发生此现象

![1509937177 1](https://user-images.githubusercontent.com/28615156/32423491-a1c51eb0-c2e1-11e7-9353-3d03a85b5258.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171107_2920_x64.exe 版本确认，close处理。
