### ISSUE TITLE
[通知管理]通知规则组页面、选择通知规则、点击删除按钮、提示删除错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1656]
1.通知规则组页面、选择通知规则、点击删除按钮、提示删除错误

![1509938566 1](https://user-images.githubusercontent.com/28615156/32424059-12c05456-c2e5-11e7-9e12-d8ffdab176a1.jpg)

![1509938580 1](https://user-images.githubusercontent.com/28615156/32424060-12fa9c60-c2e5-11e7-99a1-06b8c1d9bd3d.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171106_2916_x64.exe 版本确认，close处理。
