### ISSUE TITLE
[通知管理]添加微信通知方式、获取不到微信通知人或者部门等

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1657]
1.添加微信通知方式、获取不到微信通知人或者部门等

![1509939199 1](https://user-images.githubusercontent.com/28615156/32424319-921882f4-c2e6-11e7-920d-24367d0bb555.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171106_2916_x64.exe  确认还出现此现象

![1510018917 1](https://user-images.githubusercontent.com/28615156/32472952-0e790350-c3a0-11e7-8c9e-598afb7ffc8f.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171107_2927_x64.exe  版本确认，close处理。
