### ISSUE TITLE
[交大医学院]删除监控主机时不要将关联的数据库中间件等删除

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1659]
情况:删除监控主机时所关联的数据库中间件等删除了
要求:删除监控主机时不要将相关对象删除(数据库/中间件/标准化等)
版本:2.3/3.2

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171108_466_x64.exe   版本确认，还是出现此现象

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171115_485_x64.exe  版本确认，close处理。
