### ISSUE TITLE
[安徽电调] SSH 设备统计 项目需求

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1660]
1.根据唐登辉所提需求,网管主要使用功能依然还是多设备SSH/Telnet 功能;
    目前我们所使用对网络设备SSH的功能比较简单,客户所期望还是功能专业强大好用些.
例如: 命令信息可以复制粘贴使用；字体大小可以调整；配置命令可以抓取保存；配置会话可记录；
2.网络设备统计功能；（每年、或者每半年检查时候，经常要统计网络设备的信息数量）比如：统计设备总数，厂商设备数量占用比，每个厂商设备型号统计等；

版本:2.3/3.2
安装包:32位 64位

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
