### ISSUE TITLE
[机房视图]机柜视图页面中进行设备属性中机架U数修改、修改后机柜视图页面的机架刷不变

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1661]
1.机柜视图页面中进行设备属性中机架U数修改、修改后机柜视图页面的机架刷不变

![1509949654 1](https://user-images.githubusercontent.com/28615156/32428079-f56dda8a-c2fe-11e7-9bf2-df0175f32b9c.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171107_2927_x64.exe 版本确认，close处理。
