### ISSUE TITLE
[后台任务]添加IP不可达的设备后、后台任务提示消息不提示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1662]
1.添加IP不可达的设备后、后台任务提示消息不提示

![1509950582 1](https://user-images.githubusercontent.com/28615156/32428511-fb666cfc-c300-11e7-85e9-0b0a31e1a4d8.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171107_2927_x64.exe  版本确认，close处理。
