### ISSUE TITLE
[巡检任务管理]巡检任务管理页面、无法选择巡检任务进行删除操作

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1663]
1.巡检任务管理页面、无法选择巡检任务进行删除操作

![1509953436 1](https://user-images.githubusercontent.com/28615156/32430125-d58acaf2-c308-11e7-8d76-2babd6b1a8e9.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171108_466_x64.exe   版本确认，close处理。
