### ISSUE TITLE
你看一下 revel 框加出来的，和 play 出来的不一样

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#1664]
你看一下 revel 框加出来的，和 play 出来的不一样
![default](https://user-images.githubusercontent.com/1052632/32430479-6c48e310-c30a-11e7-8f1f-220a9a77d544.png)

![default](https://user-images.githubusercontent.com/1052632/32430495-7a69b852-c30a-11e7-8ac1-f6bf04a3e30c.png)

**Comment by eeiceyes** [comment]
fixed
