### ISSUE TITLE
[Tag列表]Tag列表页面、添加Tag时、添加失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1665]
1.Tag列表页面、添加Tag时、添加失败

![1509956860 1](https://user-images.githubusercontent.com/28615156/32431737-8ea3ac60-c30f-11e7-804a-aa0c457824ff.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171107_2920_x64.exe 版本确认  还是出现此现象

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171107_2927_x64.exe 版本确认，close处理。

**Comment by hengwei-test** [comment]
2.3版本 也修复一下

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171124_521_x64.exe  版本确认，close处理。
