### ISSUE TITLE
[常用工具]菜单中点击“Ping测试”按钮无效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1667]
1.菜单中点击“Ping测试”按钮无效
2.snmp连接测试/Trace Route/Dig 同样出现此现象

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20171109_2937_x64.exe  版本确认、还是出现此现象

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171123_2910_x64.exe   版本确认，在用户管理、用户组管理、角色管理、权限管理、通知管理、计划任务、系统空间管理、备份数据页面、点击“Ping测试”按钮无效
