### ISSUE TITLE
[报表规则管理]多个报表规则同时触发时、出现报表的PDF文件生成失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1671]
1.多个报表规则同时触发时、出现报表的PDF文件生成失败

create job handler failed, open C:\Program Files\hengwei\data\reports\18\report_18_1510106951489.pdf: The system cannot find the file specified.

[job_巡检任务统计_1510106751406_1510106751407.txt](https://github.com/three-plus-three/hw_issues/files/1452397/job_._1510106751406_1510106751407.txt)

**Comment by eeiceyes** [comment]
fixed
