### ISSUE TITLE
[上海中医药大学]标准应用（http）运维信息板块修改

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1672]
1.将http标准应用中的“运维信息”模块改为如下所示

![1](https://user-images.githubusercontent.com/28615156/32528914-7c2a9bc2-c470-11e7-9aab-ef5aee97f442.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171115_485_x64.exe  版本确认，close处理。
