### ISSUE TITLE
[通知管理]服务器设置中企业微信未设置时、通知管理中点击“添加通知规则-企业微信通知”时、提示添加失败信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1675]
1.服务器设置中企业微信未设置时、通知管理中点击“添加通知规则-企业微信通知”时、提示添加失败信息

![1510115041](https://user-images.githubusercontent.com/28615156/32531935-cf84d09c-c481-11e7-8c89-8d046d9ff6a0.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171123_2910_x64.exe   版本确认，close处理。
