### ISSUE TITLE
[通知管理]添加微信通知规则页面、点击“测试”提示错误信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1676]
1.添加微信通知规则页面、点击“测试”提示错误信息

![1510116453 1](https://user-images.githubusercontent.com/28615156/32532146-375e3ed2-c483-11e7-944a-55fc0ec15e32.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171123_2910_x64.exe   版本确认，close处理。
