### ISSUE TITLE
[登入]相同IP相同浏览器登入后、关闭浏览退出、再次登入平台提示需要强制登入

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1677]
1.相同IP相同浏览器登入后、关闭浏览退出、再次登入平台提示需要强制登入

![1510193499 1](https://user-images.githubusercontent.com/28615156/32585106-c0f79450-c536-11e7-9ca2-85a335a337b1.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171123_2910_x64.exe   版本确认，close处理。
