### ISSUE TITLE
[IT资产管理]左侧菜单栏中IT资产管理的图标和数据管理的图标重复

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1679]
1.左侧菜单栏中IT资产管理的图标和数据管理的图标重复

![1510194267 1](https://user-images.githubusercontent.com/28615156/32585399-3ca1da60-c538-11e7-9961-c79ab1c75342.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171123_2910_x64.exe   版本确认，还出现此现象

![1511460159 1](https://user-images.githubusercontent.com/28615156/33192607-b954d9a0-d0fe-11e7-9c0d-bc82984b5009.jpg)

**Comment by runner-mei** [comment]
fix
