### ISSUE TITLE
Linux使用SSH获取不到数据

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#168]
在Linux上使用SSH获取数据失败（测试失败）
![image](https://cloud.githubusercontent.com/assets/14171497/13384563/b20d1638-ded1-11e5-8125-e8f519eb5085.png)

![image](https://cloud.githubusercontent.com/assets/14171497/13384607/18ab8e60-ded2-11e5-8ef9-a64ea58a7169.png)

**Comment by runner-mei** [comment]
问题是否已解决
