### ISSUE TITLE
[告警规则]告警规则页面管理对象搜索框与查询按钮重叠

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1680]
1.告警规则页面管理对象搜索框与查询按钮重叠

![1510194849 1](https://user-images.githubusercontent.com/28615156/32585830-5adcd456-c53a-11e7-8e53-822ec3ef843e.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171123_2910_x64.exe   版本确认，close处理。
