### ISSUE TITLE
[演示环境]告警信息拓扑定位后导致根图展示不全

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#1681]
1、
![image](https://user-images.githubusercontent.com/14171518/32589852-f750c6e6-c551-11e7-92fb-93d48c5aab5d.png)

2、
![image](https://user-images.githubusercontent.com/14171518/32589870-062fa7d6-c552-11e7-81d4-e77a1f5a6642.png)

根图展示不全，也没有滚动条可以拖动

**Comment by hengweiGR** [comment]
major

**Comment by eeiceyes** [comment]
fixed
