### ISSUE TITLE
[报表规则管理]设备端口使用情况报表新建页面、每月、每周、每日、每时的按钮点击无效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1685]
1.设备端口使用情况报表新建页面、每月、每周、每日、每时的按钮点击无效
2.设备运行情况报表新建页面同样出现此现象

![1510279863 1](https://user-images.githubusercontent.com/28615156/32639583-8b10b78a-c5ff-11e7-9903-0fbb4893a224.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171121_506_x64.exe  版本确认，close处理。
