### ISSUE TITLE
[TFTP脚本管理]TFTP管理页面、按照IP地址、按照设备名称查询、提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1686]
TFTP管理页面、按照IP地址、按照设备名称查询、提示错误

![1510283371 1](https://user-images.githubusercontent.com/28615156/32641248-d58d11a2-c607-11e7-877a-d60f794799dc.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171113_476_x64.exe  版本确认，close处理。
