### ISSUE TITLE
[日志文件告警]添加SSH方式的日志文件告警、路径添加cat 2222.txt保存后、在编辑页面路径还原为“/cat”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1687]
1.添加SSH方式的日志文件告警、路径添加cat 2222.txt保存后、在编辑页面路径还原为“/cat”

![1510295243 1](https://user-images.githubusercontent.com/28615156/32645704-99bf3062-c623-11e7-8509-c652aee64ce5.jpg)

![1510295347 1](https://user-images.githubusercontent.com/28615156/32645705-99fac3d4-c623-11e7-8832-78e703e4f6b6.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171115_485_x64.exe  版本确认，还出现此现象

![1510723818 1](https://user-images.githubusercontent.com/28615156/32820414-34a4ee80-ca09-11e7-931a-4438868b41c8.jpg)

**Comment by eeiceyes** [comment]
这下应该真fix了

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171121_506_x64.exe  版本确认，会默认在开头添加一个“/”

![1511313955 1](https://user-images.githubusercontent.com/28615156/33105283-5cd3b5b8-cf67-11e7-8aa6-2f3e135e56b5.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171122_510_x64.exe版本确认，close处理。
