### ISSUE TITLE
[监控管理]设备负载监控的窗口、不显示管理对象

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1688]
1.设备负载监控的窗口、不显示管理对象
2.CPU利用率/内存利用率都出现

![1510299651 1](https://user-images.githubusercontent.com/28615156/32647795-09acfbc0-c62e-11e7-9654-a70cd8d706cc.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171113_476_x64.exe  版本确认，close处理。

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171113_476_x64.exe版本确认，还出现此现象。

![1510562421 1](https://user-images.githubusercontent.com/28615156/32716563-73ced888-c891-11e7-8a86-aa1d68b79c09.jpg)

**Comment by eeiceyes** [comment]
最新的版本再确认下

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171115_485_x64.exe  版本确认，close处理。
