### ISSUE TITLE
[生成拓扑图]生成拓扑时提示“拓扑图搜索失败” 

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1689]
1.生成拓扑时提示“拓扑图搜索失败” 
2.全新环境安装、首次登入平台、到拓扑搜索页面直接点拓扑生成按钮
3.一共进行了3次拓扑搜索、2次失败、成功搜索后再次搜索成功

[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/1465464/server_biz.txt)

[web_server.txt](https://github.com/three-plus-three/hw_issues/files/1465465/web_server.txt)

**Comment by eeiceyes** [comment]
把等待时间调长了
