### ISSUE TITLE
设备获取不到CPU数据

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#169]
CPU数据获取不到
![image](https://cloud.githubusercontent.com/assets/14171497/13384838/acaaeb90-ded4-11e5-8980-f31ea3a284dd.png)
SYS数据获取不到
![image](https://cloud.githubusercontent.com/assets/14171497/13384864/1033b3fe-ded5-11e5-90f9-2f496f4d08f2.png)
运行视图
![image](https://cloud.githubusercontent.com/assets/14171497/13384886/4384b4ec-ded5-11e5-98f0-40e52fc516e9.png)

**Comment by runner-mei** [comment]
fix by #173
