### ISSUE TITLE
[网络视图]拓扑图同步后、网络视图上设备位置为发生同步变化

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1690]
1.拓扑图同步后、网络视图上设备位置为发生同步变化

[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/1465696/server_biz.txt)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171115_485_x64.exe  版本确认，close处理。
