### ISSUE TITLE
[历史记录查看]设备右击选择实时监控-多CPU利用率、多CPU利用率窗口显示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1691]
1.设备右击选择实时监控-多CPU利用率、多CPU利用率窗口显示错误
2.多内存利用率/端口流量窗口 同样出现此现象

![1510562775 1](https://user-images.githubusercontent.com/28615156/32716872-9497f896-c892-11e7-8c73-4aafcb422a1a.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171115_485_x64.exe  版本确认，close处理。
