### ISSUE TITLE
[报表规则管理]报表规则触发、邮件发送失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1692]
1.报表规则触发、邮件发送失败
2.只要端口流量分析报表出现

create job handler failed, 'to_address' is invalid - mail: expected single address, got "\r\nzhz9561847862@163.com"

![1510653129 1](https://user-images.githubusercontent.com/28615156/32773581-944cec02-c964-11e7-9663-76e43b4d80d7.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171115_485_x64.exe  版本确认，close处理。
