### ISSUE TITLE
设备端口告警设不了

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#1694]
在添加设备端口告警页面中的 
![default](https://user-images.githubusercontent.com/1052632/32888704-232affd2-cb03-11e7-83ef-d8293f2ade0e.png)

**Comment by eeiceyes** [comment]
改了几个地方：
1，告警规则添加界面选择端口
2，历史记录规则添加界面选择端口
3，告警规则列表界面按端口查询
4，历史记录规则列表界面按端口查询
5，告警日志列表界面按端口查询

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171121_506_x64.exe  版本确认，close处理。
