### ISSUE TITLE
[标准应用服务]http使用https协议测试、测试失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1695]
1.http使用https协议测试、测试失败

![1510885419 1](https://user-images.githubusercontent.com/28615156/32926294-779c9070-cb81-11e7-8e96-51782d47c58d.jpg)

**Comment by runner-mei** [comment]
请将端口改成 443

**Comment by eeiceyes** [comment]
切换成https时，如果端口是80，会自动改成443

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171122_509_x64.exe版本确认，close处理。
