### ISSUE TITLE
[设备管理]添加设备时、同时添加多台设备时、提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1698]
1.网络视图中右击选择添加设备
2.同时添加192.168.1.2/192.168.1.6/192.168.1.141
3.snmp读参数：public、点击确认按钮提示错误

![8og 26sis5h3tf d84 f 6](https://user-images.githubusercontent.com/28615156/33111471-403bddbe-cf89-11e7-885d-dadde483278d.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171122_511_x64.exe版本确认，close处理。
