### ISSUE TITLE
[历史记录规则]添加服务器的tcp连接数的历史记录规则时、提示未选择指标参数

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1699]
1.添加服务器的tcp连接数的历史记录规则时、提示未选择指标参数

![1511329229 1](https://user-images.githubusercontent.com/28615156/33111855-202f612e-cf8b-11e7-8397-6505e002ff68.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171122_511_x64.exe版本确认，close处理。
