### ISSUE TITLE
[日志文件告警]发送snm trap日志文件、没达到触发条件情况触发了snmp trap的告警规则

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1701]
1.发送snm trap日志文件、没达到触发条件情况触发了snmp trap的告警规则

![z 2q65s up4 v s 4jyt](https://user-images.githubusercontent.com/28615156/33116259-1af8bb6a-cf9f-11e7-96a8-0c750026f90d.png)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171122_512_x64.exe版本确认，close处理。
