### ISSUE TITLE
[监控管理]实时监控的平均CPU利用率窗口的中值获取不到

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1702]
1.实时监控的平均CPU利用率窗口的中值获取不到
2.实时监控的平均内存利用率同样出现此现象

![1511402841 1](https://user-images.githubusercontent.com/28615156/33156643-b120c6ae-d036-11e7-8b57-c5ef05568257.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171123_516_x64.exe版本确认，close处理。
