### ISSUE TITLE
[监控管理]选择设备右击点击选择“实时监控-多内存利用率”、提示“加载失败:Not Found！”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1703]
1.选择设备右击点击选择“实时监控-多内存利用率”、提示“加载失败:Not Found！”

![1511457522 1](https://user-images.githubusercontent.com/28615156/33191874-a58f0162-d0f8-11e7-9895-5b65aec6f515.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171129_535_x64.exe 版本确认，close处理。
