### ISSUE TITLE
[告警规则]添加Remote ping告警窗口、选择通知方式时、提示404错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1704]
1.SHH访问参数的设备网络视图上右击选择“添加告警-Remote Ping告警”、添加Remote ping告警窗口、选择通知方式时、提示404错误
2.BUG发生后、删除所有Remote ping 告警后、再次设置Remote ping未发生此现象

![1511498265 1](https://user-images.githubusercontent.com/28615156/33195666-8e2fc4d6-d114-11e7-8720-835e0674d743.jpg)

[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/1500628/server_biz.txt)

[web_server.txt](https://github.com/three-plus-three/hw_issues/files/1500629/web_server.txt)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
