### ISSUE TITLE
[机房视图]添新的机柜、在机柜中添加已经告警的设备时、添加机柜完成后机柜不闪烁显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1705]
1.添新的机柜、在机柜中添加已经告警的设备时、添加机柜完成后机柜不闪烁显示
2.当机柜里的设备发生告警后、机柜闪烁表示→OK

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171129_535_x64.exe 版本确认，close处理。
