### ISSUE TITLE
[日志文件告警]设置syslog日志文件告警、发送syslog后、告警规则未触发的情况、告警规则中的通知方式触发

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1707]
1.设置syslog日志文件告警、发送syslog后、告警规则未触发的情况、告警规则中的通知方式触发

![1511503510 1](https://user-images.githubusercontent.com/28615156/33197539-041113ce-d121-11e7-98b8-0ff653bddd7a.jpg)
![1511503532 1](https://user-images.githubusercontent.com/28615156/33197540-044ad74e-d121-11e7-9dfd-c664baeb2926.jpg)
![1511503712 1](https://user-images.githubusercontent.com/28615156/33197541-04849736-d121-11e7-8169-4320f07e32e7.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171129_535_x64.exe 版本确认，close处理。
