### ISSUE TITLE
sqlserver 的数据文件百分比不正确

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#1709]
因为文件都是自动增长的，无上限的所以百分比不正确， 我修改元模型了，你看看
![tim 20171128183947](https://user-images.githubusercontent.com/1052632/33315654-4095ce22-d46c-11e7-83b4-c48181ce4469.png)

sqlserver_file_stat 指标中 
log_file_used_percent 和 rows_file_max_used_percent 
改成了
rows_file_max_used_percent 和 log_file_max_used_percent

意义变成了 数据文件已使用百分比 和 日志文件中最大已使用百分比

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171129_535_x64.exe 版本确认，close处理。
