### ISSUE TITLE
[数据库运行视图]sqlserver 数据库运行视图中、sql内存的值不准

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1710]
1.sqlserver 数据库运行视图中、sql内存的值不准

![nr1o61 381b_pi kdo md8y](https://user-images.githubusercontent.com/28615156/33408545-01248c0a-d5b2-11e7-9f38-af050f53c59a.png)

**Comment by runner-mei** [comment]
不知这个是什么版本， 请明确一点

**Comment by hengwei-test** [comment]
sqlserver 2008版本
