### ISSUE TITLE
[记录数据查询]查询线路的上下带宽占用比、查询出来的数据“区间最小值”的值出现负数

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1718]
1.查询线路的上下带宽占用比、查询出来的数据“区间最小值”的值出现负数

![_20171206092224](https://user-images.githubusercontent.com/28615156/33640491-f2518eda-da6b-11e7-9031-35ba2a83c85f.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3249_x64.exe  版本确认，close处理。
