### ISSUE TITLE
[组合端口管理]添加组合端口是，端口的数量过多、提示“{"errorCode": 100001, "errorMessage": "Unknown Exception"}”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1720]
1.添加组合端口是，端口的数量过多、提示“{"errorCode": 100001, "errorMessage": "Unknown Exception"}”

![1512526490 1](https://user-images.githubusercontent.com/28615156/33641532-e0b63df6-da70-11e7-84bd-85ec1c382381.jpg)

![1512534767 1](https://user-images.githubusercontent.com/28615156/33644752-bc98c57c-da81-11e7-8733-ee583ee22679.jpg)

**Comment by eeiceyes** [comment]
端口数太多了，保存时字段长度不够了

**Comment by eeiceyes** [comment]
实际现场顶多10几个端口了，这个问题不需要改
