### ISSUE TITLE
[用户管理]新建角色创建的用户、新用户登入后提示没有操作权限

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1722]
1.新建角色创建的用户、新用户登入后提示没有操作权限

![1512629073 1](https://user-images.githubusercontent.com/28615156/33702345-057662a4-db5e-11e7-8489-eabcd8de6372.jpg)

![1512629102 1](https://user-images.githubusercontent.com/28615156/33702346-05b476ac-db5e-11e7-909d-7a5e67666ffb.jpg)

![1512629119 1](https://user-images.githubusercontent.com/28615156/33702347-05f2a490-db5e-11e7-8bc6-0fde78ba2290.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180123_3203_x64.exe  版本确认，close处理。
