### ISSUE TITLE
[服务总览]oracle数据的会话信息中、用户名出现空白

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1725]
1.oracle数据的会话信息中、用户名出现空白

![1512812502 1](https://user-images.githubusercontent.com/28615156/33794507-68af13b0-dd08-11e7-9b25-70adfb708b13.jpg)

**Comment by eeiceyes** [comment]
读取来就是空，不改了

**Comment by eeiceyes** [comment]
关闭吧
