### ISSUE TITLE
[网络视图]拓扑图上选中设备后、右击列表中选择“常用工具-Telent”、页面跳转错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1733]
1.拓扑图上选中设备后、右击列表中选择“常用工具-Telent”、页面跳转错误
2.选择SSH 同样出现此问题

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171225_619_x64.exe  版本确认，close处理。

**Comment by hengwei-test** [comment]
3.3.1 同样出现此现象

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
