### ISSUE TITLE
需求: 用户设置页面对itsm中请求通知的支持

### ISSUE THREAD

**Issue by hengwei-ly** [three-plus-three/hw_issues#1734]
需要两个字段:

label:   是否自动关注请求   
key:     is_auto_attention_request_in_itsm
type :  bool

label:   是否可用邮件接收通知信息   
key:     is_notified_by_email_in_itsm  
type :  bool

label 不做要求

**Comment by runner-mei** [comment]
已完成， 可以发送 POST 请求到 /hengwei/um//users/:id 页面上

**Comment by runner-mei** [comment]
fix

**Comment by runner-mei** [comment]
在 deploy\lib\user_fields 目录下新增一个 .json 结尾的文件，内容如下

````json
{
"title": "服务管理",
"prefix": "itsm",
"fields": [
  {"id": "id_1", "name": "标题1", "type": "string"},
  {"id": "id_2", "name": "标题2", "type": "string"},
]}
````
这样子会生成两个字段  itsm.id_1 和 itsm.id_2
