### ISSUE TITLE
[机房视图]机柜视图页面、选中机柜、键盘“→”按下、机柜向右移动

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1735]
1.机柜视图页面、选中机柜、键盘“→”按下、机柜向右移动
2.选中设备同样出现此现象

![default](https://user-images.githubusercontent.com/28615156/34285561-87f0fc90-e715-11e7-898b-1acbc8b5d088.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171227_634_x64.exe  版本确认，close处理。
