### ISSUE TITLE
[用户管理]添加用户时、选择新添加的角色信息时、首页栏中显示的信息不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1738]
1.添加用户时、选择新添加的角色信息时、首页栏中显示的信息不全

![1514167733](https://user-images.githubusercontent.com/28615156/34330942-309d688a-e95d-11e7-924e-1268caf8ab44.jpg)

![1514167902 1](https://user-images.githubusercontent.com/28615156/34330943-30e01662-e95d-11e7-871e-4fb123e301d7.jpg)

![1514167949 1](https://user-images.githubusercontent.com/28615156/34330944-311fef80-e95d-11e7-9c3c-4c9deabb3ba8.jpg)

**Comment by runner-mei** [comment]
少了什么？
