### ISSUE TITLE
[集中展示] 集中监控添加一项首菜单.可直接切入.集中展示界面

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1739]
1.集中监控添加一项首菜单.可直接切入.集中展示界面
**
![image](https://user-images.githubusercontent.com/14171497/34334120-a1677116-e97e-11e7-98f3-6fe5b7bec9b3.png)
**

**Comment by eeiceyes** [comment]
页面路径是
hengwei/biz_management/biz_overview(2.3)
或者
hengwei/web/biz_management/biz_overview(3.3)

**Comment by eeiceyes** [comment]
现场通过配置加个菜单就是
