### ISSUE TITLE
[业务视图]业务视图展示界面业务图标改成绿色(目前颜色太浅),改成国网绿

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1740]
1.业务视图展示界面业务图标改成绿色(目前颜色太浅),改成国网绿
![image](https://user-images.githubusercontent.com/14171497/34333834-b405f3e0-e97b-11e7-941e-1885114f28b4.png)

**Comment by eeiceyes** [comment]
fixed，现场的话直接改下图片吧

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
