### ISSUE TITLE
[自定义首页]编辑自定义首页时、URL做成下拉选的形式、添加一个进入首页的按钮

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1741]
1.编辑自定义首页时、URL做成下拉选的形式、（新用户查不到具体哪个页面的URL）
2.编辑自定义首页时、添加一个进入首页的按钮（不想设置自定义首页时、没有办法进入巡检平台）

**Comment by runner-mei** [comment]
做成下拉选择框暂时是不行的，我在这个里面 加上了缺省 URL

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，未添加缺省URL

![default](https://user-images.githubusercontent.com/28615156/34660010-eb20db8e-f479-11e7-9f09-ae790388b140.png)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180116_3158_x64.exe  版本确认，close处理。
