### ISSUE TITLE
[登入]新创建的账号登入平台后、首页显示“您没有访问根图的权限”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1742]
1.新创建的账号登入平台后、首页显示“您没有访问根图的权限”

![1514171726 1](https://user-images.githubusercontent.com/28615156/34331820-41ee458e-e965-11e7-9528-ed93cfae1e4d.jpg)

![1514171761 1](https://user-images.githubusercontent.com/28615156/34331821-42192f24-e965-11e7-9641-81e5cadd12c5.jpg)

![1514171775 1](https://user-images.githubusercontent.com/28615156/34331822-4243aae2-e965-11e7-93a3-d755651558dd.jpg)

![1514171786 1](https://user-images.githubusercontent.com/28615156/34331823-426d6e68-e965-11e7-9ca4-ba07cfba70c3.jpg)

**Comment by runner-mei** [comment]
fix?

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3208_x64.exe 版本确认，close处理。
