### ISSUE TITLE
[安装]运维平台安装后、Java进程一直在重启

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1743]
1.运维平台安装后、Java进程一直在重启

[jbridge.txt](https://github.com/three-plus-three/hw_issues/files/1585272/jbridge.txt)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
