### ISSUE TITLE
[用户组管理]用户组中的用户删除后、用户组中的用户不删除

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1744]
1.用户组中的用户删除后、用户组中的用户不删除

![1514177428 1](https://user-images.githubusercontent.com/28615156/34333011-877c8c2a-e972-11e7-8438-8c94f3b88191.jpg)

![1514177460 1](https://user-images.githubusercontent.com/28615156/34333012-87b0e1be-e972-11e7-84c1-8322650b4db0.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
