### ISSUE TITLE
[用户管理]从Ladp中同步用户时、ladp用户名密码输入错误、提示信息的描述不清楚

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1745]
1.从Ladp中同步用户时、ladp用户名密码输入错误、提示信息的描述不清楚

![1514178513 1](https://user-images.githubusercontent.com/28615156/34333714-9cf80784-e97a-11e7-9af1-cad8b5c0c1a4.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
