### ISSUE TITLE
[用户管理]Ldap同步用户成功后、再次同步LDAP时跳转页面错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1746]
1.Ldap同步用户成功后、再次同步LDAP时跳转页面错误

![1514181850 1](https://user-images.githubusercontent.com/28615156/34333967-c23cff52-e97c-11e7-8b14-79b9312e4e43.jpg)

![1514181885 1](https://user-images.githubusercontent.com/28615156/34333968-c2848098-e97c-11e7-9e9f-955bb11c66ee.jpg)

[um.txt](https://github.com/three-plus-three/hw_issues/files/1585405/um.txt)

**Comment by runner-mei** [comment]
我重现不出来

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180112_3150_x64.exe 版本确认，close处理。
