### ISSUE TITLE
[服务管理]右边菜单栏中点击“服务管理”、跳转页面错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1747]
1.右边菜单栏中点击“服务管理”、跳转页面错误

![default](https://user-images.githubusercontent.com/28615156/34335885-670defe0-e98d-11e7-9fee-2f556afd7846.png)

[itsm.txt](https://github.com/three-plus-three/hw_issues/files/1585559/itsm.txt)

**Comment by runner-mei** [comment]
请确保 itsm 是否正常启动了

**Comment by hengwei-test** [comment]
![1515386060 1](https://user-images.githubusercontent.com/28615156/34659160-9dc834c6-f470-11e7-8b42-bc4ae3545f67.jpg)


itsm正常启动、把url中的127.0.0.1修改成网管机地址访问正常。

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180112_3150_x64.exe 版本确认，close处理。
