### ISSUE TITLE
[当前用户]LDAP当前用户登入，首页点击当前用户、当前用户页面有密码文本框

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1748]
1.LDAP当前用户登入，首页点击当前用户、当前用户页面有密码文本框

![1514193199 1](https://user-images.githubusercontent.com/28615156/34337069-6a9a8cea-e997-11e7-8361-ec52c9033271.jpg)

**Comment by runner-mei** [comment]
我没有试出来, 我进入的页面和你不一样

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，在用户管理/用户组管理/角色管理/权限管理/通知管理/系统空间管理/备份数据/计划任务等页面点击当前用户、添加页面为当前页面用户页面

![default](https://user-images.githubusercontent.com/28615156/34660095-b85040a4-f47a-11e7-8637-407d6836b7e5.png)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180112_3150_x64.exe 版本确认，close处理。
