### ISSUE TITLE
[安徽电调] 创建子图时已经创建缩略图(里面的设备)的设备不能选择

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1749]
安徽电调 需要创建一个子图 作为各个地区的核心设备的汇聚图方便查看,但是已经创建缩略图里的设备不能选择,只能选择缩略图.
请及时修复

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，无法实现选择对个缩略图中的某些设备或者单个设备
