### ISSUE TITLE
[网络视图]选中设备右击选择“实时监控-平均内存利用率”，窗口中的名称显示指标名英文名

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1761]
1.选中设备右击选择“实时监控-平均内存利用率”，窗口中的名称显示指标名英文名

![1514449072 1](https://user-images.githubusercontent.com/28615156/34405286-76d49a34-ebed-11e7-9a47-a84e22feda09.jpg)

![1514448989 1](https://user-images.githubusercontent.com/28615156/34405287-77083dc6-ebed-11e7-8136-4701b6fef31a.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
