### ISSUE TITLE
[设备管理]添加设备时、测试Telnet访问参数时测试失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1762]
1.添加设备时、测试Telnet访问参数时测试失败

![default](https://user-images.githubusercontent.com/28615156/34405774-267750ce-ebf0-11e7-849b-2c40476c771c.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
