### ISSUE TITLE
[历史记录规则]添加历史记录规则的指标参数全部是英文

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1763]
1.添加历史记录规则的指标参数全部是英文
2.告警规则同样出现此现象
3.网络视图/机柜视图中、 选中设备信息同样出现此现象
4.显示设置中同样出现此现象

![default](https://user-images.githubusercontent.com/28615156/34405922-fadec9be-ebf0-11e7-8b1f-378dc322269a.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
