### ISSUE TITLE
[网络视图]网络视图上基于节点创建子图、提示创建子图失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1764]
1.网络视图上基于节点创建子图、提示创建子图失败

![default](https://user-images.githubusercontent.com/28615156/34406383-afe5662c-ebf3-11e7-8028-9240c6db49e8.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180107_3125_x64.exe  版本确认，close处理。
