### ISSUE TITLE
[华东电网] 巡检报表统计中 图表字样修改

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1775]
![image](https://user-images.githubusercontent.com/14171497/34594440-0422e872-f20c-11e7-933a-a5b2f55514d5.png)

图表字样修改:将"无异常"修改"正常"; "无未处理异常"修改"已处理异常";"有未处理异常"修改"未处理异常"; "

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20180112_682_x64.exe    版本确认，close处理。
