### ISSUE TITLE
[数据库管理]数据库管理页面、点击DB2和sybase数据的业务视图、提示“empty String”错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1778]
1.数据库管理页面、点击DB2和sybase数据的业务视图、提示“empty String”错误

![1515387837 1](https://user-images.githubusercontent.com/28615156/34659630-d7c0e560-f475-11e7-881e-b6021b0376d4.jpg)

![1515387849 1](https://user-images.githubusercontent.com/28615156/34659631-d7feda46-f475-11e7-9f23-5ef44a7d2c0a.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180112_3150_x64.exe 版本确认，close处理。
