### ISSUE TITLE
[运行视图]运行视图中操作系统信息格式显示错行

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1782]
运行视图中操作系统信息格式显示错行

![default](https://user-images.githubusercontent.com/28615156/34874833-9c5564ac-f7d5-11e7-8ae5-56bdf773c999.PNG)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180122_3196_x64.exe    版本确认，close处理。
