### ISSUE TITLE
[服务总览]服务总览页面没有收起所有设备信息按钮、设备名称太长显示信息错行

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1783]
服务总览页面没有收起所有设备信息按钮、设备名称太长显示信息错行

![default](https://user-images.githubusercontent.com/28615156/34875386-f72182e2-f7d7-11e7-9c95-9246f9b31000.PNG)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180118_3172_x64.exe 版本确认，对比2.3还是缺少详细分类按钮

![1516253487 1](https://user-images.githubusercontent.com/28615156/35082326-14d2a548-fc54-11e7-88d6-a158067572e2.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180124_3204_x64.exe  版本确认，close处理。
