### ISSUE TITLE
[运行视图]交换机运行视图硬件信息中、电源的名称重复

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1784]
交换机运行视图硬件信息中、电源的名称重复
![default](https://user-images.githubusercontent.com/28615156/34875238-67f7a0ec-f7d7-11e7-93e6-cffe7cb80962.PNG)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180122_3196_x64.exe    版本确认，close处理。
