### ISSUE TITLE
[角色管理]添加角色信息时提示“创建GroupAndRole: pq: 插入或更新表 "hengwei_permission_groups_and_roles" 违反外键约束 "hengwei_permission_groups_and_roles_group_id_fkey"”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1787]
1.添加角色信息时提示“创建GroupAndRole: pq: 插入或更新表 "hengwei_permission_groups_and_roles" 违反外键约束 "hengwei_permission_groups_and_roles_group_id_fkey"”

![1515983479 1](https://user-images.githubusercontent.com/28615156/34924617-6bfc6272-f9df-11e7-940c-a387f355e6d7.jpg)

![1515983499 1](https://user-images.githubusercontent.com/28615156/34924618-6c882866-f9df-11e7-88ee-13a559a2f607.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180116_3158_x64.exe  版本确认，close处理。
