### ISSUE TITLE
[通知管理]通知管理页面、全选通知方式无效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1788]
通知管理页面、全选通知方式无效

![default](https://user-images.githubusercontent.com/28615156/34927963-23cd626a-f9f5-11e7-907b-837313433d46.png)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180116_3158_x64.exe  版本确认，close处理。
