### ISSUE TITLE
[通知方式]选择通知方式、点击上方的删除按钮不起效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1790]
1.选择通知方式、点击上方的删除按钮不起效

![1515997295 1](https://user-images.githubusercontent.com/28615156/34929549-739f4768-f9ff-11e7-9074-215d9673c922.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180116_3158_x64.exe  版本确认，close处理。
