### ISSUE TITLE
[网络视图]添加设备时、IP地址栏添加多个IP时、添加设备后只成功最后一个添加的设备信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1791]
1.添加设备时、IP地址添加多个时、添加设备后只成功最后一个添加的设备信息

![default](https://user-images.githubusercontent.com/28615156/34931245-be320730-fa08-11e7-85ee-586faf19522a.png)

![default](https://user-images.githubusercontent.com/28615156/34931275-efe911ba-fa08-11e7-8dc9-002a95bec1b0.png)

![default](https://user-images.githubusercontent.com/28615156/34931297-0d575a36-fa09-11e7-8e9b-f4499657da66.png)

**Comment by eeiceyes** [comment]
地址对应的设备已经存在，是设备查找有bug

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180119_3173_x64.exe 版本确认，close处理。
