### ISSUE TITLE
[机房视图]从机柜属性视图中、右键选择Telne连接的Telnet界面还是老的界面

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1793]
1.从机柜属性视图中、右键选择Telne连接的Telnet界面还是老的界面
2.ssh同样有次现象

![default](https://user-images.githubusercontent.com/28615156/34933458-d55e4d0c-fa11-11e7-83cb-d2adce7ef705.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180118_3172_x64.exe 版本确认，close处理。
