### ISSUE TITLE
[业务视图]业务视图页面点击“名称”、视图不进行特定的规则排序

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1795]
1.业务视图页面点击“名称”、视图不进行特定的规则排序

![1516006159 1](https://user-images.githubusercontent.com/28615156/34934175-782aee26-fa14-11e7-9b0c-7148505021c1.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180118_3172_x64.exe 版本确认，close处理。
