### ISSUE TITLE
[自定义首页]自定义首页中缺省的首页选项点击显示无权限

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1796]
1.自定义首页中缺省的首页选项点击显示无权限

![1516082366 1](https://user-images.githubusercontent.com/28615156/34974022-d7d38b9c-fac5-11e7-962d-7d566a9a9939.jpg)

![1516082396 1](https://user-images.githubusercontent.com/28615156/34974023-d811617e-fac5-11e7-8221-64bebf2bc744.jpg)

![1516082425 1](https://user-images.githubusercontent.com/28615156/34974024-d84e7438-fac5-11e7-98e1-926c94f898e0.jpg)

![1516082447 1](https://user-images.githubusercontent.com/28615156/34974025-d88ab682-fac5-11e7-8820-1b8ed9a8dc49.jpg)

**Comment by runner-mei** [comment]
fix?

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3208_x64.exe 版本确认，还出现此现象

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3249_x64.exe  版本确认，close处理。
