### ISSUE TITLE
[华东电网]业务视图中告警数量、与信息框中的产生告警节点显示不对

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1797]
业务视图中告警数量、与信息框中的产生告警节点显示不对

![d99ab79481be666316f09a180ee1a8a0](https://user-images.githubusercontent.com/28615156/34978276-aea2d3a0-fad8-11e7-9a0d-e903a6de2e88.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180118_3172_x64.exe 版本确认，close处理。
