### ISSUE TITLE
[华东电网]设备端口日志页面无告警日志显示、右下角表示中显示有数据

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1798]
1.设备端口日志页面无告警日志显示、右下角表示中显示有数据

![gfoelsbop 75 da0 px6 o6](https://user-images.githubusercontent.com/28615156/34978372-fb877040-fad8-11e7-8cd8-d52d8827ba9b.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180122_3196_x64.exe    版本确认，close处理。
