### ISSUE TITLE
数据库表空间名获取到的与数据库查询到的不对应

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#180]
![image](https://cloud.githubusercontent.com/assets/14171497/13561302/5ba36d3e-e466-11e5-940c-998542a7f5f0.png)

![image](https://cloud.githubusercontent.com/assets/14171497/13561293/3dfad1e6-e466-11e5-960d-3c1212bb85b0.png)

**Comment by runner-mei** [comment]
已解决
