### ISSUE TITLE
[当前告警]在用户管理页面、点击右上角的当前告警图标无效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1801]
1.在用户管理页面、点击右上角的当前告警图标无效、不同等级的颜色也不显示
2.在用户管理/用户组管理/角色管理/权限管理/通知管理/系统空间管理/备份数据/计划任务等页面点击当前用户、添加页面为当前页面用户页面
3.在服务管理页面有同样的现象

![default](https://user-images.githubusercontent.com/28615156/35139490-5342dd4a-fd2e-11e7-8749-5c94ffead221.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180123_3203_x64.exe  版本确认，close处理。
