### ISSUE TITLE
[资产同步]资产同步时、业务视图同步失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1802]
1.资产同步时、业务视图同步失败

![fzwmvfd 25 hg29y3 8tkl](https://user-images.githubusercontent.com/28615156/35143624-133868dc-fd3d-11e7-8777-5cdb205e6b47.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180123_3203_x64.exe  版本确认，close处理。
