### ISSUE TITLE
[当前巡检]在填写巡检页面、发送itsm请求时、请求标题中自动添加空格

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1803]
1.在填写巡检业务、发送itsm请求时、请求标题中自动添加空格

![m n 7 2x ln3_3zebns t](https://user-images.githubusercontent.com/28615156/35146547-59bf6018-fd46-11e7-87d2-f5b948ebeec8.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180122_3192_x64.exe   版本确认，close处理。
