### ISSUE TITLE
[当前巡检]巡检页面发送itsm请求后、在服务管理的巡检请求中删除巡检请求、巡检页面点击发送图标提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1806]
1.巡检页面发送itsm请求后、在服务管理的巡检请求中删除巡检请求、巡检页面点击发送图标提示错误

![default](https://user-images.githubusercontent.com/28615156/35203728-a7491c8c-ff64-11e7-927c-e7472c8593d8.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180122_3192_x64.exe   版本确认，还出现此现象

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180123_3203_x64.exe  版本确认，还出现此现象

![default](https://user-images.githubusercontent.com/28615156/35310559-f68393d4-00ec-11e8-8720-ef3d8e3915d6.png)

**Comment by eeiceyes** [comment]
请求实际已经被标记为删除；对于此类情况，错误页面应该需要清楚的显示该请求是在何时被谁删除，删除时请求已经执行到何种阶段

**Comment by hengwei-ly** [comment]
已解决，现在如果是被删除的请求，访问时会给出一个请求已被删除的提示页面，显示请求标题和被删除时的相关信息 (在2018-01-26 后的版本可用)

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，close处理。
