### ISSUE TITLE
[当前巡检]表空间使用率巡检设置检测所有数据行时、表空间超过阈值得出的结论不对

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1807]
1.表空间使用率巡检设置检测所有数据行时、表空间超过阈值得出的结论不对

![default](https://user-images.githubusercontent.com/28615156/35208332-caae28de-ff82-11e7-844f-41aec50e595c.png)

![default](https://user-images.githubusercontent.com/28615156/35208345-dce8de72-ff82-11e7-8caa-4735cb00dc8a.png)

**Comment by eeiceyes** [comment]
都是检测运算后的单点值，如果要检测所有值小于，则设置成最大值小于***

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180122_3192_x64.exe   版本确认，close处理。
