### ISSUE TITLE
[用户组管理]用户组中选择用户的窗口中、用户名后面的信息是描述信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1808]
1.用户组中选择用户的窗口中、用户名后面的信息是描述信息
2.正确的是昵称信息

![default](https://user-images.githubusercontent.com/28615156/35209120-cbf55704-ff86-11e7-9e12-7f8e1338d216.png)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3208_x64.exe 版本确认，close处理。
