### ISSUE TITLE
[华东电网]oracle数据库表空间使用率告警异常

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1811]
oracle数据库表空间使用率告警异常

**Comment by runner-mei** [comment]
告警规则运行日志报错，错误如下

> field 'row' isnot exists.

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，close处理。
