### ISSUE TITLE
[自定义首页]自定义首页里添加url连接、只能添加一个URL、添加第二个覆盖第一个

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1813]
1.自定义首页里添加url连接、只能添加一个URL、添加第二个覆盖第一个

![default](https://user-images.githubusercontent.com/28615156/35315690-c5143dbe-0108-11e8-80d4-d3a1093f9809.png)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3208_x64.exe 版本确认，还出现此问题

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
