### ISSUE TITLE
[用户管理]用户定制不同的首页后、账号登入后不是选择的首页

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1814]
1.用户定制不同的首页后、账号登入后不是选择的首页

![1516771061 1](https://user-images.githubusercontent.com/28615156/35315797-5269d732-0109-11e8-988c-e812e4ce8db0.jpg)

![1516771095 1](https://user-images.githubusercontent.com/28615156/35315798-52a93954-0109-11e8-8802-347ef7c85fa0.jpg)

**Comment by runner-mei** [comment]
有两个问题
1. 点退出时，跳到登录界页面时 service 参数不要传了
2.跳到你页面上进有传参数   value=vmware_topology.7

http://127.0.0.1/hengwei/web/home?ticket=ST-5a714ea8b7911c3294000004&username=zhz&value=vmware_topology.7

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
