### ISSUE TITLE
[告警日志]导出的告警日志没有“告警对象”和“规则名称”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1816]
1.导出的告警日志没有“告警对象”和“规则名称”

![default](https://user-images.githubusercontent.com/28615156/35316970-5d27f87e-010f-11e8-9b7d-c71c5b71b45c.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180124_3206_x64.exe 版本确认，close处理。
