### ISSUE TITLE
[常用工具]点击“常用工具-Telnet”、跳转连接错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1817]
1.点击“常用工具-Telnet”、跳转连接错误
2.把127.0.0.1地址改为当前网管地址后正常

![1516783098 1](https://user-images.githubusercontent.com/28615156/35322382-0cbe70f0-0125-11e8-9635-226459322922.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180124_3206_x64.exe 版本确认，close处理。

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20180308_737_x64.exe    2.3版本出现此问题
