### ISSUE TITLE
[权限管理]权限管理页面、权限组中内建的权限组出现重复

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1818]
1.权限管理页面、权限组中内建的权限组出现重复

![1516788313 1](https://user-images.githubusercontent.com/28615156/35326350-5f4bd0b8-0131-11e8-92f5-4a1f28e21970.jpg)

**Comment by runner-mei** [comment]
这个问题，我没有重现出来

**Comment by hengwei-test** [comment]
多次重现未再现先close处理
