### ISSUE TITLE
[当前用户]不同的页面显示的当前用户信息不统一、一种是用户名、一种是中文名

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1822]
1.不同的页面显示的当前用户信息不统一、一种是用户名、一种是中文名
2.要求统一改为中文名

**Comment by eeiceyes** [comment]
请列出具体页面，不然容易出现遗漏

**Comment by eeiceyes** [comment]
想到的都改了，因为没有明确的列表，所以请测试再确认下

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
