### ISSUE TITLE
[系统管理]FTP服务上传配置备份，提示“上传超时”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1825]
1.FTP服务上传配置备份，提示“上传超时”

![1517205626 1](https://user-images.githubusercontent.com/28615156/35495653-e5b19538-04fc-11e8-8f4d-9790d6a05042.jpg)

![1517205639 1](https://user-images.githubusercontent.com/28615156/35495654-e5f08112-04fc-11e8-8b84-35cdede926fb.jpg)

[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/1672423/server_biz.txt)

[web_server.txt](https://github.com/three-plus-three/hw_issues/files/1672424/web_server.txt)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
