### ISSUE TITLE
[系统管理]邮件服务器测试时、测试失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1826]
1.邮件服务器测试时、测试失败

![default](https://user-images.githubusercontent.com/28615156/35495758-649c81b4-04fd-11e8-9814-47c25f3fad87.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
