### ISSUE TITLE
[系统管理]数据库脚本执行SQL语句、提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1827]
1.数据库脚本执行SQL语句、提示错误

![default](https://user-images.githubusercontent.com/28615156/35496542-463ea1e4-0501-11e8-990c-25ec1d2c7378.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
