### ISSUE TITLE
[华东电网]业务视图中视图节点中发送告警、业务视图的图标红色闪烁提示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1828]
1.业务视图中视图节点中发送告警、业务视图的图标红色闪烁提示

![default](https://user-images.githubusercontent.com/28615156/35551853-0d38c1d8-05cc-11e8-8825-14a6127ac60e.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
