### ISSUE TITLE
[用户组]在用户组中添加用户时、提示违反唯一约束

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1830]
1.在用户组中添加用户时、提示违反唯一约束
2.此现象没有特定的规律、相同的操作也不是百分百在现

![9 cbr1 q_sa76misfkq4 c](https://user-images.githubusercontent.com/28615156/35552701-df47b352-05cf-11e8-9028-a8e9cb3679f2.png)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，做了4次出现一次此现象

![default](https://user-images.githubusercontent.com/28615156/35786121-05ca89f2-0a60-11e8-96d7-0e1c258cf77e.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180331_3101_x64.exe  版本确认，close处理。
