### ISSUE TITLE
【天风期货】自定义检测告警-SQL脚本检测方式测试时有乱码

### ISSUE THREAD

**Issue by eeiceyes** [three-plus-three/hw_issues#1831]
![image](https://user-images.githubusercontent.com/4076162/35608407-08057d00-0694-11e8-9cd0-f6f5e09bc2ad.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180331_3101_x64.exe  版本确认，close处理。
