### ISSUE TITLE
[虹桥机场] 最新更新的模块功能指标一一实现

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1832]
因虹桥机场现在查合同比较严格,按照合同的要求每项功能都必须实现:
网络设备硬件监控包含内容：当前硬件错误报告， FRU 模块状态，冗余模块状态， 传感器状态， 内部功能模块状态如重启次数，重启时间，重启原因，内部服务进程状态， 如转发进程，路由进程， 交换模块的状态及性能（包括 2层和 3层），光纤口的状态（如功率等）。

**Comment by runner-mei** [comment]
内部功能模块状态如重启次数
physical_entry

entPhysicalModuleNumResets
entPhysicalModuleLastResetReason
entPhysicalModuleLastResetTime

**Comment by runner-mei** [comment]
如转发进程，路由进程， 交换模块的状态
cpmProcessTable
cpmProcessExtRevTable

**Comment by runner-mei** [comment]
现在还差这个 
交换模块的状态及性能（包括 2层和 3层），光纤口的状态（如功率等）

**Comment by runner-mei** [comment]
硬件信息中全有了

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180402_3103_x64.exe  版本确认，close处理。
