### ISSUE TITLE
[当前告警]在用户管理页面、点击导航栏中的当前告警按钮、弹出的当前告警窗口未添加颜色样式

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1836]
1.在用户管理页面、点击导航栏中的当前告警按钮、弹出的当前告警窗口未添加颜色样式
2.在用户管理/用户组管理/角色管理/权限管理/通知管理/系统空间管理/备份数据/计划任务等页面都有此现象
3.设备负载监控/线路流量监控/设备负载TOPN/线路流量IOPN/设备端口信息/设备ARP表信息/设备路由信息/设备IP地址信息/设备TCP连接信息/设备UDP监听信息 的窗口同样出现此现象
4.在itsm页面、点击右上角的告警图标同样出现此现象

![default](https://user-images.githubusercontent.com/28615156/35785720-925d1c7a-0a5d-11e8-85c9-54f5c4846346.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3243_x64.exe  版本确认，close处理。
