### ISSUE TITLE
[当前巡检]当前巡检任务提交后、浏览器会提示更新密码提示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1838]
1.当前巡检任务提交后、浏览器会提示更新密码提示

![default](https://user-images.githubusercontent.com/28615156/35791784-9c7d05ae-0a84-11e8-8c03-53f65d3920b4.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180207_3243_x64.exe  版本确认，close处理。
