### ISSUE TITLE
[用户管理]新建用户时、角色选择“administrator”时、在选择首页时、“根图”选项不显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1840]
1.新建用户时、角色选择“administrator”时、在选择首页时、“根图”选项不显示
2.当编辑新添加的用户时、角色可以选择根图

![1517819242 1](https://user-images.githubusercontent.com/28615156/35794736-d9ccabfa-0a91-11e8-8a7a-f9c3efa0dffc.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180211_3262_x64.exe  版本确认，close处理。
