### ISSUE TITLE
[权限管理]权限组页面的分页按钮格式错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1844]
1.权限组页面的分页按钮格式错误

![1518160594 1](https://user-images.githubusercontent.com/28615156/36016091-6c514d92-0dac-11e8-8321-8bef2047c586.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180211_3262_x64.exe  版本确认，close处理。
