### ISSUE TITLE
[权限管理]权限组的权限选项没有统一的排序，导致按下一页的时候显示的并不是固定内容

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1846]
1.权限组的权限选项没有统一的排序，导致按下一页的时候显示的并不是固定内容

第一次：
![1518160999 1](https://user-images.githubusercontent.com/28615156/36016343-881395de-0dad-11e8-8c0e-3ab97dc27008.jpg)

第二次：

![1518161032 1](https://user-images.githubusercontent.com/28615156/36016431-e2d63760-0dad-11e8-8fde-777076e92388.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180211_3262_x64.exe  版本确认，还出现此现象。

第一次：
![1519611472](https://user-images.githubusercontent.com/28615156/36650438-7782ea7e-1ade-11e8-950a-8d169536105c.jpg)

第二次：
![1519611512 1](https://user-images.githubusercontent.com/28615156/36650444-7ba8819a-1ade-11e8-9d12-5583e35226b3.jpg)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180228_3296_x64.exe   版本确认，close处理。
