### ISSUE TITLE
[华东电网]添加邮件通知方式时、接收者中邮件名带特殊字符无法添加

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1848]
1.添加邮件通知方式时、接收者中邮件名带特殊字符无法添加

![default](https://user-images.githubusercontent.com/28615156/36650183-16d9e7e6-1add-11e8-9895-e9ec1fe15340.png)

**Comment by runner-mei** [comment]
it_donmei@ec.sgcc.com.cn

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180312_3043_x64.exe   版本确认，close处理。
