### ISSUE TITLE
[安装]tpt_ip_mgr/tpt_poller进程一直在重启、拓扑图上的图元没有颜色

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1849]
1.tpt_ip_mgr/tpt_poller进程一直在重启、拓扑图上的图元没有颜色

![default](https://user-images.githubusercontent.com/28615156/36650865-9f12e9ca-1ae0-11e8-852e-fec334029ce0.png)

[ip-mgr.txt](https://github.com/three-plus-three/hw_issues/files/1757031/ip-mgr.txt)

[poller.txt](https://github.com/three-plus-three/hw_issues/files/1757032/poller.txt)

**Comment by runner-mei** [comment]
fixed
