### ISSUE TITLE
[华东电网]打补丁方式只更新itsm模块、权限组页面itsm内建权限出现重复

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1854]
1.打补丁方式只更新itsm模块、权限组页面itsm内建权限出现重复
2.有什么方法可以删除内建的权限组、手动删除多余的内建权限组

![default](https://user-images.githubusercontent.com/28615156/36822483-38ec94f2-1d33-11e8-95df-30d4bfc3cd19.png)

**Comment by runner-mei** [comment]
fix

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180301_3300_x64.exe   版本确认，close处理。
