### ISSUE TITLE
[自定义统计数据]添加记录类型为Sybase的类型时、记录规则中出现MySQL数据库的记录规则

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1857]
1.添加记录类型为Sybase的类型时、记录规则中出现MySQL数据库的记录规则

![1520309583 1](https://user-images.githubusercontent.com/28615156/37013982-716d3472-2138-11e8-8f33-226bda86b247.jpg)

**Comment by eeiceyes** [comment]
fixe

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20180314_748_x64.exe  版本确认，close处理。
