### ISSUE TITLE
[用户管理]用户管理页面、点击添加按钮、提示错误“ executing "HengweiUsers/edit_fields.html" at <$field.Enumerations>: can't evaluate field Enumerations in type models.Field”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1864]
1.用户管理页面、点击添加按钮、提示错误“ executing "HengweiUsers/edit_fields.html" at <$field.Enumerations>: can't evaluate field Enumerations in type models.Field”

![default](https://user-images.githubusercontent.com/28615156/37130377-1ddc4726-22be-11e8-850e-059d1cad69e2.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180331_3101_x64.exe  版本确认，close处理。
