### ISSUE TITLE
[通知管理]微信通知方式中、添加多个通知人时、测试不通过

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1867]
1.微信通知方式中、添加多个通知人时、测试不通过

![default](https://user-images.githubusercontent.com/28615156/37131050-86db15ce-22c1-11e8-9e33-e5e22d3b533f.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180331_3101_x64.exe  版本确认，close处理。
