### ISSUE TITLE
[资产管理]资产状态变更页面、搜索资产栏中没有明确提示按照什么查询条件来搜索资产

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1872]
1资产状态变更页面、搜索资产栏中没有明确提示按照什么查询条件来搜索资产

![1520484408 1](https://user-images.githubusercontent.com/28615156/37133617-8738272e-22cf-11e8-895d-14eae4a61a67.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180321_3063_x64.exe 版本确认，close处理。
