### ISSUE TITLE
[资产管理]资产查看页面、当资产信息拉到最后时、显示资产框与页脚信息分开

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1873]
1资产查看页面、当资产信息拉到最后时、显示资产框与页脚信息分开

![1520487227 1](https://user-images.githubusercontent.com/28615156/37134906-987034f4-22d5-11e8-9929-0efea385bb6c.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180321_3063_x64.exe 版本确认，close处理。
