### ISSUE TITLE
[资产管理]申请管理不能使用

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1875]
资产管理 》库房管理 》申请管理 》 添加 
![image](https://user-images.githubusercontent.com/14171497/37138899-d9701ec2-22e6-11e8-8f07-a3a3bb6fa2b0.png)

**Comment by eeiceyes** [comment]
fixed
把默认配置放上去就应该好了

**Comment by Cuic** [comment]
默认为什么没有打包到安装包中?
