### ISSUE TITLE
[资产管理]资产的状态变更后、在资产的变更历史数据中未记载

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1879]
1.资产的状态变更后、在资产的变更历史数据中未记载

1.资产开始状态：
![1520577329](https://user-images.githubusercontent.com/28615156/37194016-31c097d0-23a7-11e8-9559-017ca3879476.jpg)

2..资产状态变更成功、变更历史中未记载：
![1520577382 1](https://user-images.githubusercontent.com/28615156/37194045-5676fa24-23a7-11e8-8ee4-f3bc73793637.jpg)

![default](https://user-images.githubusercontent.com/28615156/37194057-64f4700e-23a7-11e8-95a1-39e53b375e00.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180321_3063_x64.exe 版本确认，close处理。
