### ISSUE TITLE
[待办事件]当登入的账号有待处理事件时、待办事件页面显示菜单不对

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1881]
1.当登入的账号有待处理事件时、待办事件页面显示菜单不对

2.显示的待办事件页面显示的“系统管理”菜单不全

待办事件菜单：
![default](https://user-images.githubusercontent.com/28615156/37199246-09717e56-23bc-11e8-8adf-0d6d1318de0f.png)

正确的菜单显示：
![default](https://user-images.githubusercontent.com/28615156/37198481-64dc5610-23b9-11e8-9255-93b09419c8ba.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180326_3081_x64.exe 版本确认、还是出现。

用户角色选择的是administrator

错误菜单截图：
![default](https://user-images.githubusercontent.com/28615156/37950686-1cc03b00-31cc-11e8-8a87-7610694ee1b3.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180402_3103_x64.exe  版本确认，close处理。
