### ISSUE TITLE
[待办事件]待办事件页面、点击退出按钮、不是退出到登入页面

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1882]
1.待办事件页面、点击退出按钮、不是退出到登入页面

![1520586479 1](https://user-images.githubusercontent.com/28615156/37199400-7a3a64d6-23bc-11e8-9b33-55fdf42228ba.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180321_3063_x64.exe 版本确认，close处理。
