### ISSUE TITLE
[角色管理]用户编辑页面、点击内建角色进入内建角色编辑页面、编辑后角色能在角色管理页面删除

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1883]
1.用户编辑页面、点击内建角色进入内建角色编辑页面、编辑后角色能在角色管理页面删除

1.用户编辑页面：
![1520587622 1](https://user-images.githubusercontent.com/28615156/37200237-2927c5ae-23bf-11e8-9a11-8e350a21d7ea.jpg)

2.内建角色编辑：
![default](https://user-images.githubusercontent.com/28615156/37200262-34541b9e-23bf-11e8-9431-30c9e64a68b5.png)

3.内建角色出现删除按钮：
![1520587693 1](https://user-images.githubusercontent.com/28615156/37200295-504ae85a-23bf-11e8-824c-c73499c25654.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180331_3101_x64.exe  版本确认，close处理。
