### ISSUE TITLE
[告警通知]邮件通知方式中、添加多个邮件用户时告警发送邮件失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1889]
1.邮件通知方式中、添加多个邮件用户时告警发送邮件失败

[panic]runtime error: invalid memory address or nil pointer dereference C:/CI_Programs/go/src/runtime/asm_amd64.s:509 C:/CI_Programs/go/src/runtime/panic.go:491 C:/CI_Programs/go/src/runtime/panic.go:63 C:/CI_Programs/go/src/runtime/signal_windows.go:161 C:/CI_Programs/Jenkins/jobs/tpt_release_4/workspace/src/engine/tpt_vendor/src/github.com/runner-mei/delayed_job/mail_message.go:141 C:/CI_Programs/Jenkins/jobs/tpt_release_4/workspace/src/engine/tpt_vendor/src/github.com/runner-mei/delayed_job/mail_handler.go:472 C:/CI_Programs/Jenkins/jobs/tpt_release_4/workspace/src/engine/tpt_vendor/src/github.com/runner-mei/delayed_job/job.go:191 C:/CI_Programs/go/src/runtime/asm_amd64.s:2337

**Comment by runner-mei** [comment]
fixed
