### ISSUE TITLE
[公司内测]设备主机默认运行时间告警规则去掉

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1891]
设备主机默认运行时间告警规则去掉
![image](https://user-images.githubusercontent.com/14171497/37269432-40ac487e-2605-11e8-9bb1-54c929317c00.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180321_3063_x64.exe 版本确认，默认告警规则还是添加。

![default](https://user-images.githubusercontent.com/28615156/37747466-5795f80c-2dba-11e8-9163-37edb310e17a.png)
