### ISSUE TITLE
[记录数据查询]按照设备端口查询条件、记录规则选择窗口还是老的窗口

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1893]
1.按照设备端口查询条件、记录规则选择窗口还是老的窗口

1.老的窗口：
![default](https://user-images.githubusercontent.com/28615156/37271294-357199b6-260d-11e8-8eed-03d60e214243.png)
2.新的窗口：
![default](https://user-images.githubusercontent.com/28615156/37271363-9420876a-260d-11e8-8034-2de6869c39d3.png)

**Comment by eeiceyes** [comment]
这个列表列出的是记录规则，不是对象
