### ISSUE TITLE
[设备端口]添加设备端口的历史记录规则时、当管理对象的端口比较多时、刷新端口信息比较慢

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1894]
1.添加设备端口的历史记录规则时、当管理对象的端口比较多时、刷新端口信息比较慢
2.记录数据规则查询、流量数据查询、线路右键菜单栏的历史记录查看、告警规则、告警日志 同样出现此问题

**Comment by eeiceyes** [comment]
增加限制，端口过多时不取端口状态
默认限制是100，可以修改默认配置，配置为port_status.get.limit=100
