### ISSUE TITLE
[报表管理]生成表报查看页面、导出报表窗口的报表规则栏不显示报表规则

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1898]
1.生成表报查看页面、导出报表窗口的报表规则栏不显示报表规则

错误：
![default](https://user-images.githubusercontent.com/28615156/37276914-28fb6db8-261e-11e8-8147-0d96b93f5663.png)

正确：

![default](https://user-images.githubusercontent.com/28615156/37276923-2f100844-261e-11e8-93a2-b372715f98d5.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180524_3251_x64.exe 版本确认，预置报表查看页面还是出现此问题
