### ISSUE TITLE
[华东电网]页面跳转到服务管理模块是、加载谷歌的字体时特别慢

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1900]
1.页面跳转到服务管理模块是、加载谷歌的字体时特别慢

**Comment by eeiceyes** [comment]
fixed
验证方法是F12打开开发人员工具，在tab页network那一项，输入过滤关键字font，确实是否还能看到加载谷歌字体

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180321_3063_x64.exe 版本确认，close处理。
