### ISSUE TITLE
[用户首页]用户设置的首页是“当前巡检任务”、用户账号登入后跳转的首页是“生成拓扑图”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1903]
1.用户设置的首页是“当前巡检任务”、用户账号登入后跳转的首页是“生成拓扑图”

![1521172437 1](https://user-images.githubusercontent.com/28615156/37504579-42b5e914-291a-11e8-96fa-71ebe119cfd7.jpg)
![1521172384 1](https://user-images.githubusercontent.com/28615156/37504580-42ed8d38-291a-11e8-9d3d-385b8dbb2fe4.jpg)
![1521172408 1](https://user-images.githubusercontent.com/28615156/37504581-4322d420-291a-11e8-868f-99d1c21036bb.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180321_3063_x64.exe 版本确认，close处理。
