### ISSUE TITLE
[资产管理]批量修改资产信息提示成功、查看资产信息修改不起效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1904]
1.批量修改资产信息提示成功、查看资产信息修改不起效

修改信息：
![default](https://user-images.githubusercontent.com/28615156/37510540-62f63172-2936-11e8-89ac-7e20ab28367c.png)
![default](https://user-images.githubusercontent.com/28615156/37510546-6a6dc028-2936-11e8-88e2-e2f7883f923d.png)

修改查看信息：
![1521188645 1](https://user-images.githubusercontent.com/28615156/37510573-898ac7e4-2936-11e8-967c-81693da713c8.jpg)

**Comment by eeiceyes** [comment]
当前确认没发现这个问题，后续再观察吧
