### ISSUE TITLE
[资产管理]添加合同页面、在选择资产窗口中、点击选择查询条件时、下拉框中不显示查询条件

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1905]
1.添加合同页面、在选择资产窗口中、点击选择查询条件时、下拉框中不显示查询条件

![1521194509 1](https://user-images.githubusercontent.com/28615156/37514980-630e364c-2944-11e8-8089-c0877543c7df.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180321_3063_x64.exe 版本确认，close处理。
