### ISSUE TITLE
[华数] 华数需求

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#1907]
- [ ] 1、网络设备整体板卡信息：电压、温度、状态
- [x] ~~2、网络设备光口的收光/发光数据（原始值换算）~~
- [x] ~~3、聚合线路通过LACP获取具体端口成员的up/down状态~~
- [x]  ~~4、线路通过bgp/isis协议进行监控~~
- [x] ~~5、F5设备通过vs->pool->node的三层显示方式显示对应的流量与连接数信息~~
- [x] ~~6、juniper Bas通过ppoe地址池显示vr的在线人数~~
- [x] ~~7、防火墙（forigate 1000c）显示会话数排行榜（会话数排行以由内向外与由外向内两个角度进行排列显示）~~

**Comment by hengweiGR** [comment]
update

**Comment by runner-mei** [comment]
4 线路通过bgp/isis协议进行监控
已完成 分别为 bgpPeerTable 和  isisISAdjTable

**Comment by runner-mei** [comment]
5 F5设备通过vs->pool->node的三层显示方式显示对应的流量与连接数信息
f5ltmNodeAddrTable
f5ltmNodeAddrStatTable

**Comment by runner-mei** [comment]
6、juniper Bas通过ppoe地址池显示vr的在线人数~~
jnxPPPoESummary
jnxPppSummary

**Comment by runner-mei** [comment]
7、防火墙（forigate 1000c）显示会话数排行榜（会话数排行以由内向外与由外向内两个角度进行排列显示）
fgIpSessTable

**Comment by runner-mei** [comment]
2、网络设备光口的收光/发光数据（原始值换算）
optical_port_info

**Comment by eeiceyes** [comment]
f5设备=>右键=>实时监控=>流量信息
forigate防火墙=>实时监控=>会话统计
juniper Bas =>左键显示接口UP/DOWN数量统计

**Comment by eeiceyes** [comment]
LACP端口状态=>右键=>实时信息查看=>LACP端口信息[172.25.8.194] 取数有点慢
