### ISSUE TITLE
[监控总览]添加面板类型为“主机磁盘使用率TOPN”、参考设置中为选择数据时时、点击面板编辑按钮提示“加载错误”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1908]
1.添加面板类型为“主机磁盘使用率TOPN”、参考设置中为选择数据时时、点击面板编辑按钮提示“加载错误”

![1521435843 1](https://user-images.githubusercontent.com/28615156/37579503-8cacdf9e-2b79-11e8-9331-8917fc8a2615.jpg)
![1521435871 1](https://user-images.githubusercontent.com/28615156/37579504-8cf48f88-2b79-11e8-8337-695e9a6429d0.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180321_3063_x64.exe 版本确认，close处理。
