### ISSUE TITLE
[告警规则]告警规则触发后、邮件通知方式添加的通知用户邮件地址未通知

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1909]
1.告警规则触发后、邮件通知方式添加的通知用户邮件地址未通知

通知规则添加用户：
![1521442661 1](https://user-images.githubusercontent.com/28615156/37582086-28c814b4-2b86-11e8-9245-bda1dccf8d48.jpg)

用户页面添加邮箱：
![1521442693 1](https://user-images.githubusercontent.com/28615156/37582088-29a59cb2-2b86-11e8-8a12-2eed6b91b6a3.jpg)

邮件中未统计用户页面的邮箱：
![1521442749 1](https://user-images.githubusercontent.com/28615156/37582089-29eb5450-2b86-11e8-83b3-796c2023bae0.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
4月24日版本还是出现此问题、用户角色未发送邮件

![default](https://user-images.githubusercontent.com/28615156/39169246-a148a598-47c9-11e8-9b82-3d818225f3a8.png)


![default](https://user-images.githubusercontent.com/28615156/39169211-872aeffe-47c9-11e8-896d-5828ae4e4a16.png)
