### ISSUE TITLE
设备属性ssh 的用户密码回填成默认

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#191]
如果重新编辑设备属性所填写的 用户名与密码 恢复默认值
![image](https://cloud.githubusercontent.com/assets/14171497/13666325/ec6e6f58-e6eb-11e5-8a52-8ec5b78b3383.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by runner-mei** [comment]
在 firefox 上会出错出框

**Comment by eeiceyes** [comment]
fixed
