### ISSUE TITLE
[数据管理]发送syslog数据平台接收不到

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1914]
1.发送syslog数据平台接收不到
2.snmp trap数据同样收不到
3.Linux版本同样出现

![1521448152](https://user-images.githubusercontent.com/28615156/37586983-f0ec993a-2b98-11e8-9abc-aa221935dc4e.jpg)

![1521448178 1](https://user-images.githubusercontent.com/28615156/37586987-f1d400ea-2b98-11e8-8986-13b2d1c98a6c.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by runner-mei** [comment]
请注意防火墙开了没有

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180329_3096_x64.exe  版本确认，close处理。
