### ISSUE TITLE
【国联期货】网络设备中文名系统中显示乱码

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#1917]
![qq 20180321132528](https://user-images.githubusercontent.com/14171518/37695573-5ac378f6-2d0b-11e8-9542-c5fbd83c9368.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180329_3096_x64.exe  版本确认，close处理。
