### ISSUE TITLE
[系统组件]新安装的版本、系统组件中没有服务管理的开启信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1921]
1.新安装的版本、系统组件中没有服务管理的开启信息

![default](https://user-images.githubusercontent.com/28615156/37757549-66992d64-2de8-11e8-9e69-fe0de530acc1.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180329_3096_x64.exe  版本确认，close处理。
