### ISSUE TITLE
[双机热备]备用机器ha.properties配置中“ha.master_address=${ha_master_address}”配置不起效、日志中提示找不到主机地址

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1923]
1.备用机器ha.properties配置中“ha.master_address=${ha_master_address}”配置不起效、日志中提示找不到主机地址

不起效配置截图：
![default](https://user-images.githubusercontent.com/28615156/37809912-6bc874ee-2e8c-11e8-82a8-ccae449fdaf8.png)

起效配置截图：

![default](https://user-images.githubusercontent.com/28615156/37809920-7499bd3a-2e8c-11e8-88df-eacef4c65d34.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180408.1341~41ce94a.x86_64.rpm 版本确认，close处理。
