### ISSUE TITLE
[双机热备]当备用设备程序到达获取主机数据的时间、未成功获取主设备上数据信息

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1925]
1.当备用设备程序到达获取主机数据的时间、未成功获取主设备上数据信息

修改获取时间截图：
![default](https://user-images.githubusercontent.com/28615156/37812794-de4db762-2e9c-11e8-9436-3e244766d2f9.png)

获取失败日志信息：
![default](https://user-images.githubusercontent.com/28615156/37812761-a55fc6e8-2e9c-11e8-80a7-41ccc5550743.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180408.1341~41ce94a.x86_64.rpm 版本确认，close处理。
