### ISSUE TITLE
[告警管理]Linux版本添加SQL脚本的告警规则、点击测试按钮提示连接错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1930]
1.Linux版本添加SQL脚本的告警规则、点击测试按钮提示连接错误
2.自定义检测告警所有检测类型都出现此问题
3.win版本检测类型：维保到期检测同样出现此现象
Linux版本错误：
![default](https://user-images.githubusercontent.com/28615156/37890930-f139b3e8-3104-11e8-9431-17f9a9a79696.png)

win版本同样数据测试成功：
![default](https://user-images.githubusercontent.com/28615156/37891076-88c0a5d2-3105-11e8-85c5-f5169974ba40.png)

win版本检测类型是:维保到期检测截图：
![default](https://user-images.githubusercontent.com/28615156/38133437-cbf0d414-3441-11e8-9668-aceaa970727e.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180402_3103_x64.exe  版本确认，close处理。
