### ISSUE TITLE
[国联期货]使用非admin账号、在机柜视图中编辑机柜信息时、新添加进机柜里的设备全部显示在机柜上面

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1933]
1.使用非admin账号、在机柜视图中编辑机柜信息时、新添加进机柜里的设备全部显示在机柜上面

![default](https://user-images.githubusercontent.com/28615156/37951662-caa07ac0-31cf-11e8-984d-195dfd8ea21b.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180329_3096_x64.exe  版本确认，close处理。
