### ISSUE TITLE
[主机管理]添加ssh的设备时、当ssh采集方式的账号密码不对时、提示信息不明确

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1934]
1.添加ssh的设备时、当ssh采集方式的账号密码不对时、提示信息不明确
正确的提示信息：ssh参数的账号/密码不正确

当ssh账号密码不对时提示信息：
![default](https://user-images.githubusercontent.com/28615156/37958643-9f595346-31e3-11e8-87d9-8be1311a59a0.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180419_3136_x64.exe  版本确认，描述还不能够用户明确

![default](https://user-images.githubusercontent.com/28615156/39031791-e1dafb2c-449c-11e8-8850-89f04dd82ae6.png)

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180615_3482_x64.exe 版本确认，close处理。
