### ISSUE TITLE
[待办事件]从菜单中的“待办事件”选项进入、页面样式加载错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1938]
1.从菜单中的“待办事件”选项进入、页面样式加载错误

![default](https://user-images.githubusercontent.com/28615156/38006308-0be03aa0-3277-11e8-8852-7c54f09bc6cb.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180329_3096_x64.exe  版本确认，close处理。
