### ISSUE TITLE
[登入]登入页面账号密码框中的文字修改

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1939]
1.登入页面账号密码框中的文字修改

原文字：© 2013 Net Tech, all rights reserved.

修改后的文字：© 2012-2018 Hengwei Info Tech, all rights reserved.

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180331_3101_x64.exe  版本确认，新版本页面还是出现此问题。

![default](https://user-images.githubusercontent.com/28615156/38179685-a755e0b8-3658-11e8-9c78-1299d38abee2.png)
