### ISSUE TITLE
华力-BUG

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#194]
1.HP-UNIX 进程获取不到信息。#172

2.服务器获取数据不稳定，时有时无；历史记录数据图表出现断点情况。

3.weblogic -down的情况下暂时没测试

4.短消息命令执行暂时没测试

**Comment by runner-mei** [comment]
补充一下
1.  数据库表空间名获取到的与数据库查询到的不对应 #180
2. 邮件乱码问题是否已解决（@Cuic说已解决）

**Comment by runner-mei** [comment]
请检查一下，这些问题是否都已解决
