### ISSUE TITLE
[CA]添加的邮件服务器地址的邮件测试失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1942]
1.添加的邮件服务器地址的邮件测试失败

![default](https://user-images.githubusercontent.com/28615156/38120390-1fba777c-33fb-11e8-84ba-b67e54a4aed2.png)

[logs.zip](https://github.com/three-plus-three/hw_issues/files/1862396/logs.zip)

**Comment by runner-mei** [comment]
这个是邮件服务器反垃圾邮件导致的

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180331_3101_x64.exe  版本确认，close处理。
