### ISSUE TITLE
[登入页面]新安装的版本登入页面样式出现错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1943]
1.新安装的版本登入页面样式出现错误

![default](https://user-images.githubusercontent.com/28615156/38120582-78ffff7c-33fc-11e8-9595-784337a1b2da.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180331_3101_x64.exe  版本确认，close处理。
