### ISSUE TITLE
[上海季冠] Juniper防火墙VPN指标监控

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1948]
Juniper 防火墙IPsec VPN 指标监控
状态:
连接数
连接对象
...

**Comment by runner-mei** [comment]
nsVpnMonTable

**Comment by runner-mei** [comment]
jnxVpnPwTable

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
![default](https://user-images.githubusercontent.com/28615156/38479062-744c12b8-3bef-11e8-96a8-f04df90c76d3.png)

指标的名称信息翻译一下

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180410_3115_x64.exe
