### ISSUE TITLE
[华东电网]用户一直在登入状态、当事件分配到当前用户增加提醒功能

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1955]
1.用户一直在登入状态、当事件分配到当前用户增加提醒功能
2.原因：只有在用户登出后再次登入后才自动跳转到待办事件页面。用户一直处于登入状态、当用户有分配过来的请求没有任何提醒。

**Comment by eeiceyes** [comment]
已增加待办事项的提示入口，在界面右上角，通知消息提示左边

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180423_3145_x64.exe 版本确认，close处理。
