### ISSUE TITLE
执行数据库脚本的结果显示有问题

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#196]
在 192.168.1.6 上的 oracle 上执行 sql 语句（如下），显示有问题
select  * from TPT_SMS_FORWARDER

![_2016-03-17t10-09-48 675z](https://cloud.githubusercontent.com/assets/1052632/13842882/80e7cc90-ec6b-11e5-8c97-b6d4680ab96a.png)

**Comment by eeiceyes** [comment]
fixed
