### ISSUE TITLE
[资产管理]CMDB中配置项类型删除成功后、在数据库中还能查询到

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1962]
1.CMDB中配置项类型删除成功后、在数据库中还能查询到 

删除成功消息：
![default](https://user-images.githubusercontent.com/28615156/38486559-fa8a2656-3c0f-11e8-98f9-0972194888ef.png)
数据库中查询：
![default](https://user-images.githubusercontent.com/28615156/38486582-10d882cc-3c10-11e8-980e-4d77476a076d.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180514.1436~c507e0c.x86_64.rpm    版本确认，close处理。
