### ISSUE TITLE
[华东电网]业务总览页面添加一个按钮跳转到指定的业务视图页面

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1965]
1.业务总览页面添加一个按钮跳转到指定的业务视图页面

**Comment by eeiceyes** [comment]
特殊做法，在app.properties中增加一项配置biz_view.portal={id}
{id}是业务视图的Id，打开业务视图，在url上能取到
配置好了重启，在业务总览界面就能看到入口按钮

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180411_3119_x64.exe  版本确认，出现以下现象

![default](https://user-images.githubusercontent.com/28615156/38663733-393cf714-3e6a-11e8-8229-8a291f1f7ade.png)

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180420.1381~367f52f.x86_64.rpm  版本确认，close处理。
