### ISSUE TITLE
[自定义检测告警]检测类型为“维保到期检测”测试错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1968]
1.检测类型为“维保到期检测”测试错误

![default](https://user-images.githubusercontent.com/28615156/38539911-9846b1ea-3ccc-11e8-9db4-c68635df7fab.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180420.1381~367f52f.x86_64.rpm  版本确认，close处理。
