### ISSUE TITLE
刷新设备折线线路变直线

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#197]
原始状况：
![image](https://cloud.githubusercontent.com/assets/14171497/13916211/3759cbce-ef94-11e5-8558-b8145138d8e4.png)
操作刷新设备
![image](https://cloud.githubusercontent.com/assets/14171497/13916355/16f341f2-ef95-11e5-9f9e-ce7ece6c932f.png)
刷新好设备后,刷新根拓扑，线路折线变直线
![image](https://cloud.githubusercontent.com/assets/14171497/13916392/5570ad84-ef95-11e5-8671-42d442144fd9.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170814_270_x64.exe   版本确认，close处理。
