### ISSUE TITLE
[LDAP]LDAP账号使用自己新建角色、大小写不同账号登入平台出现不同的现象

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1970]
1.LDAP账号使用自己新建角色、大小写不同账号登入平台出现不同的现象
2.大写的账号登入、正常进入平台
3.小写的账号登入、提示没有权限操作

权限：
![default](https://user-images.githubusercontent.com/28615156/38549562-e1df1468-3ce6-11e8-86a9-d65ccb9a7f8d.png)

![default](https://user-images.githubusercontent.com/28615156/38549574-ec0d7664-3ce6-11e8-99ba-a32e7df0feea.png)

小写账号登入：
![default](https://user-images.githubusercontent.com/28615156/38549592-f716685e-3ce6-11e8-8f31-778c79200e0a.png)

**Comment by runner-mei** [comment]
我试了可以啊， 你重弄一份新数据试试

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180615_3482_x64.exe 版本确认，全新环境确认还是有此问题

**Comment by runner-mei** [comment]
fixed
