### ISSUE TITLE
[江阴国土] alcatel网络设备支持

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#1977]
alcatel网络设备监控支持

核心：alcatel 9700
汇聚：alcatel 6850
接入：alcatel 6248

数据位置：
hw_issues\现场数据\江阴国土-alcatel设备采集数据

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180413_3122_x64.exe  版本确认，200.200.5.200和200.200.5.201 还是不能获取到cpu/内存信息

**Comment by runner-mei** [comment]
缺省 Mib 文件无法支持
