### ISSUE TITLE
[用户管理]用户管理页面、点击“是否在线”"是否锁定"字样进行排序、不是所有的用户进行特殊排列

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1978]
1.用户管理页面、点击“是否在线”"是否锁定"字样进行排序、不是所有的用户进行特殊排列
2.点击字样进行排序、排序的是当前页面的数据进行排序

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180420.1381~367f52f.x86_64.rpm  版本确认，添加用户超过20个后、添加用户信息在用户管理页面不现象

**Comment by runner-mei** [comment]
不现象?

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180615_3482_x64.exe 版本确认，close处理。
