### ISSUE TITLE
[监控总览]添加Remot Ping 面板失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1980]
1.添加Remot Ping 面板失败
2.剩下的面板同样出现此问题

![default](https://user-images.githubusercontent.com/28615156/38659457-4746ae76-3e5c-11e8-8610-ebbe18813d23.png)

![default](https://user-images.githubusercontent.com/28615156/38659470-5230a968-3e5c-11e8-9ce1-6b43e52cb032.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180413_3122_x64.exe  版本确认，close处理。
