### ISSUE TITLE
[主机管理]添加主机页面采集方式中、同时选择winrn/wmi不能同时选项

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1981]
1.添加主机页面采集方式中、同时选择winrn/wmi不能同时选项

![1523519132 1](https://user-images.githubusercontent.com/28615156/38663369-2fc868d6-3e69-11e8-925c-e648ee20f352.jpg)

**Comment by eeiceyes** [comment]
故意为之，两个参数只能选一个

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180611_3471_x64.exe 版本确认，close处理。
