### ISSUE TITLE
[资产管理]合同页面、查看合同信息提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1983]
1.合同页面、查看合同信息提示错误

![default](https://user-images.githubusercontent.com/28615156/38717720-39c649ae-3f1b-11e8-834c-67f9e97f5523.png)

**Comment by eeiceyes** [comment]
问题的原因在于合同关联的资产被删除了
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180516_3211_x64.exe  版本确认，close处理。
