### ISSUE TITLE
[巡检结果]巡检结果页面、查看巡检报表信息是、异常数据中没有“结果”和“结论”的值

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1984]
1.巡检结果页面、查看巡检报表信息是、异常数据中没有“结果”和“结论”的值
2.html和PDF同样出现此问题

![default](https://user-images.githubusercontent.com/28615156/38726442-c60fad12-3f3c-11e8-8ad1-cb4d756ff4e4.png)

**Comment by eeiceyes** [comment]
巡检提交时没有勾选确认

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180516_3211_x64.exe  版本确认，close处理。
