### ISSUE TITLE
[国妇婴]线路拓扑时交换机与服务器的链路中、交换机的接口获取不对

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1985]
1.线路拓扑时交换机与服务器的链路中、交换机的接口获取不对

路径：hw_issues\现场数据\国妇婴拓扑搜索线路不准采集数据

**Comment by runner-mei** [comment]
fixed?

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180615_3482_x64.exe 版本确认，close处理。
