### ISSUE TITLE
[国联期货] 进入虚拟化的监控一览后界面很卡，是否和增加的虚拟机数量有关

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1992]
进入虚拟化的监控一览后界面很卡，是否和增加的虚拟机数量有关 

[web_server.txt](https://github.com/three-plus-three/hw_issues/files/1922903/web_server.txt)
[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/1922902/server_biz.txt)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180424.1390~cb89970.x86_64.rpm   版本确认，close处理。
