### ISSUE TITLE
[国联期货]存储性能排行：无法显示/存储容量使用；无法显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1995]
1.存储性能排行：无法显示/存储容量使用；无法显示

![default](https://user-images.githubusercontent.com/28615156/38917646-fb1adcb8-431d-11e8-9e93-f60e86519ec8.png)

![default](https://user-images.githubusercontent.com/28615156/38917659-0190d7c8-431e-11e8-9766-8e17c27f6417.png)

**Comment by eeiceyes** [comment]
这些界面的数据需要添加物理存储设备

**Comment by hengwei-test** [comment]
了解
