### ISSUE TITLE
[告警规则]告警规则中设备的告警时段不起效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1996]
1.告警规则中设备的告警时段不起效

![1524040420 1](https://user-images.githubusercontent.com/28615156/38920636-4ce3f11c-4326-11e8-9a67-f4de3c4a0fc0.jpg)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180424.1390~cb89970.x86_64.rpm   版本确认，还出现此问题

**Comment by runner-mei** [comment]
fixed
