### ISSUE TITLE
[配置备份]交换机使用snmp参数进行配置备份是提示失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1997]
1.交换机使用snmp参数进行配置备份是提示失败

![default](https://user-images.githubusercontent.com/28615156/38921924-7e97de00-4329-11e8-9c1c-446ed3036d2e.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180419_3136_x64.exe  版本确认，close处理。
