### ISSUE TITLE
[网络视图]服务器设备无法获取系统运行时间的指标值

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2001]
1.服务器设备无法获取系统运行时间的指标值
2.网络设备未出现此问题

![1524126158 1](https://user-images.githubusercontent.com/28615156/38979968-3028baf8-43ee-11e8-8a27-7ef6055f1471.jpg)

**Comment by eeiceyes** [comment]
我们现在没有指标分类，这个是ipmi的指标
