### ISSUE TITLE
[报表管理]报表规则管理页面显示内部错误

### ISSUE THREAD

**Issue by hengwei-test2** [three-plus-three/hw_issues#2004]
1.报表管理下报表规则管理页面显示内部错误
![zc 6 b9_5e0u 53w23bm j](https://user-images.githubusercontent.com/37530964/38983000-e7fb8c80-43f5-11e8-8a5e-adc03661401d.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180423.1388~7fe1582.x86_64.rpm版本验证、还是出现此问题。

![default](https://user-images.githubusercontent.com/28615156/39167245-d01d9bfc-47c0-11e8-9188-98ba34e03d56.png)
