### ISSUE TITLE
[通知管理]在通知管理里面添加通知规则、通知规则都添加失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2008]
1.在通知管理里面添加通知规则、通知规则都添加失败

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180423_3145_x64.exe 版本确认，还是出现此问题。
Linux版本未出现此问题。

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180615_3482_x64.exe 版本确认，close处理。
