### ISSUE TITLE
在资源管理添加设备后根图找不到该添加的设备

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#201]
在资源管理添加设备后根图找不到该添加的设备！

[aa.zip](https://github.com/three-plus-three/hw_issues/files/191304/aa.zip)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170814_270_x64.exe   版本确认，close处理。
