### ISSUE TITLE
[安徽电调]在产品常用工具右键web访问的功能

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2011]
1.在产品常用工具右键web访问的功能 目前所实现web连接是通过浏览器访问的机器进行访问设备,根据安徽电调的情况,需要通过网管机器访问(web访问),转移到本地访问网管机的机器上展示(因为:访问网管的机器不一定能访问网管机管理到所有的设备)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180611_3471_x64.exe 版本确认，close处理。
