### ISSUE TITLE
[设备管理]测试192.168.1.2设备时，提示：Winrm参数测试失败！Not Found

### ISSUE THREAD

**Issue by hengwei-test2** [three-plus-three/hw_issues#2018]
1.资源管理下的设备管理，添加192.168.1.2时，点击测试Winrm参数，提示：Winrm参数测试失败！Not Found！

![mwyiw9 x y8a yloxmku 2](https://user-images.githubusercontent.com/37530964/39113066-f61529ce-470c-11e8-8a32-0268053c87a7.png)

**Comment by eeiceyes** [comment]
fixed
