### ISSUE TITLE
[自定义检测告警]Linux版本文件内容告警规则触发失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2021]
1.Linux版本文件内容告警规则触发失败
2.使用测试按钮、提示测试成功。
3.wind版本告警规则触发成功。

![default](https://user-images.githubusercontent.com/28615156/39114871-abccbb38-4712-11e8-9cc3-1e40f0e1576d.png)

![default](https://user-images.githubusercontent.com/28615156/39114906-c33b1f62-4712-11e8-881d-859690a6e3fe.png)

**Comment by runner-mei** [comment]
这个是 权限问题吧
