### ISSUE TITLE
[配置备份]Linux版本snmp参数的配置备份规则触发失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2022]
1.Linux版本snmp参数的配置备份规则触发失败

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180427.1403~accb899.x86_64.rpm   版本确认，还是出现此问题。

![default](https://user-images.githubusercontent.com/28615156/39352087-2e1a2334-4a36-11e8-9234-3874d47e4708.png)

**Comment by runner-mei** [comment]
fixed
