### ISSUE TITLE
[国联期货]当虚拟机过多时、虚拟视图的下拉菜单中的下拉列表显示不完全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2024]
1.当虚拟机过多时、虚拟视图的下拉菜单中的下拉列表显示不完全

![jnm eiu8gz z1vbm r mm1b](https://user-images.githubusercontent.com/28615156/39176772-36c1fa3c-47e0-11e8-939e-b2522afa2eee.png)

**Comment by eeiceyes** [comment]
fixed
