### ISSUE TITLE
[国联期货]当子图或者缩略图名称过长时、拓扑图行切换按钮中下拉选中显示不全

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2025]
1.当子图或者缩略图名称过长时、拓扑图行切换按钮中下拉选中显示不全

![default](https://user-images.githubusercontent.com/28615156/39176887-81706e92-47e0-11e8-8011-9e5ede4035ee.png)

**Comment by eeiceyes** [comment]
fixed
