### ISSUE TITLE
[自定义检测告警]Linux版本路由表检测告警规则提示“处理设备( 958 ) 失败，不能读旧数据”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2026]
1.Linux版本路由表检测告警规则提示“处理设备( 958 ) 失败，不能读旧数据”
2.win版本未出现此问题

Linux版本截图：
![default](https://user-images.githubusercontent.com/28615156/39177490-072ddf82-47e2-11e8-83cd-1d7adb2b9522.png)

win版本截图：
![default](https://user-images.githubusercontent.com/28615156/39177506-1232210e-47e2-11e8-8f72-435d1266b97b.png)

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180508.1426~b67e848.x86_64.rpm    版本确认，还出现此问题

**Comment by runner-mei** [comment]
fixed
