### ISSUE TITLE
[国妇婴]机柜属性视图中、设备图之间的缝隙增大、增加区分度

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2039]
1.机柜属性视图中、设备图之间的缝隙增大、增加区分度

![1524808707 1](https://user-images.githubusercontent.com/28615156/39346954-3039ed1a-4a23-11e8-8183-81d5b52ef421.jpg)

**Comment by eeiceyes** [comment]
增大间隙了

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180522_3244_x64.exe 版本确认，close处理。
