### ISSUE TITLE
[流量分析]实时流量分析的背景加载使用最新的背景图

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2042]
1.实时流量分析的背景加载使用最新的背景图
2.业务流量查看同样出现此问题

![default](https://user-images.githubusercontent.com/28615156/39355704-81bcb56a-4a40-11e8-9966-7b59fbf4b12f.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180516_3211_x64.exe  版本确认，第二点 业务流量查页面未修改

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180530_3273_x64.exe 版本确认，close处理。
