### ISSUE TITLE
[Linux版本更新]更新版本后，无法加载登录页面

### ISSUE THREAD

**Issue by hengwei-test2** [three-plus-three/hw_issues#2047]
[perm-server]2018/05/02 09:42:52 permissions.go:59: [ directory:play.json:/usr/local/tpt/lib/permissions/http/play.json:play_web ] load default fail, 从 HTTP 载入 Permissions 失败: read web in '/usr/local/tpt/lib/permissions/http/play.json:play_web' fail: 502 Bad Gateway

![fkw9 f6whw 9pml 07kx](https://user-images.githubusercontent.com/37530964/39501931-2913e27c-4df0-11e8-898c-8f7235c3dcf8.jpg)

**Comment by eeiceyes** [comment]
fixed
