### ISSUE TITLE
[资产管理]点击“常用功能-已处置的资产”提示“Server Error: 序列化storepageconfig.json失败: invalid argument”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2050]
1.[资产管理]点击“常用功能-已处置的资产”提示“Server Error: 序列化storepageconfig.json失败: invalid argument”
2.维修中的资产、在库存的资产、使用中的资产、已借出的资产、已退役的资产同样出现此问题

![default](https://user-images.githubusercontent.com/28615156/39509087-85d78c12-4e17-11e8-98ed-fd5f74265eeb.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180514.1436~c507e0c.x86_64.rpm    版本确认，close处理。
