### ISSUE TITLE
[资产管理]CMDB配置项类型中、新添加的配置项类型自定义项添加不成功

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2052]
1.CMDB配置项类型中、新添加的配置项类型自定义项添加不成功

![1525311470 1](https://user-images.githubusercontent.com/28615156/39556823-c7025660-4eb5-11e8-91d8-c8034a3d55de.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180514.1436~c507e0c.x86_64.rpm    版本确认，close处理。
