### ISSUE TITLE
[公司] 思科网络设备MEM平均数据值不能与多MEM对应

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#2053]
下图为思科交换机  取到的平均数据值;  该数据不能与多CPU数据相对于(换算)
![image](https://user-images.githubusercontent.com/14171497/39557469-7a45d806-4eba-11e8-800a-1f29e155c454.png)

下图数据为能与设备数据对应
![image](https://user-images.githubusercontent.com/14171497/39557461-5d81ff2e-4eba-11e8-9256-f41a59f86fbf.png)

下面是在设备上查看的数据
![image](https://user-images.githubusercontent.com/14171497/39557383-c1375880-4eb9-11e8-9b58-199d47f2d625.png)

**Comment by runner-mei** [comment]
Total = 55929620+8388608=64318228

Used = 5329804 + 3462196 = 8792000

AVG = 8792000 / 64318228 = 13.66
