### ISSUE TITLE
[资产管理]查看资产页面、点关系图的按钮无效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2054]
1.查看资产页面、点关系图的按钮无效

![1525317371 1](https://user-images.githubusercontent.com/28615156/39558708-768c5290-4ec3-11e8-80ba-a278b2dcdd00.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180514.1436~c507e0c.x86_64.rpm    版本确认，close处理。

-
