### ISSUE TITLE
[敦和资产]增加"示意节点"类型，改类型节点为非授权节点，不计入license

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#2056]
![image](https://user-images.githubusercontent.com/14171518/39686643-d8cb40d8-51fc-11e8-84fb-8548b7b45723.png)

该节点用上述图片进行展示

**Comment by hengweiGR** [comment]
1

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
增加了设备类型`虚拟节点`

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180514.1436~c507e0c.x86_64.rpm    版本确认，close处理。
