### ISSUE TITLE
[报表管理]报表管理下的生成报表查看点击报表浏览的名称跳转页面报错

### ISSUE THREAD

**Issue by hengwei-test2** [three-plus-three/hw_issues#2065]
1.在报表管理下的生成报表查看，点击报表浏览页面的名称，跳转页面报错
![_40z 7pbfbwk _o7dslmkt6](https://user-images.githubusercontent.com/37530964/39857040-8c748522-5464-11e8-9f72-2c3d0ce8af56.png)

![pu 7kn03yi0 6ni_21f w 7](https://user-images.githubusercontent.com/37530964/39857055-9a2192f0-5464-11e8-9128-4fdcbdc7abdd.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
资产报表不在此处查看
