### ISSUE TITLE
[报表管理]报表管理下预置报表查看点击报表浏览页面的名称跳转页面报错

### ISSUE THREAD

**Issue by hengwei-test2** [three-plus-three/hw_issues#2066]
1.在报表管理下的预置报表查看，点击报表浏览页面的名称，跳转页面报错
![a1q mw incbkd6 mr8giw](https://user-images.githubusercontent.com/37530964/39857584-6b38c056-5466-11e8-9a6c-c7b0fa43d2b8.png)
![vh5pjh4 i i1 y bu 2dz5](https://user-images.githubusercontent.com/37530964/39857588-6f6d64a6-5466-11e8-9205-12d896aacba0.png)

**Comment by eeiceyes** [comment]
fixed
