### ISSUE TITLE
[网络视图]网络视图中的同步拓扑布局、选择用户时不显示admin 账号

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2074]
1.网络视图中的同步拓扑布局、选择用户时不显示admin 账号

![default](https://user-images.githubusercontent.com/28615156/39979719-c56e3c9c-577a-11e8-81ad-11dc69f1163c.png)

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180516_3211_x64.exe  版本确认，还出现此问题

1.巡检任务分配是、也无法选择admin用户

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180519_3235_x64   版本确认，close处理。
