### ISSUE TITLE
[资产管理]资产的状态一览众、拖拉图标位置后、刷新页面图标位置不保存

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2077]
1.资产的状态一览众、拖拉图标位置后、刷新页面图标位置不保存

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180516_3211_x64.exe  版本确认，还出现此问题

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180519_3235_x64   版本确认，非admin用户还出现此问题

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180525_3253_x64.exe 版本确认，非admin账号还出现此现象
