### ISSUE TITLE
[实时流量分析]流量分析下实时流量分析页面的右上角的刷新间隔和数据来源的下拉框里看不清字体

### ISSUE THREAD

**Issue by hengwei-test2** [three-plus-three/hw_issues#2078]
1.在流量分析下试试流量分析页面，右上角的刷新间隔和数据来源的下拉框内字体颜色为白色，看不见字体

![9o a zh 15hy mtksx n](https://user-images.githubusercontent.com/37530964/39990888-6295353c-57a0-11e8-9179-91f62166eb3f.jpg)

**Comment by eeiceyes** [comment]
fixed
