### ISSUE TITLE
[主机管理]添加Linux服务器、添加成功后无法获取操作系统类型

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2080]
1.添加Linux服务器、添加成功后无法获取操作系统类型（centos7）
2.刷新设备后、操作系统类型获取成功

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180519_3235_x64   版本确认，close处理。
