### ISSUE TITLE
[运行统计]运行统计页面背景颜色未被加载

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2081]
1.运行统计页面背景颜色未被加载

![default](https://user-images.githubusercontent.com/28615156/40039461-24f9e976-5849-11e8-88c7-b80685cd40f3.png)

**Comment by eeiceyes** [comment]
隐藏该页面

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180524_3251_x64.exe 版本确认，close处理。
