### ISSUE TITLE
[监控总览]当前告警查看面板中、点击查看管理对象运行视图提示“对象不支持运行视图”

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2084]
1当前告警查看面板中、点击查看管理对象运行视图提示“对象不支持运行视图”

![default](https://user-images.githubusercontent.com/28615156/40040345-7e9353a2-584c-11e8-8258-de5d141698ff.png)

![default](https://user-images.githubusercontent.com/28615156/40040353-82494038-584c-11e8-9f9e-b61129e9688a.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180519_3235_x64   版本确认，close处理。
