### ISSUE TITLE
[运行视图]交换机运行视图中、“端口”“Eigrp信息”信息获取不到

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2087]
1交换机运行视图中、“端口”“Eigrp信息”信息获取不到

![default](https://user-images.githubusercontent.com/28615156/40091026-008979c2-58e8-11e8-9052-f1053cee18fd.png)

**Comment by eeiceyes** [comment]
设备不支持时不在显示
fixed
