### ISSUE TITLE
[监控总览]TCP总连接数面板、数据信息获取不到

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2090]
1.TCP总连接数面板、数据信息获取不到

![default](https://user-images.githubusercontent.com/28615156/40093622-a706f448-58f5-11e8-8af0-b6982e414529.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180519_3235_x64   版本确认，close处理。
