### ISSUE TITLE
[徐州市电力公司]机房需求

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#2091]
增加机柜配线管理功能：
![image](https://user-images.githubusercontent.com/14171518/40092960-b2c4a332-58f2-11e8-8c2b-8ee6babe9e00.png)
1、机柜右键添加“配线管理”功能，可以添加、编辑、删除对应的配线信息
本端设备   本端IP（该端口上配置的ip）  本端端口      对端设备（添加跳转到该设备的连接）   对端IP （该端口上配置的ip） 对端端口   

2、编辑机柜添加“模糊查询”功能
![image](https://user-images.githubusercontent.com/14171518/40093689-ee278248-58f5-11e8-8d07-7bf949d23d45.png)

3、对应机柜、机房的配线情况可以拉取一张完整的配线信息表格并可下载

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180522_3244_x64.exe 版本确认，close处理。
