### ISSUE TITLE
[syslog日志分析]日志分析的总览页面、提示“400 : read field dictionary fail,cannot perform operation on empty alias”错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2095]
1.日志分析的总览页面、提示“400 : read field dictionary fail,cannot perform operation on empty alias”错误
2.查看页面也提示“500 : error executing query: cannot perform operation on empty alias”错误

日志总览页面：
![default](https://user-images.githubusercontent.com/28615156/40211008-a6fe81d8-5a7a-11e8-8f38-bda401b29c44.png)

查看页面：

![default](https://user-images.githubusercontent.com/28615156/40211059-eaf1b428-5a7a-11e8-9bd3-19efe4115f66.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180519_3235_x64   版本确认，close处理。
