### ISSUE TITLE
[日志分析]总览、查看、过滤、设置页面的右上角“告警信息”“退回”与其他页面不一致并且点击无效

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2096]
1.总览、查看、过滤、设置页面的右上角“告警信息”“退回”与其他页面不一致并且点击无效

![default](https://user-images.githubusercontent.com/28615156/40211481-8edde71c-5a7d-11e8-9650-39c9389599a7.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180522_3244_x64.exe 版本确认，过滤器和设置页面还是有此问题

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180530_3273_x64.exe 版本确认，close处理。
