### ISSUE TITLE
[日志分析]日志分析查看页面、导出的数据“设备”和“等级”与页面显示不一致

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2099]
1.日志分析查看页面、导出的数据“设备”和“等级”与页面显示不一致

![5z2suhyg5pt2pet0o 4x dn](https://user-images.githubusercontent.com/28615156/40214892-f6956652-5a8f-11e8-9e78-78221afbd2ba.png)

![default](https://user-images.githubusercontent.com/28615156/40214895-fa59229c-5a8f-11e8-966a-566aef68997d.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180519_3235_x64   版本确认，close处理。
