### ISSUE TITLE
[日志分析]总览、查看、过滤、设置页面、点击菜单的缩小再还原菜单后、菜单内容不显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2101]
1.总览、查看、过滤、设置页面、点击菜单的缩小再还原菜单后、菜单内容不显示

![default](https://user-images.githubusercontent.com/28615156/40216049-b54c0e60-5a96-11e8-9c54-581c72e38bec.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180524_3251_x64.exe 版本确认，close处理。
