### ISSUE TITLE
[日志分析]日志查询页面导出后的数据、来自设备和等级显示内容与页面的文字不一致

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2111]
1.日志查询页面导出后的数据、来自设备和等级显示内容与页面的文字不一致

![1526868723 1](https://user-images.githubusercontent.com/28615156/40287377-88abc74c-5cdf-11e8-8eb0-f38718f5d3c2.jpg)

![1526868753 1](https://user-images.githubusercontent.com/28615156/40287378-88efaf52-5cdf-11e8-9dfe-a36d004aca49.jpg)

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180523_3248_x64.exe 版本确认，还出现此问题

![default](https://user-images.githubusercontent.com/28615156/40460545-dd542846-5f39-11e8-910b-caebf67098ec.png)

**Comment by runner-mei** [comment]
fxied
