### ISSUE TITLE
[国联期货]内存统计信息不正确

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#2113]
![image](https://user-images.githubusercontent.com/14171518/40289413-b95a8bfc-5cea-11e8-9460-8895f458a230.png)
linux物理内存已使用值不一致  
将进度条改成百分比形式，展现形式同windows服务器
![image](https://user-images.githubusercontent.com/14171518/40289478-243d49c8-5ceb-11e8-873c-08bb826bd550.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180523_3248_x64.exe 版本确认，close处理。
