### ISSUE TITLE
[敦和]VPN设备支持VPN通道数据查看

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2114]
1.VPN设备支持VPN通道数据查看

数据路径：hw_issues\现场数据\敦煌VPN设备支持VPN通道信息查看

**Comment by runner-mei** [comment]
cikePeerTable 
CikeTunnelTable  

两张表按  cikeTunIndex 字段合并， 
cikePeerTable  为 cikePeerIntIndex
CikeTunnelTable  为 cikeTunIndex

**Comment by eeiceyes** [comment]
{"channel":"cikeTunnelTable/6063/","client_name":"-","client_id":10,"created_at":"2018-05-23T17:32:18.9845568+08:00","value":[{"cikeTunActiveTime":23923440000000,"cikeTunAuthMethod":2,"cikeTunDiffHellmanGrp":3,"cikeTunEncryptAlgo":3,"cikeTunHashAlgo":2,"cikeTunInDropPkts":0,"cikeTunInNotifys":0,"cikeTunInOctets":680,"cikeTunInP2ExchgInvalids":0,"cikeTunInP2ExchgRejects":0,"cikeTunInP2Exchgs":1,"cikeTunInP2SaDelRequests":0,"cikeTunInPkts":2,"cikeTunIndex":"16","cikeTunLifeTime":86400,"cikeTunLocalAddr":"0x655f0506","cikeTunLocalName":"DHSHA-CORE-ISR4331.DunHe.com","cikeTunLocalType":2,"cikeTunLocalValue":"spoke1","cikeTunNegoMode":2,"cikeTunOutDropPkts":0,"cikeTunOutNotifys":0,"cikeTunOutOctets":954,"cikeTunOutP2ExchgInvalids":0,"cikeTunOutP2ExchgRejects":0,"cikeTunOutP2Exchgs":2,"cikeTunOutP2SaDelRequests":0,"cikeTunOutPkts":4,"cikeTunRemoteAddr":"0x7ae0898a","cikeTunRemoteName":"","cikeTunRemoteType":1,"cikeTunRemoteValue":"122.22","cikeTunSaRefreshThreshold":0,"cikeTunStatus":1,"cikeTunTotalRefreshes":0,"key":"16"}],"method_id":"cikeTunnelTable_default","engine_id":0,"representation":"[]network_device_cike_tunnel_table_class","enumeration_context":"16"}

**Comment by eeiceyes** [comment]
cikeTunLocalAddr和cikeTunRemoteAddr的值都不是ip地址

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180524_3251_x64.exe 版本确认，close处理。
