### ISSUE TITLE
[资产管理]CMDB中编辑内建的关系类型、编辑成功后的关系类型在关系类型页面不显示

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2118]
1.CMDB中编辑内建的关系类型、编辑成功后的关系类型在关系类型页面不显示

![1526977924 1](https://user-images.githubusercontent.com/28615156/40350924-bc13bfdc-5ddd-11e8-99f3-6cd4df8cd091.jpg)

**Comment by eeiceyes** [comment]
fixed，内建的关系加上限制，不允许被编辑

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180523_3248_x64.exe 版本确认，close处理。
