### ISSUE TITLE
[天风期货]日志查询中 来源设备修改成来源类型

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#2126]
日志查询中 **来源设备**字段修改成**来源类型**

![image](https://user-images.githubusercontent.com/14171497/40635561-29bcbda0-632d-11e8-9620-362e77a856dc.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180530_3273_x64.exe 版本确认，close处理。
