### ISSUE TITLE
[天风期货]日志分析中  添加过滤条件 出错

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#2127]
日志分析中  添加过滤条件 出错 报错信息如下:

template: filters/edit_fields.html:81:41: executing "filters/edit_fields.html" at <index $facility.valu...>: error calling index: index of untyped nil

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180530_3273_x64.exe 版本确认，close处理。
