### ISSUE TITLE
[天风期货]日志分析中日志查看,快速查询条件 来源设备字段修改

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#2128]
[天风期货]日志分析中日志查看,快速查询条件 来源设备字段修改 来源类型
![image](https://user-images.githubusercontent.com/14171497/40635694-d53394ce-632d-11e8-95aa-7b256a955048.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180530_3273_x64.exe 版本确认，close处理。
