### ISSUE TITLE
[巡检任务管理]点击添加按钮，添加计划窗口适配有问题

### ISSUE THREAD

**Issue by hengwei-test2** [three-plus-three/hw_issues#2129]
1.在运维管理-巡检任务管理-点击添加，在分配巡检任务的巡检方式模块下点击添加按钮，弹出的“添加计划”窗口，窗口适配有问题

![l9ieeajut plfnoi6q d a](https://user-images.githubusercontent.com/37530964/40711435-bc696c56-642d-11e8-82ef-e4e85196c79a.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180611_3471_x64.exe 版本确认，close处理。
