### ISSUE TITLE
[Snmp参数]在Snmp参数读参数为密码形式显示，数据库中存储的方式为明文，未加密

### ISSUE THREAD

**Issue by hengwei-test2** [three-plus-three/hw_issues#2130]
在Snmp参数读参数为密码形式显示，在数据库中存储方式为明文，未加密
![ey6l uc5tu7dn zi qai6](https://user-images.githubusercontent.com/37530964/40713746-45e22be4-6433-11e8-9875-24d0fdea4ede.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180611_3471_x64.exe 版本确认，close处理。
