### ISSUE TITLE
[资产管理]资产查看页面通过“操作”按钮、修改资产状态、修改成功后不记录审计日志

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2136]
1.资产查看页面通过“操作”按钮、修改资产状态、修改成功后不记录审计日志

![1527753607](https://user-images.githubusercontent.com/28615156/40770002-0b04f2cc-64ec-11e8-94df-6d100670f0f8.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180611_3471_x64.exe 版本确认，close处理。
