### ISSUE TITLE
[资产管理]资产查看页面、资产状态不同的资产信息、全选情况下可以进行所有的资产关联操作

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2137]
1.资产查看页面、资产状态不同的资产信息、全选情况下可以进行所有的资产关联操作

![1527754443](https://user-images.githubusercontent.com/28615156/40770615-cd90dc74-64ed-11e8-8abb-7796769d79b5.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180611_3471_x64.exe 版本确认，close处理。
