### ISSUE TITLE
[资产管理]名称相同的资产状态关联能够被添加

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2139]
1.名称相同的资产状态关联能够被添加

![1527756886 1](https://user-images.githubusercontent.com/28615156/40772965-0ae08542-64f4-11e8-9660-fb2ade67cd13.jpg)

**Comment by eeiceyes** [comment]
加了约束，是名称，源状态，目标状态三个字段作为联合key

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180605_3458_x64.exe 版本确认，还是有问题。

![default](https://user-images.githubusercontent.com/28615156/41010760-071163d8-696c-11e8-9ee4-64d2a6dfc435.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180611_3471_x64.exe 版本确认，close处理。
