### ISSUE TITLE
[业务流量查看]数据来源IP地址、名称、升序、刷新时间的字体与背景同色

### ISSUE THREAD

**Issue by hengwei-test2** [three-plus-three/hw_issues#2141]
1.业务流量查看数据来源的IP地址、名称、升序、刷新时间的字体和背景颜色相同，字体有些模糊，看不清楚
![mbk rp5h5sifc 5 p t 4](https://user-images.githubusercontent.com/37530964/40956166-6a3107ee-68c1-11e8-84ca-c693b630878a.png)
![r3 __ 9e j t ho0nm417](https://user-images.githubusercontent.com/37530964/40956171-6f37c354-68c1-11e8-9c8e-3371d46c248c.png)

**Comment by eeiceyes** [comment]
fixed
