### ISSUE TITLE
[常用工具]打开Telnet\ssh测试工具提示、提示错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2143]
1.打开Telnet\ssh测试工具提示、提示错误
2.左边常用工具和选择设备右击常用工具同样出现此问题。

![default](https://user-images.githubusercontent.com/28615156/41011777-016ece84-6971-11e8-95bd-b79476709997.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180531_3278_x64.exe 版本确认，close处理。
