### ISSUE TITLE
[监控总览]监控总览当前告警面板中确认告警通知、提示确认失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2146]
1.监控总览当前告警面板中确认告警通知、提示确认失败

![default](https://user-images.githubusercontent.com/28615156/41017851-7c45755a-6989-11e8-9002-a9d302071da9.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180611_3471_x64.exe 版本确认，哈出现此问题。

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180709_3540_x64.exe版本确认，close处理。
