### ISSUE TITLE
[华夏银行]华夏银行需求整理

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#2147]
1、线路多折的实现
    2、根图线路流动效果的实现
    3、根图局部线路发现功能（根图框选设备进行局部线路搜索）
    4、根图、业务视图填充区块的编辑功能（类似于word中添加可填充颜色、可编辑文字的方块图形，置于根图或业务视图的最底层）
    5、线路属性中资产标签的添加功能（类似设备属性页面中的维护信息）
    6、业务视图真实设备之间添加实体线路的筛选功能（框选两台真实设备选择添加实体线路，出现线路为这两台设备之间的真实线路而非所有线路，线路的添加支持多选）

**Comment by eeiceyes** [comment]
1，线路多折已完成

**Comment by eeiceyes** [comment]
2，根图的线路流动也已经支持

**Comment by eeiceyes** [comment]
第4点已经完成

**Comment by eeiceyes** [comment]
第6点已经完成
