### ISSUE TITLE
[运维管理]巡检点的添加巡检项窗口格式出现排序错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2148]
1.巡检点的添加巡检项窗口格式出现排序错误

![default](https://user-images.githubusercontent.com/28615156/41018870-a6339770-698e-11e8-9690-899dc42be55a.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180611_3471_x64.exe 版本确认，close处理。
