### ISSUE TITLE
[IT资产管理]点击综合运维中心，点击IT资产管理，页面弹框：“加载失败！”

### ISSUE THREAD

**Issue by hengwei-test2** [three-plus-three/hw_issues#2150]
1.点击综合运维中心，点击IT资产管理，页面弹框：“加载失败！”

![sj px__af5 h z5e oxv t](https://user-images.githubusercontent.com/37530964/41022582-979a91f6-699c-11e8-9a80-407fd7a83556.png)

**Comment by eeiceyes** [comment]
fixed
