### ISSUE TITLE
[IT资产管理]资产管理的所有模块，点击刷新，页面显示没有权限

### ISSUE THREAD

**Issue by hengwei-test2** [three-plus-three/hw_issues#2151]
1.点击资产管理的所有模块，点击刷新，页面显示没有权限
![sh 9 ztjje66oejhwy ct9](https://user-images.githubusercontent.com/37530964/41023013-c4a8c9b4-699d-11e8-9e2a-80233ac66925.jpg)

**Comment by eeiceyes** [comment]
fixed
