### ISSUE TITLE
[网络视图]主机旧数据的设备属性页面、点击确认按钮后、查看snmp的参数未进行加密

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2153]
1.主机旧数据的设备属性页面、点击确认按钮后、查看snmp的参数未进行加密

![default](https://user-images.githubusercontent.com/28615156/41075901-6f34fbde-6a41-11e8-8e3b-c8b1ca79ae99.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180611_3471_x64.exe 版本确认，close处理。
