### ISSUE TITLE
[常用工具]加密都的SNMP参数使用snmp测试提示测试失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2155]
1.加密都的SNMP参数使用snmp测试提示测试失败

![default](https://user-images.githubusercontent.com/28615156/41078827-978fa470-6a51-11e8-8fb6-369d2d04aec2.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180611_3471_x64.exe 版本确认，close处理。
