### ISSUE TITLE
[资源管理]数据库管理、中间管理、标准应用管理添加的密码未进行加密

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2156]
1.数据库管理、中间管理、标准应用管理添加的密码未进行加密
2.添加的虚拟中心的密码为进行加密
3.系统设置中邮件服务器、企业微信设置，FTP服务的密码未进行加密

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180611_3471_x64.exe 版本确认，close处理。
