### ISSUE TITLE
[配置备份]网络设备使用telnet访问参数的配置备份提示失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2157]
1.网络设备使用telnet访问参数的配置备份提示失败

![default](https://user-images.githubusercontent.com/28615156/41087833-57e86b26-6a70-11e8-9803-95cb3a0e7f66.png)

**Comment by runner-mei** [comment]
fixed

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180531_3278_x64.exe 版本确认，close处理。
