### ISSUE TITLE
[国妇婴]网络视图上设备显示的名称字体太小、在大屏中显示不清楚

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2163]
1.网络视图上设备显示的名称字体太小、在大屏中显示不清楚

![802520854089601397](https://user-images.githubusercontent.com/28615156/41327376-d1713188-6ef5-11e8-998f-5580abcf98a0.jpg)

**Comment by eeiceyes** [comment]
增加了配置topology.font.size=12
可以修改配置项来设定拓扑图上字体的大小
