### ISSUE TITLE
[日志分析]日志分析设置中、设置日志的保留时间后、提示需要重启服务

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2165]
1.日志分析设置中、设置日志的保留时间后、提示需要重启服务
2.修改成不需要手动重启服务

**Comment by runner-mei** [comment]
fixed,  加了一个重启的按钮

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180615_3482_x64.exe 版本确认，close处理。
