### ISSUE TITLE
[网络视图]在网络视图页面中，当前告警显示为零，但是点击进入这个窗口后显示告警数据

### ISSUE THREAD

**Issue by hengwei-test2** [three-plus-three/hw_issues#2166]
1.在网络视图页面，右上角的告警规则显示为零，但是点击进入这个窗口后显示告警数据为零
![35 0q 73ruo b5t 1 81l b](https://user-images.githubusercontent.com/37530964/41327536-76ae496a-6ef6-11e8-9152-ebfabd94951d.png)
![k5k kt vfzhm6n 7 r03](https://user-images.githubusercontent.com/37530964/41327541-7997eadc-6ef6-11e8-9053-8c3d223e47ff.png)

**Comment by eeiceyes** [comment]
fixed
