### ISSUE TITLE
[日志分析]“所有主机数据保留,否则只保留下表中的主机发送的数据”不选择、主机设置规则添加、不是主机设置的IP地址的sylog也能接收保存

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2167]
1.“所有主机数据保留,否则只保留下表中的主机发送的数据”不选择、主机设置规则添加、不是主机设置的IP地址的sylog也能接收保存

![4 3x 27o3tlc3 gf0safnkj](https://user-images.githubusercontent.com/28615156/41329119-5d682432-6efe-11e8-8e84-48cdad18ddd5.png)

![y6 lkoebk7gw91looz 9c47](https://user-images.githubusercontent.com/28615156/41329121-5dbaa964-6efe-11e8-9261-4178b3aa8683.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180615_3482_x64.exe 版本确认，还是出现此问题。

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180615_3482_x64.exe 版本确认，close处理。
