### ISSUE TITLE
[配置备份]snmp访问参数的交换机配置备份提示、规则触发失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2168]
1.snmp访问参数的交换机配置备份提示、规则触发失败

![default](https://user-images.githubusercontent.com/28615156/41335267-cdb85c90-6f1a-11e8-95c3-18673e42c019.png)

**Comment by runner-mei** [comment]
写共同体名配了么？

**Comment by hengwei-test** [comment]
snmp配置读写都配置了
![default](https://user-images.githubusercontent.com/28615156/41451118-f6f74e52-709d-11e8-8059-90b614b22c79.png)
