### ISSUE TITLE
[告警管理]新建告警规则服务器磁盘卷的参数，修改失败

### ISSUE THREAD

**Issue by hengwei-test2** [three-plus-three/hw_issues#2174]
1.在告警管理下新建告警规则服务器磁盘卷后修改参数失败
![p 4wsfbz l q3 y6 p0e](https://user-images.githubusercontent.com/37530964/41636516-95a0964e-7481-11e8-95a1-506ea1c1e89b.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180629_3503_x64.exe 版本确认，close处理。
