### ISSUE TITLE
[优克联项]支持联想服务器带外IPMI取数（急）

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2180]
1.支持联想服务器带外IPMI取数
2.急 周一需要发给客户

![e6umwj3m75 4y cmigoky1](https://user-images.githubusercontent.com/28615156/41765765-a21d8262-7637-11e8-81d2-92ba41286cbd.png)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180629_3503_x64.exe 版本确认，加密还是有问题。

**Comment by runner-mei** [comment]
fixed
