### ISSUE TITLE
中间件巡检指标项目添加

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#219]
数据库：oracle
中间件巡检指标
weblogic、tomcat、
![image](https://cloud.githubusercontent.com/assets/14171497/14381368/6f8c38ba-fdb8-11e5-8d94-3bd8f91f501d.png)

**Comment by Cuic** [comment]
weblogic的堆使用比例需要使用百分百

**Comment by runner-mei** [comment]
fix?
