### ISSUE TITLE
[运行视图]交换机运行视图中、交换机温度信息显示不对

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2192]
1.交换机运行视图中、交换机温度信息显示不对

![cache_-3b2005dc396d0c8d](https://user-images.githubusercontent.com/28615156/41947475-5a720eae-79ea-11e8-839a-f0c906f91715.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180629_3503_x64.exe 版本确认，close处理。
