### ISSUE TITLE
[运行视图]点击设备的运行视图提示SQL错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2194]
1.点击设备的运行视图提示SQL错误

![default](https://user-images.githubusercontent.com/28615156/41947966-2e17e876-79ed-11e8-8105-53ca3aae5608.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180629_3503_x64.exe 版本确认，close处理。
