### ISSUE TITLE
[网络视图]多折线路发生告警时、线路的告警气泡位置发生偏移

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2195]
1.多折线路发生告警时、线路的告警气泡位置发生偏移

![default](https://user-images.githubusercontent.com/28615156/42013040-e8c76d96-7acd-11e8-92b0-09ba8c8275f0.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180629_3503_x64.exe 版本确认，close处理。
