### ISSUE TITLE
[告警管理]日志告警规则页面提示内部错误

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2196]
1.日志告警规则页面提示内部错误

![default](https://user-images.githubusercontent.com/28615156/42014460-0d9e1460-7ad5-11e8-9a46-4a4fc474fcad.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180629_3503_x64.exe 版本确认，close处理。
