### ISSUE TITLE
[日志分析]日志分析进程一直在重启

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2197]
1.日志分析进程一直在重启

[loganalyzer.txt](https://github.com/three-plus-three/hw_issues/files/2144490/loganalyzer.txt)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.2.20180629_3503_x64.exe 版本确认，close处理。
