### ISSUE TITLE
[通知方式]添加邮件通知方式测试提示失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2204]
1.添加邮件通知方式测试提示失败

![default](https://user-images.githubusercontent.com/28615156/42207148-c674486a-7edb-11e8-8bab-30cd58e1f49c.png)

**Comment by runner-mei** [comment]
你看看是不是被认为是垃圾邮件了

**Comment by hengwei-test** [comment]
不是垃圾邮件、邮件服务器配置 smtp.163.com zhz9561847865@163.com  hao19950224..  我登入这个邮箱发送邮件是没有问题的。
