### ISSUE TITLE
[数据库管理]数据库管理页面、鼠标放在“已设置告警”上面提示的信息不对

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2209]
1.数据库管理页面、鼠标放在“已设置告警”上面提示的信息不对
2.中间件管理、标准应用管理同样出现此问题

![default](https://user-images.githubusercontent.com/28615156/42298321-db9080b2-8037-11e8-9005-0ed53700bd40.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20180709_904_x64.exe 版本确认，close处理。
