### ISSUE TITLE
[配置备份]snmp访问参数的配置备份规则、规则触发失败

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#2210]
snmp访问参数的配置备份规则、规则触发失败
2.3错误：
![default](https://user-images.githubusercontent.com/28615156/42303284-d0b5c88a-8052-11e8-804f-a435fe575e4c.png)

3.2错误：
![default](https://user-images.githubusercontent.com/28615156/42303395-9d50fb58-8053-11e8-8b6a-c381ff755fa5.png)

**Comment by runner-mei** [comment]
fixed
