### ISSUE TITLE
短信通知方式中测试：短信已经正常发出 界面报出错误

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#223]
![qq 20160411153518](https://cloud.githubusercontent.com/assets/14171497/14420667/ee06a5d8-ffff-11e5-9c49-8f8ccd9142cc.png)

[logs.zip](https://github.com/three-plus-three/hw_issues/files/212536/logs.zip)

**Comment by runner-mei** [comment]
这确实出错了，是不是别的发送的，或者偶然的？

**Comment by Cuic** [comment]
不是个别发送的，是我特意测试发的

**Comment by runner-mei** [comment]
启后 sms 服务后，已解决了吧
