### ISSUE TITLE
访问DHCP服务失败

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#226]
运行视图正常
![image](https://cloud.githubusercontent.com/assets/14171497/14453471/ab49150a-00c7-11e6-9388-cd4389864b37.png)
出现告警
![image](https://cloud.githubusercontent.com/assets/14171497/14453673/ca05b880-00c8-11e6-9108-296186d681e6.png)

**Comment by runner-mei** [comment]
已修复

**Comment by Cuic** [comment]
http://192.168.1.143:37072/std_services/38255/status
返回结果如下：
{"channel":"","request_id":0,"created_at":"2016-05-04T17:55:11.7566+08:00","value":{"error":"internal error.","status":0},"method_id":"dhcp_status_default_for_service","engine_id":0}

**Comment by Cuic** [comment]
http://192.168.1.143:37072/std_services/38255/status
返回结果如下：
{"channel":"","request_id":0,"created_at":"2016-05-04T17:55:11.7566+08:00","value":{"error":"internal error.","status":0},"method_id":"dhcp_status_default_for_service","engine_id":0}

**Comment by runner-mei** [comment]
fix?
