### ISSUE TITLE
数据库巡检不能指定参数键入值

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#228]
![image](https://cloud.githubusercontent.com/assets/14171497/14454364/bd8d31a6-00cc-11e6-96b3-58e23df0dad6.png)

**Comment by Cuic** [comment]
![image](https://cloud.githubusercontent.com/assets/14171497/14454595/f820e316-00cd-11e6-93c9-2404d5d2e4e1.png)

**Comment by eeiceyes** [comment]
fixed
