### ISSUE TITLE
巡检分配任务时 添加季度巡检

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#233]

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，还是未添加季度巡检
![1-1](https://user-images.githubusercontent.com/28615156/30728343-d1c5eb60-9f89-11e7-9f67-d811df611fb0.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
