### ISSUE TITLE
[Tomcat] 可用连接数

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#249]
tomcat 可用连接数 > 10 (正常阀值)

**Comment by runner-mei** [comment]
tomcat  的连接数 在 applications 指标中

注意， tomcat 的管理默认是开启的，但是需要修改权限，打开 tomcat 安装目录下 conf\tomcat-users.xml 文件，



<user username="monitor" password="111111" roles="manager-gui,manager-status"/>  

最后，重启一下，访问一下 http://xxxxx/manager/status, 能成功访问就表示配好了。

参考 http://tomcat.apache.org/tomcat-8.0-doc/manager-howto.html
