### ISSUE TITLE
[weblogic] 日志关键字巡检

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#251]
weblog 日志文件中包含关键字error、fail的字段则为异常。

**Comment by runner-mei** [comment]
我们需要访问日志文件有两种方式
1. 用户可将日志文件共享出来， 如windows共享，http, ftp 等
2. 安装代理

**Comment by runner-mei** [comment]
增加了一个执行 ssh 命令的功能来解决这个问题， 相关问题 #315

**Comment by eeiceyes** [comment]
fixed,指标是`执行远程命令`

**Comment by hengwei-test** [comment]
华东电网暂不用、有事找崔业超
