### ISSUE TITLE
[Oracle] 数据库状态

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#252]
oracle 数据库状态  "OK为正常阀值"

**Comment by runner-mei** [comment]
执行一条 sql 看成不成功么， 指标 db_response_time

**Comment by Cuic** [comment]
数据库响应时间指标数据有误，如下图：

![image](https://cloud.githubusercontent.com/assets/14171497/15011294/9f8dd1ca-1223-11e6-87d2-e30b8c5d5e95.png)

**Comment by eeiceyes** [comment]
fixed
