### ISSUE TITLE
[Oracle]　日志文件关键字检查

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#258]
ｏｒａｃｌｅ　日志文件中包含关键字ora- / error /fail “为异常”

**Comment by runner-mei** [comment]
我们需要访问日志文件有两种方式
1. 用户可将日志文件共享出来， 如windows共享，http, ftp 等
2. 安装代理

请问用户是否同意。或者用户有什么好建议

**Comment by Cuic** [comment]
@runner-mei 
日志在Linux系统上，用户提供SSH方式连接

**Comment by eeiceyes** [comment]
fixed，巡检已经支持，参照指标执行远程命令

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20180202_717_x64.exe 版本确认，close处理。
