### ISSUE TITLE
[Oracle] 数据库文件是否 online

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#259]
oracle 数据库文件是否 online  "online 为正常阈值"

**Comment by runner-mei** [comment]
这个是不是可以用 类似自定义检测 sql 语句来实现

**Comment by Cuic** [comment]
是否可以使用SQL语句实现？ 如果能实现则语句为？

**Comment by runner-mei** [comment]
http://www.2cto.com/database/201503/381089.html

**Comment by Cuic** [comment]
http://blog.itpub.net/29785807/viewspace-1415296/

**Comment by eeiceyes** [comment]
fixed
