### ISSUE TITLE
数据库通知方式改成非ODBC方式

### ISSUE THREAD

**Issue by eeiceyes** [three-plus-three/hw_issues#26]

**Comment by runner-mei** [comment]
后台已修复，需要前台在帮助中加入描述说明
gdbc:address=192.168.1.6:1521;schema=xe;user=system;password=123456
各数据库的驱动名为
oracle_thin
sqlserver
db2
sybase_jtds

**Comment by runner-mei** [comment]
如果 sql 语句为多条时， 系统将自动按分成多条语句执行，语句的分隔规则时，当遇到行尾以 ; 作为结束时认为一条语句结束。

**Comment by eeiceyes** [comment]
已修复，请验证

**Comment by hengweiGR** [comment]
![image](https://cloud.githubusercontent.com/assets/14171518/11675925/cf647bb2-9e68-11e5-9f77-94bf4f2e334a.png)

**Comment by runner-mei** [comment]
这个问题解决了么？
