### ISSUE TITLE
[Oracle] 表空间状态 

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#260]
oracle  表空间状态  "online为正常阈值'

**Comment by runner-mei** [comment]
这个是不是可以用 类似自定义检测 sql 语句来实现

**Comment by Cuic** [comment]
这条指标是否有SQL语句？

**Comment by runner-mei** [comment]
http://www.2cto.com/database/201503/381089.html

**Comment by Cuic** [comment]
http://database.51cto.com/art/200910/158937.htm

**Comment by eeiceyes** [comment]
fixed
