### ISSUE TITLE
[Oracle] 归档日志表空间使用率 

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#261]
oracle 归档 日志 表空间 使用率

**Comment by runner-mei** [comment]
可以用 #294 的  sql 执行功能来解决 

http://www.2cto.com/database/201203/124510.html

select * from V$FLASH_RECOVERY_AREA_USAGE where FILE_TYPE =  'ARCHIVELOG';

**Comment by eeiceyes** [comment]
261已经解决
