### ISSUE TITLE
snmp获取不到监控数据

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#277]
获取不到数据列表如下：
**HP VC Flex-10/10D**
10.104.4.232
10.104.4.231
**ProCurve 6120G/XG Blade Switch**
10.104.0.168
10.104.0.167

**EMC-DS-300B**
10.104.4.56
**EMC DS-300B光纤交换机**
10.104.4.55
**Access Gateway暂时不确定**
10.104.4.233
10.104.4.234
**华为赛门铁克**
10.104.0.49
**eNSP V100R002 华为的模拟器**
10.104.0.38
10.104.0.32

10.104.4.64

**华为存储ISM模拟器**
10.104.0.30
10.104.0.28
10.104.0.48
[walk_results.zip](https://github.com/three-plus-three/hw_issues/files/225585/walk_results.zip)

**Comment by runner-mei** [comment]
请按厂商分一下类

**Comment by runner-mei** [comment]
请按厂商分一下类， 一个厂商一个 BUG
