### ISSUE TITLE
国联安基金的日志告警

### ISSUE THREAD

**Issue by eeiceyes** [three-plus-three/hw_issues#28]
1，检测时间，每天20点以后
2，文件名对应当天日期（只在交易日期进行检测）
3，锁定记录行瞐依据（当前日期瞐下一交易日，参照证交所的交易日期时间表）
4，文件不存在时是否告警选项
5, 告警内容是no value ?
6, 每一行满足条件的文本都会触发告警 ?
7, 关键字，日期+成功与否

**Comment by runner-mei** [comment]
5, 告警内容是no value ?
已解瘊

**Comment by runner-mei** [comment]
已解决？
