### ISSUE TITLE
[华东电力] 思科交换机端口没有流量

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#282]
描述：此设备是一台思科的交换机，设备能获取CPU、内存、端口描述等信息数据都能获取到，端口流量获取不到数据值。
设备厂商型号： Cisco   C3750E

注：有多台设备是这种情况，我walk一台设备的数据
walk 数据：“10.128.0.2.txt”
[10.128.0.2.txt](https://github.com/three-plus-three/hw_issues/files/227243/10.128.0.2.txt)

**Comment by runner-mei** [comment]
请确认是不是 snmp 版本设成 v2 了

**Comment by Cuic** [comment]
SNMP版本改成V2后问题解决
