### ISSUE TITLE
[华东电力] Linux 获取不到CPU、内存数据

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#283]
获取方式：SNMP （通）

系统：识别为 "其它Linux"

[10.128.4.151.txt](https://github.com/three-plus-three/hw_issues/files/227268/10.128.4.151.txt)
[10.128.4.150.txt](https://github.com/three-plus-three/hw_issues/files/227269/10.128.4.150.txt)

**Comment by runner-mei** [comment]
请说明，这是什么设备，如果是主机的话，是什么操作系统

**Comment by Cuic** [comment]
1.这是一个国外厂商的设备：NetScaler 
2.用于citrix
3.附件是walk的数据

**Comment by runner-mei** [comment]
已支持

**Comment by Cuic** [comment]
此设备依然获取不到数据
使用URL获取CPI内存数据结果如下：
results is empty.

但是sys数据可以获取：

{"channel":"","request_id":0,"created_at":"2016-05-18T13:13:51.7906229+08:00","value":{"catalog":0,"contact":"WebMaster (default)","descr":"NetScaler NS9.3: Build 56.5.nc, Date: May  1 2012, 09:53:56  ","location":"POP (default)","name":"NetScaler","oid":"1.3.6.1.4.1.5951.1","services":72,"uptime":5750533},"method_id":"sys_default","engine_id":0}

系统OID:1.3.6.1.4.1.5951.1
说明：设备属性中显示或者不显示"系统OID"时都不能获取CPU、内存信息（URL获取方式）。

**Comment by runner-mei** [comment]
我试了一下可以的

**Comment by Cuic** [comment]
此系统CPU 内存已经获取到！目前此系统暂时获取CPU内存信息。

**Comment by runner-mei** [comment]
什么意思？

**Comment by runner-mei** [comment]
什么意思？
