### ISSUE TITLE
[巡检功能] 数据库巡检表空间在weblogic巡检指标中重现

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#285]
描述：巡检点上打开数据库表空间后再weblogic巡检点上打开所有数据指标时显示为"数据库表空间"。

结果：在公司环境内测试没有重新此问题

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170927_2780_x64      版本确认，close处理。
