### ISSUE TITLE
[巡检功能] 巡检报表

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#292]
用意:此报表功能以图表形式展示给领导查看！（领导账号登录进去就显示此报表）
可查看统计：巡检任务量、已经巡检量、未巡检量、巡检异常量、已经处理的量、未处理的量；
1.统计总的任务量
2.统计巡检人任务量
3.统计异常量
4.统计系统量

注意：客户要求要使用柱状图、饼图...进行展示

**Comment by eeiceyes** [comment]
fixed
