### ISSUE TITLE
[巡检功能] 巡检界面上很多巡检项用 指标来实现是不好的，但是用类似于 自定义检测告警一样的东西很适合，我在后台实现了一个 json api 

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#294]
巡检界面上很多巡检项用 指标来实现是不好的，但是用类似于 自定义检测告警一样的东西很适合，我在后台实现了一个 json api 的 url 为 ：

POST http://127.0.0.1:8080/hengwei/mc/custom_check

数据结构和自定义检测告警的完全一样，将数据作为 POST 的内容就行了

你实现一个前台吧

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20180202_717_x64.exe 版本确认，close处理。
