### ISSUE TITLE
（南华期货）告警阀值与告警内容中的单位不一致

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#297]
![qq 20160427113241](https://cloud.githubusercontent.com/assets/14171518/14840958/bdb13df8-0c6b-11e6-8904-83f52e12adba.jpg)
![qq 20160427113314](https://cloud.githubusercontent.com/assets/14171518/14840967/d27bb614-0c6b-11e6-9eb4-9ee668d1779f.jpg)

**Comment by runner-mei** [comment]
这个有必要一致么？
