### ISSUE TITLE
记录数据分析-记录指标为“全部指标”时 默认不显示任何查询指标

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#298]
描述：在<记录数据分析>如果记录指标为：“全部指标”记录规则不能查询任何设备的记录指标。
![image](https://cloud.githubusercontent.com/assets/14171497/14907312/7afdd1d0-0df9-11e6-80f2-f2040b07b307.png)

**Comment by eeiceyes** [comment]
记录分析的时候，去掉全部，没有意义
