### ISSUE TITLE
[镇江农商行] Eigrp路由协议监控告警功能

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#301]
描述：Eigrp是思科私有协议（网关路由协议），运行EIGRP的路由器存储了邻居的路由表；

功能要求：监控获取查看eigrp表，指定某条邻居的路由表如果没有则告警通知！

参考链接：http://blog.sina.com.cn/s/blog_995092640101aw5w.html

事件级别：镇江农商行比较关心此功能支持，目前在测试期间（高）

**Comment by runner-mei** [comment]
表  cEigrpPeerTable 已增加，增加右键菜单

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
运转图上加了该表数据的查看
