### ISSUE TITLE
添加巡检点->线路的bfd、ospf定义中增加in，后面下拉框为多选

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#302]

**Comment by hengweiGR** [comment]
![image](https://cloud.githubusercontent.com/assets/14171518/14907958/28fa4f04-0e02-11e6-84cd-ca6f14ad9d17.png)

![image](https://cloud.githubusercontent.com/assets/14171518/14907949/0f799e22-0e02-11e6-9be1-0f2add70503b.png)

**Comment by eeiceyes** [comment]
fixed
