### ISSUE TITLE
[功能增强] 用 Postgresql 数据库替换 elastcisearch 后端

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#305]
现有的 syslog 和 snmptrap 只能用于记录网络设备的日志，量并不大（当然也不期望它有多大），用  elastcisearch 作为 syslog (snmp trap) 后端, 有点笨重且不稳定（我们没有精力花时间在这个上面），postgresql 的全文检索也能满足我们，因此想用postgresql 替换 elastcisearch。

如果用户的日志量很大时，我们应该专门开发一个日志管理系统，挑一个开源的本地化一下就行了（如 Graylog2 或 logstat）。

此功能依赖于 #304

**Comment by runner-mei** [comment]
后台已完成，需要前台改进一下，在 windows 的系统环境变量中加上下面一行将改成用 postgresql,
set es_dbstore_experimental=true

朱韩群，你有空做一下

**Comment by eeiceyes** [comment]
fixed
