### ISSUE TITLE
[巡检功能] 巡检日期区间功能

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#313]
巡检描述：
1.分配巡检任务 指定日期区间进行巡检。如：周巡检，周一到周五期间都可以巡检（巡检一次）
2.巡检人可以多选（可一次性添加多个巡检人）

![image](https://cloud.githubusercontent.com/assets/14171497/14978239/fc6b1826-114c-11e6-88eb-f2ef709194fb.png)

3.运维部有每小时巡检（从早上6点到晚上22点 每一个小时巡检一次），现在使用巡检方法是每小时有一个巡检任务，这样导致巡检任务比较多，能否创建一个巡检任务，进行每小时轮询巡检！
下图为现在每小时的巡检任务
![image](https://cloud.githubusercontent.com/assets/14171497/14978940/d82d25b2-1151-11e6-9646-839cee631548.png)

**Comment by eeiceyes** [comment]
fixed
