### ISSUE TITLE
HIMP平台界面登录密码reset

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#319]
**描述**：
如果客户将平台admin修改后的密码忘记了，如果进行reset初始账号密码？（我们自己知道如何从数据库中查看，但是不能告诉客户方法）
建议咱们做一个reset密码的工具“方法”
@eeiceyes 请您写一条reset密码的语句，然后将此case指给老梅

**Comment by eeiceyes** [comment]
update tpt_users set password ='aaa111' where name='admin';

**Comment by runner-mei** [comment]
已增加
