### ISSUE TITLE
[巡检功能] tomcat 巡检指标报错

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#321]
![image](https://cloud.githubusercontent.com/assets/14171497/15037513/840b525a-12ce-11e6-91d6-b4e4329ea5b9.png)

![image](https://cloud.githubusercontent.com/assets/14171497/15037527/a02b59e4-12ce-11e6-817a-33a98ca4b31b.png)

![image](https://cloud.githubusercontent.com/assets/14171497/15037540/b90411fe-12ce-11e6-95d2-78857e9e4d56.png)

![image](https://cloud.githubusercontent.com/assets/14171497/15037554/c91ceebc-12ce-11e6-8eb9-400321536426.png)

**Comment by eeiceyes** [comment]
fixed
