### ISSUE TITLE
[指标参数-bug] tomcat监控告警指标：wbem_exec与info指标都只有value值。

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#326]
描述：
tomcat监控告警指标：wbem_exec与info指标都只有value值。
![image](https://cloud.githubusercontent.com/assets/14171497/15243177/a6672d74-192c-11e6-96c2-cdc8df52df24.png)

**Comment by runner-mei** [comment]
我没有理解这有什么问题？
