### ISSUE TITLE
[交通大学] [VPN] l2vpn拓补生成界面的 api

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#335]
访问参数中加一个  is_l2vpn_search = true 表示为 l2vpn 生成

	// GET /{id}/result/l2vpn                               获取l2vpn业务网的名称列表
	// GET /{id}/result/l2vpn/{vpn}/links/count    获取l2vpn业务网的中的链路数目
	// GET /{id}/result/l2vpn/{vpn}/links/{index}  获取l2vpn业务网的中的链路数据

**Comment by eeiceyes** [comment]
fixed
