### ISSUE TITLE
[华东电网] 任务异常一览中巡检点过滤查询不生效

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#345]
描述：
1.任务异常一览中 使用“巡检点”指定某个巡检点查询出来的结果包含其他巡检点。

2.任务异常一览中的“时间查询"做成时间范围查询。

3.确认 已过期的任务时添加一个全选的按钮。

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
fixed
