### ISSUE TITLE
[华东电网] IBM-AIX取数问题

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#359]
**描述：**
系统：IBM-AIX
取数方式：SSH
问题：虚拟内存取不到数据、CPU取不到数据
**http://127.0.0.1:37072/objects_managed/4466/swaps**
internal error:
    swaps_linux: Process exited with: 2. Reason was:  ()
    swaps_by_snmp: 'snmp' is required.
    swaps_by_ssh: Process exited with: 1. Reason was:  ()

**http://127.0.0.1:37072/objects_managed/4466/cpu**
internal error:
    cpu_for_aix_by_sar: failed to parse '
AIX DLY55A 2 5 000663DFD600    05/26/16

System Configuration: lcpu=4 

17:20:41    %usr    %sys    %wio   %idle
17:20:43       0       0       0     100
17:20:45       0       0       0     100

Average        0       0       0     100
', column header is not located.
    cpu_for_aix_by_mpstat: Process exited with: 127. Reason was:  ()
    cpu_win32_winrm: 'wbem' is required.
    cpu_win32_wmi: 'wmi' is required.
    cpu_host_resource: 'snmp' is required.
    read 'sys.oid' failed, 'snmp' is required.

**http://127.0.0.1:37072/objects_managed/4466/sys**
'snmp' is required.

**http://127.0.0.1:37072/objects_managed/4466/mem**
{"channel":"","request_id":0,"created_at":"2016-05-26T17:44:44.3095667+08:00","value":{"clock_cycles_by_page_replacement_algorithm":0,"cpu_idle_percent":0,"cpu_iowait_percent":99,"cpu_system_percent":0,"faults_interrupts":535,"faults_kernal_thread_context_switches":60,"faults_system_calls":1738,"free_pages_by_page_replacement_algorithm":0,"kthr_block_threads":1,"kthr_run_threads":1,"mem_percent":14.262116748196462,"memory_active_pages":369455,"memory_free_pages":2221009,"pages_in_paging_space":0,"pages_out_paging_space":0,"scanned_pages_by_page_replacement_algorithm":0,"used_per":14.262116748196462},"method_id":"mem_for_aix","engine_id":0}

[AIX-swaps.txt](https://github.com/three-plus-three/hw_issues/files/292624/AIX-swaps.txt)

**Comment by runner-mei** [comment]
cpu 已修复
swaps 请在 aix 上执行的查看 交换分区的命令结果发给我

**Comment by Cuic** [comment]
HDOADB1:/ # lsps -a
Page Space      Physical Volume   Volume Group    Size %Used Active  Auto  Type
hd6             hdisk0            rootvg       16384MB    19   yes   yes    lv
HDOADB1:/ # lsps -s
Total Paging Space   Percent Used
      16384MB              19%
HDOADB1:/ #

**Comment by runner-mei** [comment]
fixed
