### ISSUE TITLE
(新拓扑)设备图标点击变模糊，不能恢复

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#371]
![1](https://cloud.githubusercontent.com/assets/14171518/15881160/6f40a750-2d66-11e6-9be7-0a72f66d8b0b.png)
![2](https://cloud.githubusercontent.com/assets/14171518/15881161/6f6b54f0-2d66-11e6-829d-d30539c01e6f.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengweiGR** [comment]
2.2.20161218_2059_x64版本仍然存在该问题
