### ISSUE TITLE
weblogic9 的支持

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#382]
weblogic9 无法以 jdk1.6 或以上版本支持， 因此改成用 snmp 取数
重要指标如下
wls9_serverTable
wls9_clusterTable
wls9_webServerRuntimeTable
wls9_webServerTable
wls9_webAppComponentTable
wls9_applicationRuntimeTable
wls9_executeQueueTable
wls9_executeQueueRuntimeTable
wls9_jdbcConnectionPoolRuntimeTable
wls9_jdbcDataSourceRuntimeTable
wls9_jmsTopicTable
wls9_jmsQueueTable
wls9_jmsServerTable
wls9_jmsRuntimeTable
wls9_jmsSessionRuntimeTable

模拟设备为
192.168.1.161:1611
public
v2c

**Comment by runner-mei** [comment]
华东电力没有开 snmp ，所以重新做了 weblogic 9 的 jmx 支持
在原来的 managed_application 增加一个 version 字段，注意这个字段存在 attributes 字段中，如下

    {"version":"v9"}

原来的  weblogic9  不要在使用， 可以隐藏掉。

**Comment by runner-mei** [comment]
![_2016-06-18t02-11-18 475z](https://cloud.githubusercontent.com/assets/1052632/16174792/30050b28-3606-11e6-87e6-60cf2370c183.png)

**Comment by eeiceyes** [comment]
fixed
