### ISSUE TITLE
数据流分析选择数据来源-bug

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#39]
在流量分析》实时流量分析 》数据来源 ： 只能选择管理IP ，不能选择详细数据来源IP
![image](https://cloud.githubusercontent.com/assets/14171497/10928634/7449471a-82e5-11e5-880c-a965b46b2eb1.png)

**Comment by runner-mei** [comment]
这个问题主要是
设备发送 netflow 包的IP 不是设备的管理 IP

**Comment by runner-mei** [comment]
已修复
