### ISSUE TITLE
单点登录的支持

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#394]
与第三方集成时有 SSO 的需求， 我启动了一个 cas 的服务器在 192.168.1.141 上， 我的浏览器访问url 是

```
http://192.168.1.141:8088/cas/login
```

它的后端数据库为  192.168.1.2 上的 tpt_cas_test, 数据库的用户名为 tpt,  数据库的密码为 extreme,  表为  tpt_users

当然这个是用来测试的，实际部署时数据库应该是自已的。

做这个时需要注意，用户名可能来之于第三方如 ldap, 这意味着用户名可能不在我们的数据库中，我的想法是不是让第三方携带一个角色信息，在我们内部用 角色 名来查找用户的授权信息 。

当用户不存在时，作如下处理
1. 查找 tpt_role 字段的值，如果为空，则为缺省值
2. 将 用户存入数据库表中。

当用户存在时，作如下处理
1. 查打 tpt_role 字段的值，如果不为空，继续下一步
2. 比较用户的 role 的旧值，不一样则更新数据库。

play 框加可用的  cas 客户端
https://github.com/pac4j/play-pac4j-java-demo

**Comment by eeiceyes** [comment]
这个算完成了吧？

**Comment by runner-mei** [comment]
恩
