### ISSUE TITLE
[巡检功能] 巡检点上Linux 使用执行远程命令报错

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#400]
![image](https://cloud.githubusercontent.com/assets/14171497/16511349/9e0ab47c-3f81-11e6-9cb3-40deae0a6155.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
