### ISSUE TITLE
[巡检功能] 巡检报告查看IE浏览器不能下拉全部查看，只能看上半部分

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#401]
使用IE浏览器查看巡检报告，只能看到上半部分内容，下半部分内容不能查看
![image](https://cloud.githubusercontent.com/assets/14171497/16516703/0362fe72-3fac-11e6-8c01-bd001642a9e0.png)

**Comment by eeiceyes** [comment]
这个问题还存在吗？再确认下

**Comment by hengwei-test** [comment]
现在还在现此现象

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
