### ISSUE TITLE
【华东电网】 weblogic9 的运转图 

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#406]
weblogic9 的运转图有点问题，大部分数据都取不到，需要重做一下
可以显示下列指标

info
heap_memory
nonheap_memory
memory_pool

weblogic_server_health_state
weblogic_subsystem_health_state
weblogic_application_status

运转图可看 https://github.com/three-plus-three/hw_issues/issues/382

**Comment by runner-mei** [comment]
仍然有问题

**Comment by runner-mei** [comment]
删除下列指标
heap_memory
nonheap_memory
memory_pool


增加下列指标
jmx_exec?jmx.action=enum&jmx.object_name=com.bea:Type=JRockitRuntime,*

**Comment by eeiceyes** [comment]
目前应该已经支持了

**Comment by hengwei-test** [comment]
下次去华东电网注意这个现象

**Comment by xiauye** [comment]
华东电网这台机器已经不存在了
