### ISSUE TITLE
[tomcat] tomcat内存使用最大百分百小数点太长，缩写小数点后2位

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#407]
在运行视图上、巡检点上、告警规则上

![image](https://cloud.githubusercontent.com/assets/14171497/16608542/7f04f270-437f-11e6-9e89-292190a92e90.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
