### ISSUE TITLE
[OEM] 江苏藤泽OEM产品带有hengwei的字样

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#410]
地址栏带“hengwei”
![image](https://cloud.githubusercontent.com/assets/14171497/16652857/e0ba9dca-447f-11e6-9146-36de46be6231.png)

![image](https://cloud.githubusercontent.com/assets/14171497/16653015/de4349ec-4480-11e6-963b-31f519ef807f.png)

**Comment by runner-mei** [comment]
fixed
