### ISSUE TITLE
[功能新增] 软件会话超时30分钟提示超时

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#414]
现象：网络断开、服务器系统关机、软件服务关闭等，在客户端打开的UI界面如果不刷新 则一直缓存在浏览器上，这样让客户误以为软件监控是好的，也如果时间长了也不知道什出现问题的！

在前端浏览器上添加一个会话超时机制（20分钟/30分），如果超时浏览器有超时提示

时间：下周周二前

**Comment by eeiceyes** [comment]
fixed
