### ISSUE TITLE
江西水利现场

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#417]
1、将实时监控中例如：设备DHCP、DNS状态等监控项做下调整
2、将根图右键设备面板图隐藏、将数据流分析模块隐藏
3、编写巡检模块使用手册@小崔

**Comment by runner-mei** [comment]
1、将实时监控中例如：设备DHCP、DNS状态等监控项做下调整

做什么调整？

**Comment by Cuic** [comment]
@hengweiGR  巡检报告文档已经编写完成！
