### ISSUE TITLE
[告警模块] tpt_metric_trigger 增加轮询间隔字段

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#418]
原来tpt_metric_trigger 的轮询间隔存在 expression 字段中，现在更改如下

新增字段  interval 字段， 类型为 integer ，可为 null ， 
它保存轮询间隔， 单位为秒

这个更改将不影响旧的数据

**Comment by eeiceyes** [comment]
在master上已经做过了

**Comment by eeiceyes** [comment]
3.3fixed
