### ISSUE TITLE
告警管理-基线数据管理

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#421]
问题描述：
创建完成后的基线数据的创建日期，变为系统当前的日期。
![001](https://cloud.githubusercontent.com/assets/20636259/17093117/eaa2335e-5279-11e6-8316-7e3dd410cac8.png)
![002](https://cloud.githubusercontent.com/assets/20636259/17093118/eaac2986-5279-11e6-88e7-7637a9f7b197.png)

**Comment by eeiceyes** [comment]
fixed
