### ISSUE TITLE
[巡检功能] 当前巡检任务中显示已经巡检过的任务

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#424]
![image](https://cloud.githubusercontent.com/assets/14171497/17131704/458c8968-5351-11e6-926a-37515ea3b539.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，close处理。
