### ISSUE TITLE
[根图设备显示] 设备迁移后根图地址显示不变成迁移后的地址

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#425]
描述：设备地址迁移成功后，根图设备图标不显示迁移后的地址，鼠标点击上去内存、cpu不显示数据，实际能取到数据！ 重启服务 恢复显示

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/21299987/92369f40-c5db-11e6-8558-11e83a8b61fe.png)
迁移后的设备，点击拓扑图上的图标。没有CPU 内存等指标显示

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170919_382_x64.exe  版本确认，close处理。
