### ISSUE TITLE
设备修改管理IP不生效

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#43]
1.拓扑图某设备上两个IP，修改成另一个IP，刷新设备后设备不能获取数据。

**Comment by runner-mei** [comment]
根原因可能因为后台 snmpling 进程有 cache, 当你用这个设备的 ID 刷新时, sampling 进程使用的 ip 是 cache 中的旧 IP, 因此不正确， 解决方案可能是在刷新时加上 @address 参数

**Comment by eeiceyes** [comment]
修改后后台会触发自动刷新
