### ISSUE TITLE
[分众传媒] 告警多次提醒功能

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#434]
描述:对于未处理的告警进行二次（多次）提醒功能（邮件、短信、微信等）
要求：客户可以选择性设置是否需要多次告警提醒的功能,提醒的时间间隔。

时间:客户现在是测试期间,越快越好

**Comment by runner-mei** [comment]
朱， 在各个通知方式中增加一个 repeat_count 整型字段，表示重复几次。repeat_interval 字符串字段表示重复时间间隔如 20m,  1d

**Comment by eeiceyes** [comment]
fixed
