### ISSUE TITLE
运维管理-业务视图-复制

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#450]
复制视图时，复制失败，报错
![04](https://cloud.githubusercontent.com/assets/20636259/17390726/51d47ac6-5a42-11e6-9b05-0e69ccc3fa1d.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/17653845/fde80cae-62cd-11e6-9371-e7e0568f61e1.png)
当添加的设备通过虚拟线路相连时，无法对业务视图进行复制

![image](https://cloud.githubusercontent.com/assets/20636259/17653830/d0cb459c-62cd-11e6-8e83-1505a205397b.png)

**Comment by eeiceyes** [comment]
fixed
