### ISSUE TITLE
[主机端口流量] Linux 192.168.1.14 无端口流量

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#454]
系统：192.168.1.14  Linux

取数方式：SSH

运转视图无端口流量：
![image](https://cloud.githubusercontent.com/assets/14171497/17425004/9b2ee54e-5afb-11e6-99c7-6c1e4fe99e2a.png)

端口信息无端口状态及流量

**Comment by runner-mei** [comment]
刷新设备后问题解决。
