### ISSUE TITLE
添加主机-维护信息模块

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#459]
维护信息模块添加自定义模块时，没有进行左对齐
![1](https://cloud.githubusercontent.com/assets/20636259/17428834/e2d2e8b0-5b1d-11e6-8788-ee46e264043d.png)

**Comment by eeiceyes** [comment]
现在都是左对齐，界面的布局都是针对此种做法来布局的，这个不再改了
