### ISSUE TITLE
当前告警，显示错误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#461]
原有拓扑图中存在告警时，生产新拓扑图对原有拓扑覆盖。
界面左上角的告警栏显示有告警，点开之后。当前告警窗口无告警显示
![02](https://cloud.githubusercontent.com/assets/20636259/17429323/b85344ce-5b20-11e6-9bab-f1f372ea5e2b.png)

**Comment by eeiceyes** [comment]
fixed
