### ISSUE TITLE
在机房视图页面设置默认显示设置会影响到网络视图页面

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#464]
在机房视图页面设置默认显示设置修改项成功后，会影响到网络视图页面的默认显示设置修改项
![06](https://cloud.githubusercontent.com/assets/20636259/17430373/623764b6-5b26-11e6-88cd-bc89d32bfe7f.png)

**Comment by eeiceyes** [comment]
就是这么实现的，这个是针对设备的全局设置
