### ISSUE TITLE
内存信息-平均内存利用率

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#466]
资源管理-主机管理-主机运转图-指标一览-Windows指标-内存信息中的“平均内存利用率” 小数点后尾数过长，应该考虑取小数点后2位或3位。 （windows 指标下的内存信息也是同样问题）
![08](https://cloud.githubusercontent.com/assets/20636259/17432129/25bb6dde-5b30-11e6-9b6d-a70aacc17fee.png)

**Comment by runner-mei** [comment]
应该可以通过元模型来解决

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，close处理。
