### ISSUE TITLE
右键设备-设备面板视图

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#470]
设备运行视图中的，CPU利用率和内存利用率视图中的显示采集间隔随着时间会变的越来越小。由原先的10分钟，显示到后来的15S间隔
![02](https://cloud.githubusercontent.com/assets/20636259/17467586/6bb52b4e-5d52-11e6-80d5-290bb9264d0f.png)

**Comment by eeiceyes** [comment]
fixed
