### ISSUE TITLE
机房视图-编辑机柜

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#474]
在机房视图中，添加一个新的机房视图（机房1），在机房1中，添加一个机柜。右键机柜，点击“编辑机柜”，在所属机房中，选择“默认机房”，点击“确定”按钮。提示更新机柜成功。跳转回“默认机房”，机柜未迁移过来。仍然在原来机柜中

**Comment by eeiceyes** [comment]
界面错误，机柜 所属机房是不能修改的
