### ISSUE TITLE
业务视图-添加管理对象

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#476]
在业务视图中，右键空白区域点击添加管理对象。在网络设备分栏中选择设备，在主机、数据库、中间件、标准应用中，都分别选取设置，最好在标准应用分栏中，点击 确定 。最好添加的设备只有在“标准应用”中选择的设备，之前选中的设备没有被添加

**Comment by eeiceyes** [comment]
目前就是这么实现的，暂时不改
