### ISSUE TITLE
业务视图-圆形

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#477]
在业务视图中，右键空白区域，弹出选择框，点击“圆形”选项后，没有发生改变。功能未实现

**Comment by eeiceyes** [comment]
如没有连线，集中排布方式的效果是一样的

**Comment by RasAlGu1** [comment]
添加视图节点后，圆形排布 功能无法实现

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/17722838/dd7ce05c-6467-11e6-93db-2b31acc122c8.png)
业务视图连线不与视图节点相连时，圆形功能可以实现。与视图节点有连线时，圆形功能无法实现
