### ISSUE TITLE
运维管理-监控总览-全屏

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#479]
在监控总览面板中，全屏时。屏幕下方出现黑色缺失
![09](https://cloud.githubusercontent.com/assets/20636259/17470421/ad1b29e6-5d6e-11e6-901f-80aee030f498.png)

**Comment by eeiceyes** [comment]
现在这个问题还有吗？

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，close处理。
