### ISSUE TITLE
监控总览-设备负载监控总览

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#480]
在设备负载监控面板中，设置参数，选取5个参数。点击确定。生产的模块视图表达不明显
![10](https://cloud.githubusercontent.com/assets/20636259/17470595/0a64a536-5d70-11e6-8291-7e7ccbb61246.png)
![11](https://cloud.githubusercontent.com/assets/20636259/17470610/30680b88-5d70-11e6-9116-84b02f6b41d8.png)

**Comment by eeiceyes** [comment]
没取到数，所以看不到线路的颜色，这个不用改了
