### ISSUE TITLE
监控总览-主机指标查看-内存利用率

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#481]
创建“主机指标查看”面板。选择参数设置-内存信息。选择主机，点击确定。显示的平均内存利用率建议精确
![12](https://cloud.githubusercontent.com/assets/20636259/17470772/8fc2b1c2-5d71-11e6-84d3-a21b38ba1fbc.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，close处理。
