### ISSUE TITLE
监控总览-主机指标查看-多内存信息

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#482]
在监控总览中，创建一个“主机指标查看”，参数选择“多内存信息”。完成后新增面板。面板中的大小、已使用、空闲的单位建议从（byte）改成GB或者MB，以便于查看。内存利用率小数也建议精确
![14](https://cloud.githubusercontent.com/assets/20636259/17470930/ca7bf106-5d72-11e6-92cc-388b998b5993.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，close处理。
