### ISSUE TITLE
监控总览-线路流量监控

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#484]
在监控总览中，创建一个“线路流量监控”，随机选择5个参数。点击确定。
![16 1](https://cloud.githubusercontent.com/assets/20636259/17471211/2205ff82-5d75-11e6-9a98-dc006269d95a.png)
只显示了单条的线路
![16 2](https://cloud.githubusercontent.com/assets/20636259/17471217/2bafb276-5d75-11e6-900a-b4c02439ae24.png)
线路名没有完全显示，应该左对齐

**Comment by eeiceyes** [comment]
显示区域设置大点就好了，不然线路名称太长，显示不下
