### ISSUE TITLE
监控管理-主机运行视图-Windows指标-DHCP状态

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#489]
花费时间 单位拼写错误。建议单位改为小时
![20](https://cloud.githubusercontent.com/assets/20636259/17501820/0990fce0-5e15-11e6-84ab-661b2a157bdb.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171011_2_x64.exe     版本确认，close处理。
