### ISSUE TITLE
监控管理-主机运行视图-Windows指标-ping测试

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#494]
输入正确格式的IP地址，但无法检测时ping时，会一直显示正在采集
![image](https://cloud.githubusercontent.com/assets/20636259/17502369/d704466a-5e19-11e6-8e9c-efec0d7c2889.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
