### ISSUE TITLE
资源管理-标准应用管理-添加

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#498]
输入地址栏有误时。提示错误不直白
![26](https://cloud.githubusercontent.com/assets/20636259/17503806/734d351c-5e25-11e6-9d3d-5f7fbe25a6fe.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/18735548/27d1ae8e-80b1-11e6-81bc-155d99bfba59.png)

**Comment by runner-mei** [comment]
朱韩君，这个问题你通过匹配字符串是改不完的，你只能将错误框改进一下
