### ISSUE TITLE
[磁盘卷-BUG] 磁盘使用率为0时显示为：“-1”

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#499]
系统：Linux
取数方式：SSH
磁盘告警、运转视图磁盘指标中，磁盘使用率为0时显示为0%

![image](https://cloud.githubusercontent.com/assets/14171497/17503803/65d705b6-5e25-11e6-9ce6-ba68676816ed.png)

**Comment by eeiceyes** [comment]
fixed
