### ISSUE TITLE
资源管理-运行时段设置

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#500]
设置主机运行时段时，设置时间09:00-18:00，每周一、二、三、四、五 工作。
点击“确定”按钮。点击后，为提示设置成功。且界面由变回原来格式（标准应用也是相同）
![27](https://cloud.githubusercontent.com/assets/20636259/17503962/1c0db630-5e27-11e6-8b71-b523c61dfa12.png)

**Comment by eeiceyes** [comment]
fixed
取消主机的单元设置
