### ISSUE TITLE
报表管理-记录数据查询

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#505]
每次打开 记录数据查询 页面的时间都过长

操作选择记录类型时，响应时间也过长
![30](https://cloud.githubusercontent.com/assets/20636259/17506750/00072158-5e3e-11e6-8e2d-943556fdef50.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
优化过了，再看下
