### ISSUE TITLE
设备负载监控-内存利用率

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#510]
在实时监控面板下，设备负载-内存利用率功能无法实现。
![34](https://cloud.githubusercontent.com/assets/20636259/17540005/76e20e4e-5ee5-11e6-8d97-63ab41db6943.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170814_270_x64.exe   版本确认，close处理。
