### ISSUE TITLE
网络视图-线路显示设置

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#511]
先设置线路显示设置中的显示属性，选择线路名称在下标中显示，点击确定。线路名称在下标中显示成功。
再将原来的线路名称在下标中显示取消勾选，点击确定。部分线路名称立刻显示消失。仍有多数线路的名称显示在网络视图中，在几分钟之后才会消失

**Comment by eeiceyes** [comment]
新版本再验证下

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170814_270_x64.exe   版本确认，close处理。
