### ISSUE TITLE
主机运转视图-ping测试

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#513]
在ping测试弹出的参数设置窗口中，输入目标地址后，点击确定按钮。显示
![image](https://cloud.githubusercontent.com/assets/20636259/17542825/acf35df8-5efe-11e6-9565-548db3e95038.png)

时，页面一直处于这种状态，不自动刷新结果，不提示连接失败。

**Comment by runner-mei** [comment]
“正在采集中” 改成 ”正在采集中，请稍后重新采集“。

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_219_x64.exe     版本确认，close处理。

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_219_x64.exe     版本确认，close处理。
