### ISSUE TITLE
常用工具-设备配置模板

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#515]
创建时间的实现显示格式错误
![37](https://cloud.githubusercontent.com/assets/20636259/17544560/a9b003c4-5f0a-11e6-90f0-f19d61787204.png)

**Comment by runner-mei** [comment]
确认一下，还这样么？

**Comment by xiauye** [comment]
创建格式还是错误的

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170921_2754_x64.exe  版本确认，close处理。
