### ISSUE TITLE
显示已确认告警出错

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#517]
1.打开系统管理-用户操作日志。
2.点击查询按钮，查询成功后点击页面左上角的告警提示
![image](https://cloud.githubusercontent.com/assets/20636259/17578890/5a4bac86-5fc1-11e6-88b2-d38dc7f435e0.png)
3.点击“显示已确认告警”
4.出现错误显示，显示用户操作日志
![38](https://cloud.githubusercontent.com/assets/20636259/17578898/7dcbfaa8-5fc1-11e6-9355-800422bb30fa.png)

**Comment by eeiceyes** [comment]
fixed
