### ISSUE TITLE
报表管理-预置报表管理-启用

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#519]
在预置报表管理界面下，先选中报表（单个或多个）对报表进行禁用操作，然后对禁用的报表进行启用。提示
![image](https://cloud.githubusercontent.com/assets/20636259/17611203/c596d02c-6077-11e6-9489-38e8f8ee6dd8.png)

返回上一页，刷新页面后有部分报表启用成功，部分仍然是禁用

**Comment by eeiceyes** [comment]
fixed
