### ISSUE TITLE
巡检异常一览

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#522]
选择 已过期的任务
![image](https://cloud.githubusercontent.com/assets/20636259/17615594/e55de290-60a1-11e6-8739-9ee491c7ab78.png)

点击“确定”按钮（按钮置灰还能点击，属于BUG）

![39](https://cloud.githubusercontent.com/assets/20636259/17615657/43e59c22-60a2-11e6-983f-4a3011988bae.png)

弹出消息提示框，点击确定，弹出空白提示框
![40](https://cloud.githubusercontent.com/assets/20636259/17615685/60ed1e58-60a2-11e6-94fa-70d3709439a8.png)

**Comment by eeiceyes** [comment]
fixed
