### ISSUE TITLE
监控管理-主机运行视图

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#524]
打开监控管理-主机运行视图，选择主机确定后，进入主机视图，点击“当前告警数”
![image](https://cloud.githubusercontent.com/assets/20636259/17616457/72f1632a-60a7-11e6-8eea-1d39aeafb9e7.png)

弹出当前告警窗口。点击“显示已确认告警”按钮，页面出现“加载中...”， 随后页面卡死
![image](https://cloud.githubusercontent.com/assets/20636259/17616482/9b93c64c-60a7-11e6-92e7-4b56112f8e72.png)

**Comment by eeiceyes** [comment]
fixed
