### ISSUE TITLE
Linux 主机中 添加告警规则未实现

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#529]
在linux主机中添加的关于“ping测试”和“进程信息”的告警无法被触发
![43](https://cloud.githubusercontent.com/assets/20636259/17688479/339f53a4-63b2-11e6-9983-a6265c71e613.png)

**Comment by runner-mei** [comment]
这个字段是从什么地方来的，我在代码中找不到啊

**Comment by runner-mei** [comment]
与 #531 重复了吧

**Comment by runner-mei** [comment]
“进程信息”的告警无法被触发， 原因是规则没有设好， 阀值为空了。

**Comment by RasAlGu1** [comment]
解决了
