### ISSUE TITLE
Linux 主机中 添加告警规则未实现（内存）

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#530]
注：禁用的规则可以实现
![2](https://cloud.githubusercontent.com/assets/20636259/17688719/5c822cc2-63b4-11e6-93d0-da23544f17a0.png)
![1](https://cloud.githubusercontent.com/assets/20636259/17688725/65595154-63b4-11e6-8bda-ef36bdbe30c1.png)

**Comment by runner-mei** [comment]
这个是使用什么访问参数导致

**Comment by runner-mei** [comment]
已修复， 内存不再有这些字段
