### ISSUE TITLE
Linux 主机中 添加告警规则未实现（Ping）

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#531]
![ping1](https://cloud.githubusercontent.com/assets/20636259/17688746/9fd49d84-63b4-11e6-97b3-3ed0eb08cc0a.png)
![ping2](https://cloud.githubusercontent.com/assets/20636259/17688750/afcb663c-63b4-11e6-8eb3-e131df555b11.png)

**Comment by runner-mei** [comment]
请将数据库中表中记录的规则数量给我看看， 表名为 tpt_alerts

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/18038588/987dd04c-6dcc-11e6-9ce8-c973028f168c.png)

**Comment by RasAlGu1** [comment]
"{"attribute":"result","value":"traversableAgain","operator":"="}"
