### ISSUE TITLE
Linux 主机中 添加告警规则未实现（磁盘）

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#532]
![1](https://cloud.githubusercontent.com/assets/20636259/17688841/902c612c-63b5-11e6-8362-006f2c186afe.png)
![2](https://cloud.githubusercontent.com/assets/20636259/17688861/ac85fc34-63b5-11e6-9c65-dd40356a81c8.png)

**Comment by runner-mei** [comment]
fixed
