### ISSUE TITLE
Linux 主机中 添加告警规则未实现（进程）

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#533]
![1](https://cloud.githubusercontent.com/assets/20636259/17688943/3c83313a-63b6-11e6-81b8-fbe4e7845a6a.png)
![2](https://cloud.githubusercontent.com/assets/20636259/17688946/4418bd48-63b6-11e6-8c9c-739d23065583.png)

**Comment by runner-mei** [comment]
这个是元模型的问题，后续会改的，现在只测试进程是否存在
