### ISSUE TITLE
网络设备-添加的告警无法触发（内存）

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#535]
![1](https://cloud.githubusercontent.com/assets/20636259/17689599/49e3c916-63bb-11e6-81bb-528ae0ae77d0.png)
![2](https://cloud.githubusercontent.com/assets/20636259/17689618/6af4b46c-63bb-11e6-816e-bf343a4564cc.png)

**Comment by runner-mei** [comment]
百分比可以告警出来， 其它字段告不出来，对吧？

**Comment by RasAlGu1** [comment]
对的

**Comment by runner-mei** [comment]
该问题是有一些设备不支持取内存大小，仅有百分比。回头想办法
