### ISSUE TITLE
网络设备-添加的告警无法触发（Remote Ping）

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#536]
![1](https://cloud.githubusercontent.com/assets/20636259/17689693/f143bbf8-63bb-11e6-810e-af303ce76b2a.png)
![2](https://cloud.githubusercontent.com/assets/20636259/17689714/0bf5c63a-63bc-11e6-8a53-af54d0ddd0b6.png)

**Comment by runner-mei** [comment]
这个无法在模拟设备上测试，只能用 linux 主机代替

**Comment by RasAlGu1** [comment]
Linux 主机也有错误
![image](https://cloud.githubusercontent.com/assets/20636259/18237343/a54ba27c-7362-11e6-9198-00552abba18c.png)

**Comment by runner-mei** [comment]
远程 ip 没有设吧

**Comment by RasAlGu1** [comment]
远程IP设置时
![image](https://cloud.githubusercontent.com/assets/20636259/18259580/1c9f5bce-7418-11e6-88d6-8a4f20587e7f.png)

**Comment by runner-mei** [comment]
delay 字段已删除
