### ISSUE TITLE
告警规则-添加告警规则

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#538]
添加告警规则时，添加时选择多个指标进行规则的添加时，有时会发生仅添加成功部分选中的规则，会有未添加的规则

**Comment by runner-mei** [comment]
这个说的太模糊

**Comment by RasAlGu1** [comment]
同一个设备，添加种类（例如CPU、内存等等）信息是，有时添加的告警数据多时，能成功添加的数量少于添加时的告警类型条数。例如 我添加了20条不同种类的告警，点击确定后，只成功添加的10条左右

**Comment by RasAlGu1** [comment]
现在重现几次都无法重现了。

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
问题仍然存在

**Comment by eeiceyes** [comment]
最新的版本试了好几次，没有发现

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20180202_717_x64.exe 版本确认，close处理。
