### ISSUE TITLE
删除业务视图中添加的视图节点无法删除

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#539]
删除时报错，无法删除。

**Comment by RasAlGu1** [comment]
[web_server.txt](https://github.com/three-plus-three/hw_issues/files/454455/web_server.txt)
[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/454454/server_biz.txt)

**Comment by eeiceyes** [comment]
fixed
