### ISSUE TITLE
报表规则管理-中间件负载统计报表-生成报表

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#540]
先创建一个中间件负载统计报表，选择指标为最大连接数
![image](https://cloud.githubusercontent.com/assets/20636259/17726534/3ed4f4f2-6486-11e6-9d3d-4e2eacb1ff0c.png)
点击确定 ，完成创建。
创建完成后选择此报表，点击立刻生成按钮。选择 存档 ，点击确定。弹出错误信息
![image](https://cloud.githubusercontent.com/assets/20636259/17726558/712cc1dc-6486-11e6-82a9-183426aa7d7e.png)

**Comment by eeiceyes** [comment]
fixed
