### ISSUE TITLE
WMI / WinRM 主机设备添加告警

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#542]
运用WMI采数方式的主机设备，对其进行添加告警，进程信息-cpu利用率，点击“所有数据行”。弹出进程信息窗口。部分信息无法取到
![image](https://cloud.githubusercontent.com/assets/20636259/17761022/671e6546-6536-11e6-8a8b-87bbeb014940.png)

**Comment by eeiceyes** [comment]
现在暂时的做法是区分进程信息和进程信息(WMI | WINRM),第一个指标针对snmp，后者针对WMI和WINRM
