### ISSUE TITLE
监控管理-设备TCP连接信息

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#548]
选择设备为仅使用WMI取数的主机设备
![image](https://cloud.githubusercontent.com/assets/20636259/17766052/b379657e-655b-11e6-810c-dc65e724b9b6.png)

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/18190428/8750a1d8-70f5-11e6-9cfa-c7fd98016663.png)

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/18190549/51aabfd6-70f6-11e6-9383-c9d0640fae95.png)

**Comment by runner-mei** [comment]
将会返加错误如下 
    
       “仅 window 8 或 window 2012 及以上版本才支持”

**Comment by RasAlGu1** [comment]
返加成功

**Comment by runner-mei** [comment]
返加成功？

**Comment by RasAlGu1** [comment]
描述添加成功。。。。。。。。。。。。

**Comment by runner-mei** [comment]
描述添加成功？还是不明白。

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/18459968/6b000cae-79a0-11e6-8cf1-163747e9ae2a.png)
