### ISSUE TITLE
监控管理-设备UDP监听信息

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#549]
选择取数方式仅为WMI的主机设备
![image](https://cloud.githubusercontent.com/assets/20636259/17766114/182f415a-655c-11e6-889b-4d6805f3f0ee.png)

**Comment by RasAlGu1** [comment]
![1](https://cloud.githubusercontent.com/assets/20636259/18197967/b32ad756-712c-11e6-85f9-bb8dccf4a1f8.png)
![2](https://cloud.githubusercontent.com/assets/20636259/18197969/b36d2f48-712c-11e6-89fd-9e8635948144.png)
![3](https://cloud.githubusercontent.com/assets/20636259/18197970/b3924a1c-712c-11e6-8af1-29d70869c0a3.png)

**Comment by runner-mei** [comment]
仅 win2012 或以下版本支持，错误描述已改正，请验证一下。

**Comment by RasAlGu1** [comment]
描写修改完毕
