### ISSUE TITLE
WMI主机的设备运行视图-指标一览

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#550]
内存信息取数无法取到
![image](https://cloud.githubusercontent.com/assets/20636259/17766524/19c944d2-655e-11e6-85ba-578275f2228c.png)

**Comment by runner-mei** [comment]
确认一下还有问题么

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_219_x64.exe     版本确认，close处理。
