### ISSUE TITLE
告警规则-组合告警

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#552]
删除原有的一条“提示级”的组合告警规则，再新建一条组合告警规则，设置的条件使其能被触发告警。设置成功并触发后。该级别的告警页面出错
![image](https://cloud.githubusercontent.com/assets/20636259/17767341/2dd7b31a-6562-11e6-979f-9882ec3b6677.png)

**Comment by runner-mei** [comment]
出什么错，我没有看到错误啊？

**Comment by RasAlGu1** [comment]
第二条报错的规则是已经删除的，而且级别不同，却在另外一个级别中出现

**Comment by runner-mei** [comment]
靠，你在啊，我的理解是 “新建一条组合告警规则”， 这一条没有问题。
旧的规则级别不正确是吧？

**Comment by RasAlGu1** [comment]
新的没问题 ， 是旧的已经被删除了 告警还在，而且在每个级别都有存在

**Comment by runner-mei** [comment]
恩，你明天重现一下，到时叫我一下

**Comment by RasAlGu1** [comment]
无法重现了

**Comment by runner-mei** [comment]
不能重现，不能关闭。
多试几次

**Comment by RasAlGu1** [comment]
与 #607  相同
