### ISSUE TITLE
实时监控-端口信息

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#553]
对仅使用WMI取数的设备进行查看端口信息，端口信息无法取得
![image](https://cloud.githubusercontent.com/assets/20636259/17796042/29ff51ce-65f0-11e6-86f3-e0076253fd60.png)

**Comment by runner-mei** [comment]
已修复

**Comment by RasAlGu1** [comment]
reopen

**Comment by runner-mei** [comment]
你现在是特殊做的吧，现在不需要了，现在 wmi 和 winrm 也支持 interface_descr 和 interface_status 和 interface_flux

**Comment by RasAlGu1** [comment]
可以读取出来，但是读的太慢了

**Comment by runner-mei** [comment]
朱韩君， 你现在是特殊做的吧，现在不需要了，现在 wmi 和 winrm 也支持 interface_descr 和 interface_status 和 interface_flux
