### ISSUE TITLE
Linux 主机中 -实时监控-IP地址信息

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#559]
显示数据缺失
![image](https://cloud.githubusercontent.com/assets/20636259/17801419/87fc83d8-661c-11e6-91de-5855704b55b5.png)

**Comment by runner-mei** [comment]
什么设备，什么访问参数

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/18038982/d4f5710c-6dd0-11e6-93f3-4e30c2efaadb.png)
IP地址为空

**Comment by runner-mei** [comment]
fixed
