### ISSUE TITLE
Linux主机运行视图，指标一览-CPU详细信息

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#562]
指标值中多数据无法取到
![image](https://cloud.githubusercontent.com/assets/20636259/17802700/6a51908c-6624-11e6-9f6e-c43fc35a226a.png)

**Comment by runner-mei** [comment]
什么设备，什么访问参数

**Comment by RasAlGu1** [comment]
Linux主机的运行视图中的指标一览中，CPU详细信息。平均CPU利用率和其他参数 为空

**Comment by runner-mei** [comment]
什么访问参数，

**Comment by runner-mei** [comment]
什么访问参数？

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/18112893/fd1fa678-6f5d-11e6-820f-8d5d331b59f6.png)

**Comment by RasAlGu1** [comment]
现在可以取到了

**Comment by runner-mei** [comment]
这是不对的，我们没有修复这个，说明问题还在
你分别单独用 snmp 和 ssh 试一下

**Comment by RasAlGu1** [comment]
单独使用SSH时，出现BUG

**Comment by xiauye** [comment]
CPU详细信息，还是没有取得CPU利用率的值

**Comment by runner-mei** [comment]
说清楚，什么参数时是好的，什么参数下是有问题的。这个是和访问参数有关的

**Comment by xiauye** [comment]
SSH
