### ISSUE TITLE
Linux主机-右键菜单-实时监控-ARP

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#565]
类型参数缺失
![image](https://cloud.githubusercontent.com/assets/20636259/17842801/3dc32a58-6859-11e6-9b19-5ce236ae5763.png)

**Comment by runner-mei** [comment]
什么取数方式

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/18038985/df63f76c-6dd0-11e6-8b32-f2c8d60052cd.png)

**Comment by runner-mei** [comment]
这个用 ssh 取数时确实没有。
