### ISSUE TITLE
[bug] 巡检功 Linux远程执行命令功能不能使用

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#573]
Linux （ssh取数）
指标：远程执行命令

![image](https://cloud.githubusercontent.com/assets/14171497/17878294/7a94fdd0-691c-11e6-9e3d-b0a95d31f033.png)

**Comment by eeiceyes** [comment]
@runner-mei ，指标shell_exec，是干啥用的，原模型定义是有value字段的，但是取值返回的是纯字符串，不是带value字段的json

**Comment by runner-mei** [comment]
元模型定义已改成 字符串

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
