### ISSUE TITLE
[BUG] Windows 无端口流量

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#575]
系统：Windows
取数方式：winrm/WMI

http://192.168.1.143:37072/managed_objects/38443/if_index/17/interface_flux

结果：
internal error:
    read 'sys.oid' failed, 'snmp' is required.
    port_scalar_by_ssh_netstat_with_bytes-if_index: unix class is support only.
    port_interface_scalar-if_index: 'snmp' is required.
    port_scalar_by_ssh_netstat-if_index: unix class is support only.
    port_interface_scalar_linux-if_index: linux is support only.

**Comment by runner-mei** [comment]
fixed
