### ISSUE TITLE
(G&D KVM)数据不一致

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#579]
![1](https://cloud.githubusercontent.com/assets/14171518/17955638/426454d8-6ab6-11e6-936a-215893b59319.png)
![2](https://cloud.githubusercontent.com/assets/14171518/17955641/472cc78e-6ab6-11e6-8ee6-a7f7d7961bef.png)
![3](https://cloud.githubusercontent.com/assets/14171518/17955656/4ffbd30a-6ab6-11e6-95d5-66e6b3f1073c.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengweiGR** [comment]
![image](https://cloud.githubusercontent.com/assets/14171518/18191532/0746ce50-70fe-11e6-8ded-3f2a9b284f97.png)

备注信息没有
