### ISSUE TITLE
运维管理-业务视图

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#597]
圆形排布 和 树形排布 的各个种类的间距都无法实现。间距始终是默认间距
![image](https://cloud.githubusercontent.com/assets/20636259/18042633/139c7828-6df5-11e6-8c20-562481bef36c.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
不需要这些功能，已简化
