### ISSUE TITLE
监控管理-实时监控-指标（内存利用率）

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#598]
在实时监控页面，选择监控指标（平均内存利用率），后选择多个管理对象，点击启动。无反应，没有取到 内存利用率 的参数
![image](https://cloud.githubusercontent.com/assets/20636259/18043410/3508a446-6dfa-11e6-84a0-44cd2c8592a3.png)

**Comment by RasAlGu1** [comment]
先在监控管理-实时监控中，点击监控管理-设备负载监控-CPU利用率，选择设备后，点击确定。等到报错后，确定，然后选择 监控指标（CPU利用率） ，监控设备。点击启动后，会有参数取到，然后停止。监控指标改为（内存利用率）。启动，无法取到参数

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
问题仍然存在
1.点击 监控管理-实时监控 ，进入实施监控页面
2.点击 监控管理-设备负载监控-CPU，选择对象点击确定按钮。等窗口弹出后，关闭窗口
3. 选择监控指标 内存信息-平均内存利用率，选择对象。点击启动
监控对象取不到内存利用率
![image](https://cloud.githubusercontent.com/assets/20636259/21302048/3ea10876-c5ee-11e6-87f3-65a70958e597.png)

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_219_x64.exe     版本确认，close处理。
