### ISSUE TITLE
[系统增强] 增加菜单自定义功能

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#602]
现在的整个菜单结构是预定好的，想要变就要改代码，但是常常有一些现场需求，要改动一下菜单结构，隐藏一些菜单。所以我设想菜单是可以用一个配置文件来定义，根据用户需要直接改配置文件就行了。

设想如下
1. 菜单结构是从一个 xml 文件中加载
2. 每一个菜单项，有一个唯一的 key, 和多个 tags 来授权

甚至未来，菜单结构可以通过界面来配置。

**Comment by eeiceyes** [comment]
现在可以close了
