### ISSUE TITLE
CPU信息  告警错误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#615]
4721   "{"attribute":"key","operator":"equals","value":"","function":"any"}"\
4722   "{"attribute":"name","operator":"equals","value":"","function":"any"}"
4723   "{"attribute":"cpu_percent","operator":">","value":"0","function":"any"}"
4724   "{"attribute":"","operator":">","value":"0","function":"count"}"

![image](https://cloud.githubusercontent.com/assets/20636259/18157920/a4d6580e-7052-11e6-9466-a9114db7a5ba.png)

**Comment by runner-mei** [comment]
fixed
