### ISSUE TITLE
实时监控 对象类型为 服务器时 【1670】

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#616]
监控指标 系统信息-连续运行时间 选择管理对象 后，启动
WMI 和 WinRM 数据为空
![image](https://cloud.githubusercontent.com/assets/20636259/18157993/f537a4c4-7052-11e6-8876-dc68e80a5bee.png)

**Comment by runner-mei** [comment]
我试是好的

**Comment by RasAlGu1** [comment]
属于设备区分问题
