### ISSUE TITLE
WMI 进程信息 占用过多资源

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#617]
在进程信息 告警过多时，取数时，进程信息会占用过多的资源，导致后面排队的任务资源被占用

**Comment by runner-mei** [comment]
因为 wmi 采集是单队列的，而采某些指标（如进程）很耗时，后续任务常常会超时。

**Comment by RasAlGu1** [comment]
设备告警规则仅启动5条时，设备运行视图的读取速度有点慢，需要1分钟才能读取到数据。

![2](https://cloud.githubusercontent.com/assets/20636259/18235727/19b1782e-7351-11e6-84f5-89cd46945a3f.png)
![3](https://cloud.githubusercontent.com/assets/20636259/18235728/1a6f6fd2-7351-11e6-8832-bb908e4f2453.png)
