### ISSUE TITLE
数据运行视图（sybase）

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#622]
视图中，数据显示为空
![image](https://cloud.githubusercontent.com/assets/20636259/18197007/84e3b3ea-7127-11e6-8c79-4ba0ef7c65dd.png)

**Comment by runner-mei** [comment]
请将日志，也传上来

**Comment by runner-mei** [comment]
在 web_server.log 中

**Comment by RasAlGu1** [comment]
[web_server.txt](https://github.com/three-plus-three/hw_issues/files/454234/web_server.txt)
[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/454235/server_biz.txt)

**Comment by eeiceyes** [comment]
MFK解决以下错误
http://127.0.0.1:37072/managed_objects/80362/sybase_locks_stat
Incorrect syntax near the keyword 'count'.


http://127.0.0.1:37072/managed_objects/80362/sybase_response_time
'sybase_response_time' is not acceptable.

**Comment by runner-mei** [comment]
已修复
