### ISSUE TITLE
运维管理-巡检异常一览

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#628]
对已过期的任务进行确认，确认成功后。该任务仍然存在界面中
[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/454627/server_biz.txt)
[web_server.txt](https://github.com/three-plus-three/hw_issues/files/454628/web_server.txt)

**Comment by RasAlGu1** [comment]
[web_server.txt](https://github.com/three-plus-three/hw_issues/files/460926/web_server.txt)
[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/460927/server_biz.txt)

**Comment by eeiceyes** [comment]
fixed
