### ISSUE TITLE
Windows SNMP 主机 运行视图-指标一览-进程信息 

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#630]
Windows SNMP 主机 中， 运行视图-指标一览-进程信息  数据不显示
提示
No value present

**Comment by eeiceyes** [comment]
现在重现不了，可以修改其他问题时同时修复，观察下吧

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/19333503/fda77fd4-9128-11e6-8f33-9c848ab116b1.png)
