### ISSUE TITLE
WinRM设备 实时监控 端口信息

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#637]
在端口信息中，IP地址不显示
![image](https://cloud.githubusercontent.com/assets/20636259/18297199/7b4e5f16-74e1-11e6-8244-787e5f3712c0.png)

**Comment by eeiceyes** [comment]
ip_address指标，snmp和winrm返回的字段名格式不同意，注意字段if_index和ifIndex
snmp
{"address":"121.0.0.20","bcastAddress":1,"if_index":183,"netmask":"255.255.255.0","reasmMaxSize":65500}
winrm
{"address":"192.168.1.2","bcastAddress":-1,"ifIndex":"17","netmask":"","reasmMaxSize":-1}

**Comment by eeiceyes** [comment]
老梅看下后面要怎么改，改完指给我，我做相应修改

**Comment by runner-mei** [comment]
fixed
