### ISSUE TITLE
机房视图-机柜视图

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#638]
机柜视图中 121.0.0.3设备 存在一个中级告警。机柜视图中，这台设备却没有闪烁提示
![image](https://cloud.githubusercontent.com/assets/20636259/18297421/f5bc6d00-74e2-11e6-9da2-7428ebab6062.png)

![image](https://cloud.githubusercontent.com/assets/20636259/18297410/de35b8e4-74e2-11e6-8a93-fa70321c940e.png)

[Desktop.txt](https://github.com/three-plus-three/hw_issues/files/458144/Desktop.txt)

**Comment by RasAlGu1** [comment]
把.TXT改为 .ZIP 后解压

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
有的设备有告警，却仍然不会闪烁提示
