### ISSUE TITLE
WinRM设备 实时监控-端口流量

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#639]
端口信息中，有2个端口的流量可以取到。在端口流量中无法取到流量的数据。

![image](https://cloud.githubusercontent.com/assets/20636259/18298526/c5e617b2-74eb-11e6-9085-8c35418afc49.png)

**Comment by runner-mei** [comment]
请用 interface_descr 和 interface_flux  取数，之前是用 windows 专用指标做的。
另外 interface_status 是不需要的， interface_flux 中的这两个字段

**Comment by eeiceyes** [comment]
fixed
