### ISSUE TITLE
weblogic运行视图数据显示不全

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#64]
weblogic运行视图部分数据不显示
"服务通道信息"无数据
“Servlet信息”无数据

Java版本：1.6.0_22
weblogic版本：10.3.4.0

![image](https://cloud.githubusercontent.com/assets/14171497/11264048/879f1ab4-8ecb-11e5-8f2a-34d78d052fd8.png)

**Comment by RasAlGu1** [comment]
fixed
