### ISSUE TITLE
[告警功能] 磁盘告警功能，磁盘空闲告警不可用

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#641]
磁盘使用空闲告警不可以用！
如图：
![frm u 8 j hu az7dmg4dnu](https://cloud.githubusercontent.com/assets/14171497/18301042/ec8c93cc-7500-11e6-8001-602736574ad5.png)
![1h t8v ut8nzht ee t](https://cloud.githubusercontent.com/assets/14171497/18301047/f4ccf7ca-7500-11e6-9530-0c23bf03aa42.png)

数据库tpt_arlerts
27088;"192.168.1.2[hengwei-server1]_[指标]磁盘卷[空闲]";"";"metric_trigger";12194;"2016-08-09 17:53:01.929569";"2016-09-07 13:26:33.464";2;"json2";"{"function":"0","attribute":"free","value":"104857600","operator":">"}";"disk_partition_free";"";TRUE;2;"[]";""

**Comment by eeiceyes** [comment]
fixed
