### ISSUE TITLE
建立新的角色 进入虚拟化视图【1696】

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#642]
使用新建的角色（角色具有所有权限），点击 运维管理-虚拟化视图 。提示没有权限
![image](https://cloud.githubusercontent.com/assets/20636259/18303166/44ef0ea2-750e-11e6-8636-4d0b02e7188b.png)
[新建文件夹.txt](https://github.com/three-plus-three/hw_issues/files/458505/default.txt)
（.txt 改成 .zip后解压）

**Comment by RasAlGu1** [comment]
运维管理：虚拟化视图服务总览、巡检文件管理 
监控管理：实时监控、

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
区分有没有添加虚拟中心的情况；如果没有添加过虚拟中心，默认会跳转到添加虚拟中心的界面，如果没有虚拟中心管理的权限，同样会报这个错误

**Comment by RasAlGu1** [comment]
没有添加虚拟中心时，仍然报错：没有权限。我分配权限的时候，新账号是拥有所有权限的

**Comment by RasAlGu1** [comment]
新建用户在 创建一个VCenter后，同步虚拟中心时出错

同步虚拟中心失败！ ### Error updating database. Cause: org.postgresql.util.PSQLException: 错误: 插入或更新表 "tpt_topology_link_relations" 违反外键约束 "tpt_topology_link_relations_mo_id_fkey" 详细：键值对(mo_id)=(2)没有在表"tpt_objects"中出现. ### The error may involve com.tpt.nm.biz.topology.dao.TopologyBizMapper.createLinkRelation-Inline ### The error occurred while setting parameters ### SQL: insert into tpt_topology_link_relations(mo_id, element_id, view_id, created_at, updated_at) values(?, ?, ?, ?, ?) ### Cause: org.postgresql.util.PSQLException: 错误: 插入或更新表 "tpt_topology_link_relations" 违反外键约束 "tpt_topology_link_relations_mo_id_fkey" 详细：键值对(mo_id)=(2)没有在表"tpt_objects"中出现. org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26) org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:154) org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:141) sun.reflect.GeneratedMethodAccessor227.invoke(Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) org.apache.ibatis.session.SqlSessionManager$SqlSessionInterceptor.invoke(SqlSessionManager.java:278) com.sun.proxy.$Proxy63.insert(Unknown Source) org.apache.ibatis.session.SqlSessionManager.insert(SqlSessionManager.java:198) org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:51) org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52) com.sun.proxy.$Proxy66.createLinkRelation(Unknown Source) com.tpt.nm.biz.topology.service.TopologyBase.createLink(TopologyBase.java:55) com.tpt.nm.biz.vmware_management.service.impl.VMWareTopologyManager.syncVMRelationChange(VMWareTopologyManager.java:154) com.tpt.nm.biz.vmware_management.service.impl.VMWareTopologyManager.listen(VMWareTopologyManager.java:67) sun.reflect.GeneratedMethodAccessor265.invoke(Unknown Source) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) com.tpt.nm.share.eventbus.EventHandler.handleEvent(EventHandler.java:72) com.tpt.nm.share.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45) com.tpt.nm.share.eventbus.EventBus.dispatch(EventBus.java:322) com.tpt.nm.share.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) com.tpt.nm.share.eventbus.EventBus.post(EventBus.java:266) com.tpt.nm.biz.vmware_management.service.impl.VMWareManagedObjectManager.syncVCenter(VMWareManagedObjectManager.java:191) com.tpt.nm.biz.vmware_management.service.impl.VMWareManagedObjectManager$$EnhancerByGuice$$876cd28a.CGLIB$syncVCenter$0(

**Comment by RasAlGu1** [comment]
服务总览 和 巡检文件管理 还是没有获得权限

**Comment by eeiceyes** [comment]
fixed
