### ISSUE TITLE
告警规则-显示出错

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#643]
在WMI设备上添加了数条提示级别为 “提示级” 的告警
![1](https://cloud.githubusercontent.com/assets/20636259/18337879/09d79988-75c7-11e6-95b5-e2701b524e8f.png)
在“提示级”中的当前告警中 显示为低级，并且 不计入 提示级 数中

![image](https://cloud.githubusercontent.com/assets/20636259/18337898/2882be6c-75c7-11e6-963f-f617f872abbb.png)
[web_server.txt](https://github.com/three-plus-three/hw_issues/files/460887/web_server.txt)
[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/460888/server_biz.txt)

**Comment by runner-mei** [comment]
请确认数据库 tpt_data 中 tpt_alert_cookies 中该告警的级别是多少

**Comment by RasAlGu1** [comment]
level 2
![image](https://cloud.githubusercontent.com/assets/20636259/18458953/5ea4c722-7998-11e6-8437-1c1cb89e4713.png)
