### ISSUE TITLE
告警管理-添加规则

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#644]
在添加规则页面中，选择网络设备-交换路由。参数设置下，展开ping测试，点击参数设置下的“点击设置参数”按钮。输入任意参数，然后点击确定按钮。随后页面上显示设置的参数，再次点击设置的参数，弹出设置参数页面，删除原来设置的参数，点击确定后。无法再次设置参数，“点击设置参数”为空。
![image](https://cloud.githubusercontent.com/assets/20636259/18377240/711fff8c-7698-11e6-825b-7868434fbfb8.png)

**Comment by eeiceyes** [comment]
fixed
