### ISSUE TITLE
WMI设备 告警-端口流量 

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#645]
WMI设备添加的告警-端口流量告警，告警失败，运行错误

![image](https://cloud.githubusercontent.com/assets/20636259/18423002/8fa8e3aa-78d3-11e6-8f2a-79f72b7be2e8.png)

**Comment by runner-mei** [comment]
问题没有解决，但错误描述已更改，将重新将错误日志发上来

**Comment by RasAlGu1** [comment]
[web_server (2).txt](https://github.com/three-plus-three/hw_issues/files/468655/web_server.2.txt)
[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/468656/server_biz.txt)

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/18462568/e8ee974c-79b5-11e6-846f-f547c47f2246.png)

**Comment by runner-mei** [comment]
fixed
