### ISSUE TITLE
机房视图-机柜视图-右键机柜内设备-当前告警

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#646]
有时右键设备，选择当前告警时，没有响应。需要再次操作才能实现
![image](https://cloud.githubusercontent.com/assets/20636259/18423224/e19979e8-78d5-11e6-8479-28700cf386b9.png)
[web_server.txt](https://github.com/three-plus-three/hw_issues/files/466447/web_server.txt)
[sever_biz.txt](https://github.com/three-plus-three/hw_issues/files/466446/sever_biz.txt)

**Comment by eeiceyes** [comment]
这个是不是已经好了

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170919_382_x64.exe  版本确认，close处理。
