### ISSUE TITLE
运维管理-当前巡检任务

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#647]
点击 运维管理-当前巡检任务，打开失败

![image](https://cloud.githubusercontent.com/assets/20636259/18424206/e575a50a-78df-11e6-9b41-f6df162ad982.png)

[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/466496/server_biz.txt)
[web_server.txt](https://github.com/three-plus-three/hw_issues/files/466497/web_server.txt)

**Comment by eeiceyes** [comment]
fixed
