### ISSUE TITLE
告警管理-告警日志-级别图标缺失

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#648]
级别图标缺失，变为未知
![222](https://cloud.githubusercontent.com/assets/20636259/18428372/2bbdd3fa-7900-11e6-90cf-63c1aace7691.png)

**Comment by eeiceyes** [comment]
告警历史记录没有存储告警级别，只能以该规则当前级别为准

**Comment by eeiceyes** [comment]
fixed
