### ISSUE TITLE
资源管理-IP服务分布

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#650]
先输入参数IP范围 192.168.1.1 - 192.168.1.255 ； 服务端口：80 点击查询后，显示IP服务分布

![image](https://cloud.githubusercontent.com/assets/20636259/18429980/0adbcdd2-7909-11e6-95db-a74ee65d703c.png)

再将服务端口改为 81 再次点击查询，查询结果为空， IP服务分布无变化 。还是显示原来的分钟样式

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180211_3262_x64.exe  版本确认，close处理。
