### ISSUE TITLE
CA新增一台深信服的VPN设备，需要我们添加支持

### ISSUE THREAD

**Issue by eeiceyes** [three-plus-three/hw_issues#651]
附件是张昭给的mib文件
[SANGFOR-SSL-MIB.zip](https://github.com/three-plus-three/hw_issues/files/469129/SANGFOR-SSL-MIB.zip)

**Comment by runner-mei** [comment]
运行视图


sangfor_general
sangfor_alarmInfo
sangfor_ethTable
sangfor_cpuLoadAvg
sangfor_status
sangfor_sfDiskTable
