### ISSUE TITLE
[bug] WMI主机线路取不到值

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#652]
主机取数为：WMI

主机添加线路 上下行带宽为“-8”
![image](https://cloud.githubusercontent.com/assets/14171497/18498086/54d00e86-7a66-11e6-8ffd-883547fa7e78.png)

主机端口信息
![image](https://cloud.githubusercontent.com/assets/14171497/18498071/31df3d20-7a66-11e6-90bc-17c3e5a4eddd.png)

修改上下行带宽值，线路颜色也是为蓝色

**Comment by runner-mei** [comment]
fixed
