### ISSUE TITLE
配置备份规则删除后仍在设备配置查看中显示

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#654]
配置备份规则删除后，原来的设备配置仍然在设备配置查看中存在，并且设置都是备份出错的，也无法删除几率。

**Comment by runner-mei** [comment]
配置备份规则删除后, 设备配置确实应该还在， 不过出错信息还在是不对的。

**Comment by runner-mei** [comment]
配置备份规则删除后, 设备配置确实应该还在， 不过出错信息还在是不对的。

**Comment by eeiceyes** [comment]
我试了下，现在规则删除后，备份的配置是能正常查看的

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，close处理。
hengwei_setup_3.2.20171027_2837_x64.exe   版本确认，close处理。
