### ISSUE TITLE
当前巡检任务在，建立的任务不显示

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#656]
新建立的巡检任务在“当前巡检任务”中没有显示。没有显示的任务为“每周指定段巡检”的任务，任务均为新建的。没有确定过。【今天是周日】
![image](https://cloud.githubusercontent.com/assets/20636259/18612555/f919183a-7d8f-11e6-937d-8527813204f0.png)
![image](https://cloud.githubusercontent.com/assets/20636259/18612560/00451898-7d90-11e6-9144-72e42af5fdc4.png)

**Comment by eeiceyes** [comment]
每周以周日为第一天，周六为最后一天
