### ISSUE TITLE
[IPMI] 风扇问题

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#658]
1.灰色的风扇鼠标放上去 为何状态为：OK ？  应该是：Not Installed
2.最后一个风扇“”fans“” 并没有，多一个风扇！ 并且状态为绿色，风扇还不动，详看IPMI界面监控图

![image](https://cloud.githubusercontent.com/assets/14171497/18613221/3308d22a-7da8-11e6-95ff-9b808530c2b8.png)

![image](https://cloud.githubusercontent.com/assets/14171497/18613216/20454ace-7da8-11e6-8ec1-bf3d181b18fc.png)

**Comment by eeiceyes** [comment]
fixed
