### ISSUE TITLE
[IPMI] IPMI测试功能异常

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#662]
![image](https://cloud.githubusercontent.com/assets/14171497/18614739/3879da1e-7dc7-11e6-8676-27da444dd2b7.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
设置参数、密码是什么

**Comment by eeiceyes** [comment]
192.168.1.15
Administrator
123456abc
