### ISSUE TITLE
右键设备-常用工具-Snmp测试中,读共同体名默认为空

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#668]
右键设备-常用工具-Snmp测试中,读共同体名默认为空。导致第一次结果为timeout，需要手动输入读共同体名后，再次测试才有结果。建议读共同体名改成第一次就有一个默认的。
![image](https://cloud.githubusercontent.com/assets/20636259/18622090/2757e356-7e5e-11e6-985f-2b9bc124cbe1.png)

![image](https://cloud.githubusercontent.com/assets/20636259/18622114/7b755932-7e5e-11e6-8795-4cb603e72fa5.png)

**Comment by eeiceyes** [comment]
已经不存在这个问题了
