### ISSUE TITLE
设备脚本执行-winrm设备执行脚本失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#669]
Winrm设备执行脚本时，提示读取设备访问参数失败
![image](https://cloud.githubusercontent.com/assets/20636259/18624085/100362ac-7e77-11e6-8f8d-cd3684fbbbd2.png)

**Comment by runner-mei** [comment]
系统设置中有一个网管机访问地址，设好就可以了

**Comment by RasAlGu1** [comment]
哪里设置 没找到。设置采数是什么

**Comment by runner-mei** [comment]
系统管理 ->    脚本共享设置

**Comment by runner-mei** [comment]
朱韩君，你加一个链接或说明吧，不然没人会用这个

**Comment by RasAlGu1** [comment]
只有脚本设置，没有脚本共享设置

**Comment by runner-mei** [comment]
系统管理 ->服务器设置->脚本共享设置

**Comment by eeiceyes** [comment]
加了个链接

**Comment by RasAlGu1** [comment]
链接添加成功。仍然无法执行脚本
![image](https://cloud.githubusercontent.com/assets/20636259/18737667/de8be350-80c6-11e6-8f7b-20b8e2778f3d.png)
脚本共享已经设置
![image](https://cloud.githubusercontent.com/assets/20636259/18737677/fe8b91b4-80c6-11e6-90cc-cb677bc18e6a.png)
