### ISSUE TITLE
数据库脚本管理执行错误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#670]
在点击“执行”时。提示错误，然而在指标一览中的“执行SQL语句”中 输入执行时。有结果
![image](https://cloud.githubusercontent.com/assets/20636259/18624185/1d55ce12-7e78-11e6-9157-1089d185a3dd.png)

![image](https://cloud.githubusercontent.com/assets/20636259/18624217/5b130cc4-7e78-11e6-850b-e8b840a7953e.png)

**Comment by runner-mei** [comment]
可能是后面有一个分号导致的

**Comment by eeiceyes** [comment]
fixed
