### ISSUE TITLE
数据库运行视图-指标一览-执行SQL语句

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#671]
测试数据库为ORACLE，选择预置脚本后，下方的SQL语句一览中不会显示预置脚本中的语句
![image](https://cloud.githubusercontent.com/assets/20636259/18624352/9be0dda2-7e79-11e6-9531-3610c3fb0acc.png)

**Comment by eeiceyes** [comment]
fixed
