### ISSUE TITLE
主机ACPI电源状态不匹配

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#688]
硬件信息面板显示系统电源 working   ，指标一览中显示为 0
![image](https://cloud.githubusercontent.com/assets/20636259/18857710/d2cc83be-8498-11e6-9fb0-6760f25bacfd.png)

![image](https://cloud.githubusercontent.com/assets/20636259/18857726/e6622cd0-8498-11e6-9ed5-f84c8ec1a480.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
指标一览中的系统电源数仍然为0
