### ISSUE TITLE
(广州南粤银行)树形结构的设备展现方式

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#692]
1、构建一棵可灵活增、删、改的树，目录与设备可同级
2、构建tag管理界面，可根据树形目录名称或自身需求增、删、改、查各个tag
3、在设备属性中添加一个设备tag项，做成类似于通知组的形式
![image](https://cloud.githubusercontent.com/assets/14171518/18897616/58ed78c0-855e-11e6-8036-f5f0a4307f90.png)
4、在树形图旁增加一个同步按钮，点击同步，如果目录名称包含在某一设备的tag标签中，该设备自动归入该目录下

结合昨天商量的提供一个小思路，你们看看要做些什么改进

**Comment by runner-mei** [comment]
````
  2、构建tag管理界面，可根据树形目录名称或自身需求增、删、改、查各个tag
````
我认为tag 是不必要的， 用资产管理信息可以代替 tag，但是资产管理信息需要增强，如可以指定资产信息中地域是一个下拉框， 下拉框中的选项是预定义的，可以由用户预先定义。

**Comment by runner-mei** [comment]
````
4、在树形图旁增加一个同步按钮，点击同步，如果目录名称包含在某一设备的tag标签中，该设备自动归入该目录下
````
无需同步按钮，只要刷新面要就可以了

**Comment by eeiceyes** [comment]
fixed
