### ISSUE TITLE
虚拟化复制统计报表立刻生成出现问题

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#699]
立即生成时会发生报错
![image](https://cloud.githubusercontent.com/assets/20636259/18903421/9f3b0bee-858b-11e6-8748-c1f6bcc4e819.png)
![image](https://cloud.githubusercontent.com/assets/20636259/18903425/a45f6d7c-858b-11e6-977d-37a40b517d3f.png)

![image](https://cloud.githubusercontent.com/assets/20636259/18903398/8173fbfc-858b-11e6-957d-fef6c677e217.png)

**Comment by eeiceyes** [comment]
fixed
