### ISSUE TITLE
服务对象树中对标准应用的运转视图无法跳转到

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#700]
标准应用的运转图无法跳转到，提示 资源未找到
![image](https://cloud.githubusercontent.com/assets/20636259/18939478/3a46b910-8633-11e6-807c-7cc3563cb116.png)

![image](https://cloud.githubusercontent.com/assets/20636259/18939489/522f01ea-8633-11e6-919a-94ab9f51af7f.png)

**Comment by eeiceyes** [comment]
fixed
