### ISSUE TITLE
机房视图首选机房有误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#708]
当机房视图中存在多个机房是，点击运维管理-机房视图时，进入的机房视图不是默认的机房视图

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，close处理。
hengwei_setup_3.2.20171027_2837_x64.exe   版本确认，close处理。
