### ISSUE TITLE
服务总览总对Windows进行监控设置出错

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#711]
点击Windows
![image](https://cloud.githubusercontent.com/assets/20636259/18978459/f50647bc-86f5-11e6-92cc-da0ded9bf5e4.png)
选择检测所有数据行
![image](https://cloud.githubusercontent.com/assets/20636259/18978462/0232c316-86f6-11e6-833b-f7392f3a360d.png)
选任意的管理对象，点击确定
![image](https://cloud.githubusercontent.com/assets/20636259/18978479/1a58ad02-86f6-11e6-8963-321569a0ebc6.png)
没有可以选择的监控项
![image](https://cloud.githubusercontent.com/assets/20636259/18978486/2a00b7a4-86f6-11e6-9f38-6860de14a520.png)

**Comment by eeiceyes** [comment]
fixed
