### ISSUE TITLE
[南京数据公司] 网络设备端口查看实时出入流量在一张图表上

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#712]
目前实时查看出入流量在一张图表上线路可以查看，设备端口还不可以查看
功能：功能如线路出入流量一样，出入流量可叠加，可堆积
如图：

![image](https://cloud.githubusercontent.com/assets/14171497/18979142/f2bf0782-86fa-11e6-8592-51a87ef4a96d.png)

**Comment by eeiceyes** [comment]
fixed
