### ISSUE TITLE
自定义资产信息

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#714]
自定义资产信息：由于有些现场会有类似于“维保期”之类的资产信息需要录入方便日后生成资产报表，现阶段设备属性自定义标签虽然可以做到标签设备，但是与报表关联不密切。
可以考虑将用户添加的自定义资产标签作为tag，作为报表中选取设备的过滤条件，以此来达到生成资产报表的目的

**Comment by runner-mei** [comment]
资产已有新版本， 请评估一下。
