### ISSUE TITLE
[杭州华数] 添加查看实时流量图的功能

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#715]
线路流量及端口流量的实时查看图类型于CATIA  
1.多个线路、端口（出入流量）显示在一张页面中。
参考下图：
![image](https://cloud.githubusercontent.com/assets/14171497/19211397/b9d0c54a-8d6d-11e6-8c4b-c851906571d5.png)

**Comment by eeiceyes** [comment]
fixed
