### ISSUE TITLE
巡检结果查询浏览巡检报告出错

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#728]
巡检结果查询，浏览巡检报告出错
![image](https://cloud.githubusercontent.com/assets/20636259/19298605/8028562a-9081-11e6-9fb7-89bf3d72848f.png)

![image](https://cloud.githubusercontent.com/assets/20636259/19298618/9c5c3622-9081-11e6-961d-3a27b6203e6d.png)

**Comment by eeiceyes** [comment]
原先这个目录在数据备份的时候没有被包含，现在把他加进去了

**Comment by eeiceyes** [comment]
fixed
