### ISSUE TITLE
巡检结果查询，导出结果为乱码

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#729]
导出的结果打开显示乱码

![image](https://cloud.githubusercontent.com/assets/20636259/19298649/fa46b3c0-9081-11e6-82c5-eef2873a8661.png)

![image](https://cloud.githubusercontent.com/assets/20636259/19298642/e9c8c8da-9081-11e6-86d7-6ce3eb67c8ea.png)

**Comment by eeiceyes** [comment]
fixed
