### ISSUE TITLE
巡检文件管理查看文件失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#730]
巡检文件管理中的.xlsx 文件点击查看后，下载的文件格式出错
![image](https://cloud.githubusercontent.com/assets/20636259/19298855/4b560f8a-9083-11e6-855d-d3c1d7615df6.png)

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/19298984/17da5a34-9084-11e6-8a88-6bd8cfc19572.png)

**Comment by eeiceyes** [comment]
fixed
