### ISSUE TITLE
在机柜视图中对设备使用Telnet失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#738]
右键设备，常用工具-Telnet，提示操作失败
![image](https://cloud.githubusercontent.com/assets/20636259/19334870/afb188f2-9131-11e6-84f6-4708c0edcff2.png)
![image](https://cloud.githubusercontent.com/assets/20636259/19334897/ddb38f84-9131-11e6-9500-1c8b599a8b36.png)

**Comment by eeiceyes** [comment]
ficxed
