### ISSUE TITLE
在机柜视图中，对设备使用SSH操作失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#739]
在机柜视图中，右键设备，常用工具-SSH ，操作失败。提示NO FOUND
![image](https://cloud.githubusercontent.com/assets/20636259/19334927/163c229e-9132-11e6-9177-3f091b0aa540.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
-
