### ISSUE TITLE
有时对设备进行操作时操作成功，没有执行结果

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#740]
例如，在机柜视图中时，右键对机器进行操作，如：常用工具，ping，WEB 等操作，有时会发生操作之后，没有响应的情况

![image](https://cloud.githubusercontent.com/assets/20636259/19335148/93358816-9133-11e6-9e21-8dbe74a68ef6.png)

**Comment by eeiceyes** [comment]
这个问题还存在吗？

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170919_382_x64.exe  版本确认，close处理。
