### ISSUE TITLE
机房视图找出设备失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#744]
在机房视图空白处右键，点击查询设备，在地址框内输入设备地址（机柜内存在的设备地址）
提示内部错误
![image](https://cloud.githubusercontent.com/assets/20636259/19423359/29fcf466-9452-11e6-8ccf-1187973ca24e.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
````
org.apache.ibatis.exceptions.PersistenceException: ### Error querying database. Cause: org.postgresql.util.PSQLException: 错误: 语法错误 在 ".1" 或附近的 位置：423 ### The error may exist in com/tpt/nm/biz/mos/dao/NetworkMapper.xml ### The error may involve com.tpt.nm.biz.mos.dao.NetworkMapper.allDevicesByParams-Inline ### The error occurred while setting parameters ### SQL: select id,name,zh_name as zhName, level, display_name as displayName, host(address) as ip,manufacturer, description,location,oid,device_type as deviceType, os_type as osType, engine_id as engineId, type,owner, owner_phone as ownerPhone, domain_id as domainId, domain_name as domainName, created_at as createdAt, updated_at as updatedAt from tpt_network_device_view where address = `192.168.1.6` order by ip asc limit 100000 offset 0 ### Cause: org.postgresql.util.PSQLException: 错误: 语法错误 在 ".1" 或附近的 位置：423
````

**Comment by RasAlGu1** [comment]
org.apache.ibatis.exceptions.PersistenceException: ### Error querying database. Cause: org.postgresql.util.PSQLException: 错误: 语法错误 在 ".1" 或附近的 位置：423 ### The error may exist in com/tpt/nm/biz/mos/dao/NetworkMapper.xml ### The error may involve com.tpt.nm.biz.mos.dao.NetworkMapper.allDevicesByParams-Inline ### The error occurred while setting parameters ### SQL: select id,name,zh_name as zhName, level, display_name as displayName, host(address) as ip,manufacturer, description,location,oid,device_type as deviceType, os_type as osType, engine_id as engineId, type,owner, owner_phone as ownerPhone, domain_id as domainId, domain_name as domainName, created_at as createdAt, updated_at as updatedAt from tpt_network_device_view where address = `192.168.1.6` order by ip asc limit 100000 offset 0 ### Cause: org.postgresql.util.PSQLException: 错误: 语法错误 在 ".1" 或附近的 位置：423

**Comment by eeiceyes** [comment]
fixed
