### ISSUE TITLE
机房视图添加机柜问题

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#745]
存在2个机房，谁为‘机房1‘,‘机房2‘。在‘机房2‘中有名称为‘001’的机柜。再在’机房1’中添加机柜，机柜名为‘001‘’时，添加失败，报错如下
![image](https://cloud.githubusercontent.com/assets/20636259/19423440/efe00ed4-9452-11e6-848a-0dd629c56ebf.png)

**Comment by eeiceyes** [comment]
fixed
