### ISSUE TITLE
业务视图中告警循环增大

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#747]
设置2个业务视图，2个业务视图中都存在视图节点。视图节点关联另一视图，使得2个视图循环。当一个视图中存在 告警时。会使得告警循环增大

**Comment by eeiceyes** [comment]
加了限制，不允许循环引用

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，提示的文字信息不够清楚，容易产生误导

![1509330272 1](https://user-images.githubusercontent.com/28615156/32152088-b38cb566-bd5c-11e7-9a46-910d3cb1e012.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171102_457_x64.exe   版本确认，close处理。
