### ISSUE TITLE
当前巡检任务，巡检填写

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#748]
填写巡检时，先按“确认所有项”按钮，所有巡检被确认，再按“确认正常项”按钮，巡检确认状态没有改变，异常项仍然是选定情况

**Comment by runner-mei** [comment]
确认一下， 问题还存在么？

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170725_210_x64.exe  版本还存在此现象

**Comment by eeiceyes** [comment]
就是这么设计的，就是几个快捷按钮，"确认正常项"，不是"只确认正常项"

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170919_382_x64.exe  版本确认，close处理。
