### ISSUE TITLE
实时监控导出的数据图像有问题

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#751]
导出的统计图形无法明确的表达。
![image](https://cloud.githubusercontent.com/assets/20636259/19431085/892bca7a-9489-11e6-96ab-9d843c299495.png)

实际图像:
![image](https://cloud.githubusercontent.com/assets/20636259/19431140/c8c6be38-9489-11e6-87f6-faf689e1d38b.png)

**Comment by eeiceyes** [comment]
fixed
