### ISSUE TITLE
历史记录提示出现错误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#762]
右键设备或者线路，选择历史记录里面的项。在历史记录弹出2小时的记录，其他记录为跳出时，关闭记录窗口。之后会弹出消息提示框
![image](https://cloud.githubusercontent.com/assets/20636259/19506863/880b024a-9601-11e6-96d3-e5bbd9556e65.png)

**Comment by eeiceyes** [comment]
fixed
