### ISSUE TITLE
监控管理-设备运行视图，无法打开主机 

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#764]
对象选择Windows主机（SNMP,Winrm,WMI）时，无法打开。提示内部错误

![image](https://cloud.githubusercontent.com/assets/20636259/19508253/c670dc5e-960a-11e6-8334-b0a94ddf2007.png)
![image](https://cloud.githubusercontent.com/assets/20636259/19508296/f70835e2-960a-11e6-8cf8-ee856324fca7.png)

**Comment by eeiceyes** [comment]
fixed
