### ISSUE TITLE
虚拟化视图-监控项

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#765]
在虚拟化视图-监控项中，选择监控项打开，然后关闭，页面显示异常、无法操作
![image](https://cloud.githubusercontent.com/assets/20636259/19510330/5cf7ff86-9615-11e6-953e-9fa340556903.png)

![image](https://cloud.githubusercontent.com/assets/20636259/19510338/677f4950-9615-11e6-8389-34e324a11429.png)

**Comment by eeiceyes** [comment]
fixed
