### ISSUE TITLE
设备迁移

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#768]
将设备121.0.0.6通过设备迁移改为121.0.0.66，迁移成功
再将121.0.0.66 迁移改成 121.0.0.6 ，提示迁移失败
![image](https://cloud.githubusercontent.com/assets/20636259/19548381/ba1a2430-96d0-11e6-8544-46be31c753ba.png)
通过“查找”查找121.0.0.6时，查找到121.0.0.66 设备

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe   版本确认，close处理。
