### ISSUE TITLE
WMI设备进程信息无法查看

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#770]
WMI的实时监控-进程信息无法查看
![image](https://cloud.githubusercontent.com/assets/20636259/19587412/c4a86658-9790-11e6-870c-fecc98d871d7.png)

**Comment by RasAlGu1** [comment]
wait

**Comment by eeiceyes** [comment]
wmi取进程信息非常慢

**Comment by eeiceyes** [comment]
确实是慢，没有办法了
