### ISSUE TITLE
图元管理自动添加图元

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#771]
在图元管理中，图元自动生成了与原先相同的图元
![image](https://cloud.githubusercontent.com/assets/20636259/19591951/330dfe3a-97ac-11e6-9656-3ca6a865356f.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
还有这个问题吗？鼠标移上去可以看图元的文件名

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170920_387_x64.exe  版本确认，close处理。
