### ISSUE TITLE
(南粤银行)当设备树中存在未识别设备时报错，树无法完成加载

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#780]

**Comment by eeiceyes** [comment]
<img width="313" alt="default" src="https://cloud.githubusercontent.com/assets/4076162/19642635/b91c10e8-9a18-11e6-8867-a67100bd1c14.png">

**Comment by eeiceyes** [comment]
错误描述看截图

**Comment by runner-mei** [comment]
fixed
