### ISSUE TITLE
（南粤银行）报表报错

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#781]
图片、文件无法上传，文字说明下
1、创建  设备运行情况报表  A
2、创建  设备端口使用情况报表  命名为与1相同的名称 A
3、点击确定报错
4、修改名称点击确定后生成的报表类型变为了  设备运行情况报表  
5、点击立即生成报错

**Comment by runner-mei** [comment]
fix?

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/21215888/d6907774-c2de-11e6-9938-045a61cb866a.png)
这条报错提示需要修改下，其他的问题都好了

**Comment by runner-mei** [comment]
这个没有什么好的办法
