### ISSUE TITLE
拓扑视图，右键设备实时监控-CPU,提示未选择设备

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#784]
在拓扑视图和虚拟化视图中，右键设备，点击实时监控-内存，出现错误提示框。
![image](https://cloud.githubusercontent.com/assets/20636259/19674254/6d3838cc-9ab9-11e6-99aa-0e00dd3bc7e9.png)
![image](https://cloud.githubusercontent.com/assets/20636259/19674296/ae1d6d26-9ab9-11e6-8ce7-d48da2be4fc7.png)

**Comment by eeiceyes** [comment]
fixed
