### ISSUE TITLE
Linux设备编辑异常

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#785]
对拓扑图上的Linux设备设备进入编辑页面，对已经设备的SNMP参数点击测试按钮。提示测试通过，然后点击编辑按钮，以保存编辑。页面一直显示加载中。
![image](https://cloud.githubusercontent.com/assets/20636259/19675592/b7eefbd2-9ac1-11e6-8d13-3d251d201fb3.png)
 对网页进行刷新，提示保存失败
![image](https://cloud.githubusercontent.com/assets/20636259/19675608/c5b04fbe-9ac1-11e6-9c6c-062f0736f130.png)

**Comment by eeiceyes** [comment]
fixed
