### ISSUE TITLE
报表规则管理-添加报表界面错误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#786]
生成方式模块有误
![image](https://cloud.githubusercontent.com/assets/20636259/19677670/f77b78e2-9acc-11e6-99a2-2d6ec28c4f44.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-lhm** [comment]
fixed

**Comment by RasAlGu1** [comment]
reopen

**Comment by hengwei-lhm** [comment]
fixed
