### ISSUE TITLE
设备端口使用情况报表，添加成功后，成功提示出现错误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#787]
设备端口使用情况报表，添加成功后返回主界面没有添加成功提示，再次进入编辑或者添加剂界面，界面上方出现成功提示
![image](https://cloud.githubusercontent.com/assets/20636259/19677889/061a8342-9ace-11e6-8557-ceeb640f07ad.png)

**Comment by hengwei-lhm** [comment]
fix

**Comment by RasAlGu1** [comment]
reopen

**Comment by RasAlGu1** [comment]
fixed
