### ISSUE TITLE
添加报表界面-流量统计，设备选择中的复制黏贴无法实现

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#788]
添加报表界面-流量统计，设备选择中的复制选择项和粘贴选择性按钮，无法实现功能
![image](https://cloud.githubusercontent.com/assets/20636259/19678024/a0fba7a6-9ace-11e6-8321-b7f1c8514035.png)

**Comment by hengwei-lhm** [comment]
fixed
