### ISSUE TITLE
设备端口、设备运行报表，对其进行编辑时。原先的数据缺失

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#791]
对添加的报表进行编辑时，原来添加的数据在编辑页面不显示。数据丢失
![image](https://cloud.githubusercontent.com/assets/20636259/19678700/5f779c88-9ad1-11e6-98ca-f2b3a5126f56.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-lhm** [comment]
fixed
