### ISSUE TITLE
设备端口、设备运行报表，添加和编辑页面的取消按钮均无法实现作用

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#792]
设备端口、设备运行报表。的添加和编辑设备页面中，右下角的取消按钮，点击后均无响应，没有实现功能

![image](https://cloud.githubusercontent.com/assets/20636259/19678823/f5914d9a-9ad1-11e6-83d3-3dd7194124fe.png)

**Comment by hengwei-lhm** [comment]
fixed
