### ISSUE TITLE
报表管理-设备负载统计报表，趋势分析设备无法选择

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#796]
使用复制选择项复制主机设备，在趋势分析中点击粘贴选择性，选择设备后，点击关闭按钮，返回主界面，显示对象选择仍然为0
![image](https://cloud.githubusercontent.com/assets/20636259/19715132/b2ea1026-9b85-11e6-8bd0-076516671603.png)

![image](https://cloud.githubusercontent.com/assets/20636259/19715140/bc70313e-9b85-11e6-8892-5cf22f46d564.png)

**Comment by eeiceyes** [comment]
fixed
