### ISSUE TITLE
(南粤银行)需求列表

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#801]
1、配置备份自定义脚本功能；（该功能完成后路由变更监控同时也可由该功能完成）
2、全网设备ping时延top10界面：在监控总览中修改ping检测面板，在面板中可以选择全网设备，展示界面在原有可达的基础上增加下列项，按照时延进行top排序参照下图：
![image](https://cloud.githubusercontent.com/assets/14171518/19733364/5c1130bc-9bd6-11e6-89a3-68adfd584c07.png)

3、设备过保告警：设备上增加时间格式维保标签，根据将这个时间与系统时间进行比对进行过保告警提示
4、背板带宽
5、配置文件浏览界面增加一个导出配置文件功能
6、右侧导航栏中“服务总览”改为“设备总览”，点击直接跳转到“设备总览”页面，将“服务监视”隐藏。

**Comment by runner-mei** [comment]
都已实现了吧
