### ISSUE TITLE
右键设备，添加告警时，添加页面容易卡死

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#802]
点击“其他告警”后，跳转到添加告警页面，设备告警参数如：CPU理由率>90 ，内存利用率>90% ，磁盘已使用了>90% , 设备告警级别等参数后 ，点击确定按钮。页面会显示一直在加载中
![image](https://cloud.githubusercontent.com/assets/20636259/19760757/b53e97ee-9c65-11e6-81d6-5c221ae64060.png)

![image](https://cloud.githubusercontent.com/assets/20636259/19760829/0b15fa7c-9c66-11e6-9af2-aefa9a2fe590.png)

**Comment by eeiceyes** [comment]
这个问题还存在吗？再验证下

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170922_2764_x64.exe  版本确认，close处理。
