### ISSUE TITLE
右键设备-添加告警，端口类告警

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#803]
选择端口状态或端口流量告警，点击后出现相对应的端口告警窗口，
![image](https://cloud.githubusercontent.com/assets/20636259/19761149/459e13fe-9c67-11e6-9574-a5ec104eb6c3.png)
在窗口中，选择与不选择数据的情况下，点击确定按钮，均可能发生页面出现一直处于加载中的状态。（在窗口中，当窗口数据很少时，会添加成功）
![image](https://cloud.githubusercontent.com/assets/20636259/19761210/896d03ec-9c67-11e6-8372-ed4af78961c8.png)

![image](https://cloud.githubusercontent.com/assets/20636259/19761266/ba8a8364-9c67-11e6-9d40-3cb89eefc97f.png)

**Comment by eeiceyes** [comment]
这个问题还存在吗？再验证下

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170922_2764_x64.exe  版本确认，还存在

**Comment by eeiceyes** [comment]
加上端口为选择的提示

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，close处理。
hengwei_setup_3.2.20171027_2837_x64.exe   版本确认，close处理。
