### ISSUE TITLE
添加通知方式，syslog测试失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#805]
在添加syslog通知时 ，不填写“标签”栏时，测试失败。

![image](https://cloud.githubusercontent.com/assets/20636259/19827516/606a4a58-9ddf-11e6-83c1-8dfd96305172.png)

![image](https://cloud.githubusercontent.com/assets/20636259/19827494/e268fcf8-9dde-11e6-84dd-71edd3d07f5f.png)

**Comment by runner-mei** [comment]
fixed
