### ISSUE TITLE
TFTP脚本管理-提示不友好

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#807]
在TFTP脚本设备时，若只填写的脚本而不选择设备时，点击确定，提示错误信息不友好
![image](https://cloud.githubusercontent.com/assets/20636259/19827802/8f41581e-9de7-11e6-9f34-b791814e1814.png)

![image](https://cloud.githubusercontent.com/assets/20636259/19827788/70efcdaa-9de7-11e6-8ade-70362fe62198.png)

**Comment by eeiceyes** [comment]
fixed
