### ISSUE TITLE
设备总览中，监控项的运行时间没有自动生成历史规则

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#808]
设备监控项的运行时间，没有自动生成历史规则

![image](https://cloud.githubusercontent.com/assets/20636259/19827884/82840f0c-9de9-11e6-9c93-be1e93a34460.png)

**Comment by eeiceyes** [comment]
故意不设置的，没有意义

**Comment by eeiceyes** [comment]
close吧

**Comment by RasAlGu1** [comment]
点击这个选择，展开的窗口会显示没有设置历史记录。可以修改一下弹出的窗口
![image](https://cloud.githubusercontent.com/assets/20636259/20910636/ab2391ae-bb9d-11e6-85d2-7fec8f195004.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
运维管理-**设备总览**中的运行时间窗口也设置不弹出
![image](https://cloud.githubusercontent.com/assets/20636259/21086911/dbd00dd8-c05b-11e6-87a1-dbd271e8d5c6.png)

**Comment by eeiceyes** [comment]
fixed
