### ISSUE TITLE
主机运转视图-当前告警颜色问题

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#812]
某些告警的颜色显示有问题
![image](https://cloud.githubusercontent.com/assets/20636259/19877598/a7e1a9b0-a01b-11e6-83c4-202e9ba615cc.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170922_2764_x64.exe  版本确认，close处理。
