### ISSUE TITLE
schd_jobs, 自己新添加的任务无法编辑

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#816]
新添加的任务默认均为系统任务，无法进行编辑
![image](https://cloud.githubusercontent.com/assets/20636259/19991604/b1368cda-a271-11e6-98b4-6b18b8050e22.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by hengwei-lhm** [comment]
fixed
