### ISSUE TITLE
通知查询

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#819]
mc/notifications/confirmed
目录和消息查找对应的数据是什么。在下方的对应数据是什么。和下方的对应数据不匹配。
每页显示条目移动到右边

![image](https://cloud.githubusercontent.com/assets/20636259/19992184/baeb38fc-a276-11e6-8081-dab24c2d4946.png)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by RasAlGu1** [comment]
内容和目录查找均无法查找到数据
![image](https://cloud.githubusercontent.com/assets/20636259/20166072/3b8278ce-a74d-11e6-8048-dbbd3af55899.png)

**Comment by hengwei-lhm** [comment]
fixed
