### ISSUE TITLE
提示消息不会自动消失

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#820]
创建或者编辑成功后的 提示消息不会自动消失，设备成5秒后自动关闭

![image](https://cloud.githubusercontent.com/assets/20636259/19992250/5feacb56-a277-11e6-8053-9640925c7e0c.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
成功提示用alert-info，错误提示用alert-error，alert-error现在需要用户手动删除
