### ISSUE TITLE
告警提示栏中，告警显示错误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#823]
紧急级中出现高级告警。这条高级本来是高级，改成紧急级后，在告警栏中的级别仍显示为高级却出现在紧急栏中
![image](https://cloud.githubusercontent.com/assets/20636259/20049789/50d31412-a500-11e6-971d-1da9f1b25393.png)

**Comment by eeiceyes** [comment]
fixed
