### ISSUE TITLE
端口告警添加有误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#828]
同一种端口告警可以重复添加，并且添加时，会一次添加2条告警规则

![image](https://cloud.githubusercontent.com/assets/20636259/20085883/13c02766-a5a7-11e6-9b57-315db65d9545.png)

**Comment by eeiceyes** [comment]
重复添加是可以的

**Comment by eeiceyes** [comment]
fix一次添加出现两条的问题
