### ISSUE TITLE
设备配置任务

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#835]
只改了显示的50，实际还是40

![image](https://cloud.githubusercontent.com/assets/20636259/20167226/0ff885c4-a755-11e6-86fe-bfe0e547fc02.png)

**Comment by RasAlGu1** [comment]
备份任务无法触发

**Comment by hengwei-lhm** [comment]
fixed

**Comment by RasAlGu1** [comment]
每天 和每周的 还是一样 没有该回来

**Comment by RasAlGu1** [comment]
创建的任务 enable boolean 值为 false
