### ISSUE TITLE
告警邮件通知有问题

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#836]
预期：邮件通知方式有设置重复通知
先在告警中设置邮件通知方式，等到告警发生通知之后，再将通知方式中的邮件通知改为不通知，之后一段时间内，还会收到重复的告警通知

**Comment by runner-mei** [comment]
我认为这是不对的， 告警发生通知之后，再将通知方式中的邮件通知改为不通知， 和正在执行的通知是不相干的。
不过禁用告警规则后，如果还在发则是不对的
