### ISSUE TITLE
脚本管理，保存成功提示框位置有问题

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#843]
![image](https://cloud.githubusercontent.com/assets/20636259/20298114/1c01af64-ab4f-11e6-803c-24f2c933b6cd.png)

**Comment by runner-mei** [comment]
3.2 中还有么？

**Comment by xiauye** [comment]
sh脚本执行结果有乱码
![image](https://user-images.githubusercontent.com/22296563/28861420-7062b3a8-7793-11e7-8e55-e4484ac5af8d.png)

**Comment by runner-mei** [comment]
fix?
