### ISSUE TITLE
（南粤银行）流量数据查询页面，纵轴与曲线上的值单位不一致，容易引起用户误会，修改一致

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#847]
![734682967389506707](https://cloud.githubusercontent.com/assets/14171518/20300638/07e7aafe-ab5b-11e6-92d5-1c808c9dafc0.jpg)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/20374156/ae1d69b6-acb1-11e6-831c-ccda9e3d628b.png)
