### ISSUE TITLE
新用户，在登录时删除用户出现错误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#849]
当登录用户删除自己的用户时，会出现提示。
![image](https://cloud.githubusercontent.com/assets/20636259/20341129/c0fab742-ac1f-11e6-895b-d55b4922ea37.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
与原先一样

**Comment by RasAlGu1** [comment]
fixed
