### ISSUE TITLE
设备管理-生成拓拓扑图-拓扑添加失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#854]
在增加新的IP段，使用拓扑添加进行添加设备时，新加IP段内的设备没有被添加进行。
而在拓扑生成时，新加IP段内的设备会被添加进去

**Comment by RasAlGu1** [comment]
拓扑添加的功能还是无效，原来网段内的设备删除后，拓扑添加也添加不上去。新增网段的设备也没有去识别

**Comment by runner-mei** [comment]
在其他选项中有一个 “不扫描新设备” 的选项不要勾选
