### ISSUE TITLE
常用工具Trace Route

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#860]
![image](https://cloud.githubusercontent.com/assets/20636259/20508161/947e4998-b09a-11e6-9138-c210a0d6f5f2.png)

**Comment by runner-mei** [comment]
3. 安装依赖包 net-snmp， traceroute， bind-utils, fontconfig
   yum -y install net-snmp           # 右键 snmp 测试和采数
   yum -y install traceroute         # 右键 tracert 命令
   yum -y install bind-utils         # 右键 dig 命令
   yum -y install fontconfig         # 生成报表需要用到
