### ISSUE TITLE
进行信息中出现乱码

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#861]
主机192.168.1.6上
![image](https://cloud.githubusercontent.com/assets/20636259/20511660/1a0688ea-b0b5-11e6-9162-a6b3b5f66873.png)

**Comment by runner-mei** [comment]
这个不是我的 bug, 正确的 中文是好的，这个在进程管理器中也是乱码， 你可自己找一个进程管理器中不是乱码的看看

**Comment by RasAlGu1** [comment]
知道了 close
