### ISSUE TITLE
（idea）增加设备间发现线路的功能

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#872]
用户场景：
有些现场添加设备之后想发现设备间线路，利用拓扑添加可以完成这一需求，但是当设备比较多或者只想对新增的几台设备之间发现时操作稍有不便
新增需求：
1、框选需要发现线路的几台设备，右键点击“发现线路”功能
2、在空白处右键点击“发现线路”，弹出设备选择框，可选择需要发现线路的设备

**Comment by runner-mei** [comment]
我后台已支持， 参数据指定不扫描新设备就行了
