### ISSUE TITLE
[镇江农商行]check point 防火墙支持

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#874]
厂商：check point 
防火墙地址：32.223.242.6
walk数据：附件！
OID：1.3.6.1.4.1.8072.3.2.10
MIB：
[SecurePlatform_SNMP_OS_MIB.pdf](https://github.com/three-plus-three/hw_issues/files/615707/SecurePlatform_SNMP_OS_MIB.pdf)
[32.223.241.6.txt](https://github.com/three-plus-three/hw_issues/files/912531/32.223.241.6.txt)

**Comment by runner-mei** [comment]
无 walk 文件，无法支持

**Comment by runner-mei** [comment]
我看了一下这个， 他没有私有 Mib, 都是标准的 mib
mem 确实高，这个没有办法， 不是我们取错了，就是这个样子
