### ISSUE TITLE
Linux主机运转视图，执行脚本

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#876]
设备名，显示有问题
![image](https://cloud.githubusercontent.com/assets/20636259/20661473/e2c0ca06-b589-11e6-957f-02727c734a74.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
还是存在问题
![image](https://cloud.githubusercontent.com/assets/20636259/20910771/9b7dc1ec-bb9e-11e6-9375-a3ff5f2530c4.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
