### ISSUE TITLE
执行脚本的结果报错

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#877]
![image](https://cloud.githubusercontent.com/assets/20636259/20661844/c1975c12-b58b-11e6-9e8f-92e6ecc0e63a.png)

**Comment by runner-mei** [comment]
将 plink 改成 ssh

**Comment by eeiceyes** [comment]
fixed

**Comment by runner-mei** [comment]
如果有错的话，出错信息会不一样，你将错误重贴上来

**Comment by RasAlGu1** [comment]
fork/exec runtime_env/putty/plink.exe: no such file or directory

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
重复点击执行，前一次执行的结果不会消失，而且还是执行错误
![image](https://cloud.githubusercontent.com/assets/20636259/21249219/7ce37b1a-c377-11e6-911d-8ed139691e24.png)

**Comment by eeiceyes** [comment]
现在的情况是第一次调用是好的，第二次开始就出错了

**Comment by eeiceyes** [comment]
会等一会报timeout

**Comment by runner-mei** [comment]
fix?

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171129_535_x64.exe 版本确认，close处理。
