### ISSUE TITLE
添加端口状态告警，添加一次，会产生十几条的告警规则

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#878]
添加端口状态告警，添加一次，会产生十几条的告警规则
![image](https://cloud.githubusercontent.com/assets/20636259/20694643/95cf2952-b621-11e6-8699-118e87a4cc57.png)

![image](https://cloud.githubusercontent.com/assets/20636259/20694657/a5f78afe-b621-11e6-922b-b5fe80302975.png)

**Comment by eeiceyes** [comment]
最新版本未重现

**Comment by hengwei-test** [comment]
tpt-2.3.20170821.166~7a131d8.x86_64.rpm 版本确认，close处理。
