### ISSUE TITLE
FTP,上传备份

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#881]
FTP立刻上传备份
![image](https://cloud.githubusercontent.com/assets/20636259/20698776/4c86e358-b63e-11e6-8f08-6af8bf2cd1c4.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
还是原来的样子

**Comment by RasAlGu1** [comment]
exec: "tpt_upload_backup": executable file not found in $PATH
