### ISSUE TITLE
设备备份规则没有被触发执行

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#882]
![image](https://cloud.githubusercontent.com/assets/20636259/20699227/2da37304-b641-11e6-8035-b1ba29bf30ab.png)
![image](https://cloud.githubusercontent.com/assets/20636259/20699232/3644a0dc-b641-11e6-8171-a9106652f91f.png)

**Comment by runner-mei** [comment]
fixed
