### ISSUE TITLE
设备规则查看，规则状态

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#883]
点开显示规则上传失败
![image](https://cloud.githubusercontent.com/assets/20636259/20746285/1bb735c4-b720-11e6-8d9f-f83267d2ee92.png)

**Comment by runner-mei** [comment]
fix

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/20952145/4adc3b8e-bc65-11e6-9597-70bf262a9691.png)
