### ISSUE TITLE
添加告警规则时，点击“全选”或者“清空”按钮，会出现异常提示

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#885]
点击“全选”或者“清空”按钮，会出现异常提示
![image](https://cloud.githubusercontent.com/assets/20636259/20823366/4a4a594c-b88e-11e6-93f2-dc9c7d3c8d99.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
问题仍然存在

**Comment by eeiceyes** [comment]
肯定好了，应该测试版本的原因

**Comment by RasAlGu1** [comment]
fixed
