### ISSUE TITLE
巡检任务的过期任务总数错误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#889]
任务总数变为0，也有任务名称丢失情况
![image](https://cloud.githubusercontent.com/assets/20636259/20824935/787fdabe-b89b-11e6-86e2-751af6535f8b.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.2.20170831.901~70e2f59.x86_64.rpm  版本确认，close处理。
