### ISSUE TITLE
(国联安)自定义告警通知项中告警分页错误

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#891]
自定义告警通知项中告警数量为三百多条，点击进去分页显示两页，但是点击第二页为空白
![image](https://cloud.githubusercontent.com/assets/14171518/20910036/17e48fb8-bb9a-11e6-8496-3a15c3e01a89.png)

**Comment by eeiceyes** [comment]
这个问题还能重现吗?

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180125_3210_x64.exe 版本确认，还出现此现象

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180202_3234_x64.exe  版本确认，close处理。
