### ISSUE TITLE
缩略图线路连接方式设置时。先竖后横和先横后竖显示一样

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#894]
![image](https://cloud.githubusercontent.com/assets/20636259/20953428/86d8b9b0-bc6e-11e6-8301-b782e9791d75.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe   版本确认，close处理。
