### ISSUE TITLE
SNMP、Trace route 测试失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#897]
![image](https://cloud.githubusercontent.com/assets/20636259/20996734/af23dcd4-bd3a-11e6-9288-b5d82690df41.png)

**Comment by runner-mei** [comment]
确认下面两条是否成功
sudo apt-get -y install snmp                        # 右键 snmp 测试和采数
sudo apt-get -y install traceroute                  # 可选，右键 tracert 命令

**Comment by RasAlGu1** [comment]
fixed
