### ISSUE TITLE
[杭州华数] 线路历史数据查询最大值平均值有误

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#898]
根图，线路历史记录查询（线路、端口）最大值、平均值跟图标值不对应

![image](https://cloud.githubusercontent.com/assets/14171497/21005805/467defda-bd71-11e6-91d1-7ca14aa0a745.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
平均值与图标值不对应
![image](https://cloud.githubusercontent.com/assets/20636259/21299767/ae2edbb0-c5d9-11e6-9bc0-bf56f31db904.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe   版本确认，close处理。
