### ISSUE TITLE
ping告警异常。

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#899]
ping告警异常发生，拓扑图上面的设备是可以ping通的。却发生告警
![image](https://cloud.githubusercontent.com/assets/20636259/21038501/36fd244a-be11-11e6-815e-828827399b28.png)

**Comment by runner-mei** [comment]
无法重现，待观察

**Comment by RasAlGu1** [comment]
有可能是多台网管设备连接到同一个数据库，导致的问题
