### ISSUE TITLE
当前巡检任务。提交后，提示错误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#900]
当前巡检任务。点击打开巡检填写页面后，点击提交，提示错误
![image](https://cloud.githubusercontent.com/assets/20636259/21038918/b71a92ea-be14-11e6-961e-666f69045dda.png)

**Comment by runner-mei** [comment]
我改好了， 朱韩君请注意，脚本的第一行是非常重要的， 虽然看起来是注释，但实际上它不是注释。

#!/usr/bin/bash 改居  #!/bin/bash
