### ISSUE TITLE
虚拟化视图，拓扑图上主机CPU数据显示缺失

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#904]
![image](https://cloud.githubusercontent.com/assets/20636259/21086506/172f7c0a-c058-11e6-9661-4435d4fe000e.png)
虚拟化主机运转视图中,CPU和内存的显示缺失
![image](https://cloud.githubusercontent.com/assets/20636259/21086754/54ab5246-c05a-11e6-8c9b-e8c70c120d02.png)

**Comment by runner-mei** [comment]
fix
