### ISSUE TITLE
虚拟化负载统计报表，内存利用率没有数据

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#905]
![image](https://cloud.githubusercontent.com/assets/20636259/21086769/897a4e00-c05a-11e6-92ed-46e743a7a2ea.png)

**Comment by runner-mei** [comment]
fix

**Comment by RasAlGu1** [comment]
生成的还是没有内存利用率

**Comment by RasAlGu1** [comment]
记录的规则有记录到数据，到“虚拟化负载统计报表”中报表没有统计数据
![image](https://cloud.githubusercontent.com/assets/20636259/24788203/cc483e0a-1b9e-11e7-933a-1a2a119fe915.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170823_2647_x64.exe 版本确认，close处理。
