### ISSUE TITLE
设备备份后，恢复到其他机器的客户端时，报表里的设备对不上

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#907]
设备备份后，恢复到其他机器的客户端时，报表里的设备对不上
![image](https://cloud.githubusercontent.com/assets/20636259/21088645/0cbedf86-c06c-11e6-9d53-cb400715ce2d.png)

**Comment by runner-mei** [comment]
这个你有什么好建议

**Comment by eeiceyes** [comment]
这个没有办法，原先报表里设置的设备已经不存在了，顶多显示的更友好点

**Comment by eeiceyes** [comment]
@hengwei-test 再验证下这个问题还存在吗
