### ISSUE TITLE
数据管理-地址簿总览打开失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#910]
打开了地址簿采集
环境 ：192.168.1.201:8080 
192.168.1.155:37070
![image](https://cloud.githubusercontent.com/assets/20636259/21091017/7c1eca5a-c07e-11e6-9fd2-0581e8800b04.png)

**Comment by eeiceyes** [comment]
数据重搞下就好了，多套系统连一个数据库造成

**Comment by runner-mei** [comment]
那也不对吧，就算多套系统连一个数据库， 也不应该啊？
