### ISSUE TITLE
右键设备-端口状态告警，窗口中端口重复

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#911]
右键设备-添加告警-端口状态告警，窗口中的端口出现重复。

![image](https://cloud.githubusercontent.com/assets/20636259/21093702/35a46732-c08e-11e6-9fc0-2a0231787d3b.png)

**Comment by eeiceyes** [comment]
把数据重搞下，现在不会出现了

**Comment by eeiceyes** [comment]
fixed
