### ISSUE TITLE
添加线路时，界面中的源目交换按钮功能无法实现

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#913]
对添加后的线路使用。可以实现功能
![image](https://cloud.githubusercontent.com/assets/20636259/21128788/9c84a3f4-c138-11e6-9cf0-71bec131031a.png)

**Comment by eeiceyes** [comment]
添加时隐藏该功能

**Comment by RasAlGu1** [comment]
Linux 系统，添加线路时，该按钮仍然存在

**Comment by RasAlGu1** [comment]
fixed
