### ISSUE TITLE
线路显示设置-单位也设置的有出入

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#914]
线路显示设置中，总流量单位显示设置为Mb/s 。并且在下标中显示。实际下标显示的单位与设置不符
![image](https://cloud.githubusercontent.com/assets/20636259/21129043/497377c4-c13a-11e6-81e9-dfb48695f227.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
Ubuntu的版本仍然存在这个问题
