### ISSUE TITLE
Linces生成工具页面，提示没有权限

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#915]
![image](https://cloud.githubusercontent.com/assets/20636259/21130909/68f83f24-c146-11e6-91b1-484464d55ceb.png)

**Comment by runner-mei** [comment]
fix

**Comment by RasAlGu1** [comment]
2016/12/15 09:47:12 [info] load properties '/usr/local/tpt/conf/app.properties'. 2016/12/15 09:47:12 [info] load properties '/etc/tpt/app.properties'. 2016/12/15 09:47:12 [info] load properties '/usr/local/tpt/conf/engine.properties'. 2016/12/15 09:47:12 [warn] load tsdb http port (37086) from /usr/local/tpt/conf/tsdb_config.conf 2016/12/15 09:47:12 [warn] load tsdb admin port (39183) from /usr/local/tpt/conf/tsdb_config.conf write tsn to file, open /var/lib/tpt/tpt-license.tsn: permission denied exit status 148

**Comment by runner-mei** [comment]
fix
