### ISSUE TITLE
服务总览-修改自定义监控项时。修改指标，属性值没有改变

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#919]
监控种类为，数据库-oracle
![image](https://cloud.githubusercontent.com/assets/20636259/21171911/fd8f7918-c209-11e6-9214-64f866c9eca3.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170919_382_x64.exe  版本确认，close处理。
