### ISSUE TITLE
Winrm采集方式的主机采数不稳定

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#920]
设备经常出现无法采集到的现象
![image](https://cloud.githubusercontent.com/assets/20636259/21173219/a7ba1996-c211-11e6-9a2e-e17844b7b629.png)

**Comment by RasAlGu1** [comment]
{"channel":"cpu/3884/","client_name":"-","client_id":8,"created_at":"2016-12-14T15:40:55.2039738+08:00","error":{"code":562001,"message":"internal error:\r\n    cpu_win32_winrm: arguments must is two string and a options map[string]string.\r\n    cpu_win32_wmi: 'wmi' is required.\r\n    cpu_host_resource: snmp is missing.\r\n    read 'sys.oid' failed, snmp is missing.","internals":[{"code":500,"fields":{"metric_id":"cpu_win32_winrm"},"message":"arguments must is two string and a options map[string]string."},{"code":404,"fields":{"metric_id":"cpu_win32_wmi"},"message":"'wmi' is required."},{"code":400102,"fields":{"metric_id":"cpu_host_resource"},"message":"snmp is missing."},{}]}
,"engine_id":0}

**Comment by runner-mei** [comment]
你再试一下， 看看错误是什么？我改了描述

**Comment by RasAlGu1** [comment]
rpc time out
