### ISSUE TITLE
业务视图添加编辑功能

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#923]
复制完毕后的“业务视图”没有编辑名称功能

![image](https://cloud.githubusercontent.com/assets/14171497/21209637/625c3f6a-c2b0-11e6-88c8-d7565c91bd20.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe   版本确认，close处理。
