### ISSUE TITLE
标准应用管理-运行视图中的数据显示值有 倍差

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#928]
差10的6次倍
![image](https://cloud.githubusercontent.com/assets/20636259/21255178/2e3b9a50-c3a5-11e6-8124-7d19a9214279.png)

**Comment by runner-mei** [comment]
确认一下，还有这个问题么？

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170725_210_x64.exe  版本还出现此现象
