### ISSUE TITLE
告警触发脚本失败

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#93]
== delayed_job 规则的设置如下

runtime_env/putty/plink.exe -batch -pw {{sparams "ssh.user_password"}} {{params "ssh.user_name"}}@{{.managed_object.address}} -m start.sh

== delayed_job 表中结果如下
{
  "command": "runtime_env/putty/plink.exe -batch -pw \u003cno value\u003e \u003cno value\u003e@192.168.1.66 -m start.sh",
  "created_at": "2015-12-09T17:01:55.918Z",
  "description": "",
  "id": 26655,
  "max_attempts": 25,
  "name": "start splunk",
  "parent_id": 2,
  "parent_type": "notification_group",
  "prompt": "hyhhhhhhhhhhhhhhhhhhhhhhhhh",
  "type": "exec_command",
  "updated_at": "2015-12-09T17:32:43.231Z",
  "work_directory": ""
}

**Comment by runner-mei** [comment]
已修复
