### ISSUE TITLE
右键线路-实时监控-流量。

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#930]
标题单位不正确。 线路流量数据 和坐标轴上的数据对不上
![image](https://cloud.githubusercontent.com/assets/20636259/21302995/4ea2c752-c5f6-11e6-93c7-00fc89c78b4f.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe   版本确认，close处理。
