### ISSUE TITLE
CenterOS设备取不到IP地址表

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#933]
internal error: ip_address_wmi: 'wmi' is required. ip_address_linux: failed to parse 'eth0: flags=4163 mtu 1500 inet 192.168.1.157 netmask 255.255.255.0 broadcast 192.168.1.255 inet6 fe80::215:5dff:fe01:d728 prefixlen 64 scopeid 0x20 ether 00:15:5d:01:d7:28 txqueuelen 1000 (Ethernet) RX packets 41314609 bytes 9122327924 (8.4 GiB) RX errors 0 dropped 0 overruns 0 frame 0 TX packets 41224846 bytes 8130609979 (7.5 GiB) TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0 lo: flags=73 mtu 65536 inet 127.0.0.1 netmask 255.0.0.0 inet6 ::1 prefixlen 128 scopeid 0x10 loop txqueuelen 0 (Local Loopback) RX packets 86710577 bytes 35256343773 (32.8 GiB) RX errors 0 dropped 0 overruns 0 frame 0 TX packets 86710577 bytes 35256343773 (32.8 GiB) TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0 ', don't parse first line 'eth0: flags=4163 mtu 1500'. ip_address_winrm: wbem is missing. ip_address_default: snmp is missing. 'wmi' is required. failed to parse 'eth0: flags=4163 mtu 1500 inet 192.168.1.157 netmask 255.255.255.0 broadcast 192.168.1.255 inet6 fe80::215:5dff:fe01:d728 prefixlen 64 scopeid 0x20 ether 00:15:5d:01:d7:28 txqueuelen 1000 (Ethernet) RX packets 41314609 bytes 9122327924 (8.4 GiB) RX errors 0 dropped 0 overruns 0 frame 0 TX packets 41224846 bytes 8130609979 (7.5 GiB) TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0 lo: flags=73 mtu 65536 inet 127.0.0.1 netmask 255.0.0.0 inet6 ::1 prefixlen 128 scopeid 0x10 loop txqueuelen 0 (Local Loopback) RX packets 86710577 bytes 35256343773 (32.8 GiB) RX errors 0 dropped 0 overruns 0 frame 0 TX packets 86710577 bytes 35256343773 (32.8 GiB) TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0 ', don't parse first line 'eth0: flags=4163 mtu 1500'. wbem is missing. snmp is missing.

**Comment by runner-mei** [comment]
fix
