### ISSUE TITLE
CenterOS设备的主机运转视图的指标一览中，取不到 端口（累积量）

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#934]
internal error: interface_default: snmp is missing. interfaces_by_ssh: failed to parse 'Kernel Interface table eth0: flags=4163 mtu 1500 inet 192.168.1.157 netmask 255.255.255.0 broadcast 192.168.1.255 inet6 fe80::215:5dff:fe01:d728 prefixlen 64 scopeid 0x20 ether 00:15:5d:01:d7:28 txqueuelen 1000 (Ethernet) RX packets 41460730 bytes 9148952105 (8.5 GiB) RX errors 0 dropped 0 overruns 0 frame 0 TX packets 41352871 bytes 8151516537 (7.5 GiB) TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0 lo: flags=73 mtu 65536 inet 127.0.0.1 netmask 255.0.0.0 inet6 ::1 prefixlen 128 scopeid 0x10 loop txqueuelen 0 (Local Loopback) RX packets 87391763 bytes 35517112951 (33.0 GiB) RX errors 0 dropped 0 overruns 0 frame 0 TX packets 87391763 bytes 35517112951 (33.0 GiB) TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0 ', don't parse first line 'eth0: flags=4163 mtu 1500'. interfaces_by_ssh_netstat_with_bytes: failed to parse 'netstat：无效选项 -- b usage: netstat [-vWeenNcCF] [] -r netstat {-V|--version|-h|--help} netstat [-vWnNcaeol] [ ...] netstat { [-vWeenNac] -I[] | [-veenNac] -i | [-cnNe] -M | -s [-6tuw] } [delay] -r, --route display routing table -I, --interfaces= display interface table for -i, --interfaces display interface table -g, --groups display multicast group memberships -s, --statistics display networking statistics (like SNMP) -M, --masquerade display masqueraded connections -v, --verbose be verbose -W, --wide don't truncate IP addresses -n, --numeric don't resolve names --numeric-hosts don't resolve host names --numeric-ports don't resolve port names --numeric-users don't resolve user names -N, --symbolic resolve hardware names -e, --extend display other/more information -p, --programs display PID/Program name for sockets -o, --timers display timers -c, --continuous continuous listing -l, --listening display listening server sockets -a, --all display all sockets (default: connected) -F, --fib display Forwarding Information Base (default) -C, --cache display routing cache instead of FIB -Z, --context display SELinux security context for sockets ={-t|--tcp} {-u|--udp} {-U|--udplite} {-w|--raw} {-x|--unix} --ax25 --ipx --netrom =Use '-6|-4' or '-A ' or '--'; default: inet List of possible address families (which support routing): inet (DARPA Internet) inet6 (IPv6) ax25 (AMPR AX.25) netrom (AMPR NET/ROM) ipx (Novell IPX) ddp (Appletalk DDP) x25 (CCITT X.25) '. interfaces_by_ssh_netstat: failed to parse 'Kernel Interface table Iface MTU RX-OK RX-ERR RX-DRP RX-OVR TX-OK TX-ERR TX-DRP TX-OVR Flg eth0 1500 41460745 0 0 0 41352886 0 0 0 BMRU lo 65536 87391795 0 0 0 87391795 0 0 0 LRU '. snmp is missing. failed to parse 'Kernel Interface table eth0: flags=4163 mtu 1500 inet 192.168.1.157 netmask 255.255.255.0 broadcast 192.168.1.255 inet6 fe80::215:5dff:fe01:d728 prefixlen 64 scopeid 0x20 ether 00:15:5d:01:d7:28 txqueuelen 1000 (Ethernet) RX packets 41460730 bytes 9148952105 (8.5 GiB) RX errors 0 dropped 0 overruns 0 frame 0 TX packets 41352871 bytes 8151516537 (7.5 GiB) TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0 lo: flags=73 mtu 65536 inet 127.0.0.1 netmask 255.0.0.0 inet6 ::1 prefixlen 128 scopeid 0x10 loop txqueuelen 0 (Local Loopback) RX packets 87391763 bytes 35517112951 (33.0 GiB) RX errors 0 dropped 0 overruns 0 frame 0 TX packets 87391763 bytes 35517112951 (33.0 GiB) TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0 ', don't parse first line 'eth0: flags=4163 mtu 1500'. failed to parse 'netstat：无效选项 -- b usage: netstat [-vWeenNcCF] [] -r netstat {-V|--version|-h|--help} netstat [-vWnNcaeol] [ ...] netstat { [-vWeenNac] -I[] | [-veenNac] -i | [-cnNe] -M | -s [-6tuw] } [delay] -r, --route display routing table -I, --interfaces= display interface table for -i, --interfaces display interface table -g, --groups display multicast group memberships -s, --statistics display networking statistics (like SNMP) -M, --masquerade display masqueraded connections -v, --verbose be verbose -W, --wide don't truncate IP addresses -n, --numeric don't resolve names --numeric-hosts don't resolve host names --numeric-ports don't resolve port names --numeric-users don't resolve user names -N, --symbolic resolve hardware names -e, --extend display other/more information -p, --programs display PID/Program name for sockets -o, --timers display timers -c, --continuous continuous listing -l, --listening display listening server sockets -a, --all display all sockets (default: connected) -F, --fib display Forwarding Information Base (default) -C, --cache display routing cache instead of FIB -Z, --context display SELinux security context for sockets ={-t|--tcp} {-u|--udp} {-U|--udplite} {-w|--raw} {-x|--unix} --ax25 --ipx --netrom =Use '-6|-4' or '-A ' or '--'; default: inet List of possible address families (which support routing): inet (DARPA Internet) inet6 (IPv6) ax25 (AMPR AX.25) netrom (AMPR NET/ROM) ipx (Novell IPX) ddp (Appletalk DDP) x25 (CCITT X.25) '. failed to parse 'Kernel Interface table Iface MTU RX-OK RX-ERR RX-DRP RX-OVR TX-OK TX-ERR TX-DRP TX-OVR Flg eth0 1500 41460745 0 0 0 41352886 0 0 0 BMRU lo 65536 87391795 0 0 0 87391795 0 0 0 LRU '.

**Comment by runner-mei** [comment]
fix
