### ISSUE TITLE
设备脚本执行错误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#938]
![image](https://cloud.githubusercontent.com/assets/20636259/21413843/4a8720e6-c835-11e6-8641-a6e3daa0ccb8.png)

**Comment by runner-mei** [comment]
fix

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/23686686/1b8f00aa-03e6-11e7-9225-28ad81bb3ab4.png)

**Comment by runner-mei** [comment]
fixed

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，close处理。
hengwei_setup_3.2.20171027_2837_x64.exe   版本确认，close处理。
