### ISSUE TITLE
实时监控，管理对象多勾选一个“已选择项时” 没有数据显示

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#940]
监控管理-实时监控，监控网络设备，平均CPU利用率，当管理对象在选择时，多勾选一个已选择项时，监控取不到数据
![image](https://cloud.githubusercontent.com/assets/20636259/21445822/1ae9295a-c8f9-11e6-86f1-85c776415a4e.png)

**Comment by eeiceyes** [comment]
fixed
