### ISSUE TITLE
企业微信设置报错

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#941]
选择客户现场5时，发生错误
![image](https://cloud.githubusercontent.com/assets/20636259/21447587/a2029904-c911-11e6-80e9-6c46f083f91e.png)

**Comment by eeiceyes** [comment]
微信端设置错误，和程序无关，关掉吧

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe   版本确认，close处理。
