### ISSUE TITLE
系统管理-脚本管理中出现.old脚本，且无法删除

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#943]
数据恢复时，选择覆盖原有数据，会产生old脚本
.old 脚本无法编辑删除
![image](https://cloud.githubusercontent.com/assets/20636259/21476556/6fd88064-cb74-11e6-85a8-b8eb1e940094.png)

**Comment by eeiceyes** [comment]
fixed
忽略此类文件
