### ISSUE TITLE
常用工具-dig测试，弹出的执行窗口 默认测试种类不是DIG

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#944]
![image](https://cloud.githubusercontent.com/assets/20636259/21477327/a113e8ce-cb7b-11e6-8e0b-2a80419d8777.png)
![image](https://cloud.githubusercontent.com/assets/20636259/21477335/b5c9d990-cb7b-11e6-804c-c26fc69ab48e.png)

**Comment by eeiceyes** [comment]
fixed
