### ISSUE TITLE
在TFTP脚本管理页面上，点击常用工具-DIG测试，执行失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#945]
在TFTP脚本管理页面上，点击常用工具-DIG测试。选择DIG测试，输入有效的IP地址，执行失败
![image](https://cloud.githubusercontent.com/assets/20636259/21477358/ff2c532e-cb7b-11e6-8ffc-b873ccbcd19b.png)

**Comment by eeiceyes** [comment]
fixed
