### ISSUE TITLE
告警执行脚本，在执行脚本时缺少脚本路径位置

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#95]
通知方式>外部程序通知方式

![image](https://cloud.githubusercontent.com/assets/14171497/11711611/9e9f3c60-9f62-11e5-8070-07ac2f33793f.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by Cuic** [comment]
Is not fixed !

**Comment by eeiceyes** [comment]
really fixed
