### ISSUE TITLE
虚拟化视图中的虚拟机采数失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#950]
虚拟设备采集数据失败，其他版本的机器可以采集到虚拟设备的数据
![image](https://cloud.githubusercontent.com/assets/20636259/21539635/a1a77034-cde3-11e6-9721-38cc3283ec6a.png)

采集地址：
http://192.168.1.201:8080/Saber/internal/s/network_devices/3958/cpu
采集错误：
{"channel":"cpu/3958/","client_name":"-","client_id":392,"created_at":"2016-12-29T16:30:37.0873401+08:00","error":{"code":562001,"message":"internal error:\r\n    cpu_for_vmware_virtual_machine: metric 'cpu_usage_average' is unsupported.\r\n    cpu_host_resource: snmp is missing.\r\n    read 'sys.oid' failed, snmp is missing.","internals":[{"code":500,"fields":{"metric_id":"cpu_for_vmware_virtual_machine"},"message":"metric 'cpu_usage_average' is unsupported."},{"code":400102,"fields":{"metric_id":"cpu_host_resource"},"message":"snmp is missing."},{}]}
,"engine_id":0}

**Comment by runner-mei** [comment]
这是网络问题导致的吧

**Comment by RasAlGu1** [comment]
{"channel":"cpu/4147/","client_name":"-","client_id":389,"created_at":"2017-01-06T10:21:16.8078694+08:00","error":{"code":562001,"message":"internal error:\r\n    cpu_for_vmware_host: results is empty.\r\n    cpu_host_resource: snmp is missing.\r\n    read 'sys.oid' failed, snmp is missing.","internals":[{"code":481001,"fields":{"metric_id":"cpu_for_vmware_host"},"message":"results is empty."},{"code":400102,"fields":{"metric_id":"cpu_host_resource"},"message":"snmp is missing."},{}]}
,"engine_id":0}

**Comment by runner-mei** [comment]
fix
