### ISSUE TITLE
基线数据创建时提示失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#953]
![image](https://cloud.githubusercontent.com/assets/20636259/21708437/86f6ff62-d413-11e6-8e3d-b36c48348e7b.png)

![image](https://cloud.githubusercontent.com/assets/20636259/21708431/742c70a6-d413-11e6-9907-c87c2551ea04.png)

**Comment by eeiceyes** [comment]
fixed
