### ISSUE TITLE
[Ubuntu]巡检任务统计报表,导出PDF出现方块和图像缺失

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#955]
![image](https://cloud.githubusercontent.com/assets/20636259/21711871/662ca8f4-d42c-11e6-89dc-04c3a62ed1f1.png)

**Comment by eeiceyes** [comment]
fixed

**Comment by RasAlGu1** [comment]
问题仍然存在
![image](https://cloud.githubusercontent.com/assets/20636259/22006795/f195e926-dca8-11e6-9d7b-f26136340a3b.png)

**Comment by runner-mei** [comment]
https://github.com/three-plus-three/hw_issues/issues/954
同一个问题，注意一下

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt_2.3.20170908.211~1b465a2_amd64.deb  版本确认，close处理。
