### ISSUE TITLE
lincense生成出错

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#956]
2017/01/09 13:24:59 [info] load properties '/usr/local/tpt/conf/app.properties'. 2017/01/09 13:24:59 [info] load properties '/etc/tpt/app.properties'. 2017/01/09 13:24:59 [info] load properties '/usr/local/tpt/conf/engine.properties'. 2017/01/09 13:24:59 [warn] load tsdb http port (37086) from /usr/local/tpt/conf/tsdb_config.conf 2017/01/09 13:24:59 [warn] load tsdb admin port (39183) from /usr/local/tpt/conf/tsdb_config.conf write tsn to file, open /var/lib/tpt/tpt-license.tsn: permission denied exit status 148

#915

**Comment by runner-mei** [comment]
fix
