### ISSUE TITLE
sqlserver运转图中数据库数量错误

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#957]
sqlserver
192.168.1.2
数据库中11个
![image](https://cloud.githubusercontent.com/assets/14171518/21757857/c487d2c6-d66f-11e6-980d-906c581ecf72.png)
![image](https://cloud.githubusercontent.com/assets/14171518/21757864/d38ab84c-d66f-11e6-80fd-d286325ae315.png)

软件界面显示12个
![image](https://cloud.githubusercontent.com/assets/14171518/21757838/7ff8324a-d66f-11e6-9fcd-68726ec9deb9.png)

**Comment by runner-mei** [comment]
这个是因为我们多了一个叫  tempdb  的数据库， 详细请看 sqlserver_databases 指标
