### ISSUE TITLE
历史记录查看：磁盘使用率记录规则没有区分，不知道显示的是哪个磁盘的数据

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#958]
![image](https://cloud.githubusercontent.com/assets/14171518/21758259/d8e7e422-d674-11e6-958e-7ae7bc996e28.png)

**Comment by eeiceyes** [comment]
fixed
但只针对新增加的主机，自动生成的记录规则名称

**Comment by eeiceyes** [comment]
fixed
