### ISSUE TITLE
(国妇婴)snmp设备配置备份方式添加

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#959]
![image](https://cloud.githubusercontent.com/assets/14171518/21792108/637b6a3e-d722-11e6-8d24-dd92dba9d689.png)

下拉框右侧的帮助按钮中的文本内容：“默认备份”、“tftp脚本备份”，请在“设备属性”页中配置telnet或ssh参数；“snmp备份”，请在“设备属性”页面中配置snmp读写参数

**Comment by runner-mei** [comment]
fix
