### ISSUE TITLE
报表管理-预置报表查看，选择时间段查看失效

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#962]
进行选择时间段分类查看时，无法查询到数据

![image](https://cloud.githubusercontent.com/assets/20636259/22091347/e6434c6e-de31-11e6-9891-fafd1609a35b.png)

**Comment by eeiceyes** [comment]
这个问题还有吗？

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170922_2764_x64.exe  版本确认，close处理。
