### ISSUE TITLE
[数据流]数据流分析需求

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#965]
1.数据流首页面固定有数据流的设备！**---卓豪无**
首页默认分析流量图区分开数据流分析来源设备（针对设备来源进行分析数据）
2.分析出入流量数据，可在界面中过滤查看**---卓豪无**
注：任意指定地址、端口、应用等等，进行过滤查看。
3.报表统计查看每周、每天、或者半天.、等....报表。（图表、表格等形式展示，目前只有表格形式）！**--卓豪有**
3.1 并且报表需要导出！ （纯前台工作，暂时不好评估）**---卓豪无**
附图为卓豪统计报表
![image](https://cloud.githubusercontent.com/assets/14171497/22871703/5b0a3b8c-f1ee-11e6-8211-2b0f75c1650c.png)

6.攻击告警及过滤查看**---卓豪已有功能** （后台已完成， 前1周）
数据流数据中有攻击的事件进行告警功能
7.记录攻击日志/原始数据查看（目前原始数据查看所遗留的问题是查询慢“因数量量大”）  （后台3天，前台1周）
针对有攻击的数据、日志、原始数据进行统计查看。**---卓豪无攻击日志查询**
8.统计TCP/UDP会话数统计（后台1天， 前台1天）。**---卓豪无**
针对http会话数、UDP/TPC会话数统计
9.账号密码**-卓豪已有功能**   (2月15日前已完成)
登录账号密码添加、删除、编辑！账号权限指定添加修改！
10.应用分析统计**-卓豪已有功能**  (2月9日完成)！
根据网络应用协议进行统计分析，比如：http、SNMP、SMTP协调统计等。
11.网管平台上的数据流功能也需要完善到新数据流平台上！（这个不花时间，等新界面完成再做吧）
12.仪表板统计时间有限制，不能自定义时间统计查看；--卓豪无

**Comment by runner-mei** [comment]
看一下，还缺什么？
