### ISSUE TITLE
通知方式添加电子邮件通知时，不填写参数直接测试，提示测试通过

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#966]
通知方式添加电子邮件通知时，不填写参数直接测试，提示测试通过

**Comment by runner-mei** [comment]
除 服务器地址和端口外，其它都是可选项。

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170727_219_x64.exe     版本确认，close处理。
