### ISSUE TITLE
数据流开发

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#967]
2.登录账号密码
账号登录退出，密码修改，账号、权限添加、修改；
3.添加仪表板--设备分析表盘添加以下分析表盘 
 设备排行-线图 
 最近告警 
 接口的速度排行 
 接口的利用率排行 
 接口组的速度排行 
 接口组的利用率排行 
 流入丢包排行 
 流出丢包排行 
 问题排行 
 嫌疑犯排行 
 目标排行 
 嫌疑犯位置排行 
 目标位置排行 
 接口(经由路由)排行 
5.告警：
告警没有通知方式；
告警端口/协议不全
告警应用列表不对（无）
6.饼图上方的来源地址/目标地址是否能对齐排行；（或者去掉）
![image](https://cloud.githubusercontent.com/assets/14171497/23059080/c8b49a5a-f532-11e6-8b7e-b1ed313041a0.png)
7.会话排行报表应用显示的是未知
![image](https://cloud.githubusercontent.com/assets/14171497/23059251/8cb322b4-f533-11e6-900a-dbafb17abbba.png)

**Comment by runner-mei** [comment]
看一下，还缺什么？
