### ISSUE TITLE
[数据流]报表生成时，生成有误

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#969]
定义条件为源端口或者目的端口时，生成报表没有数据
按端口和端口范围生成时，生成报表的数据有误

**Comment by hengwei-lhm** [comment]
http://127.0.0.1/hengwei/internal/nflow/query/report?start_at=2017-02-24T03:45:02.417Z&end_at=2017-02-24T04:45:02.417Z&title=&max_records=10&port=4006-4009

**Comment by hengwei-lhm** [comment]
http://127.0.0.1/hengwei/internal/nflow/query/report?start_at=2017-02-24T03:45:02.417Z&end_at=2017-02-24T04:45:02.417Z&title=&max_records=10&port=80

**Comment by runner-mei** [comment]
fixed
