### ISSUE TITLE
巡检结果查询导出的excel表格中，单位缺失

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#976]
![image](https://cloud.githubusercontent.com/assets/20636259/23247175/8480659e-f9d3-11e6-93ce-a3b68a8babfb.png)

单位缺失%

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20170811_265_x64.exe   版本确认，close处理。
