### ISSUE TITLE
【数据流】设置中的用户管理添加新用户或修改管理员密码无法登陆

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#982]
添加新用户，或者修改管理员密码后无法登陆。显示密码错误
注:密码要求带有特殊字符(目前只能填写数字和字母)

**Comment by hengwei-lhm** [comment]
fixed

**Comment by RasAlGu1** [comment]
密码修改和添加新用户可以登录了
但是密码中还是不能使用特殊字符
![image](https://cloud.githubusercontent.com/assets/20636259/23447184/2dc65a32-fe84-11e6-8a29-7d952fbe0472.png)

**Comment by hengwei-lhm** [comment]
验证 破折号 和 下划线可以通过验证
