### ISSUE TITLE
主机运转视图中的当前告警数中的告警消息确认后，再次打开点击已确定告警消息不显示

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#986]
Windows主机运转视图中的当前告警数中的告警消息确认后，
再次打开告警消息窗口，点击 已确定告警消息 不显示已经确定的告警消息

**Comment by runner-mei** [comment]
fix?

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170830_2674_x64.exe   版本确认，close处理。
