### ISSUE TITLE
右键设备-添加告警-端口流量告警，默认添加不发生告警

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#989]
添加端口流量告警时，不修改参数，使用默认参数添加告警时，添加成功的告警规则不会被触发
![image](https://cloud.githubusercontent.com/assets/20636259/23448008/87aa419e-fe89-11e6-9eff-75d5054e8de7.png)
修改告警规则的触发值后，可以触发该规则

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170830_2674_x64.exe   版本确认，close处理。
