### ISSUE TITLE
Linux设备设置告警-文件信息，检测数据行时，提示失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#993]
告警设置，文件信息指标 检测数据行时，提示失败
设备 192.168.1.157 
SSH:root  root 
![image](https://cloud.githubusercontent.com/assets/20636259/23494635/eb57a4a0-ff4e-11e6-8a70-72b0f6e12700.png)
![image](https://cloud.githubusercontent.com/assets/20636259/23494666/274f84c8-ff4f-11e6-98f5-57fe7019701b.png)

**Comment by runner-mei** [comment]
fix
