### ISSUE TITLE
Windows（winrm取数）文件夹大小获取不到

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#995]
![image](https://cloud.githubusercontent.com/assets/14171518/23497596/d17086c8-ff5e-11e6-8e41-08475f20abb4.png)

**Comment by runner-mei** [comment]
fix

**Comment by RasAlGu1** [comment]
大小信息还是缺少

**Comment by runner-mei** [comment]
文件信息中 目录大小是没有的， 有一个专门的 文件或目录大小指标。
