### ISSUE TITLE
windows（winrm）路径中有空格报错

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#997]
![image](https://cloud.githubusercontent.com/assets/14171518/23500698/e14be01c-ff6b-11e6-88a9-1e92d7498587.png)

**Comment by runner-mei** [comment]
fix

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/23637901/58359da2-0319-11e7-9c98-9e661d51c8ae.png)

**Comment by runner-mei** [comment]
你这是什么机器上， 什么参数？

**Comment by runner-mei** [comment]
fix

**Comment by RasAlGu1** [comment]
![image](https://cloud.githubusercontent.com/assets/20636259/24782381/70bbac0a-1b78-11e7-8425-c30000af7861.png)
Version 2.2.20170406_2280_x64

**Comment by eeiceyes** [comment]
fixed
