### ISSUE TITLE
巡检bug汇总

### ISSUE THREAD

**Issue by hengweiGR** [three-plus-three/hw_issues#998]
1、对于巡检点已经删除的巡检异常记录，在查询页面中无法查找
![image](https://cloud.githubusercontent.com/assets/14171518/23535735/3c027126-fffb-11e6-8fee-7a0df8a9740f.png)
2、异常处理页面数据显示问题
![image](https://cloud.githubusercontent.com/assets/14171518/23535767/750c9c76-fffb-11e6-9eef-06ef873b8a21.png)
3、巡检点统计报表中异常描述都没有显示
![image](https://cloud.githubusercontent.com/assets/14171518/23535801/b075767a-fffb-11e6-9c40-5995fdbe5839.png)
4、巡检点设置中对于主机文件信息获取失败（192.168.1.2已设置winrm）
![image](https://cloud.githubusercontent.com/assets/14171518/23535886/3b3b9848-fffc-11e6-8ae2-5298b92962a4.png)
![image](https://cloud.githubusercontent.com/assets/14171518/23535907/5c3de3c0-fffc-11e6-86fa-6891807fc476.png)

**Comment by runner-mei** [comment]
第4个问题已解决

**Comment by eeiceyes** [comment]
2和3已经解决

**Comment by eeiceyes** [comment]
关于第一个问题，在巡检异常处理界面肯定是查不到了，因为都可以删了，没必要再去处理或确认其中的某些异常条目，但在巡检结果查询界面已经改成能继续查到

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20171009_2789_x64.exe  版本确认，close处理。
